### ISSUE TITLE
[Web] Search results UI overflow the layout

### ISSUE THREAD

**Issue by Moshyfawn** [bluesky-social/social-app#1000]
**Describe the bug**
Parts of Bluesky Web UI get cut off on screen height less than the height of the search popover list.

**To Reproduce**

1. Open your [Bluesky timeline](https://bsky.app/)
2. Input any query into the search box that yields results _(i.e. `bsky.app`)_
3. Adjust the browser window height to be less than the search popover list
4. Open any "floating" UI element (i.e. popover)
- Click on the "More Actions" icon button under any post in your timeline
5. Scroll down as much as possible
6. See parts of the UI get cut off

**Expected behavior**

The floating UI elements don't cause the body to overflow and cut off the timeline UI

**Screenshots**

<img width="1421" alt="bsky-height-overscroll-scrsht" src="https://github.com/bluesky-social/social-app/assets/16290753/fd949abe-930f-46ca-b890-dbf18445f8eb">

**Details**

 - Platform: Desktop Firefox MacOS
 - Platform version: MacOS Sonoma 14.0 Beta 3, Firefox Developer Edition 116.0b2 (64-bit)
 - App version: 1.41.0

**Additional context**

Potentially related to #1001

**Comment by pfrazee** [comment]
Thanks -- this UI element definitely needs work when we can get to it.

**Comment by surette** [comment]
Just noting that this can also be reproduced horizontally if you resize your window to 1230px wide (where the breakpoint is to put that component on the right-hand side)

![image](https://github.com/bluesky-social/social-app/assets/1082048/d77a8088-ad2f-4031-945f-105fc2833a9e)

**Comment by ansh** [comment]
This has been fixed in #1351
