### ISSUE TITLE
[Web] A lot of post content in a modal causes parts of modal to become inaccessible

### ISSUE THREAD

**Issue by Moshyfawn** [bluesky-social/social-app#1001]
**Describe the bug**
Adding enough post content like media and long text content in the "Create Post" modal causes the modal header actions like "Cancel" or "Post" to be hidden

**To Reproduce**

1. Open your [Bluesky timeline](https://bsky.app/)
2. Click "New Post" primary action button
3. Add media _(you can use the reproduction screenshot)_ and text content _(you can use the reproduction steps text)_
4. See the modal header actions are hidden behind the browser app bar

**Expected behavior**

The modal UI
- **either** shrinks
- **or** becomes scrollable

**Screenshots**

<img width="1421" alt="bsky-modal-overflow-scrsht" src="https://github.com/bluesky-social/social-app/assets/16290753/1005e892-88b1-4e3a-b2bb-5a3243b2455c">

**Details**

 - Platform: Desktop Firefox MacOS
 - Platform version: MacOS Sonoma 14.0 Beta 3, Firefox Developer Edition 116.0b2 (64-bit)
 - App version: 1.41.0

**Additional context**

Potentially related to #1000

**Comment by jaysoni-ash42** [comment]
@Moshyfawn  does this change resolve this issue . if it does i am happy to pull up a pr 

https://github.com/bluesky-social/social-app/assets/68722497/d921a70a-e947-495c-a271-b3b07a87290a

**Comment by Moshyfawn** [comment]
> @Moshyfawn does this change resolve this issue

That's basically what I had in mind, yes 🙏

There're 2 types of modal scrolls and I'm unsure which one the BlueSky team would prefer to go with. [Here's an example](https://mui.com/material-ui/react-dialog/#scrolling-long-content) of what I'm talking about.

**Comment by pfrazee** [comment]
@jaysoni-ash42 Your screen recording matches what I'd expect it to do. Please feel welcome to open a PR; otherwise we can implement.
