### ISSUE TITLE
Cursor not pointer on ProfileHeader back button

### ISSUE THREAD

**Issue by sbsto** [bluesky-social/social-app#1006]
**Describe the bug**
The cursor is default on `ProfileHeader.tsx` back button. I think (correct me if I'm wrong, just assuming!) it was intended to be a pointer, like on `PostThread.tsx`. 

**To Reproduce**

1. Navigate to a profile
2. Hover over "Back" button in the top left

**Expected behavior**

I'd expect the cursor to change to pointer when hovering over an action button

**Screenshots**

Existing:
<img width="1157" alt="Screenshot 2023-07-11 at 22 42 15" src="https://github.com/bluesky-social/social-app/assets/37947148/77413add-564f-4c22-a38c-7c325b1021d2">

Expected:
<img width="1145" alt="Screenshot 2023-07-11 at 22 43 05" src="https://github.com/bluesky-social/social-app/assets/37947148/b979abc6-1979-4020-9993-25776e1afcce">

**Details**

 - Platform: Desktop web, Arc browser (chromium)
 - Platform version: Arc, latest
 - App version: 1.41

**Additional context**

Could be `TouchableWithoutFeedback` for a reason, but seems like it would be better to be a `TouchableOpacity` which has the cursor pointer. I have a PR ready that changes this if you want it, two line change.

**Comment by estrattonbailey** [comment]
Hey @sbsto 👋 great call, pointer would be good there. We'd be happy to take a look at your PR, mind pushing that up?

**Comment by estrattonbailey** [comment]
Nice one! Appreciate your help :)
