### ISSUE TITLE
Tooling: Consider using typescript-eslint's new presets

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bluesky-social/social-app#1007]
👋 Hi! I'm one of the maintainers of [typescript-eslint](https://typescript-eslint.io). We just [released a v6.0.0 as stable](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6) that, among other things, includes a reworked set of [recommended preset configurations](https://typescript-eslint.io/linting/configs). 

Would you be interested in using those recommended configs? I'm happy to send a PR akin to those linked in https://github.com/typescript-eslint/typescript-eslint/issues/6760, where I set it up for you & mark the _"todo: do we want these?"_ rules. 🙂 

Since you're not yet [linting with type information](https://typescript-eslint.io/linting/typed-linting), my standard starting recommendation is to roughly start with:

```js
extends: [
  'eslint:recommended',
  'plugin:@typescript-eslint/recommended',
  'plugin:@typescript-eslint/stylistic',
]
```

_P.S. Love that you've open sourced this repo, that's awesome. Thanks for all your work on it!_ ❤️

**Comment by pfrazee** [comment]
Hi @JoshuaKGoldberg! Thanks for letting us know about the tool. We're happy with our current setup but we'll keep it in mind for the future.
