### ISSUE TITLE
App allows slurs in the usernames 

### ISSUE THREAD

**Issue by purploid** [bluesky-social/social-app#1008]
**Describe the bug**
A user with a racial slur in their username has been allowed on the platform. This is not the first time it has happened 

**To Reproduce**

1. Create an account that has a racial slur against a Black person in the name. Goes for most other racially marginalized groups. Does not happen for white people though.

**Expected behavior**

Blocked. Even for custom URLs it should be blocked.

**Details**

 - Platform: All

**Additional context**

You have aggressive AI filters that mark women's bodies as lewd and NSFW, but you don't do the same for racial slurs? This is a huge oversight.

**Comment by purploid** [comment]
It's not just Black people. This app allows for slurs for every group except white people for some reason. What's going on here?

**Comment by joelghill** [comment]
There's no reason the PDS and client can't have a ban list of words for usernames. It's not perfect but it's something.

**Comment by ZASMan** [comment]
Where exactly does this code live?

Bluesky, although it's an "open beta" has expanded to a very sizable community of users with understandable moderation demands, of they could just have some hardcoded validations for at least the flagship instance like arrays of profanity for the major languages spoken across the main Bluesky instance that could be a step forward in positive user experiences.

**Comment by joelghill** [comment]
> To any of the devs who might read this, where exactly does this code live concerning content moderation so the community could take a go at it?
> 
> Bluesky, although it's an "open beta" has expanded to a very sizable community of users with understandable moderation demands, of they could just have some hardcoded validations for at least the flagship instance like arrays of profanity for the major languages spoken across the main Bluesky instance that could be a step forward in positive user experiences.

Not a dev, but the roadmap for federation relies on the concept of custom moderation services. These services will label posts, and people will be able to subscribe to these services, (similar to custom feeds) and decide for themselves what content they want to hide.

The source code for this is not readily available to my knowledge.

**Comment by pfrazee** [comment]
The code has been updated through team and community contributions to handle these issues. For reference, see:

- https://github.com/bluesky-social/social-app/pull/1016 (adds reporting to the app, thanks @therealjeffg)
- https://github.com/bluesky-social/atproto/pull/1336 (introduces automated detection and handling behaviors)

Please let me know if there are any remaining issues but I believe these cover it.
