### ISSUE TITLE
Reporting account workflow to include usernames & hate speech

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#1010]
Having the ability to report accounts usernames/display names

**Describe the solution you'd like**

adding an easy option to directly report usernames. not all offensive usernames that are offensive/derogatory have content to be reported. 

Being able to report usernames, can streamline the reporting process and help it become more automated.

![image](https://github.com/bluesky-social/social-app/assets/66647238/38c388c1-b9a8-44f3-abbc-c3224ef4d992) 
![image](https://github.com/bluesky-social/social-app/assets/66647238/87a30ea8-340a-4f29-94e9-e545074fb9c1)

**Comment by therealjeffg** [comment]
Added this PR:

https://github.com/bluesky-social/social-app/pull/1016

It's probably not complete, definitely needs review.

**Comment by monicaellerose** [comment]
just realized this got done thank yall!
