### ISSUE TITLE
Unable to scroll in Home Feed Preferences

### ISSUE THREAD

**Issue by ChaseGeeseman** [bluesky-social/social-app#1014]
**Describe the bug**
User is unable to scroll down and fully display all home feed Preferences settings. 

Resolve issue by toggling any visible setting or changing any visible slider 

**To Reproduce**

1. Open bluesky app
2. From the app home screen select hamburger menu in the top left
3. Select Settings 
4. Select Home Feed Preferences 
5. Issue occurs here and shows as user being unable to scroll down and fully display all home feed Preferences 
6. Resolve issue by toggling any visible setting or changing any visible slider

**Expected behavior**

The home screen Preferences screen should either display fully from the start, or allow the user to scroll it without first needing to toggle an option. 

**Screenshots**

Screenshot displaying the home feed Preferences screen not displaying fully and not allowing the user to scroll down
![Screenshot displaying the home feed Preferences screen not displaying fully and not allowing the user to scroll down](https://github.com/bluesky-social/social-app/assets/9387644/425e587d-2e4f-44ef-8a3c-a80dbd79a583)

creenshot displaying the home feed Preferences screen after user is able to scroll down 
![Screenshot displaying the home feed Preferences screen after user is able to scroll down.](https://github.com/bluesky-social/social-app/assets/9387644/8bb929fa-4aa1-4070-bd8a-d26878d7061e)

[Screen recording hosted on Google drive](https://photos.app.goo.gl/72WzEi7vtgrrrLYj6)

Note that when recording the app behaves as expected when opening the home feed preferences section the first time, but shows the bug after backing out and then reopening it.

I do not know why the behavior requires a back out to trigger when screen recording, but occurs every time when not screen recording. 

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: 1.41.0

**Additional context**

Device in use is a Google Pixel 7.
On my device, under Accesability Settings - > Display Size and Text
Font size set to option 3
Display size set to option 2

Under accessibility Bitwarden is allowed to enter usernames and passwords, and a bitwarden bubble is displayed in the screen recording.

Potentially similar to [this closed issue](https://github.com/bluesky-social/social-app/issues/901)

**Comment by pfrazee** [comment]
This appears to be an issue with Android and the bottom-view's handling of scrollviews. Since @ansh is taking lead on interaction behaviors I'm going to pass to him.

**Comment by ansh** [comment]
Working on this!

**Comment by ansh** [comment]
Hey @ChaseGeeseman , this should've been resolved in a previous update. Can you please update your app from the Google Play Store and check if it has been resolved?

**Comment by ChaseGeeseman** [comment]
I confirm this is working as expected on Build version: 1.46.0 (33); Platform: android
