### ISSUE TITLE
Posts with hashtag show “Translate this post”

### ISSUE THREAD

**Issue by hensonb3** [bluesky-social/social-app#1018]
**Describe the bug**
Posts with hashtag show “Translate this post” message.

**Expected behavior**

“Translate this post” should not appear

**Screenshots**
![IMG_8688](https://github.com/bluesky-social/social-app/assets/50562920/d7e54c63-3df5-4a88-b6f4-50bb1f12076e)

**Details**

 - Platform: iOS
 - App version: 1.40

**Comment by pfrazee** [comment]
@hensonb3 are you creating these posts with a bot or similar? This can be solved by correctly setting the language value on the post.

**Comment by BrandonHenson-KR** [comment]
@pfrazee I am indeed posting with a bot. Do you have a quick/handy example? Here is a snippet of my Python code:

from atproto import Client
    # Set up Bluesky Social API
    bluesky_client = Client()
    bluesky_client.login('mlbscores.bsky.social', 'REMOVED)
    
               # Post to Bluesky Social
            bluesky_client.send_post(text=final_score_text)

**Comment by pfrazee** [comment]
I dont know which API you're using so I can't say for sure. The relevant schema is here:

https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json#L32

So you ultimately want something like this:

```
{
  text: "Hello!",
  langs: ["en"],
  ...
}
```

This is a recent update so if your python client doesnt have a parameter for it yet, you'll need to ask them for the addition!

**Comment by pfrazee** [comment]
Going to close this issue to keep things clean but feel free to reply

**Comment by BrandonHenson-KR** [comment]
Thanks, I have asked the Discord for: https://github.com/MarshalX/atproto
