### ISSUE TITLE
Bluesky content moderation system is flagging non-explicit images as explicit

### ISSUE THREAD

**Issue by CassieDingo** [bluesky-social/social-app#1019]
**Describe the bug**
Bluesky content filtering is flagging images with no NSFW/Explicit imagery as sexually explicit.

**To Reproduce**

1. Upload images or media that contain no explicit elements to them
2. Post the images
3. Observe that Bluesky content flagging will automatically flag them as explicit despite no noticeable signs of NSFW nature to them

**Expected behavior**

Bluesky content moderation allows SFW/Non-Explicit images to go through without any tagging or false flagging behavior. 

**Screenshots**

![bskyfalseflag](https://github.com/bluesky-social/social-app/assets/123167034/1517f26b-a01d-466e-a6cc-2ab361f8ef4c)

**Details**

 - Platform: All platforms 
 - Platform version: Do Not Know
 - App version: Do Not Know

**Additional context**
Attempting to upload art as an introduction for my bluesky account, repeated twice and both times i was flagged as having explicit imagery despite images containing no nudity or elements of explicit behavior in them.

**Comment by Sininini** [comment]
Automatic tagging of completely wholesome content is still an issue.
