### ISSUE TITLE
desktop: mute list overflows screen

### ISSUE THREAD

**Issue by llllvvuu** [bluesky-social/social-app#1036]
**Describe the bug**

https://github.com/bluesky-social/social-app/assets/5601392/8c3bdcee-b21e-4333-83bd-6d9fa7940a35

**To Reproduce**

Here is the one I tested with: https://bsky.app/profile/did:plc:iijrtk7ocored6zuziwmqq3c/lists/3k2lzfzwiwf2f

**Expected behavior**

Should scroll like the timeline

**Details**

 - Platform: Desktop Chrome MacOS
 - Platform version: Chrome 114.0.5735.198
 - App version: 1.41.0

**Additional context**

Probably forgot to put it in a scroll container or something

**Comment by ansh** [comment]
Thanks for the report. It is planned to be fixed. However, if you would like to take a stab at it, please go ahead!

**Comment by ansh** [comment]
Done!
