### ISSUE TITLE
Bluesky (web app) randomly sends you back to blank page

### ISSUE THREAD

**Issue by onmyouji** [bluesky-social/social-app#1045]
**Describe the bug**
On the web app (staging.bsky.app), clicking on "Home" (on the left navigation bar) sometimes will cause your browser page to send you back to blank page (about:blank). 

**To Reproduce**

There's no reliable way to reproduce it, it happens from time to time. 

**Expected behavior**

The web app should not randomly opens a blank page.

**Details**

 - Platform: 
Windows 10 Home 64 bit
Vivaldi 6.1.3035.204 (Stable channel) (64-bit) (Chrome 114.0.5735.245)

**Comment by pfrazee** [comment]
Assigning to @estrattonbailey for when theyre back

**Comment by estrattonbailey** [comment]
Relates to #1045

**Comment by estrattonbailey** [comment]
Let's track this via #710
