### ISSUE TITLE
Ability to manually create non-algorithmic Feeds directly via Bluesky

### ISSUE THREAD

**Issue by HeyItsLollie** [bluesky-social/social-app#1046]
**Is your feature request related to a problem? Please describe.**

I would like a way to author _non-algorithmic_ Feeds directly via Bluesky, from both the New Post dialogue window itself, and a dedicated Feed editor for adding Posts to a Feed retroactively. As an artist, I want to be able to offer a way for other users to easily find my work, without them having to search for it, or sift through any unrelated posts and shares on my account.

Feeds have the potential to be hugely useful for everyone, whether they're an artist, an analyst, or someone with a specialized interest. Feeds could easily be utilized as a way for users to tag and organize their posts for other users, in a way that would allow everyone else to choose exactly what they wish to view and follow.

On other platforms, there are users who appreciate being able to follow art-only accounts, and creators who prefer to have their creative posts separated from everyday posts. Being able to manually curate a Feed via the app would satisfy these use-cases in a way that is easy for everyone:
It lessens the need for creators to micromanage posts across multiple accounts, and gives users the ability to selectively choose what they want to see from the accounts they follow.

Unfortunately, the creation of Feeds currently appears to be limited to people who are able to code and set up server apps. As you can probably guess, your average user isn't going to be a web-developer.

---

**Describe the solution you'd like**

Here's a mock-up as an example of how this functionality could be added to Bluesky. I'm sure there'd be many cases where it would be beneficial to be able to curate multiple Feeds. For example, adding works to a general Art feed, but also curating posts related to a specific subject matter.

![firefox - 2023-07-24 - 19-08-11](https://github.com/bluesky-social/social-app/assets/30498581/0f250a71-a648-47fa-8b7d-39b0fc8dfe9b)

You would first set up your custom Feed in another section of the app (eg: My Feeds). This would also offer a way to select existing posts to add to your to-be-created Feed, or edit existing Feeds to add OR remove posts from them.

Your Feeds could then be selected in the New Post dialogue box, visible only when you've enabled "Add Post to Feed". If you have more than one custom Feed, "Change Selection" would open a list where you can select one or more Feeds to add your new post to. Otherwise, the very first Feed in a list could be the Feed selected by default - most useful when a user only has one custom Feed to select from.

---

**Describe alternatives you've considered**

The alternative to this is that nothing changes, and it's life as usual. If you want a way to split your posts into separate Feeds, you either pay to host a server and figure out how to code your own Feed, or you create multiple accounts and micro-manage posts across them - and users then have to follow multiple accounts if they want to see everything.

**Comment by pfrazee** [comment]
@HeyItsLollie Thank you for the well-written suggestion. We've been thinking about ways to do this and similar things. We _are_ unfortunately backed up on some other tasks but we will try to keep our eye on this.

**Comment by HeyItsLollie** [comment]
Understood! Glad to hear there's been discussion on similar features, looking forward to whatever the future brings.

**Comment by IgorArnaut** [comment]
Seriously, feeds should be fixed. Like how is this related to Dungeon Meshi? It's just because the woman in the picture has the name Marcille, which is also the name of a character in Dungeon Meshi.
![image](https://github.com/user-attachments/assets/311b95cb-a432-4ee8-8caa-7c4d709ae38f)

**Comment by HeyItsLollie** [comment]
That doesn't really have anything to do with how feeds function on a base level (and nothing to do with this issue), the feed you're following just casts a wide net.
