### ISSUE TITLE
Quote post viewing

### ISSUE THREAD

**Issue by neucales121** [bluesky-social/social-app#1050]
I think a way to see a posts QTs would be really nice. It feels like a low hanging fruit that'd make discovery a lot easier.

**Comment by neucales121** [comment]
(oops, should that have been "quote post" instead?)

**Comment by pfrazee** [comment]
This is something we're discussing right now. Quote posts have a habit of being pretty dunk-prone, but we're talking about a mitigation to that issue (that you can essentially unquote yourself) so once that's in place, I'm in favor.

It might be neat to do as somehow integrated into the replies actually.

**Comment by skunecuscre1** [comment]
> This is something we're discussing right now. Quote posts have a habit of being pretty dunk-prone, but we're talking about a mitigation to that issue (that you can essentially unquote yourself) so once that's in place, I'm in favor.
> 
> It might be neat to do as somehow integrated into the replies actually.

As a temporary stopgap, maybe you could have a setting where a post's author can turn off the view quotes button for people on the official app?

I feel like that'd add enough friction to make dunking a non-problem, 99% of people aren't gonna mess with the API just to see some dunks.

**Comment by skunecuscre1** [comment]
@pfrazee Could this be revisited now that blocking hides a post from QTs?

**Comment by mschwendener** [comment]
> a way to see a posts QTs would be really nice. 

I don't mind if that's not possible, but I would just have used it if it was: 

Many new people haven't learned yet that eomojis often steer inclusion in a thematic thread. 

So I often quote post things, just adding an emoji like _books_ or the _test tube_. 

It would be good if I could check if somebody else has already done that, with the same post.

**Comment by DanielZKlein** [comment]
At the risk of necro'ing this, this is currently my number 1 feature I miss from The Bad Place. I agree that in a worst-case situation, QTs can be very dunky and we don't want that. Mitigation for that would be great, either manually unquoting yourself, using blocking to disable blocked parties from QTing me, or simply (I say, knowing nothing about how simple or complicated any of this is) adding an account level feature that is basically "people can QT me" or even "QTs are shown under my skeets".

**Comment by mschwendener** [comment]
https://bsky.app/profile/bsky.app/post/3l2s5ocuzyc24 :D

**Comment by pfrazee** [comment]
Yaaaay

**Comment by mschwendener** [comment]
Coming back to add that I use this almost daily to check if something has been quote posted for inclusion in a feed already, before I do so.

**Comment by linas** [comment]
Hmm. I use quote posts to highlight something I like, and to add to it, to expand on it.
