### ISSUE TITLE
Consider "Skeet" and "Reskeet"

### ISSUE THREAD

**Issue by Phosphorshy** [bluesky-social/social-app#1062]
I’m sure it’s challenging to come up with brand-exclusive recognizable terms for things that exist on other platforms, but please consider “skeet”. Users frequently mention enjoyment of this term; I’ve yet to see a skeet in opposition of the name

I humbly suggest that there is no real need to use generic terms and that simply using "skeet" and "reskeet" would be much more popular.
/

**Comment by pfrazee** [comment]
Please stop
