### ISSUE TITLE
Add a share link to feed screen on mobile (when feed is not in my feeds)

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#1080]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to share a link to a feed in the mobile app even if the feed is not added to my feeds. Right now in order to share a feed you need to add it to your feeds first. There seems to be enough space in the nav bar to add a "…" menu button with a share link.

Feed which is added to my feeds - there is a menu with "share link" option:

<p><img src="https://github.com/bluesky-social/social-app/assets/28465/ff7023e3-91aa-4667-a6e8-7fca1881f3b6" width="500"></p>

Feed which is not added to my feeds - no share link option anywhere:

<p><img src="https://github.com/bluesky-social/social-app/assets/28465/f5dd7cc5-62b9-4b24-9072-266d8ccabe05" width="500"></p>

**Comment by pfrazee** [comment]
+1, assigning to @estrattonbailey

**Comment by estrattonbailey** [comment]
This was fixed when we [added the Report option to the dropdown](https://github.com/bluesky-social/social-app/pull/1070/files#diff-7a43d359d265360bcecb858cdfe5aaee1e64f69d6a130a7114b5da9c31077095R305) in #1070, will be released soon! 🎉
