### ISSUE TITLE
Consider changing app logo

### ISSUE THREAD

**Issue by skunecuscre1** [bluesky-social/social-app#1084]
The current app logo is.. not too good in my opinion. Are there any considerations of changing it as of now?

I still like [this proposed logo](https://bsky.app/profile/roselia.gay/post/3jyufklbni32u) by a user

**Comment by pfrazee** [comment]
We are planning to, we just need to resolve on the final logo.

I love Roselia's logo but it doesn't scale down well. Logos need to be able to work at multiple resolutions without losing visual clarity.

**Comment by mschwendener** [comment]
While we wait: you can replace the icon on your phone https://knowtechie.com/how-to-change-app-icons-on-iphone

**Comment by mschwendener** [comment]
https://rosemarymosco.com 

<img width="455" alt="screenshot_4508" src="https://github.com/bluesky-social/social-app/assets/4497705/55518509-d7d2-4224-b675-b7bfc302503b">

**Comment by mschwendener** [comment]
Start from this? https://bsky.app/static/social-card-default.png 

![social-card-default](https://github.com/bluesky-social/social-app/assets/4497705/bb4e5a2f-01d3-48a4-8aa0-ce33e5a3fb7f)

**Comment by OzzyCzech** [comment]
What about butterfly icon originally designed by @pfrazee. Can be scaled, looks great, it's easy to identify and it's playful

https://github.com/OzzyCzech/blueskyicon

Here some examples from Zdrojak.cz (czech blog about technology)

From the footer:
<img width="527" alt=" 2023-09-21 v 8 29 52" src="https://github.com/bluesky-social/social-app/assets/105520/323b12ec-7b8b-47cb-8a8b-e5e3d288475a">

B&W small version
<img width="357" alt=" 2023-09-21 v 8 29 43" src="https://github.com/bluesky-social/social-app/assets/105520/c3aa1b6e-33a6-48e9-b9e5-f683c8ac0a14">

**Comment by tvanantwerp** [comment]
Should this be considered closed by #2301?

**Comment by pfrazee** [comment]
Yes indeed!
