### ISSUE TITLE
Show full domain to add TXT for in handle update modal

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#1087]
When setting a custom domain handle, the ”well-known” method tab updates with the domain name you enter which makes the instructions very clear. But for the DNS method tab, it just says to add a TXT for ”_atproto” regardless of what you typed in the handle field. I think it would be more user-friendly and clear to display the full domain name in the instructions. It would reduce confusion especially when setting a subdomain handle. Essentially, it’s probably clearer to say add this TXT record for ”_atproto.my.domain.com” than just ”_atproto”.

**Comment by pfrazee** [comment]
@alimony That is originally what we did but people would frequently copy the value as given into their settings panel, leading them to register `_atproto.bob.com.bob.com` instead of `_atproto.bob.com`. I've received far fewer support requests since making this change.

**Comment by alimony** [comment]
Interesting piece of real-world data! Maybe updating the paragraph above it to be more explicit could help:

<img width="523" alt="Screenshot 2023-08-02 at 22 14 37" src="https://github.com/bluesky-social/social-app/assets/331091/2e9e29b7-feac-4e16-a7c0-9d545fe6d6da">

<img width="526" alt="Screenshot 2023-08-02 at 22 15 07" src="https://github.com/bluesky-social/social-app/assets/331091/1641a3c8-579e-4717-a543-68afdef4cebf">

Maybe also add a link in there somewhere to the documentation on custom handles, which also [someone said](https://bsky.app/profile/jayispainting.earthskyart.ca/post/3k3ws5hs5wx2i) isn't super clear on subdomains.

**Comment by pfrazee** [comment]
Proposing this in a PR, we'll see if it passes review:

<img width="398" alt="CleanShot 2023-08-21 at 19 40 54@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/6818b9ed-a665-40d4-992d-cc2cd8652a6b">
