### ISSUE TITLE
"See more from" in My Feeds going to wrong link

### ISSUE THREAD

**Issue by SenpaiSharp** [bluesky-social/social-app#1088]
**Describe the bug**

The **See more from [. . .] feed** goes to an erroneous link to a feed that doesn't exists, because it's using the user handle of the the feed creator rather than the did.

**To Reproduce**

1. Go to My Feeds.
2. Scroll down a feed to get to the "**See more from**" link.
3. Click it and go to the page it takes you to.

**Expected behavior**

The URLs for feeds have always used did instead of user name, from what I've always noticed. If I replace the user name with the proper did, I'm shown the feed that I am expecting. 

**Screenshots**

![wrong](https://github.com/bluesky-social/social-app/assets/36146858/bc7d027e-d493-4f06-bdfa-8e82557c2daf)

![right](https://github.com/bluesky-social/social-app/assets/36146858/f664a527-7ad8-4ff3-9a02-fd4741739670)

**Details**

 - Platform: Windows Desktop

**Additional context**

This seems like a very recent change? Maybe user handle is intended to be a valid link in a coming update but that seems not like a great idea?

**Comment by pfrazee** [comment]
Ah shoot. I believe we do want to use the handle, we just need to resolve the handle to a DID before sending the query. @estrattonbailey I'm going to punt this one to you.
