### ISSUE TITLE
Link Cards not working?

### ISSUE THREAD

**Issue by jolyonralph** [bluesky-social/social-app#1100]
**Describe the bug**
I am unable to get the link cards from my site to work.  Checking the logs on my site it doesn't appear there was any attempt to access this particular page (chosen for the test)

**To Reproduce**

1. Add a link to https://mindat.org/photo-918742.html and see if a link card appears

**Expected behavior**

A link card appearing

**Details**

 - Operating system: Chrome, Windows 11

**Additional context**

This might be as documentation issue about the link cards.  Need to know how they are obtained, what user agent to search for in the logs, because it may be our system has detected automated access pretending to be a regular browser and blocked it. I can whitelist BlueSky *IF* I know either the IP range of the crawlers or there is a user agent for bsky access to the page.

Here is an example of how it appears in my log when the same link is posted in Twitter, which is expanded correctly to show the image.

199.16.157.169 - - [02/Aug/2023:23:24:14 +0000] "GET /photo-918742.html HTTP/1.1" 200 13883 "-" "Twitterbot/1.0"

<img width="443" alt="image" src="https://github.com/bluesky-social/atproto/assets/15212030/8096dcfc-6b43-462a-9706-6b33e129d53c">

**Comment by pfrazee** [comment]
Actually we use the cardyb service now, so this is a @Jacob2161 question

**Comment by Jacob2161** [comment]
This is due to the fact that Cloudflare is blocking the `cardyb` service's request. I'm in contact w/Cloudflare and they've offered to help, so this should be resolved soon.

**Comment by jolyonralph** [comment]
Thank you all!

**Comment by MichaelGHUser** [comment]
Will this address link cards not showing up in Discord?  I have been having to use a third-party redirect for previews to show up.

**Comment by Jacob2161** [comment]
Cloudflare has very kindly attempted to fix this issue for us, so for example link cards for `https://mindat.org/photo-918742.html` should work now.

**Comment by Danie10** [comment]
@Jacob2161 that test link is also not showing any image returned in the card for me - using the desktop browser to Bluesky. Found this issue as I've been having the same problem with my own website sites (also behind Cloudflare) and it seemed to be a Cloudflare related issue, as other links do show the image fine with the card view.

Maybe it is also an issue with the browser version of Bluesky?

**Comment by Jacob2161** [comment]
@Danie10 that link `https://mindat.org/photo-918742.html` is now returning a 403 Forbidden response and it seems to be done at the server itself not by Cloudflare.

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

If you want to share a link to your web site I'd be happy to check what the problem is and try to fix it.

**Comment by Danie10** [comment]
Hi @Jacob2161 thanks yes an example post link is https://gadgeteer.co.za/how-to-protect-ssh-login-with-fail2ban-a-beginners-guide/.  It does have Open Graph tags set, and is pulling through OK to Twitter and through my RSS feed to other sites. But yes it does have Nginx PM in front too.

**Comment by Jacob2161** [comment]
@Danie10 it looks like grabbing all the meta data is working just fine but the image isn't being served with a `Content-Type: image/webp` as the `cardyb` service currently requires. Maybe it shouldn't require a valid header but it does right now.

If you want to change that on your end, it may be that `/etc/nginx/mime.types` is missing a `image/webp webp` line on your server or something like that.

**Comment by Danie10** [comment]
Ah thanks a lot @Jacob2161 - yes when I tried one of my older posts that still used JPG, it created the card fine with the image pulled in. Well that explains my issue then and it is not Cloudflare. I'll look into what you suggested around the serving of the WEBP format.
