### ISSUE TITLE
Suggestion: rename "Share" button on the web to "Copy link"

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#1107]
**Is your feature request related to a problem? Please describe.**

Since in the web version the "Share" button simply copies the link to a post/profile to the clipboard (unlike in the mobile app, where it displays the native share sheet), I think it would be a bit clearer if it said something like "Copy link" or "Copy link to post/profile" instead.

(It could also use a more link-like icon like Twitter does)

(On mobile it should stay "Share" since it does something else)

Here's how it looks on Twitter:

<p><img width="303" src="https://github.com/bluesky-social/social-app/assets/28465/ba0f65e4-a90a-48ba-a453-1400f13ed814"></p>
<p><img width="334" src="https://github.com/bluesky-social/social-app/assets/28465/661f8711-115b-4118-9e80-56e254fca78d"></p>

Bluesky version:

<p><img width="270" src="https://github.com/bluesky-social/social-app/assets/28465/35fbd169-12df-4476-9f44-c17b27294a1b"></p>
<p><img width="262" src="https://github.com/bluesky-social/social-app/assets/28465/87d47a3c-83c6-46d3-8715-1b7745a7c204"></p>

**Comment by pfrazee** [comment]
That seems legit, @estrattonbailey can you hit this?
