### ISSUE TITLE
Feed wont be showed under Discover or My Feeds

### ISSUE THREAD

**Issue by skyerjoe** [bluesky-social/social-app#1112]
**Describe the bug**

When i subscribe to a feed list or just discover them , the list is empty  or it shows an error.

**To Reproduce**

**Feed itself** 

- Got to an Feed over "Discover Feeds" like the feed "Whats Science"

- Tap into it then it comes "This List is Empty" ,

_**Adding Feed:**_

- Add the Feed over "+" to ur Feeds 

-  Go to my Feeds

- Tap "see from discover" there comes the error "could not find feed"  and under it This list is empty  
     
**Expected behavior**

The Feed should showing up correctly 

**Screenshots**

![IMG_20230805_150053_2](https://github.com/bluesky-social/social-app/assets/1038130/40feb0d5-5657-4a65-bed4-be3156eaa87b)

![IMG_20230805_104152 (1)](https://github.com/bluesky-social/social-app/assets/1038130/48729974-ba4a-4211-9b83-79d47b1d8915)

**Details**

 - Platform:  
 **Android** 
 - Platform version:
 **Miui 12.5.1 Based on Android 11**
 App version: 
 1.42.0 (28) Production

**Additional context**

best regards

**Comment by skyerjoe** [comment]
Do u have an apk version from it ? 
Im not a dev so im not able to compile an apk.

Best regards

**Comment by skyerjoe** [comment]
I downloaded the 1.4.3  it from apk mirror ( play Store not rolled out yet ) . Same behaviour nothing has changed. 

Best regards

**Comment by skyerjoe** [comment]
The only feed  which wirks flawless on any device ( phone,web) is "whats hot classic"

**Comment by estrattonbailey** [comment]
Hey! Thank you for the updates. So to summarize:
- Feeds _do not work_ on your phone (except What's Hot Classic)
- Feeds _do work_ on your old Huawei

Is that correct?

**Comment by estrattonbailey** [comment]
Apologies, I mistakenly wrote `1.4.3` instead of `1.43.0`. Also, we've since updated to `1.44.0`. Can you please upgrade to `1.44.0` from the Play Store and see if that works?

**Comment by skyerjoe** [comment]
Helio @estrattonbailey 
I have it already same errors  and also in the brower.( Ff/kiwi browser) 

Moreover there was an error on the classic feed ( wont fetch  old threads, reload error)  on  Browser and Xiaomi device.

Best regards.

**Comment by estrattonbailey** [comment]
Just returning to provide an update 👋  we still cannot reproduce this issue, unfortunately 😕

I'm going to close for now, but we can reopen at a later date if this surfaces again ✌️
