### ISSUE TITLE
DMs, direct messages

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1114]
**Is your feature request related to a problem? Please describe.**

I browsed all open issues but did not see the wish for DMs / direct messages. 
(If I just overlooked it, it's enough to post a link and close this thread.) 
 
I know that for some people it's the only thing that keeps them from shutting down their twitter account. 
  
**Describe the solution you'd like**

I like how it worked in the end at twitter: you could decide if you wanted to open DMs to everybody or not.

**Describe alternatives you've considered**

If it's easier, only opening DMs between people who follow each other would also be ok (this is how it was for a long time at twitter). 

**Additional context**

Kudos for making this public.

**Comment by mschwendener** [comment]
"eventually but that'll be a bit out"

https://bsky.app/profile/pfrazee.com/post/3k6bt5gx4c72m

**Comment by mschwendener** [comment]
https://bsky.app/profile/bsky.app/post/3krwrn4rato2z   :-)

**Comment by mschwendener** [comment]
This can be closed :D 

https://bsky.social/about/blog/05-22-2024-direct-messages

**Comment by haileyok** [comment]
@mschwendener Thanks for sticking around and being so patient waiting on this :)

**Comment by mschwendener** [comment]
Will be interesting to see if this triggers a spike in new accounts.

**Comment by surfdude29** [comment]
> Will be interesting to see if this triggers a spike in new accounts.

It will, and I'll also be keeping a close eye on Eric Davis's graphs of user numbers:

https://bskycharts.edavis.dev/edavis.dev/bskycharts.edavis.dev/bsky_users_total.html
