### ISSUE TITLE
Link card: ability to keep the text, but delete the picture

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1118]
**Is your feature request related to a problem? Please describe.**

Link cards as they are displaying at the moment are not elegant.
 
**Describe the solution you'd like**

I'd like the possibility to keep the text of the link card in the 'preview' display, but delete the picture if I don't like it / when it doesn't look good. 

**Describe alternatives you've considered**

**Additional context**

In the screenshot, for example, I'd like to show the lower part with the text as a link card, but without the image above it. 

<img width="591" alt="screenshot_4468" src="https://github.com/bluesky-social/social-app/assets/4497705/dfc89a51-d432-44a8-9f42-0f81875e6260">

But in other cases the image looks good and I'd want to keep it.

**Comment by mschwendener** [comment]
As an alternative: place the picture left of the text instead of above it = would make the picture smaller 

But it does happen in many cases that I'd like to show the preview of the text (via link card), but find the picture ugly or unfitting. 

<img width="583" alt="now" src="https://github.com/bluesky-social/social-app/assets/4497705/9ccb2cc8-c396-4273-af04-9763e16cecbf">

<img width="535" alt="twitter" src="https://github.com/bluesky-social/social-app/assets/4497705/b61fb8cb-acaa-4098-aefb-977f824a0cec">

**Comment by pfrazee** [comment]
I'll poke around at it

**Comment by mschwendener** [comment]
Hi 

Does posting here reopen the issue or should I start a new one with the same feature request? 

Example from today: 

https://bsky.app/profile/manuschwendener.bsky.social/post/3kjv6qilvx22x 

I would like to keep the link card with the text, but without the picture 

![lc](https://github.com/bluesky-social/social-app/assets/4497705/240ab954-c2b0-44e3-a74a-a35f2a921a7b)

**Comment by surfdude29** [comment]
> As an alternative: place the picture left of the text instead of above it = would make the picture smaller
> 
> But it does happen in many cases that I'd like to show the preview of the text (via link card), but find the picture ugly or unfitting.

This would be similar to what Telegram offers as an option (except the picture appears on the right) and I think it works well. You can tap Shrink Photo and the photo preview appears as a small square instead of a large rectangle:

![IMG_6732](https://github.com/bluesky-social/social-app/assets/149612116/b8a14d3d-bb7c-4e18-b036-7d5cae8db19b)
![IMG_6734](https://github.com/bluesky-social/social-app/assets/149612116/380f90b2-8af9-4f23-857e-b7579913963c)

**Comment by mschwendener** [comment]
Oooh, thank you! "Shrink photo" would be great! :D

**Comment by mschwendener** [comment]
I would really like an option to remove the picture from a link card and just keep the text. 

Or, if that's not possible, a way to make the picture smaller.

**Comment by mschwendener** [comment]
I see https://github.com/bluesky-social/social-app/pull/1190, but this is not what I see in my posts. 

Preview
[
![preview](https://github.com/bluesky-social/social-app/assets/4497705/99eed3c4-5d6c-4b87-a564-00dab88e9217)
](url)

Post
![post](https://github.com/bluesky-social/social-app/assets/4497705/b26f3ec3-6383-412c-9539-6bde72c265f1)

**Comment by steveharoz** [comment]
I want to add another voice to the request to have an option to hide the image in link cards. For sites with lots of articles, the image is just a logo that's it's the same for every page.

Shrinking the image may be a good option too.

![image](https://github.com/bluesky-social/social-app/assets/2257540/264f81e3-897d-46b5-b75d-54a98a2389d8)

![image](https://github.com/bluesky-social/social-app/assets/2257540/2beca339-88c2-4f51-ba50-070d5df558b5)

![image](https://github.com/bluesky-social/social-app/assets/2257540/b0d24d9d-8ca6-454d-9d49-e2828fa839c9)

**Comment by mschwendener** [comment]
I would really like an option to suppress or minimize the photo of the link cards – this is ugly. 

<img width="347" alt="screenshot_4965" src="https://github.com/bluesky-social/social-app/assets/4497705/b084fdb1-63a1-49ec-8a18-b75ad5cd8835">

**Comment by mschwendener** [comment]
Why has this been closed? 

![pic](https://github.com/user-attachments/assets/090e5cd2-888c-4620-bf1c-12b78bfbeab5)

**Comment by mschwendener** [comment]
<img width="621" alt="screenshot_5052" src="https://github.com/user-attachments/assets/700877ac-26de-4a58-afdc-a350c1361635">

**Comment by mschwendener** [comment]
This bugs me in about half of my posts. Pretty please? 

I'd really like to keep the text in the link card but either delete or minimize the picture. The way it is at the moment is just ugly in so many cases. 

![Uploading screenshot_5075.png…]()

**Comment by mschwendener** [comment]
And why is the thread closed??

**Comment by mschwendener** [comment]
This had been fixed in August 2023, but then broke with a later update. How do I reopen?

**Comment by mschwendener** [comment]
To be clear: the default can stay as it is (example https://bsky.app/profile/manuschwendener.ch/post/3l5s2r4c5jn2c ); I only need a way to get rid of the picture when the link card otherwise looks bad.

**Comment by mschwendener** [comment]
So ugly 
![Uploading screenshot_5184.png…]()

**Comment by mschwendener** [comment]
Could we just get a second " X " button? The one in the picture would just remove the picture, the one connecting the picture and the text would remove both. 

![screenshot_5189](https://github.com/user-attachments/assets/06d9424c-4539-4d35-8c08-79b5effa5054)

**Comment by mschwendener** [comment]
Can this please be reopened?

**Comment by mschwendener** [comment]
*Bump*

Why is this closed? It's not fixed, or rather: the fix got lost again.

![Image](https://github.com/user-attachments/assets/ec52cec3-0b8f-4946-84e1-3805ba34b824)

**Comment by mschwendener** [comment]
See also https://github.com/bluesky-social/social-app/issues/7443

**Comment by mschwendener** [comment]
Why has this been closed? It's still ugly 

<img width="646" height="626" alt="Image" src="https://github.com/user-attachments/assets/b54a83e4-c10b-46eb-ad30-582d929ddb8b" />

**Comment by surfdude29** [comment]
@estrattonbailey @mozzius Could this be reopened please? As @mschwendener rightly points out, it's still an issue.

**Comment by mschwendener** [comment]
<img width="601" height="483" alt="Image" src="https://github.com/user-attachments/assets/c1265074-ca23-4942-a1e7-b5d1ece6884a" />

**Comment by mschwendener** [comment]
<img width="595" height="494" alt="Image" src="https://github.com/user-attachments/assets/d984727f-7e0a-497f-9398-c999c62b812c" />

**Comment by mschwendener** [comment]
I don't understand that not more people seem to mind this.

**Comment by mschwendener** [comment]
@abenzer 

Related to "why is post editing important to you?" 

https://bsky.app/profile/alexbenzer.com/post/3mlvrfztuvu25

**Comment by mschwendener** [comment]
https://bsky.app/profile/status.1password.com.web.brid.gy/post/3mlyuyjtw45t2 

<img width="593" height="469" alt="Image" src="https://github.com/user-attachments/assets/24e465ca-16f4-41a6-b773-65ade8bce0cb" />

**Comment by mschwendener** [comment]
Shrinking the photo, as @surfdude29 proposes here https://github.com/bluesky-social/social-app/issues/1118#issuecomment-1912093188 would also be an option.

**Comment by mschwendener** [comment]
<img width="659" height="1158" alt="Image" src="https://github.com/user-attachments/assets/1eef396a-a86e-4b9f-91bf-9868ec3c3543" />

**Comment by mschwendener** [comment]
Many recent examples here https://github.com/bluesky-social/social-app/issues/5263, which now has been closed.

**Comment by mschwendener** [comment]
This one https://github.com/bluesky-social/social-app/issues/7443 is open, but it's about the preview (which yes, would help..)

_Edit:_ open, but not assigned to anybody.
