### ISSUE TITLE
Make cropping the header image easier

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1119]
**Is your feature request related to a problem? Please describe.**

Uploading the header image is not as easy as it should be. 

**Describe the solution you'd like**

When my picture does not have the proportions it needs to be the header image, allow me to decide which part to keep (= cropping step during upload). 

**Describe alternatives you've considered**

Tell me somewhere which dimensions/proportions the picture needs to have to be used 1:1 as the header picture. 
 
**Additional context**

I used Chrome on Mac (worked better than Firefox). Not completely sure if this is a feature request or a bug report.

**Comment by HeyItsLollie** [comment]
I believe this is related to #760, and it is a bug.

One workaround is to use the mobile app: If you're able, send the image to your phone, and save it to your phone's gallery. Then you'll be able to update your profile's header image via the Bluesky app.

**Comment by mschwendener** [comment]
Thank you @HeyItsLollie - glad to know this will be worked on. I'll follow #760.  

Closing as duplicate.
