### ISSUE TITLE
discover feeds search wrong query sent 

### ISSUE THREAD

**Issue by UXDart** [bluesky-social/social-app#1120]
**Describe the bug**
search feeds is not sending last character keypress/keydown used

**To Reproduce**

go to https://bsky.app/search/feeds
search for "zz"
add another "z"
in the console you can see the query sent is "zz" not "zzz"

to be more clear add in the search "2"
and not query is "zzz" (without the "2")

**Expected behavior**

without looking at the console is not simple to see, but send correct query param to api

**Details**

web / chrome / macos

**Comment by pfrazee** [comment]
Huh, we somehow dropped some changes I made here. I'll fix this up. Thanks for the report
