### ISSUE TITLE
Seemingly empty alt text due to special whitespace chars

### ISSUE THREAD

**Issue by emmagamma** [bluesky-social/social-app#1124]
**Describe the bug**
I recently saw a post where the author had added the blank space character (char code: 32) as the only alt text, resulting in the alt banner appearing over the image, but then there's no actual alt text.

so it's currently possible to include only whitespace as the alt text, with no other characters present.

**To Reproduce**

1. make a new post containing an image
2. add the alt text " " <- copy paste this or use String.fromCharCode(32), or any other special whitespace char you wanna test.

**Expected behavior**

if the alt text contains ONLY special whitespace characters, strip them out.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/5084142/e667173f-54e2-44a0-bd3a-1f6625dc128e)

![image](https://github.com/bluesky-social/social-app/assets/5084142/43844008-15bd-4997-a716-c6cb2a8dce12)

**Details**

 - Platforms: all
 - Platform version: n/a; latest
 - App version: latest

**Additional context**

seems like there's a few ways this could be solved
but the right way is probably just adding a guard to the model or sanitizing for special whitespace chars when the alt text is set: [setAltText in the image model](https://github.com/bluesky-social/social-app/blob/89fc975a150d8c1f79d2a728f9f252fc3438a613/src/state/models/media/image.ts#L123-L125)

**Comment by pfrazee** [comment]
@ansh handing to you
