### ISSUE TITLE
[Android] Swiping left on the Following feed to get to the flyout menu is laggy

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/social-app#1127]
**Describe the bug**

The flyout menu that opens when a user swipes left on the Following feed is consistently laggy every time I attempt to open it.
This rarely has the intended effect.

**To Reproduce**

1. Swipe left on the Following feed
2. Observe that the animation is not smooth.

**Expected behavior**

The menu should not noticeably lag. The app slows down when I swipe to open the menu.

**Details**

 - Platform: Android
 - Platform version: Android 13, Google Pixel 4a 5G
 - App version: 1.43.0

**Additional context**

A thin white line to the right of the menu flickers when I open it.

**Comment by pfrazee** [comment]
@ansh Handing this one to you

**Comment by ansh** [comment]
Unfortunately, this is a consequence of our app running on a older device. We are working on optimizations to make it run well on devices of our types and ages, but it will take a while.

**Comment by heikadog** [comment]
it's not that old—it *just* turned 3 this month and it still runs android 13. but i get what you're saying!

**Comment by ansh** [comment]
@heikadog  Could you share a screen recording of this issue?

**Comment by heikadog** [comment]
Seems like most of the issue has been fixed. Closing this!
