### ISSUE TITLE
"Load new posts" obscures post at top of feed

### ISSUE THREAD

**Issue by HeyItsLollie** [bluesky-social/social-app#1130]
**Describe the bug**
The "Load new posts" button appears over the top-most post, often obscuring its contents.

![firefox - 2023-08-08 - 20-10-51](https://github.com/bluesky-social/social-app/assets/30498581/a08afecf-6a6c-4423-b2cd-722388abe090)

**Details**

 - Platform: Windows 11, Firefox

**Additional context**
One easy fix would be to move the button to a position above the Feed. eg:

![firefox - 2023-08-08 - 20-23-45](https://github.com/bluesky-social/social-app/assets/30498581/0867391f-40c5-4602-994b-99d4e1cbbdf8)

**Comment by pfrazee** [comment]
Yeah this is bugging me too. Putting it in the feed causes some layout difficulties (it would bump posts down) so we need to figure out how to handle this.

**Comment by HeyItsLollie** [comment]
There's room to place it in the feed's tab itself too, which wouldn't bump posts down. Could be done via a little "refresh" notification badge, or by expanding the tab's highlight upwards.

![Bluesky - New Post Notification](https://github.com/bluesky-social/social-app/assets/30498581/1691d4c0-7174-471d-a240-e601ef3a23ad)
![Bluesky - New Post Bar](https://github.com/bluesky-social/social-app/assets/30498581/009458da-7cc6-49bc-8afa-9ae95d176240)

**Comment by emmagamma** [comment]
@pfrazee why not just bump the posts down to begin with? just by about 72px (48px for the button and 12px of spacing on top and bottom)... the extra space above the top post would 'disappear' naturally as you scroll down without having to adjust the vertical positions of anything, and the `load new posts` button could just drop down into that space.

**Comment by pfrazee** [comment]
This is fixed in the upcoming 1.51 release
