### ISSUE TITLE
race condition - get set preferences

### ISSUE THREAD

**Issue by UXDart** [bluesky-social/social-app#1139]
**Describe the bug**
I can see that to save preferences a "read and save" happens, but it seems a race condition can be done opening just two tabs same page

**To Reproduce**

for example go to https://bsky.app/profile/bsky.app in two tabs
be already in the first feed but not in the second one
in first tab click on remove (trash icon) and very fast go to second tab
on second tab add second feed 
now fast go to first tab and click on confirm

you are not in any of both feeds now (I saw different results also)

there is an automatic refresh of the preferences, if that refresh happens it works, I assume that when the confirm dialog shows the auto refresh is not happening that fast. but even if it is happening you can be in 5 tabs also

**Expected behavior**

IMO read/write will be always a problem. one solution at least to mitigate it, broadcast changes on preferences to tabs. on one browser a host.domain can broadcast to same host.domain msgs. broadcast that a change happened. that way without realtime updates you know a change happened in another tab. anyway if you are in mobile and at the same time on web, read/write will be a problem...

**Additional context**

wasn't sure to write it here or in the protocol repo. not sure why an updatePreferences isn't there? it is because of how preferences are stored?

**Comment by pfrazee** [comment]
Yeah the app was originally written with mobile in mind so cross-tab sync wasn't considered, and it needs to be. This is also why folks get logged out of the web app occasionally. We need to introduce some syncing primitives to counteract this.
