### ISSUE TITLE
Keyboard input on Android misses a ton of touches causing frequently garbled text

### ISSUE THREAD

**Issue by jetpacktuxedo** [bluesky-social/social-app#1145]
**Describe the bug**
At some point seemingly within the last month or so the Android app started dropping a lot of keyboard input. I cannot reproduce on mobile web.

**To Reproduce**

1. Use the Android app
2. Type a post or reply

**Expected behavior**

Accept all input like every other app seems to do

**Screenshots**

Here's a video of it in action. You can see that it really likes missing the space bar, and I have "show touches" on so you can tell I'm actually hitting it.
https://youtube.com/shorts/LaBMKucMj5o?feature=share

**Details**

 - Platform: Android
 - Platform version: Android 13 with August security update
 - App version: 1.43.0

**Additional context**

**Comment by pfrazee** [comment]
Did this happen to start recently (within the last few weeks)?

**Comment by jetpacktuxedo** [comment]
I would say yes as long as "last few weeks" is pretty rough. I don't remember exactly when it started (because it took a while to realize it didn't happen everywhere), but it has definitely been more than one week and less than six weeks.

I also just verified that it seems to only happens with the on-screen keyboard and doesn't happen if I plug an external keyboard into my phone.

**Comment by pfrazee** [comment]
Yeah I'm wondering if it was caused by https://github.com/bluesky-social/social-app/pull/1033, which is a hack we introduced to handle issues with the textinput failing to render styles correctly.

**Comment by jetpacktuxedo** [comment]
That would have probably updated in-app on the 19th or 20th I guess? That seems like a plausible point-in-time to me I think.

**Comment by jetpacktuxedo** [comment]
This seemed better for a few days, but came back again this morning as bad as ever. Not sure why it improved or returned though, or if anything even changed.

**Comment by jetpacktuxedo** [comment]
Oh actually I think I figured it out. Rebooting my phone seems to have (almost certainly temporarily) fixed it. I had an android update earlier in the week which is probably the reboot that resolved it last time. So I guess repro instructions should also include "don't reboot your phone for a while" (unsure if "heavily use bluesky between reboots" is also a requirement, I can't really control for that).

**Comment by pfrazee** [comment]
A phone reboot could just indicate that there's a memory leak or similar that's causing a performance regression which manifests this way.

I'm testing a replacement for our text editor to see if we can't fix the issue that way

**Comment by jetpacktuxedo** [comment]
Memory leak or similar should be cleared by an app restart though (unless it's somehow causing the OS itself to leak memory) I think? Force closing the app doesn't resolve it for me, so I think something weirder is going on.

**Comment by pfrazee** [comment]
I'm not convinced of it, but it's possible that #2351 will fix this

**Comment by pfrazee** [comment]
How are things looking since the latest update?

**Comment by jetpacktuxedo** [comment]
Seems good so far, but it had also become much much less frequent. I'll drop an update if I notice it again in the next couple of weeks 🤞

**Comment by pfrazee** [comment]
That's wonderful to hear. I'm going to optimistically close but please do let us know if it happens again

**Comment by jetpacktuxedo** [comment]
I think I am still hitting this 😞
Not with the frequency or severity I was when I first opened it, but it definitely still seems present post- #2351
