### ISSUE TITLE
android app crashes immediately after showing the first screen

### ISSUE THREAD

**Issue by TheAwesome98-Real** [bluesky-social/social-app#1146]
**Describe the bug**
the android app crashes immediately after showing the full-screen sky background (doesn't have any other controls on it like logos or buttons)

**To Reproduce**

1. install the app from play store
2. run it
3. it crashes

**Expected behavior**
it shouldn't've crashed

**Screenshots**
n/a

**Details**

 - Platform: Android
 - Platform version: 12
 - App version: 1.43.0

**Additional context**
n/a

**Comment by SaxxonPike** [comment]
This is happening on my phone, and has been happening for a couple weeks now. I have to use the browser to access Bluesky from my phone for the time being.

Google Pixel 5
Android 13
App version 1.43.0

**Comment by pfrazee** [comment]
@ansh Going to hand this one to you, maybe sentry has some info for us

**Comment by ansh** [comment]
@TheAwesome98-Real Does this happen every single time?

**Comment by TheAwesome98-Real** [comment]
> @TheAwesome98-Real Does this happen every single time?

yes, every single time without fail

**Comment by ansh** [comment]
Really sorry about that @TheAwesome98-Real 

I am looking into this issue now

**Comment by Maxwell-Fisher** [comment]
Happens to me too on Pixel 6
App version `1.43.0`
Android version `13 (build TQ3A.230705.001.A1`

**Comment by ansh** [comment]
@SaxxonPike Can you give more details about which phone you have? Pixel? Which model?

**Comment by ansh** [comment]
There seems to be a bug plaguing Pixel devices mainly. 

`Exception in HostFunction: Incompatible object passed to scheduleOnJS. It is only allowed to schedule functions defined on the React Native JS runtime this way. ` due to the Reanimated library.


<img width="351" alt="CleanShot 2023-08-15 at 17 04 08@2x" src="https://github.com/bluesky-social/social-app/assets/8207733/538acc40-1d77-451d-a005-064dfe31e76c">

**Comment by pfrazee** [comment]
No stack traces?

**Comment by ansh** [comment]
@pfrazee Unfortunately not since the error is happening purely on the native side of things
