### ISSUE TITLE
While writing a post, it looks as if I can link words - but after posting, the link is stripped

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1149]
**Describe the bug**

While writing a post / reply in Chrome on Mac, I can mark a word, add a link with ctrl&v, and the word looks clickable. 

After saving the post, the links are stripped. 

**To Reproduce**

Copy an URL to your clipboard (ctrl&c), start writing a post, mark a word in the post and use ctrl&v 

**Expected behavior**

Either make the link work, or somehow disable that it looks like a link while I'm typing 

**Screenshots**

<img width="612" alt="screenshot_4471" src="https://github.com/bluesky-social/social-app/assets/4497705/08326e4a-945b-4fb2-a044-a771b2ac7194">

**Details**

 - Platform: desktop, chrome on macbook pro
 - Platform version:
 - App version:

**Comment by Zero3K** [comment]
I also notice it when copying a URL from the address bar in Edge, etc. and pasting it into the box for making a new post.

**Comment by mschwendener** [comment]
Hi

If the fix is not live yet, you can ignore the rest of this post. 

----

This is not fixed for me on desktop (Chrome on Mac). 

Example from just now: 

My post https://bsky.app/profile/manuschwendener.bsky.social/post/3k5ags4hmcr2t - 

while I was writing it, it looked like this: 

<img width="584" alt="screenshot_4483" src="https://github.com/bluesky-social/social-app/assets/4497705/31f0f077-6da7-48f2-9c1c-305657391fa2">
