### ISSUE TITLE
Blocking an account should prevent that account from seeing my posts and following me 

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1162]
**Is your feature request related to a problem? Please describe.**

Blocking in bluesky: 

![bluesky](https://github.com/bluesky-social/social-app/assets/4497705/ece93336-ed2b-4a83-b293-5a93e46ad54d)

**Describe the solution you'd like**

I'd expect it to behave like 

twitter
![tw](https://github.com/bluesky-social/social-app/assets/4497705/a2fa6d08-e306-47c5-8148-9ead86fa58e1)

instagram
![ig](https://github.com/bluesky-social/social-app/assets/4497705/c4b0d3b7-6eca-4e25-8739-b103de87781b)

facebook
<img width="379" alt="fb" src="https://github.com/bluesky-social/social-app/assets/4497705/597fa94c-b418-44ff-9f3f-3c955c0f974f">

An account that I block should no longer see my posts or be able to follow me. 

-----
 
(related https://github.com/bluesky-social/social-app/issues/1160)

**Comment by pfrazee** [comment]
This is what blocks already do

**Comment by mschwendener** [comment]
Thank you, good to know. Maybe edit the text in screenshot 1 to reflect that?

**Comment by mschwendener** [comment]
On the block list 

"Blocked accounts cannot reply in your threads, mention you, or otherwise interact with you. **You will not see their content and they will be prevented from seeing yours."**

Message before I block somebody 

"Blocked accounts cannot reply in your threads, mention you, or otherwise interact with you."

It would [help](https://www.reddit.com/r/BlueskySocial/comments/15u8v4t/comment/jwsqzai/?utm_source=reddit&utm_medium=web2x&context=3) if the second one was an exact copy of the first one.
