### ISSUE TITLE
Profile posts tab shouldn't filter out self-threads

### ISSUE THREAD

**Issue by intrnl** [bluesky-social/social-app#1166]
**Is your feature request related to a problem? Please describe.**

In a social media where short-form text is the way to communicate, it often happens that you would create multiple chained posts, I usually refer this as "self-threading" as it is primarily a thread containing of only your posts.

Bluesky's profile posts tab currently filters out any subsequent posts within a self-thread, and that isn't nice for users who prefer this way of communicating, especially when they're coming from Twitter

**Describe the solution you'd like**

It would be nice if self-threads were not filtered out from the posts tab

**Describe alternatives you've considered**

None yet.

**Additional context**

None.

**Comment by pfrazee** [comment]
This one is a little challenging. We assemble threads in the client using replies. For the self-threads to be preserved we'll need to see if we can get the `posts` filter on the server send down posts that are part of a self-thread.

@estrattonbailey

**Comment by intrnl** [comment]
It's definitely not something that can be implemented easily yeah, because it's possible you run into this scenario

```
Alice
  Bob
    Alice
      Alice
```

if posts were being filtered out individually, then you can't tell if the last Alice post is part of a self-thread or not, both root and parent links to a post from Alice.

I suppose trying to join up the posts into slices before filtering them out would be a hassle to do from the server?

**Comment by pfrazee** [comment]
It's a hassle but it's not impossible, just have to give it a look

**Comment by mschwendener** [comment]
If it's easier: let the poster decide that now she's writing a thread = link the posts tighter together somehow? 

When I'm writing a thread, I know that in advance (example https://bsky.app/profile/manuschwendener.bsky.social/post/3k4cfnzvu3v2o). 

I also want to be able to add new posts to the thread, ideally without having any replies between my posts.

**Comment by estrattonbailey** [comment]
Just giving y'all an update 👋 

We've looked into this, and in general our threading capabilities atm are below where we'd like them to be. We're currently in the process of moving to a new database architecture that should improve this, and so we're going to wait to invest more time here until we've migrated to the new architecture.

We will improve this soon!
