### ISSUE TITLE
Profile media tab should filter out retweets

### ISSUE THREAD

**Issue by intrnl** [bluesky-social/social-app#1167]
**Is your feature request related to a problem? Please describe.**

on Twitter, people use the media tab to see media content coming especially from the author

so it is odd to see that Bluesky also shows reposts of a media content from a different user entirely

**Describe the solution you'd like**

It would be nice if reposts of other user's media content are filtered out, reposts of self media content is fine but not sure what the Art cluster et al thinks of this specifically

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by pfrazee** [comment]
Yeah I'm +1 to this, assigning to @estrattonbailey

**Comment by mschwendener** [comment]
Maybe post an update to https://bsky.app/profile/bsky.app/post/3k4z345e75d2e that this is planned? 

(in the meantime, it can be achieved via feed https://bsky.app/profile/did:plc:vc7f4oafdgxsihk4cry2xpze/feed/media)

**Comment by Zero3K** [comment]
Maybe you all can just replace the Media tab with that.

**Comment by intrnl** [comment]
Not how it works.

**Comment by Zero3K** [comment]
Okay.
