### ISSUE TITLE
darkmode bug - creator name on mute lists  link color is invisible

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#1170]
the creator of the mute list, name color - link is the same color as the background on dark mode.

ideally, i would like the name color to be a different color, like white or blue here. 

image of a users mute list - showing that their name is invisible unless its highlighted 
![image](https://github.com/bluesky-social/social-app/assets/66647238/f12aab5a-d7c3-4160-bbba-f81304d33209)

**Comment by pfrazee** [comment]
Fixed! Thanks for reporting
