### ISSUE TITLE
Feeds tab on profile page broke with latest update

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1172]
**Describe the bug**
 
 Can confirm from my own profile: clicking on the Feeds tab showed me the feed that I had done myself. 
 Now it is empty

https://bsky.app/profile/chrispywolf.bsky.social/post/3k4z4ycpriw2d 

https://bsky.app/profile/eustace.link/post/3k4z3pnagra2g 

**To Reproduce**

Click on your own Feeds tab? 
 
**Expected behavior**

Behaviour before it broke: I saw the feed 

<img width="586" alt="screenshot_4478" src="https://github.com/bluesky-social/social-app/assets/4497705/fead8cb8-a475-4ade-b39f-8560bc0992ba">

(not necessarily the behaviour I _did_ expect, but I didn't mind, either)

**Additional context**

https://bsky.app/profile/bsky.app/post/3k4z345e75d2e

**Comment by pfrazee** [comment]
Duplicate issue, fix is already merged and sent to review
