### ISSUE TITLE
[APP-808] Cmd+enter in the Web composer causes a newline to get inserted

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#1173]
It should trigger the post submission without weirdly modifying the input

<sub>[APP-808](https://linear.app/blueskyweb/issue/APP-808/cmdenter-in-the-web-composer-causes-a-newline-to-get-inserted)</sub>

**Comment by intrnl** [comment]
Passing true in the keybind handler like [this](https://github.com/intrnl/langit/blob/c4b7044182e06822a988acf6e5e066f56c33ffc0/src/routes/u.%24uid.compose/route.tsx#L473) tells ProseMirror/Tiptap to ignore subsequent keybinds like Enter on newline

**Comment by pfrazee** [comment]
@intrnl Wow you saved me a solid 15 minutes, thank you!
