### ISSUE TITLE
Don't list people I've muted on a list of follow suggestions

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#1185]
**Describe the bug**

When you open the search tab, the app shows suggestions of users that I can follow. The problem is, the third item in the "In your network" section was someone I had explicitly muted. I also saw some muted people (manually or through a mutelist) in other sections below ("Followed by X"). If I had muted someone, then I probably don't want to follow them to keep seeing what they post.

**To Reproduce**

1. Mute some people
2. Create a mute list and add some people there
3. Go to the search tab and look through the follow suggestions list -> some of the people from 1 and 2 might be there (with the "muted" badge)

**Expected behavior**

If I muted someone, they don't appear on the suggestions list in the search tab.

**Details**

 - Platform: web & iOS

**Comment by pfrazee** [comment]
Yeah that shouldn't be happening, I'll check into it
