### ISSUE TITLE
As an option, allow opening links on iOS in a SafariViewController

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#1186]
**Is your feature request related to a problem? Please describe.**

Some subset of iOS users prefers it when apps open links in an in-app browser (SafariViewController). The advantage is that you stay in one app and don't lose context instead of being redirected to a different app and have to go back, and you don't need to manually close the tab that was opened in Safari for you.

> @mergesort.me:
>
> I hate losing context, if I end up in another app there’s a good chance I’m going to be distracted and forget what I was doing. Especially when I click an article that takes 5-10 minutes to read, I’m not going to remember that I was browsing Bluesky and go back to that.

Other subset of iOS users prefers it when apps redirect to Safari instead. Some arguments for this are listed here: https://pspdfkit.com/blog/2019/open-links-in-safari-not-safari-view-controller/

These two are hard to reconcile and they both have good points, it just depends on the personal preference. So it's pretty common for apps that include a lot of user-generated links, like social media apps, to have a switch in the settings which allows you to choose whether you want to open links in an in-app browser or in the system browser.

**Describe the solution you'd like**

Some examples from other apps:

Ivory:

<p><img src="https://github.com/bluesky-social/social-app/assets/28465/b6ea5084-cbfa-4fbf-ab89-914a4f717658" width="400"></p>

ProtonMail:

<p><img src="https://github.com/bluesky-social/social-app/assets/28465/e98fac25-7ccb-49e0-b98c-3a808f9430fa" width="400"></p>

Tweetbot (old version?):

<p><img src="https://github.com/bluesky-social/social-app/assets/28465/e9f3262d-cc94-42cb-bb77-43d72528b1b7" width="400"></p>

**Comment by pfrazee** [comment]
We can consider this, I'm just somewhat inclined to avoid adding the code for something that's somewhat niche

**Comment by deceptionagent** [comment]
> We can consider this, I'm just somewhat inclined to avoid adding the code for something that's somewhat niche

in-app browsers via this API are commonplace on iOS, and users are generally used to having a setting to control whether links are in-app or to-browser. it's pretty standard here.

**Comment by haileyok** [comment]
@mackuba I'm pretty sure I understand this right and you're referring to what mozzius added, which lets you open up the links in either the app or by opening safari/default browser. If not lmk.

**Comment by mackuba** [comment]
@haileyok yeah yeah, this is what mozzius added, I forgot to close this one
