### ISSUE TITLE
Content in a `FlatList` not refreshing - pass the time that the data was last fetched to `FlatList`'s `extraData`

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1196]
**Describe the bug**

When refreshing any feed (but for example's sake, notifications), updated data will not show if the posts are the same as last time.

**To Reproduce**

1. Receive a post notification
2. Press notification, like post from /profile/xxx/post/xxx screen (also applies to repost/reply)
3. Return to previous page - post is not liked, but it's stale data so that's understandable
4. Refresh feed, and if you have no additional notifications, the post is still not liked

**Expected behavior**

The refresh refreshes the post data info (isLiked, isReposted, like/repost count, reply count)

**Details**

 - Platform: iOS, but will almost certainly apply to all platforms

**Additional context**

I ran into this on Graysky, since `FlatList` uses `PureComponent` it won't know to update the rendered post if the post ID is the same as the last time. It will only show the latest data when the order of the posts changes, for example by recieving a new notification.

 The solution is to pass something that uniquely identifies the request to `extraData` to force a rerender - Graysky uses `dataUpdatedAt` from React Query, you might want to use something different since your abstractions are different.

**Comment by pfrazee** [comment]
I noticed it too, my theory was it might be the new caching layer but you might be right about the cause

**Comment by mozzius** [comment]
Oh yeah the caching layer, I could be wrong about the cause then. It just seemed suspiciously similar to one I had so I thought I'd share my solution :)

**Comment by mozzius** [comment]
99% sure my solution will not fix the issue actually - it is probably a local caching problem as you initially thought
