### ISSUE TITLE
Liking or reposting your own posts results in notifications

### ISSUE THREAD

**Issue by gensakudan** [bluesky-social/social-app#1201]
**Describe the bug**
When liking or reposting one of your own posts, you receive a notification for that.

**To Reproduce**

1. Find a post you've made, or make a new post.
2. Either like or repost said post.

**Expected behavior**

You should not receive notifications for likes or reposts of your posts if those likes or reposts came from yourself.

**Details**

 - Platform: Web browser version (https://bsky.app)
 - Platform version: Build version 1.45.0

**Comment by pfrazee** [comment]
@devinivy do you think we should solve this in backend or frontend? It's pretty easy to do frontend
