### ISSUE TITLE
Trailing whitespace in email field will cause sign in to fail

### ISSUE THREAD

**Issue by TheSofox** [bluesky-social/social-app#1202]
**Describe the bug**

**To Reproduce**

1. Go to https://bsky.app/
2. Sign in using email and password
3. See you've signed in successfully.
4. Sign out
5. Got to sign in again, but this time put a single space after your email address.

**Expected behavior**

You sign in successfully, since your details are correct and most platforms use a "trim()" to remove trailing whitespace from any username/email login details

**Actual behavior**

The login fails, unless you remove the space

**Additional context**

On Android phone I used autocomplete for the email address, but often adds a space after it by default. I couldn't figure out why I was signing in no problem on PC, but had problems on mobile, even though I used the same email and password.

**Comment by pfrazee** [comment]
passing to @ansh

**Comment by ansh** [comment]
Working on it
