### ISSUE TITLE
Make it easier to write to somebody when I'm looking at their profile

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1206]
**Is your feature request related to a problem? Please describe.**

I'm looking at a profile and would like to send that person a message / write to that person, but don't see a button or link to do so. 

**Describe the solution you'd like**

In twitter, when I look at a profile, and from there start a new message, the '@ profile handle' is pre-filled in my new message. 

In instagram, when I look at a profile, I have a 'Message' button. 

Im mastodon, when I look at a profile, I can click on the ... and have "Mention '@ profile handle' " – while that is a strange way to phrase it, it lets me send a message to the person. 

**Describe alternatives you've considered**

Typing @ and the person's handle – but that's so much work ;)   

**Additional context**

Desktop and mobile.

**Comment by ansh** [comment]
By message, you mean creating a post and automatically @ing them. Is that correct?

**Comment by intrnl** [comment]
this is a bit confusing, so let's make sure we're getting the definitions right here

the term messaging here usually refers to Private/Direct Messages which is a 1:1 conversation,

Instagram's Message button starts a Direct Message between you and them

Mastodon's "Mention @ profile handle" is a way to quickly create posts while mentioning said person

**Comment by mschwendener** [comment]
> By message, you mean creating a post and automatically https://github.com/ing them. Is that correct? 

Yes

> the term messaging usually refers to Private/Direct Messages which is a 1:1 conversation

Which are on the [roadmap](https://github.com/bluesky-social/social-app/issues/1114), I know.

---

I'm not saying everything needs to be exactly as it was on twitter – it's just that many people come from there and are used to how it worked. 

So trying to rephrase: 

When I look at a person's profile, I would like something I can click on that starts a post which already has their profile handle pre-filled without me having to type it.

**Comment by pfrazee** [comment]
Yeah this isn't difficult, I'm +1

**Comment by ansh** [comment]
In progress

**Comment by mschwendener** [comment]
This would be even better if there automatically was a space added after the handle.
