### ISSUE TITLE
Filtering Reposts in the Media Tab

### ISSUE THREAD

**Issue by Zoodee** [bluesky-social/social-app#1210]
The new media tab is a nice improvement, however I believe most users would prefer the media tab to not include reposts from other accounts. I personally used the media tab on (other site) to browse visual content created *by that user*, essentially to filter out reposts and text posts, and I think most other users used it the same way. If you'd rather not change the way the tab works completely then alternatively this could be some sort of toggleable option so that users can customise their experience as desired.

Additionally removing reposts, or making them optional, in the "Posts and Replies" tab would also be an improvement in my opinion.

**Comment by pfrazee** [comment]
This fix was server side, it has been merged and will roll out soon https://github.com/bluesky-social/atproto/pull/1486
