### ISSUE TITLE
Improve how the media tab handles threads

### ISSUE THREAD

**Issue by Zoodee** [bluesky-social/social-app#1212]
Currently the new media tab does not show all media when scrolling through it. Media within threads requires the someone browsing the tab click on "view full thread" to see that media, which could make sense in the main profile feed, but not in the media tab, where users are typically looking for a more exhaustive list of all media from the account.

Displaying media in thread form like this also prevents the media tab from being a fully chronological view of the media posted from an account, as you can scroll down seeing posts one by one in reverse chronological order except for posts in threads which are ordered by the chronology of the first media post in the thread, rather than when the reply iself was posted. If someone was to add an image as a reply to a month old thread that image would be a month back in their media tab despite having just been posted.

**Comment by intrnl** [comment]
just curious, is this something that Twitter also does? I know that the likes tab is not grouped at all but no idea about how media tab works there

**Comment by pfrazee** [comment]
@estrattonbailey I think this is similar to the question around threads in the posts tab, yeah?
