### ISSUE TITLE
[APP-829] Too many pinned feeds creates performance issues

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#1233]
See why this might be -- is it too many views in the pager, are we loading things optimistically when we shouldn't? Etc. Then see if there are some reasonable fixes available to us without changing the existing behavior. This might require unloading views from the pager if too many are there. (Realistically might not be possible to have more than 3.) 

<sub>[APP-829](https://linear.app/blueskyweb/issue/APP-829/too-many-pinned-feeds-creates-performance-issues)</sub>

**Comment by estrattonbailey** [comment]
Performance related to feeds should be improved after #1271, gonna close this
