### ISSUE TITLE
Image editor: Icons don't show up

### ISSUE THREAD

**Issue by fenarinarsa** [bluesky-social/social-app#1264]
**Describe the bug**

In the image editor/crop tool, the icons for "None", "flip vertically", "flip horizontally" don't show up correctly.

**To Reproduce**

1. Upload an image and open the edit tool

**Expected behavior**

** Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/17545417/50a7bcbd-9ac1-4ecb-a937-157c533b670d)

**Details**

 - Platform: Web  
 - Platform version: Firefox 116.0.3, Windows 11, French
 - App version: 1.46

**Additional context**

Seems like the selected Unicode characters don't exist everywhere. Maybe replace them with svg icons.

**Comment by mary-ext** [comment]
I believe this is fixed now
https://github.com/bluesky-social/social-app/blob/main/src/view/com/modals/EditImage.tsx

**Comment by haileyok** [comment]
Yep, thanks Mary!
