### ISSUE TITLE
Add the option to hide alt text on images

### ISSUE THREAD

**Issue by enmaku** [bluesky-social/social-app#1265]
**Is your feature request related to a problem? Please describe.**

Alt text is useful, but frequently covers the entire lower portion of tall images, making their lower portions unreadable.

**Describe the solution you'd like**

A button or swipe gesture to close the alt text panel, and perhaps a small corner button or reversed gesture to bring it back. The option to display or not display alt text by default in settings would also be nice. 

**Describe alternatives you've considered**

Users can kind of get around the issue now by zooming and swiping, but this is not ideal and does not work 100% of the time. 

**Additional context**

None.

**Comment by pfrazee** [comment]
+1 to this or some similar solution
