### ISSUE TITLE
Viewport breaks at ~1200px

### ISSUE THREAD

**Issue by raykyri** [bluesky-social/social-app#1267]
**Describe the bug**

The compose box is broken at 1200px width. 

There may be other bugs related to screen width too - timeline rendering was broken for a day or so until I resized to 1300px width, but then was fixed after switching back. I can't tell if this was because of some client side query malfunctioning or because the feed generator just happened to fix itself at the same time.

**To Reproduce**

1. Set window to ~1200px width. On a 14" Mac this can be done by just enabling vertical tabs.
2. Go to a post

**Expected behavior**

Compose box appears in regular place.

**Screenshots**

<img width="1220" alt="image" src="https://github.com/bluesky-social/social-app/assets/1273926/e192d396-b97d-4466-b80d-d73baa4f091b">

**Details**

 - Platform: Brave 1.56.20 Chromium 115.0.5790.171
 - Platform version: OS X Ventura
 - App version:

**Additional context**

**Comment by pfrazee** [comment]
Yeah there's two things that need to happen:

1. We need to introduce dynamic hooks for viewport size akin to what @mozzius is sharing
2. We need to actually style desktop to handle the different viewport sizes, which is a whole bundle of work

**Comment by mozzius** [comment]
@pfrazee was this fixed in v1.49 then? Patch notes implies it was

**Comment by pfrazee** [comment]
Yep!
