### ISSUE TITLE
cmd+click on user name should open the profile in a new tab, as does cmd+click on avatar

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1268]
**Describe the bug**, **To Reproduce**

https://bsky.app/profile/benjaminpercy.bsky.social/post/3k5pob23uhr2e 

Clicking on the poster's name or photo both bring me to https://bsky.app/profile/benjaminpercy.bsky.social 

On the **replies**, also cmd+click on the name or the photo of a person behave the same. 

But: for the **first** post, cmd+click only works on the avatar, not on the name. 

(let me know if it's not clear what I mean, then I'll try to describe it better)

**Expected behavior**

Also for the first post, cmd+click on the name should behave the same as cmd+click on the avatar. 

**Details**

Chrome on MacBook Pro with trackpad.

**Additional context**

Related? https://github.com/bluesky-social/social-app/issues/650

**Comment by mschwendener** [comment]
PS Same in Chrome on Windows. 

And to add: when I cmd+click / right click on the same name, looking at the same post, but as part of a feed, it also works as expected.

**Comment by mschwendener** [comment]
This might be related? https://github.com/bluesky-social/social-app/issues/1286

**Comment by intrnl** [comment]
doesn't seem to be, the issue you linked is about mentions not being linked properly in profiles so you can't click them at all

**Comment by mschwendener** [comment]
Thank you, @intrnl 

> the issue here is about being able to ctrl+click ... the mentions to open them in a new tab, right?

Yes, exactly.

**Comment by mschwendener** [comment]
While **cmd**+click now behaves as expected, on Firefox and Chrome on MacBook the following is still happening: 

Example: https://bsky.app/profile/mpgphd.bsky.social/post/3kg5si5p6vq2w 

I can ctrl+click on the avatar and open the link in a new tab, but this doesn't work with the user name.
