### ISSUE TITLE
 Double tap zoom on a picture zooms in too much

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1275]
**Describe the bug**
In the app, when you double tap on a picture to zoom in, the zoom is too important and you often have to zoom out to see better.

Example (on my Android with 720p display) : 

A picture when you display it in the app :
![Screenshot_20230825-110403_Bluesky](https://github.com/bluesky-social/atproto/assets/36693311/53e1ff45-f172-492c-b7b5-84edc6204fc4)

After double tap : it's zoomed in far too much, to the point it's useless.
![Screenshot_20230825-110425_Bluesky](https://github.com/bluesky-social/atproto/assets/36693311/5a0f2e2e-df0b-4f2f-8593-7ddcd444584f)

**To Reproduce**

1. Tap on a post's picture to display it in fullscreen
2. Double tap on the picture

**Expected behavior**

A less important zoom would be better in my opinion, so that a landscape picture would fill about the encore screen. So when you double tap, it would display like this for example :
![Screenshot_20230825-110648_Bluesky](https://github.com/bluesky-social/atproto/assets/36693311/5846aa67-a07c-445f-8dd6-a835d08aa304)

**Details**

 - Operating system: Android 
 - App version: 1.47.0

**Additional context**

**Comment by pfrazee** [comment]
Yeah I've noticed this too. Goes in way too far on android only

**Comment by gaearon** [comment]
https://github.com/

**Comment by gaearon** [comment]
https://github.com/bluesky-social/social-app/pull/1482
