### ISSUE TITLE
option to choose between photo picker or file browser when uploading images on android

### ISSUE THREAD

**Issue by edbcollie** [bluesky-social/social-app#1278]
todays change to using only the photo picker is not a good one. 

an option to choose between photo picker or file browser would be a better way, photo picker cannot access hidden folders or cloud storage

**Comment by intrnl** [comment]
culprit is that a recent yarn.lock sync updated expo-image-picker to the new version which makes use of Android's new photo picker

https://github.com/bluesky-social/social-app/blame/main/yarn.lock#L10434

it doesn't seem like expo-image-picker supports the older one, the only option is to use the newer one.

**Comment by Juppstein** [comment]
The new implementation makes the app nearly unusable for me since I use it almost exclusively to post art stuff that is located in dedicated folders on Dropbox or on my phone. Finding that stuff via photo picker is a hopeless endeavor. This basically kills the app/service for me :/

**Comment by boytwink** [comment]
for now you can press the 3 dots at the top, then "Browse" to get access to the file browser 

![browse](https://github.com/bluesky-social/social-app/assets/135167145/e5b4b36d-1b0b-46c5-ac75-70425e6b717f)

not the best solution, but at least it's still there

**Comment by edbcollie** [comment]
the dot menu does not appear on every device for some reason. I don't have it on my s22 ultra

**Comment by Juppstein** [comment]
@boytwink  that option is not available anymore and it is the reason this ticket has been created in the first place.

**Comment by pfrazee** [comment]
🤦 isn't that just our luck. Is this in the android native app or android web app?

**Comment by intrnl** [comment]
we can't really control the photo picker on web app unfortunately, the complaints have been about the native app 😅

**Comment by edbcollie** [comment]
android native

noticed on googles support page for photo picker it mentions some apps don't allow the browse menu. so it may just not be enabled by default and could be something as simple as finding how to allow it

**Comment by intrnl** [comment]
not sure if it's there hmm
https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickeroptions

**Comment by intrnl** [comment]
given the comment in https://github.com/bluesky-social/social-app/pull/1452#pullrequestreview-1629518051 is this supposed to be closed?

**Comment by estrattonbailey** [comment]
Ah, no, good call. The "Maybe fix" clearly closed this, but there's more work to be done. Thanks for the ping!

**Comment by duanemoody** [comment]
![Screenshot_20231013_114205_Media](https://github.com/bluesky-social/social-app/assets/159372/30683538-fee2-4696-82ac-6e9856149504)
My UI on Android 13, Samsung A45. Long-pressing does nothing; this feature needs to default to the file picker and not make assumptions about the photo picker being able to access outside the default gallery.

**Comment by mozzius** [comment]
@estrattonbailey I think this can be closed thanks to #2384
