### ISSUE TITLE
Emoji Picker does not scroll on Firefox

### ISSUE THREAD

**Issue by ansh** [bluesky-social/social-app#1283]
**Describe the bug**
Emoji picker does not scroll on Firefox

**To Reproduce**

1. Open Firefox
2. Click "New Post"
3. Try scrolling
4. Doesn't work

**Expected behavior**

Scrolling on emoji popup works

**Details**

 - Platform: Desktop Firefox, any version
 - Platform version: Any Firefox version
 - App version: Build version: 1.47.0; Platform: web

**Comment by mschwendener** [comment]
Same in Chrome on MacBook with trackpad.

I can scroll, but only when I drag the scroll bar with the cursor, not with the normal trackpad scroll.

**Comment by redouane59** [comment]
Same in chrome on Windows 10 with trackpad.

**Comment by ansh** [comment]
With the change that pushed the composer to the top #1282 this bug is not there on both Chrome and Firefox. Safari seems to not have an issue with it.

**Comment by mschwendener** [comment]
Also still here on Chrome on 13-inch MacBook
