### ISSUE TITLE
Don't pre-fill the post composer with your handle if you're looking at your own profile

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1285]
Nice feature, but when you're on your own profile (esp. when it's the tab) I can't imagine why you'd want to tag yourself.

It would make more sense to only do this on other people's profiles

**Comment by ansh** [comment]
This bug does not happen on web.

But, the bug snuck in on mobile.

It was fixed earlier today  in #1279  and should be out on the App Store soon
