### ISSUE TITLE
Clicking in the New Post text field such that the cursor is placed on a link opens the link

### ISSUE THREAD

**Issue by MetaflameDragon** [bluesky-social/social-app#1292]
**Describe the bug**
When composing a post, left-clicking anywhere such that the cursor ends up on top of a link will open the link.
After clicking, the cursor is placed behind the non-whitespace last character of the post each time.

This does not occur with RMB (opens context menu) or MMB (normal behavior). Click-dragging to select text works as expected too, including dragging and returning to make a zero-width selection (effectively placing the cursor with LMB) - this only happens when strictly clicked with LMB.

Mobile versions don't allow clicking in text fields to open the link, so this does not apply there.

**To Reproduce**

1. Begin composing a New Post and write a link anywhere.
2. Click outside of the text such that the cursor ends up on top of the link (including after the last link character, but not before the first link character - anywhere where the cursor turns blue instead of white/black).
3. The link will be opened, and the text cursor will be placed behind the last non-whitespace character in the text field (that is, excluding trailing spaces and newlines).

Examples include placing a link at the end and clicking well-outside the text, e.g. in the bottom-right corner, to move the cursor to the end; or making a one-line post with a link in the middle, and then clicking somewhere perpendicular to the text to place the cursor onto the link.

**Details**

 - Platform: Desktop, Chrome 115.0.5790.171
 - App version: 1.47.0

**Comment by pfrazee** [comment]
Yeah the solution for #1293 should also cover this
