### ISSUE TITLE
Embedding mute lists as link cards no longer works

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/social-app#1294]
**Describe the bug**
Embedding mute lists as links doesn't work.

**To Reproduce**

1. Make a new post
2. Paste a link to a mute list.
3. Choose "Add a link card" at the bottom.
4. The link card embeds for a second with no header image, but it quickly disappears.

**Expected behavior**
It should be embedded as a link card in the same way a feed is, with the image to the left and the name + description to the right. I think this used to work this way, actually.

**Details**

 - Platform: 
 - Platform version: Android 13, but I've tested on mobile web and desktop web with the same results 
 - App version: 1.47.0

**Comment by pfrazee** [comment]
@ansh we break this *again*?? 🤦‍♂️ Give it a look for me

**Comment by heikadog** [comment]
Nevermind, it's apparently been fixed! Thanks, guess that was just a fluke. 💞
