### ISSUE TITLE
Date format doesn't respect locale

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#1296]
**Describe the bug**
Dates are rendered using M/D/YYYY instead of using the user's locale setting.

This may be a Chrome privacy setting - I get the right values in other browsers.

**To Reproduce**

Set browser locale to a non-US location, and look at a post that occurs long enough in the past that it doesn't use relative time - i.e. https://bsky.app/profile/retr0.id/post/3k5l4vko6jp2p

**Expected behavior**

Dates should be rendered using the user's locale preferences

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/114112113/f86b1dda-3f78-430a-8a61-b7b327f40344)

![image](https://github.com/bluesky-social/social-app/assets/114112113/caafea46-57bd-412d-9df1-5cf5b4ff0c66)

**Details**

 - Platform: desktop chrome windows
 - Platform version: 
 - App version: 1.47

**Comment by pfrazee** [comment]
Assigned to @gaearon

**Comment by gaearon** [comment]
I can't repro this on desktop Chrome (macOS). Don't have Windows unfortunately. Tried both normal and private mode. I tried overriding location via Sensors menu and also via `chrome://settings/languages`.

The relevant code is [here](https://github.com/bluesky-social/social-app/blob/main/src/lib/strings/time.ts) and it just uses `toLocaleDateString()`. So this seems like either a Chrome bug or some edge case (I think we'll need more info or guesses about what makes your setup special).

Can you try to repro on another computer with the same locale?

**Comment by Bossett** [comment]
This seems to be a privacy setting somewhere -

**Comment by Bossett** [comment]
This seems to be a privacy setting somewhere - I'll keep digging, but I can't reproduce this in a fresh Chrome profile (but I can in incognito with no plugins), or in other browsers (incl. Edge & other Chromium). May be a hangover from some profile update somewhere along the way?

I'll re-open if I can reproduce more broadly.
