### ISSUE TITLE
Infinite fetch loop on notifications page

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1302]
**Describe the bug**

https://github.com/bluesky-social/social-app/assets/10959775/c31ab7be-1383-4fe6-a449-b58b2e5f5c39

**To Reproduce**

Not sure, sorry :(
I think I when from notifications > home > notifications to get new notifications (or perhaps just clicked notifications from the notifications screen)

**Expected behavior**

Don't do that

**Details**

 - Platform: Web
 - Platform version: Firefox
 - App version:

**Comment by pfrazee** [comment]
Yeah I ran into this over the weekend myself, managed to get myself logged out due to rate limiting. Going to diagnose today and deploy a hotfix
