### ISSUE TITLE
Notification via app or push notification should trigger refresh of notification tab

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#1304]
**Describe the bug**
When I get notified about new events, regardless of via app or via push notification, the event is not displayed, when I navigate to notifications. I always have to refresh the tab to get to read the event. However, in push notifications the content of the event is already displayed.

**To Reproduce**

1. Get notified.
2. Navigate to notifications.
3. Nothing new to see 
4. Refresh.
5. Notification event appears.

**Expected behavior**
When I get notified I expect to see the notified event, when I move there.

**Screenshots**

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: 1.47.0

**Additional context**

**Comment by mschwendener** [comment]
Same in Chrome on Mac desktop, but somehow not consistent, I think. 
Had written about it, but deleted again, because sometimes it works as expected = shows the notification after 1 click.
