### ISSUE TITLE
Issue when pasting a copied URL from the address bar of a browser

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#1321]
When pasting a copied URL from the address bar of a browser into a new post, instead of the URL being inserted (like in Twitter), the title of the page and domain of the URL appear.

**Comment by Zero3K** [comment]
If this is a bug, please mark it as such.

**Comment by pfrazee** [comment]
Can you show a screenshot or video or give more details please?

**Comment by Zero3K** [comment]
https://github.com/bluesky-social/social-app/assets/6194332/db9e87e8-b894-4c9c-9132-2ebb29f3cab5

**Comment by pfrazee** [comment]
Okay thanks for the video. I decided to delete it so we don't share your desktop any longer than necessary.

I'm not sure what's causing that, but that's absolutely not bluesky. It might be a feature of your browser, your OS, or some software you installed on your desktop. As far as I know, our app wouldn't be able to produce that information even if we wanted to.

Sorry I can't help, good luck

**Comment by Zero3K** [comment]
It doesn't happen in Twitter though.

**Comment by Zero3K** [comment]
This should fix it:

https://stackoverflow.com/questions/67560944/how-to-force-browser-to-paste-url-and-not-page-title-in-edge

**Comment by Zero3K** [comment]
What do you think?

**Comment by pfrazee** [comment]
I'll be darned, you might be right. I apologize for dismissing this prematurely. I'll look into it.

**Comment by Zero3K** [comment]
Any news?

**Comment by Zero3K** [comment]
@estrattonbailey

**Comment by mschwendener** [comment]
Just cosmetics, but maybe it coudl also be fixed: 

Chrome on Mac, first time I see this today: in the composer, copying an URL shows the last letter of the URL black, as if it was unliked. 

<img width="505" alt="screenshot_4499" src="https://github.com/bluesky-social/social-app/assets/4497705/ba6d3bf6-d5b7-4e01-938b-baf6713ef95f">

After posting, the links look normal https://bsky.app/profile/manuschwendener.bsky.social/post/3k6bgsmtfzo2v

**Comment by mschwendener** [comment]
Found https://github.com/bluesky-social/social-app/issues/1293#issuecomment-1694682160, which seems related, but is closed 

"whether or not the underlining happens doesn't actually reflect what will be sent on the post"

**Comment by mschwendener** [comment]
To reproduce (Chrome on Mac): 

add a carriage return before you paste the URL: both URLs start on a new line. The display bug does not happen if I just paste the URL after the text. 

Also happens if I first just paste the URL after the text and then insert the CR before the link; also, if the CR is not right in front of the link.

**Comment by mschwendener** [comment]
Same on Firefox on Mac. 

And: the number of Carriage returns determines how many characters do not look linked before submitting the post. 

<img width="493" alt="screenshot_4500" src="https://github.com/bluesky-social/social-app/assets/4497705/dd29c4b7-e743-46b1-85a4-c84c9ad3d745">

**Comment by Zero3K** [comment]
I thought this would be an easy fix.

**Comment by Zero3K** [comment]
I hope it gets fixed by the time a new release gets used.

**Comment by estrattonbailey** [comment]
It's not as simple as we'd hoped, unfortunately. It's up to the browser and OS to use the correct clipboard buffer, and the solution [linked above](https://stackoverflow.com/questions/67560944/how-to-force-browser-to-paste-url-and-not-page-title-in-edge) doesn't work out of the box. We'll keep this one in the backlog for now 👍 

For the time being, users who wish to use Edge can either elect to disable this pasting behavior as noted in the [link above](https://stackoverflow.com/questions/67560944/how-to-force-browser-to-paste-url-and-not-page-title-in-edge), or use the built-in `Right Click > Paste as > Plain text` to work around it.

**Comment by Zero3K** [comment]
I wonder how Twitter does it.

**Comment by Zero3K** [comment]
I switched to using Thorium (which is based off of Chromium) and no longer have this issue. It would still be nice to get it fixed for those that still use Edge, etc.

**Comment by jgarplind** [comment]
From #4301 (cc: @mary-ext):

> could you try seeing if Ctrl+Shift+V would give you the URL? that should get it to do a plain-text paste I believe.

It works just fine (on Windows, Edge)! Will do it for me, but I imagine other users will remain low-key frustrated.

Also noticing that this link: https://reactrouter.com/en/main/guides/api-development-strategy#current-future-flags looks like this: API Development Strategy v6.23.1 | React Router

Whereas this link: https://bsky.app/ looks like this: Following — Bluesky (bsky.app)

In the post composer, bsky.app looks like a clickable link, so obviously there is something going on that is making that one works better.
