### ISSUE TITLE
New post: images go beyond the screen on mobile

### ISSUE THREAD

**Issue by ryvwel** [bluesky-social/social-app#1323]
**Describe the bug**

Adding more than 1 image to post crops the last image, so you cannot remove it until you make room for it (it isn't scrollable)

**To Reproduce**

1. Click "New post"
2. Add 2 or more images
3. The last image goes beyond

**Expected behavior**

I can see & remove any image after adding it

**Screenshots**
![IMG_20230829_094913](https://github.com/bluesky-social/social-app/assets/111886772/3ebeee3a-3fcf-4418-9224-69eeca0479fc)

**Details**

 - Platform: 
 - Platform version: Android 10
 - App version: 1.48.0

**Comment by AMBehrDesigns** [comment]
I checked to see if this was an issue on iOS. And it doesn't seem to be happening there or on the web app. Can I take a stab at this?

**Comment by ryvwel** [comment]
That's odd. Happens in chrome to me
![Screenshot_2023-08-29-10-08-30-120_com android chrome](https://github.com/bluesky-social/social-app/assets/111886772/a37f91d4-6f83-495d-9e9a-9264d4bf3584)

**Comment by AMitBehr** [comment]
does the bug happen on your laptop or desktop too or just your phone? I'm wondering if it's a bug with the responsiveness of the android app. I tried recreating the bug on both my desktop (2560x1440) and 14in apple m1 laptop using chrome, firefox and safari, and I wasn't able to recreate it.

**Comment by ansh** [comment]
@AMitBehr If you would like to take a stab at it, feel free!

**Comment by AMitBehr** [comment]
Sweet! I'll see what I can find.

**Comment by ansh** [comment]
@ryvwel I am unable to reproduce this issue. Do you mind sending me the images which were causing the problem? Might be something to do with their aspect ratio.

**Comment by mnsrv** [comment]
I was able to reproduce this issue. It appears in small devices or small web browser, because image width was hardcoded to be 350 / size. But small screens have less than 350 width (minus paddings and borders). Created pull request, I'll be happy to hear feedback
