### ISSUE TITLE
Labels Rude / Unpleasant – and then?

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1324]
Not a feature request, but a question. 

https://bsky.app/profile/carlbergstrom.com/post/3k5rdjzdrk42c 

https://github.com/bluesky-social/proposals/tree/main/0002-labeling-and-moderation-controls 

I don't see the thread that caused this, because the author has deleted it. 

I think what he describes would be covered by the labels Rude / Unpleasant and some of their sub-labels.

If they were already available, what would have happened if he used them / if many people reading the thread had used them? 

On LibraryThing, there is a feature that if more than (I think) 3 people mark a post with a certain label, the post is hidden. Readers can still see the post, but it needs an extra click. 

But: this is after the fact and I don't know if the author of the offending posts gets blocked in any way. And the original author of the thread would still have seen the aggressive posts, so for him, not much would have changed. 

Having to make your profile private (once that's possible) can't be the solution. 

Having to approve replies before they get published can't be the solution, because the original author would still see them. 

Being able to close your posts from being replied to can't be the solution. 

Blocking the aggressors would have hidden the whole thread, if I understand it correctly. 

Is there a plan for situations like this?

**Comment by pfrazee** [comment]
> Blocking the aggressors would have hidden the whole thread, if I understand it correctly.

First real quick - this isn't the case. If people in the replies are blocked, it won't affect the visibility of the entire thread.

The most immediately relevant feature we're planning is a way for thread-creators to hide replies and detach quote posts.  We're also moving toward a way to use lists to control who can reply, which we're hoping can expand to larger communities of people with high trust. It's going to take a combination of tools and a lot of effort to steer social media to a positive place.

Sometimes discussions get divisive in completely unintended ways. I don't like that at all. I want people to have productive conversations that leave them knowing more about a topic and, importantly, feeling more positively connected to each other.  We can't guarantee that outcome, but we're going to try these mechanisms and keep pushing on the issue.

**Comment by mschwendener** [comment]
Thank you , Paul

> It's going to take ... a lot of effort to steer social media to a positive place

"the difference between a truly great and a truly terrible social network." ([proposal](https://github.com/bluesky-social/proposals/tree/main/0002-labeling-and-moderation-controls)) 

I sure hope you/we will succeed.

**Comment by mschwendener** [comment]
Adding in case somebody else lands here: 

More details about Paul's reply: https://github.com/bluesky-social/proposals/tree/main/0001-user-lists-replygating-and-thread-moderation

**Comment by mschwendener** [comment]
This can be closed, see https://bsky.social/about/blog/03-12-2024-stackable-moderation
