### ISSUE TITLE
[Android] When blocking, the modal goes all the way to the top

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/social-app#1333]
**Describe the bug**

When blocking someone, the modal inexplicably goes to the top of the screen and leaves a big blank white half at the bottom. 

**To Reproduce**

1. Block someone
2. Observe

**Expected behavior**

The modal should be at the bottom.

**Screenshots**

![Screenshot_20230829-180509](https://github.com/bluesky-social/social-app/assets/41552394/e19f4a6a-e25b-4806-8ba2-6c9b784a7171)

**Details**

 - Platform: Android, Google Pixel 4a 5G
 - Platform version: 13
 - App version: 1.48.0

**Additional context**

This has been in the app for a while—not a side effect of the new update or anything. This happens every time I block someone. I also wanna note that I can still use the Block button in the prompt that shows up. It just shouldn't look like this.

**Comment by pfrazee** [comment]
I noticed this happening specifically when doing the profile preview modal

**Comment by heikadog** [comment]
Wanna note that this also happens sometimes when reporting as well.
