### ISSUE TITLE
Web browser badge notifications don’t disappear after viewing posts

### ISSUE THREAD

**Issue by stefanmve** [bluesky-social/social-app#1338]
**Describe the bug**
The web notification badge counter doesn’t reset to zero (disappear) after viewing notifications; it only disappears after clicking to another page and then back.

**To Reproduce**

1. Do or post something that other users find engaging/encourages them to follow you
2. When you get notifications, note the notifications badge counter in the browser
3. Tap on the bell icon for notifications
4. Close browser window
5. Note that badge counter is unchanged (even though you’ve “seen” the notifications)

**Expected behavior**

Badge counter resets to zero after viewing the notifications.

**Screenshots**
![image](https://github.com/bluesky-social/social-app/assets/1799881/78988acc-2bd6-428b-82ed-73b91d143903)

**Details**

 - Platform: OS X Chrome
 - Platform version: Web
 - Build version: 1.48.0

**Comment by ansh** [comment]
Similar to #1090 but for web (non-native)

**Comment by Shohreh** [comment]
I can confirm the bug is still there in the web interface

Build version: 1.51.0; Platform: web

![image](https://github.com/bluesky-social/social-app/assets/1541861/d9f2e398-e6b9-4f5c-84b6-bbadf127c7fd)
