### ISSUE TITLE
Capture Input Focus on the Emoji Picker on desktop

### ISSUE THREAD

**Issue by SenpaiSharp** [bluesky-social/social-app#1343]
On desktop, when I click on the Emoji Picker, I have to make a subsequent click onto the search field if I want to start typing a search for the emoji that I want. I think opening the Emoji Picker should put the text input focus on the search field automatically, saving a click and improving flow, when it is first opened. Failing that, if I start typing with the emoji picker open and the browser focus is on the app, then it should automatically capture the focus into the search bar.

**Comment by mschwendener** [comment]
I think this will be added with the next update https://github.com/bluesky-social/social-app/issues/1328

**Comment by ansh** [comment]
@mschwendener Is absolutely right. Thanks for that!

It will be included in the next update as it has been solved by #1332

**Comment by ansh** [comment]
@simonetthomas Thanks for testing. I will retake a look at it.
