### ISSUE TITLE
`blockAccount()` has no `createBlock` endpoint

### ISSUE THREAD

**Issue by XaurDesu** [bluesky-social/social-app#1344]
**Is your feature request related to a problem? Please describe.**

As explained by @mozzius in https://github.com/bluesky-social/atproto/issues/1438 , we're trying to find a way on the server side to have someone unfollowed when blocked, as part of this, we've been taking a look into the way blocking works and, as the function `blockAccount()` stands client-side, there seems to be no `createBlock` endpoint; it's currently sitting like this:

```ts
async blockAccount() {
    const res = await this.rootStore.agent.app.bsky.graph.block.create(
      {
        repo: this.rootStore.me.did,
      },
      {
        subject: this.did,
        createdAt: new Date().toISOString(),
      },
    )
    this.viewer.blocking = res.uri
    await this.refresh()
  }
```

 This function creates a block record but has no real endpoint. This makes manipulating the way blocks work somewhat inconvenient.

**Describe the solution you'd like**

Adding a `createBlock` endpoint might be useful in the future if we ever need to mess around with the way blocking people work. It would let us work with the block itself more directly instead of depending merely on the record created by the function. As far as i know there is no concise solution on how to implement this and would probably require some discussion for an eventual implementation to be devised, if ever.

**Describe alternatives you've considered**

The solution for blocking and unfollowing someone at the same time most probably will come on the server-side rather than on the client. It is possible that some of the grievances this creates can equally be solved server-side, if such a solution was to be found it might not even be needed to modify the client at all.

**Additional context**

I'm pretty new to this codebase, if there's any inaccurracy or problem with my assesments please let me know, i will try to correct whatever i got wrong.

**Comment by pfrazee** [comment]
We're trying not to place business logic in the PDS unless we absolutely have to. In this case, if you want to unfollow first, just run the unfollow call along with the block-record creation.
