### ISSUE TITLE
Show preview of post's image if embed is of type `AppBskyEmbedRecordWithMedia` in Notifications feed

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1348]
Currently, notifications will show a tiny preview of a post's image if the embed is of type `AppBskyEmbedImages`. However, that is not the only circumstance a post will have images. It would be good if posts with an embed of type `AppBskyEmbedRecordWithMedia` also get the little preview.

I think the change required is pretty simple:

```diff
 // src/view/com/notifications/FeedItem.tsx

 const images = AppBskyEmbedImages.isView(additionalPost.thread.post.embed)
   ? additionalPost.thread.post.embed.images
+  : AppBskyEmbedRecordWithMedia.isView(additionalPost.thread.post.embed) &&
+    AppBskyEmbedImages.isView(additionalPost.thread.post.embed.media)
+  ? additionalPost.thread.post.embed.media.images
   : undefined
```

**Comment by mozzius** [comment]
PR is ready to go if you want it: https://github.com/mozzius/bluesky-official-app/tree/notification-recordwithmedia

**Comment by ansh** [comment]
@mozzius Feel free to open it!
