### ISSUE TITLE
web composer: pasting URL on new line messes with the display (minor bug)

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1353]
**Describe the bug**

<img width="493" alt="screenshot_4500" src="https://github.com/bluesky-social/social-app/assets/4497705/18808d28-0614-4d25-9cec-d0ddd651eb82">

**To Reproduce**

Start a post, copy&paste some URLs, but each on a new line. 

**Expected behavior**

Show the whole URLs as linked, and only the URLs.

**Details**

Chrome and Firefox on Mac. 

Also happens when you insert the carriage return after having pasted the URL. 

After posting, all looks as it should https://bsky.app/profile/manuschwendener.bsky.social/post/3k6bgsmtfzo2v 

**Additional context**

Related to https://github.com/bluesky-social/social-app/issues/1293#issuecomment-1694682160.

**Comment by pfrazee** [comment]
nice

**Comment by estrattonbailey** [comment]
@mschwendener this is really strange, but I can't reproduce this now 🤔 I know I've seen this kinda thing in the past but perhaps we bumped something and resolved it? Are you able to reproduce this?

**Comment by mschwendener** [comment]
Still can reproduce, Chrome on MacBook, see screenshot.

I use shift&carriage return to get to the new line. 

<img width="590" alt="screenshot_4567" src="https://github.com/bluesky-social/social-app/assets/4497705/ba8566a3-d78d-4adc-bea5-9a564a0630eb">

**Comment by mschwendener** [comment]
Closing this, let's continue in https://github.com/bluesky-social/social-app/issues/1391
