### ISSUE TITLE
Embedding mute lists as link cards doesn't work (but this time it seems like it's not a fluke)

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/social-app#1359]
**Describe the bug**
Embedding mute lists as link cards doesn't work.

**To Reproduce**

1. Make a new post.
2. Paste a link to a mute list.
3. Choose "Add a link card" at the bottom.
4. The link card embeds for a second with no actual embed with information, but it quickly disappears.
5. Posting the link itself after attempting to embed a link card doesn't work.

**Expected behavior**
It should be embedded as a link card in the same way a feed is (feeds still embed properly.)

**Details**

    Platform: Android, Google Pixel 4a 5G
    Platform version: Android 13, but I've tested on mobile web and desktop web with the same results
    App version: 1.48.0

I wanna additionally note that this happens with any mute list with any time I try to embed them in a post.

**Comment by sgitsp** [comment]
Yeah it's because the mute lists share button create link with handle name instead of DID
