### ISSUE TITLE
Web: Composer shifts text cursor after tab loses focus

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#1363]
**Describe the bug**

When the window with the text composer loses focus (either different window or new tab), the cursor is moved from wherever it's position was to the end of entire written text, albeit n characters back where n is the number of lines (always minimum n=1). It gets a little finnicky when it lands on a line break (looks like line breaks count as two characters by my testing), and additionally this behavior is NOT exhibited when there is an @ towards a user written anywhere in the post. It is still affected by links in the post.

**To Reproduce**

1. Write "asdasdasd" in the text composer.
2. Change windows and then come back.
3. Notice how the text cursor is set 1 character from the end.
4. Repeat steps 1-3 for an additional new line with each new line corresponding to an additional character set back.
5. Observe how an @ fixes the behavior.

**Expected behavior**

The cursor should remain where it was left off.

**Details**

I've tested this in Chrome, Opera, and Firefox.

**Comment by gaearon** [comment]
I can't repro. I believe I fixed this in https://github.com/bluesky-social/social-app/pull/1374 since the responsible code was likely the `onFocus` handler which I removed. If you can still repro please let me know!

**Comment by Juicysteak117** [comment]
@gaearon Looks to be fixed in #1374, yeah. Related issue with the emoji picker where clicking inside the picker to search immediately closes the picker on account of not having focus on the composer, but I'm not sure if that's already been reported.

**Comment by ansh** [comment]
@Juicysteak117 That is a completely different issue that was fixed in #1440

**Comment by Juicysteak117** [comment]
@ansh Great to hear, that one's been obnoxious. Thanks.
