### ISSUE TITLE
Event tracking is inverted in some cases

### ISSUE THREAD

**Issue by Jacob2161** [bluesky-social/social-app#1364]
**Describe the bug**

There are some incorrect tracking events being sent, they're inverted. Not sure if this is a matter of the logic being wrong, a data race, incorrect viewer state, or what.

Liking an individual post:
* `Post:Unlike`

Unliking an individual post:
* `Post:Like`

Liking a post on a feed:
* `FeedItem:PostLike`
* `Post:Unlike`

Unliking a post on a feed:
* `FeedItem:PostUnlike`
* `Post:Like`

There seems to be similar problems with a number of events, but I haven't tested them all:

Following from a profile:
* `ProfileHeader:UnfollowButtonClicked`
* `Profile:Follow` 

Unfollowing from a profile:
* `ProfileHeader:FollowButtonClicked`
* `Profile:Unfollow` 

When clicking Reply (but before replying, maybe intentional?):
* `FeedItem:PostReply`

**To Reproduce**

* Open DevTools and filter HTTP requests for `api.evt.bsky.app`
* Like and Repost things
* Check the event payload for `https://api.evt.bsky.app/t` (track) endpoints events

**Expected behavior**

Tracking events to be emitted that match the action.

**Screenshots**

The result of liking two posts:

![image](https://github.com/bluesky-social/social-app/assets/52801504/4c27c04a-f974-400a-b803-5ee2f4212a8c)

Aggregate results showing the issue:
![image](https://github.com/bluesky-social/social-app/assets/52801504/bf565ce3-ce53-4969-926c-b9a7c5ed639b)
![image](https://github.com/bluesky-social/social-app/assets/52801504/4a6b5495-12be-4920-9a33-14fd42b2272b)

**Details**

 - Platform: Desktop/Chrome/Linux and iOS
 - Platform version:
 - App version: `1.48.0`

**Comment by ansh** [comment]
I'll take a look at this
