### ISSUE TITLE
Can't scroll with mouse wheel in emoji picker

### ISSUE THREAD

**Issue by gensakudan** [bluesky-social/social-app#1367]
**Describe the bug**
It is not possible to scroll through the available emojis within the emoji picker by scrolling with the mouse wheel. Methods that *do* work, however, are:
- Clicking on the arrow buttons at the top and bottom of the scrollbar
- Clicking and dragging the scrollbar itself
- Clicking the mouse wheel within the emoji picker and using the auto-scroll function

**To Reproduce**

1. Open the post editor, either by clicking "New post" or via responding to/quote-reposting another post.
2. Click the emoji icon in the editor in order to open the emoji picker.
3. Hover your mouse cursor anywhere in the container and attempt to scroll the mouse wheel up or down.

**Expected behavior**
Scrolling the mouse wheel should allow you to scroll up and down in the emoji picker.

**Details**

 - Platform: Desktop, Windows 10 64-bit, Mozilla Firefox 117.0 (64-bit)
 - Platform version: Build version 1.48.0

**Comment by ansh** [comment]
This has been fixed by #1283 and should be merged shortly.
