### ISSUE TITLE
Gap between the scrollbar and the right order

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1368]
**Describe the bug**
On the website, there is a gap between the scrollbar and the border of the page, which should not appear.
It's only the case in the Home and My Feeds screens. In the Notifications or Profile for example, no issue.

It's a bit unnerving when you want to put the cursor directly against the screen border and click on the scrollbar, you end up clicking in the empty space.

**Expected behavior**
The scrollbar should appear directly next to the border.

**Screenshots**
Firefox :
![Bluesky capture bug Firefox](https://github.com/bluesky-social/social-app/assets/36693311/9ba603e7-9356-45ec-939f-aadabef16cd2)

Edge :
![Bluesky capture bug Edge](https://github.com/bluesky-social/social-app/assets/36693311/0184f324-8ecb-4962-9b30-7683ade81808)

**Details**
 - Platform: Tested on Firefox and Edge, Windows 10
 - App version: 1.48.0

**Comment by NsdHSO** [comment]
I wanted to work on this issue, but I don't have an account, There is an account for the test env ???

**Comment by ansh** [comment]
@NsdHSO If you run the atproto dev environment locally, you can create a local test environment without an invite code

**Comment by NsdHSO** [comment]
ok, tnx I runned the dev-env and I got this 
<img width="802" alt="image" src="https://github.com/bluesky-social/social-app/assets/37635083/8ca5a020-770f-418e-9471-4db995d3aaf2">
and for these routes I receive empty
