### ISSUE TITLE
The emoji picker is not fully displayed when there is a picture in the post

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1369]
**Describe the bug**
In the post composer, if you add a picture in the post, it expands the composer, which means the emoji picker doesn't have the place to be totally displayed.

**To Reproduce**

1. Create a post
2. Add a picture

**Expected behavior**

The emoji picker should not be hidden. It could be displayed upwards, and not downwards (this is what they do on Twitter when there is a picture).

**Screenshots**

Screenshot in Firefox, on a 1920x1080 display.
![Bluesky capture bug emoji picker Firefox](https://github.com/bluesky-social/social-app/assets/36693311/955ac1e1-103f-473a-8ed8-34a70f8b46e4)

**Details**

 - Platform: Firefox
 - App version: 1.48.0

**Comment by ansh** [comment]
This should be solved by #1283 which should be released shortly. If the issue still persists, please comment here and I will re-open this issue.
