### ISSUE TITLE
Notifications don't respect muted threads

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1370]
**Describe the bug**

You still get push notifications for threads you've muted. This is annoying.

**To Reproduce**

1. Mute a thread
2. Get a push notification for it

**Expected behavior**

Don't get a push notification

**Details**

 - Platform:  iOS
 - Platform version: 17 beta
 - App version: 1.48

**Additional context**

No idea how feasible this is because muted threads are clientside

**Comment by pfrazee** [comment]
Heh I was wondering who would catch this first

Yeah I'm going to need to work with backend to fix this, and it might be a bit of work. Ahh, computers

**Comment by haileyok** [comment]
Wow, we really came around full circle on this one didn't we @mozzius

**Comment by mozzius** [comment]
Haha I've been playing the long game
