### ISSUE TITLE
In the search results, pictures are displayed at the top of the results list

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1373]
**Describe the bug**
In the search results, when you click on an image to view it in fullscreen, it is displayed at the very top of the screen. So when you scrolled down in he results and click on an image, you have to scroll up to the top to see it.

**To Reproduce**

1. Click on the Search button.
2. Enter a term in the search field and press enter. The results are displayed.
3. Scroll until you see an image, and click on it. You won't see it until you scroll back up.

**Expected behavior**
The picture should open where it is, in the same way as in the Home menu.

**Screenshots**
Example :

https://github.com/bluesky-social/social-app/assets/36693311/18d2accc-1078-42b6-9f9c-2f1fa50d2ee5

**Details**

 - Platform: Firefox and Edge, Windows 10
 - App version: 1.48.0

**Comment by pfrazee** [comment]
This actually just got fixed by Eric and the fix will be released soon
