### ISSUE TITLE
Revert new "sort replies by likes" feature

### ISSUE THREAD

**Issue by bondjimbond** [bluesky-social/social-app#1407]
**Is your feature request related to a problem? Please describe.**

The change to sort replies by likes instead of chronologically was introduced today (1.49). It was widely panned in the replies as being harmful to the user experience rather than an improvement. 

**Describe the solution you'd like**

Revert this change and sort replies chronologically by default. Ideally, also add an *option* to sort replies by other criteria (likes, number of replies), but leave chronological the default.

**Additional context**

See the many replies to the announcement: https://bsky.app/profile/bsky.app/post/3k6t3d3wkxv26

**Comment by Bossett** [comment]
There are three main concerns as I see it:

- Likes to be weaponised as we have seen on twitter, as a means of harassment (i.e. 'ratio')
- Large accounts now have a massive visibility advantage in replies, and will dominate conversations - even if they come late with the same reply, this will harm smaller accounts looking for visibility
- Threads will now be 'decided' early, and late replies are simply pointless for engagement. This is especially bad where there needs to be follow-up engagement (i.e. for clarification, etc.), but wild assumptions have been made early.

+1 on reverting.

**Comment by skunecuscre1** [comment]
Disagree on reverting it, just add more options (with most liked still being the default for new users).

Putting bangers at the top was one of the good things about Twitter before Elon messed it up with the bluecheck stuff.

**Comment by str4d** [comment]
> Ideally, also add an option to sort replies by other criteria

This is already tracked in #1103.

**Comment by mschwendener** [comment]
The [announcement](https://bsky.app/profile/bsky.app/post/3k6t3d3wkxv26) just mentions "Thread replies" (and web), not replies to single posts. 

Until now, replies to posts in a **thread** * were just added at the end of the thread. They may have been sorted chronologically, but the context of which post in the thread they were a reply to was not visible. Here I think sort by number of likes isn't worse than chronological sort, but it's not the solution, either. 
 
Details in https://github.com/bluesky-social/social-app/issues/1044.  

 * thread in the sense of: the original author chains together a series of posts.

**Comment by str4d** [comment]
> leave chronological the default.

Chronological was not the previous default, which is what makes this somewhat confusing. It was a hybrid of chronological and reverse-chronological, with some additional logic. I wrote up what I believe to be the current default [here](https://github.com/bluesky-social/social-app/issues/1103#issuecomment-1710600223):
> - Original Poster's replies always first.
>   - Within OP's replies, oldest-first (reverse chronological).
> - Remaining posts sorted in order of moderation score, lowest-first.
>   - Within each moderation score band, most-liked-first.
>     - For posts with equal likes, newest-first (chronological).

**Comment by pfrazee** [comment]
I'm going to close this as a dup of #1103. If it looks like adding the option will take too long, we'll consider reverting.

**Comment by simonetthomas** [comment]
> Threads will now be 'decided' early, and late replies are simply pointless for engagement. This is especially bad where there needs to be follow-up engagement (i.e. for clarification, etc.), but wild assumptions have been made early.

> And post fast - I could get a big boost if I'm the first on a thread with a hot take.

@Bossett I don't see in what way a chronological order would be better about that... On the contrary, the first replies would be displayed first and couldn't even be replaced by "better" (more liked) ones

**Comment by bondjimbond** [comment]
@pfrazee Thanks for being open to the feedback.
