### ISSUE TITLE
"Load new posts" button obscures top post, can't be dismissed

### ISSUE THREAD

**Issue by Iananan** [bluesky-social/social-app#1419]
![image](https://github.com/bluesky-social/atproto-website/assets/1507624/4777a43a-a277-4992-b372-0447dc7a67b8)
Hi all,

looks like the "load new posts" dynamic button is appearing over the top of a chunk of the top post. the only way to dismiss it is to press the button, which usually means that the post you were trying to read isn't there anymore.

### **steps to reproduce:**
1. open new tab (discover feed works best as higher post turnover)
2. wait for the feed to update in the background
3. button appears on top of the top post, obscuring the user's handle and the middle of the first line of text

this isn't the hugest problem if you've already read the top post or if you're scrolled down the feed a bit, but if you open the tab in the background, it's fairly obstructive UX.

maybe introduce a 40px padding to the top of the feed whenever the button is showing, or allow the button to be dismissed with a scroll up?

**Comment by pfrazee** [comment]
Yeah this annoys me too, going to find something else soon

**Comment by pfrazee** [comment]
Closing as a dup of #1130
