### ISSUE TITLE
Broken links on early access email

### ISSUE THREAD

**Issue by maheshmnj** [bluesky-social/social-app#1422]
The invites sent over email have broken links it only launches playstore and appstore does not redirect  to app page

![image](https://github.com/bluesky-social/social-app/assets/31410839/2b5a0fe3-4350-4b5e-b018-95844803a4b3)

**Comment by ansh** [comment]
Thanks for reporting this. We have updated the email to directly link to the App Store and Play Store. Unfortunately, we obviously won't be able to change the links for emails already sent, but you can find the links here:
https://play.google.com/store/apps/details?id=xyz.blueskyweb.app
https://apps.apple.com/us/app/bluesky-social/id6444370199
