### ISSUE TITLE
[Web] Emoji picker closes instantly 

### ISSUE THREAD

**Issue by n0vedad** [bluesky-social/social-app#1423]
**Describe the bug**
If I open the emoji picker and click in the search field, for example, it closes immediately

**To Reproduce**

1. open the emoji picker on web and click in the search field

**Expected behavior**

I expect to be able to enter a search term or access the emoji categories like I was able to do in 1.48 before the scroll bug was fixed

**Details**

 - Platform: Windows 11
 - Platform version: Firefox 117.0
 - App version: 1.49

**Comment by mschwendener** [comment]
Same in Firefox and Chrome on 13inch MacBook (where I have to zoom out first, because otherwise I get the mobile display and see no emoji picker at all).

**Comment by jlg6** [comment]
Same in Chrome version 116.0.5845.141 on Dell Inspiron laptop running Windows 10 Home.

**Comment by monicaellerose** [comment]
same issue in firefox

**Comment by ansh** [comment]
Thanks for reporting this. I have fixed it in #1427

**Comment by jlg6** [comment]
> Thanks for reporting this. I have fixed it in #1427

Thanks! It seems I can select an emoji, but the particular issue givien as an example initially remains (ie when I click the 'search' bar, the emoji picker closes.)

**Comment by ansh** [comment]
@jlg6 Yes, the issue you have mentioned has been fixed in PR #1427 but it has not yet been released.

Feel free to clone this repo to test that PR out!
