### ISSUE TITLE
[Web] Emoji picker should not close automatically after picking an emoji

### ISSUE THREAD

**Issue by n0vedad** [bluesky-social/social-app#1425]
I'm not really sure if this is a bug or work as designed, but I really would like to see an emoji picker which doesn't close automatically after picking an emoji and I have to reopen it if I want to add another emoji.

**Describe the solution you'd like**

See above.

**Additional context**

This afflicts only the web client. I'm usig Windows 11 and Firefox 117.0

**Comment by mschwendener** [comment]
Related https://github.com/bluesky-social/social-app/issues/1423

**Comment by ansh** [comment]
@mschwendener Is describing a bug with the search bar in the emoji picker. This issue is about a feature request of allowing multiple emojis to be inserted.

**Comment by zarakk** [comment]
Hi @ansh, is this feature still in discussions? I've added this feature locally. If this is the expected behavior I'll submit a PR which would resolve this.  

https://github.com/bluesky-social/social-app/assets/52151884/707b7898-73fd-4a55-8e24-db2bb56eede8
