### ISSUE TITLE
[Web]  Emoji picker search not working

### ISSUE THREAD

**Issue by glOOmyART** [bluesky-social/social-app#1440]
**Describe the bug**
When klicking in the search field in the emoji picker, the emoji picker closes

**To Reproduce**

1. open the emoji picker
2. click in the search field

**Expected behavior**

obviously the user should be able to search for emojis

**Details**

 - Platform: Desktop
 - Platform version: OpenSUSE Leap 15.5
 - App version: Browser Firefox 115.1.0esr

**Comment by gensakudan** [comment]
To add to the above, the emoji picker closes no matter *where* you click on it (except for the scrollbar), meaning that the emoji category tabs are unusable, too.

**Comment by ansh** [comment]
This was fixed in #1423 

Will be released soon.
