### ISSUE TITLE
Can't select alt text

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1445]
**Describe the bug**

Alt text is not selectable, because `<Pressable>` goes to `<button>` on web, which is not selectable by default

**To Reproduce**

1. Open an image with alt text
2. Try and select the text

**Expected behavior**

Text is selectable (may want to copy it for example)

**Screenshots**

<img width="953" alt="Screenshot 2023-09-13 at 13 36 04" src="https://github.com/bluesky-social/social-app/assets/10959775/ae4eef8d-bf9f-4f32-ba83-3a5ff7835511">
(I added `user-select: text` in dev tools in order to select the word "text")

**Details**

 - Platform: Web

**Additional context**

You can fix it by adding `user-select: text` to the `<Pressable>`

**Comment by monicaellerose** [comment]
also want to add, that we cant select alt text on android

**Comment by gaearon** [comment]
I removed the [web] from the title since it's useful to be able to select on other platforms too.
