### ISSUE TITLE
Content filtering: Birthday cannot be entered

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#1459]
**Describe the bug**
To see content marked as for adult audience I have to enter my birthday. If I enter my birthday under "Set age" the frame of the date field gets red. When I save my entry there is an error message: "TypeError: t.findLast is not a function". I did follow the entry scheme that was default. (There is no calendar to choose from implemented.) But even when I use YYYY/MM/DD the same error message appears.

**To Reproduce**

1. Go to Moderation
2. Go to Content Filtering
3. Click on Set Age
4. Set an age.

**Expected behavior**

I should be able to set my birthday.

**Screenshots**
![image](https://github.com/bluesky-social/social-app/assets/7019947/41a05a2c-2301-45d9-92be-434d2287dece)

**Details**

 - Platform: desktop chrome windows
 - Platform version: Chrome Version 95.0.4638.69 (Offizieller Build) (64-Bit)

**Comment by simonetthomas** [comment]
I think you have to use the MM/DD/YYYY format.

**Comment by diesocke** [comment]
Nope. This does not work as the two other ways.

**Comment by BrandiBlitz** [comment]
I'm having the same issue. Is this a misconfiguration of the server's API protocals?
