### ISSUE TITLE
[Web] Home Feed Preferences are not saved in any case

### ISSUE THREAD

**Issue by n0vedad** [bluesky-social/social-app#1460]
**Describe the bug**
I don't really know how Home Feed Preferences are saved, but if I use privacy mode in a Webbrowser they are reset every time I restart the browser. Even if I save the cookie this happens. 

**To Reproduce**

Use a webbrowser (e.g. Firefox) in privacy mode, set Home Feed Preferences and restart the browser. 

1.

**Expected behavior**

I wish the Home Feed Preferences would be saved on server-side and/or synced between devices if this is possible.

**Details**

 - Platform: Windows 11
 - Platform version: Firefox 117.0
 - App version: 1.50

**Additional context**

Please tell me if I'm wrong in my understanding or something.

**Comment by pfrazee** [comment]
This is fixed in the upcoming 1.51 release
