### ISSUE TITLE
follow suggestions show inactive accounts

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#1466]
Currently follow suggestions will suggest (good, however inactive accounts some 30 days)

I feel like this is frustrating because it draws a stigma that bsky isnt an active social app.

I would like inactive accounts of 7-14 days to be removed from the follow suggestions/recommended.

Low priority, but a nice to have.

**Comment by pfrazee** [comment]
@estrattonbailey @ansh something to evaluate with the updates you're making

**Comment by ansh** [comment]
Thanks for the report @monicaellerose !

We have updated these suggested follows and will continue monitoring them. We also have some dynamically updating suggested follows based on who you follow! cc @emilyliu7321
