### ISSUE TITLE
Long threads are impractical to read

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1478]
**Describe the bug**

It's not really a bug, but something I find annoying.

At the moment, a long thread is quite impractical to read, because it loads only 7 posts at a time. Then you have to click "Continue thread" to read the rest. When you click continue, it opens the post that was displayed just before the Continue button, displays the 7 following posts, and so on.

It makes reading a thread that's more than 7 posts long (which is quite common) very impractical and slow.

**To Reproduce**

1. Go to Bluesky
2. Open a thread that has a least 8 posts

**Expected behavior**

I see several possibilities :

- Load all the posts in the thread (like Twitter). When you open the first post, you could scroll to read the entire thread without interruption.
- Display a "Continue thread" button, but instead of opening on the 7th post, load the next posts of the thread by staying in the same view. Not sure if it would be quicker, but it would already be more logical and ergonomic in my opinion.
- Just load more posts instead of 7. Doesn't really fix the issue but would be less annoying.

**Details**

 - Platform: Firefox & Android App
 - App version: 1.50.0

**Comment by pfrazee** [comment]
There's a "Thread Mode" experiment coming in 1.51 that is intended to fix this. Give it a try when the release happens and let us know what you think! (Closing optimistically)

**Comment by dfgshdsfh** [comment]
The ability to load additional comments in a thread "inline" would be greatly appreciated, and make archiving threads easier as a single page, rather than multiple disjoint pages.
