### ISSUE TITLE
Translate button on Android app does not copy text

### ISSUE THREAD

**Issue by chrisford** [bluesky-social/social-app#1487]
**Describe the bug**
The translate button on posts in the Android app (under the three dots menu) launches Google Translate but does not copy the text to be translated

![Screenshot_20230920-211158](https://github.com/bluesky-social/social-app/assets/403728/db1c44f2-29b9-4d93-8cb0-f988d0c31e9e)
![Screenshot_20230920-211216](https://github.com/bluesky-social/social-app/assets/403728/84c7038f-6b75-41fd-b1dd-82af09456919)

Build version: 1.50.0 (37); Platform: android
Pixel 7, Android 13,.Build TQ3A.230805.001

**To Reproduce**

1. Open a post
2. Click on the three dots menu
3. Click on Translate

**Expected behavior**

The text of the post to be automatically copied into the Google Translate app

**Screenshots**

See above

**Details**

See anove

**Additional context**

**Comment by ansh** [comment]
@chrisford Can you do me a favor and delete the Google Translate app from your device and then try translating something? Does the issue still occur?

**Comment by chrisford** [comment]
@ansh - with the Google Translate app uninstalled, clicking Translate opens Google Translate in my browser and the text is copied  correctly as expected
