### ISSUE TITLE
Number of unread notifications not cleared after reading

### ISSUE THREAD

**Issue by Shohreh** [bluesky-social/social-app#1488]
Hello

Title says it all: In the web app at least, even after clicking and reading the notifications, their number isn't cleared, like they haven't yet been read.

Cheers,

![image](https://github.com/bluesky-social/social-app/assets/1541861/4b98481e-9810-4b23-90a2-782b4cdeee6d)

**Comment by pfrazee** [comment]
Known issue! Closing as a duplicate of https://github.com/bluesky-social/social-app/issues/1090
