### ISSUE TITLE
Support RSS/Atom/JSON Feeds

### ISSUE THREAD

**Issue by Quinn64** [bluesky-social/social-app#1491]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, there isn't a way to follow people on bluesky from any news aggregators.

**Describe the solution you'd like**

Implement a RSS/Atom/JSON feed for use user's public posts. Maybe supports credentials for RSS/Atom/JSON feeds so people can also follow users private posts, if their account is allowed to see them. Though, I think public posts is plenty.

**Additional context**

If Bluesky is aiming for decentralization and user freedom, supporting open standards like RSS/Atom/JSON is needed. Especially now, with people leaving centralized platforms. Currently, I can follow people on Mastodon, Cohost, Twitter (using Nitter), and Tumblr easily from my news aggregator, but people that go over to Bluesky are essentially disappearing off the internet for me, at least until Bluesky supports news feeds.

**Comment by markcellus** [comment]
Yeah I was looking for these as well. Maybe Open RSS can provide them if Bluesky somehow can't. Looks like Bluesky has an API to do it.

**Comment by bnewbold** [comment]
The basic feature has shipped. If there are more specific requests for additional features, like different formats (Atom), please open new issues.

**Comment by AlexRVillalobos** [comment]
Please develop the functionality to be able to add RSS feeds to my BlueSky feeds. That is, take the URL of an RSS, give it a title and add it to the BlueSky custom list (feed). 

So you can read that RSS, INSIDE BlueSky,  as if they were posts from other users.

Many thanks in advance, I love BlueSky
