### ISSUE TITLE
Feed menu moving up and down 

### ISSUE THREAD

**Issue by erixven** [bluesky-social/social-app#1493]
**Describe the bug**

When scrolling the timeline and an image is in the top, sometimes the feeds menu and the Load new posts button start moving up and down.
**To Reproduce**

Open a feed on the Home page and scroll
1.

**Expected behavior**

The menu and button should not move
**Screenshots**

Added a screencast demonstrating the issue. https://github.com/bluesky-social/social-app/assets/145605505/8ee86b6b-2c31-47ae-b0ec-fc2244030cfd

**Details**

 - Platform: 
 - Platform version: Windows 11
 - App version: Firefox 117.0.1.

**Additional context**

https://github.com/bluesky-social/social-app/assets/145605505/8ee86b6b-2c31-47ae-b0ec-fc2244030cfd

**Comment by pfrazee** [comment]
This is fixed in the upcoming release!
