### ISSUE TITLE
Number of follower/followings/posts not consistent between apps

### ISSUE THREAD

**Issue by simonetthomas** [bluesky-social/social-app#1504]
**Describe the bug**

The displayed number of followers, followings and posts of an account is not consistant between the webapp and the Android app.
The web version shows the exact number, but the Android app shows a number rounded to the tens or to the hundreds. I don't know about the iOS app.

**Expected behavior**

I think the number should be the same.

**Details**

 - Platform: Android & Firefox
 - App version:1.50.0

**Comment by haileyok** [comment]
https://github.com/bluesky-social/social-app/issues/5538
