### ISSUE TITLE
Long press profile tab to quick switch accounts

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1514]
**Is your feature request related to a problem? Please describe.**

Switching accounts is a common action for me, so I find going to the drawer menu then settings every time to be quite arduous

**Describe the solution you'd like**

It'd be great if long pressing the  profile tab would bring up a bottom sheet to quick switch accounts, like twitter does

**Describe alternatives you've considered**

Perhaps a quick switcher in the drawer menu?

**Additional context**

Here's a screenshot of twitter's menu - I'm imagining something pretty close to this:

![image](https://github.com/bluesky-social/social-app/assets/10959775/9b208a8d-c0fe-4525-89a3-9370def01831)

- [x] I would be willing to submit a PR for this

**Comment by ansh** [comment]
Please submit a PR if you want/can!
