### ISSUE TITLE
No Password Reset E-Mail, No Response from Support in Two Months Either

### ISSUE THREAD

**Issue by katjazwitschert** [bluesky-social/social-app#1519]
**Describe the bug**
I was logged out of the Bluesky app on my iPhone. I tried to reset the password through the app as well as the web interface. I have not once received a password reset e-mail or error message.

**To Reproduce**

1. Click "Sign in" on 
2. Click "Forgot"
3. Enter my e-mail address
4. Click "Next"

**Expected behavior**

A) An e-mail with instructions to reset my password.
OR B) An error message that the e-mail address is not registered (i.e. because I mistyped during registration)

**Details**

 - Platforms: several (Windows 11 in Chrome and Firefox browsers, iOS in BlueySky app and Safari browser)

**Additional context**

I have also tried the support e-mail address support@bsky.app and the support form provided online. I have sent a dozen messages over the course of two months now.

I have received no response to any of my e-mails to support@bsky.app.

Upon filling out the online form, I received a generic response each time with various steps to try. My responses to these messages remained unanswered.

I am at the end my rope here. I'd really like to regain access to my account - so maybe the right person is reading this.

**Comment by pfrazee** [comment]
Hey @katjazwitschert. I'm really sorry this is happening to you. We have an active support agent so I'm surprised you haven't gotten any help yet; I've reached out to them to find out what's going on there. (In a sense, this is a bug: you should be getting a response!)

I'll get back to you when I've spoken to support

**Comment by katjazwitschert** [comment]
@pfrazee Thank you for your help. I have heard back from your support team and it turns out that there's a typo in my e-mail address. They are looking into the issue so I am keeping my hope to get my account back.

It would be helpful if the password reset process gave the information that the entered e-mail was not registered (expected behavior B above). But I'm sure this is on the Bluesky roadmap already.

**Comment by pfrazee** [comment]
Glad that's moving forward, hope that gets resolved for you!

I need to check in on the current "best practice" but it's been long considered wise not to reveal whether an email is in use, to avoid giving away potentially private information.
