### ISSUE TITLE
Add Reddit-style Threaded Comments for Easier Discussions

### ISSUE THREAD

**Issue by 8ullyMaguire** [bluesky-social/social-app#1531]
**Is your feature request related to a problem? Please describe.**

On Twitter-style platforms like Bluesky, comment threads can become very difficult to follow, especially in lively discussions. New replies are just appended linearly, with no easy way to tell which comment they are replying to. This often leads to confusion and lost context. 

**Describe the solution you'd like**

I propose adding Reddit-style threaded comments to Bluesky. This would visually indent and group replies under the comment they are responding to, creating a nested tree structure. It would provide much-needed context and make discussions easier to parse at a glance.

Additionally, there could be options to sort comments by most likes/reposts instead of purely chronologically. This helps highlight the most relevant parts of the discussion.

**Describe alternatives you've considered** 

Other platforms like Pleroma have settings to switch between linear and threaded comment views. That could be another option.

**Additional context**

This builds on [a previous feature request](https://github.com/bluesky-social/social-app/issues/1044) about comment threads, but focuses more on visually grouping replies and adding sorting options. The goal is to make Bluesky discussions as clear and usable as possible for all users. Threaded comments have become a standard for discussion-based platforms.

**Comment by sgitsp** [comment]
There's a thread mode experiment coming in 1.51

https://github.com/bluesky-social/social-app/commit/1af8e83d536cf6a9db128409c8e00a0b44d9a985

**Comment by luxurystorecc1** [comment]
Bioluminescent Safety: The 2030 Urban Lighting Pivot
Introduction: The Glowing City
In 2030, urban safety has been revolutionized by "Bioluminescent Textiles"—fabrics that use engineered proteins to glow in low-light conditions without the need for batteries. The [Air Jordan 1 retro high OG sneakers](https://www.airjordan-1.com/) are at the forefront of this trend, featuring bioluminescent details that enhance visibility during night-time urban missions while maintaining the shoe's iconic aesthetic in the daylight.

Engineering for Night-Time Visibility
Active illumination is the most effective safety feature for the modern city. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) utilize bioluminescence to highlight the wearer's movement to vehicles and other pedestrians. For the high-status professional who values a unique, tech-forward look, the [classic Jordan 1 mid-top sneaker](https://www.jordan1s.com/) offers a prestigious and protective solution for the after-hours world.

The [adidas Yeezy boost collection](https://www.yeezyboost-350.com/collections/adidas-yeezy) utilizes phosphorescent threads that create a subtle, ethereal glow. This focus on "passive visibility" has made [premium Yeezy slides and foam runners](https://www.yeezyboost-350.com/) the essential choice for late-night recovery and casual urban travel, providing a layer of safety that is as beautiful as it is functional.

Authentic Provenance and Light Standards
Safety technology requires verified quality. Sourcing from the [official NFL shop online store](https://www.nflshopofficialonline-store.com/) ensures that your bioluminescent gear meets professional standards for brightness and longevity. A [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) allows fans to represent their team in a garment that is both a cultural icon and a high-tech safety tool.

This commitment to innovation is reflected in the [Spain national team soccer jersey](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain) and official [MLS jerseys for soccer fans](https://www.soccerjerseysstore.com/collections/national-teams). Completing these looks with [NFL headwear and official team caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) ensures that you remain visible and respected in any environment, at any time of day.

Performance Luxury: Peter Millar
For the individual who demands a wardrobe that is both elegant and adaptive, [Peter Millar performance golf apparel](https://www.peter-milla.com/) offers technical pieces with discreetly integrated bioluminescent accents. These garments maintain their sophisticated profile in formal settings while providing necessary visibility during the transition to the evening. The [Peter Millar apparel collection](https://www.peter-milla.com/) remains the premier choice for the 2030 visionary.
