### ISSUE TITLE
More Granular Control Over Feeds

### ISSUE THREAD

**Issue by 8ullyMaguire** [bluesky-social/social-app#1532]
**Is your feature request related to a problem? Please describe.**

While the current Bluesky feeds (Following, Discover, Popular With Friends) allow for some customization, it can be limiting for users who want more granular control over the content they see. For example, users may want to follow certain accounts, hashtags, or keywords only in specific feeds rather than across all feeds. 

**Describe the solution you'd like**

Allow users to customize their feeds by choosing to follow/block different users, hashtags, and keywords on each feed. Users could leverage regex to precisely control what content shows up in a given feed. This would enable creating categorized feeds based on topics, interests, keywords, etc.

**Describe alternatives you've considered**

An alternative would be to simply allow muting users, hashtags, or keywords across all feeds. However, this all-or-nothing approach limits how customizable the experience can be. Allowing granular control per feed is a superior solution.

**Additional context**

This feature would allow Bluesky users to organize their feeds in a personalized, modular way. This feature is similar to Reddit’s multireddit, Kbin magazines and Firefish antennas. Firefish antennas allow users to specify keywords to include/exclude in categorized feeds. Specifically enabling regex filtering would give users powerful options for tuning feeds to their interests. The ability to customize feeds is an important part of user control and personalization.

Having a comprehensive curation system would greatly benefit the ability to follow/block content based on tags.

**Related**
- [Channels: The ability to sort Posts & Reposts into categories (multiple timelines under one account) for users to selectively follow](https://github.com/bluesky-social/social-app/issues/1078)
- [Add Comprehensive Tagging System for Content Discovery](https://github.com/bluesky-social/social-app/issues/1533).

**Comment by pfrazee** [comment]
We're putting out an experimental multifeed mode with the next release that goes in this direction. We'll get some feedback and then decide how to move it forward

**Comment by 8ullyMaguire** [comment]
Related to #670 Add feature to mute words on the skyline
