### ISSUE TITLE
Few small visual UI changes that could make the website look nicer

### ISSUE THREAD

**Issue by Tanza3D** [bluesky-social/social-app#1539]
**Is your feature request related to a problem? Please describe.**

Depends, but probably not. Just a few little wonky things in the UI which I feel could be improved visuals-wise

**Describe the solution you'd like**

Note: this is just regarding desktop web in widescreen
I'll list each of my issues, and the way I'd resolve them:
- Profile picture is too big in the top left
I feel this could be downsized a bit, by doing so it looks nicer (in my opinion) but also ends up in-line with the back button;
![image](https://github.com/bluesky-social/social-app/assets/33783503/ca66c429-4027-421e-8921-a19df440c212)

- Search bar is too close to content
The search bar has a different padding on the top than on the left, making it feel much too close to the content, and this leads to it just generally looking wonky. Here it is with equal padding on the left and the top:
![image](https://github.com/bluesky-social/social-app/assets/33783503/9f7d8b6b-b77b-4810-829a-13268ae087ca)

- Description box for user edit too small
For users with big descriptions, this becomes a bit hard to edit, upscaling it with width and height is a nice solution:
![image](https://github.com/bluesky-social/social-app/assets/33783503/1ff4fbee-bdcd-44db-9b2a-f0602f1681b1)

I'm happy to try do a PR with these changes if wanted, though I feel someone else could do it easier and better as I have no experience with typescript or such.

**Comment by pfrazee** [comment]
Happy to try out PRs for each of these, just break them up into individual PRs if you could please!

**Comment by Tanza3D** [comment]
will do!
