### ISSUE TITLE
Back button visible on profile tab

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1566]
**Describe the bug**

There's a back button on the profile tag. I swear it didn't used to be there, might be a regression

**To Reproduce**

1. Go to profile tab

**Expected behavior**

Don't show back chevron on profile tab

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/10959775/41104976-79bc-4a34-96d7-ac992e8e79a5)

**Details**

 - Platform:  iOS
 - Platform version: 17
 - App version: 1.51.0 (5)

**Additional context**

It takes you to the timeline

**Comment by pfrazee** [comment]
Ah no that's always been there!

**Comment by mozzius** [comment]
Ah my bad, I saw there was a `showBackButton` prop so I thought that that might've the intended behaviour

**Comment by pfrazee** [comment]
Oh you mean this is showing on your profile when you press the tab. Yeah that's a regression.
