### ISSUE TITLE
Odd visual jitter

### ISSUE THREAD

**Issue by HenrickTheBull** [bluesky-social/social-app#1570]
**Describe the bug**
Graphical items tend to jump and jitter around on web

**To Reproduce**

1. Just click around, eventually it happens

**Expected behavior**
Items shouldn't just jump and jitter like it's a school dance. Refer to video below.

**Screenshots**
[Screencast_20230928_160906.webm](https://github.com/bluesky-social/social-app/assets/3945192/c5d231c2-d383-4098-a1ee-e23e8431c8f1)

**Details**

 - Platform: Desktop | Firefox
 - Platform version:  117
 - App version:

**Comment by pfrazee** [comment]
What OS?

**Comment by simonetthomas** [comment]
I've never seen that but I'd like it to become a feature, please!

**Comment by HenrickTheBull** [comment]
> What OS?

Fedora 38, I've also found it happens sometimes on Windows 11 as well in Firefox but not in Chromium based browsers.
