### ISSUE TITLE
Open User Profile Instead of Post When Clicking on User Handle

### ISSUE THREAD

**Issue by 8ullyMaguire** [bluesky-social/social-app#1578]
**Is your feature request related to a problem? Please describe.**

Currently, when a user clicks on a user handle in a post on Bluesky Social, it opens the post instead of the user profile.

**Describe the solution you'd like**

When a user clicks on a user handle in a post, it should open the user's profile instead of the post.

**Comment by Sininini** [comment]
Huh, it already works like that? In Chrome at least?

**Comment by 8ullyMaguire** [comment]
You are right, I didn't test it everywhere. It's in the search page where it isn't working as expected.
