### ISSUE TITLE
Publish an APK download

### ISSUE THREAD

**Issue by chfuchte** [bluesky-social/social-app#1581]
**Is your feature request related to a problem? Please describe.**

My problem is, that I cannot download the app from the Google Play store in Germany (EU). 

**Describe the solution you'd like**

Until this is patched, for all users who are not willing to use an app story, I'd suggest publishing an official APK for Android users.

**Describe alternatives you've considered**

Alternatively, you could create a PWA (progressive web app), which is just a manifest.json, and a small additional script, which allows users to download the web view as a Desktop-App, even on mobile. With the script, you are also able to send push notifications, and more if you want to.

**Comment by felschr** [comment]
Ideally APKs would be published in GitHub releases, so tools like [Obtainium](https://github.com/ImranR98/Obtainium) can be used.

On a related note, perhaps there could also be a release on [Accrescent](https://accrescent.app/).

**Comment by surfdude29** [comment]
From @haileyok's [comment in #2222](https://github.com/bluesky-social/social-app/issues/2222#issuecomment-2143580501):

> I'm adding a step to our current build process that produces a production APK and add them to GitHub releases, so that you can use Obtanium to fetch them rather than needing to the the Play Store.

So this issue can be probably be closed I think?

**Comment by haileyok** [comment]
Yep, see #2222 for more details on this (with Obtanium).
