### ISSUE TITLE
mention typeahead / autocomplete ditches @sweets.ky

### ISSUE THREAD

**Issue by thecubic** [bluesky-social/social-app#1582]
Hello hi, my operates-via-mentions bot has a UI problem on desktop web (tested also with mobile, same result exactly)

typing just the @, it shows the target:
![image](https://github.com/bluesky-social/atproto-website/assets/165080/6377076c-454a-4878-9165-78d6b6a2b4b2)

starting to type its name, it disappears immediately:
![image](https://github.com/bluesky-social/atproto-website/assets/165080/8a4d38d0-9830-4d45-966a-11df1e7d7754)

even when you type the whole handle, it's invalid:
![image](https://github.com/bluesky-social/atproto-website/assets/165080/7dea3f9e-7d82-4bbf-b769-d3d3af79b790)

This is quite annoying - and actually disabling -  I think that I was just lucky enough to mention it as a recent follow to put it in my personal cache, but otherwise it is not possible to mention that handle for other users, which is the point of the bot behind the account

Thanks!

**Comment by pfrazee** [comment]
Not sure which repo this should be in so I'm putting it on `social-app` for now.

@ericvolp12 do yall have bandwidth to fold in improvements on this?

**Comment by ericvolp12** [comment]
That account doesn't appear to have a `app.bsky.actor.profile` record at all (no displayname, no bio, etc.) so it didn't get indexed by the search service.

Compare: https://bsky.social/xrpc/com.atproto.repo.listRecords?repo=did:plc:7zmbq3223pb6kx7giq6wuplj&collection=app.bsky.actor.profile

To my repo: https://bsky.social/xrpc/com.atproto.repo.listRecords?repo=did:plc:q6gjnaw2blty4crticxkmujt&collection=app.bsky.actor.profile

Try setting the displayname to something and/or adding a description to the profile, then it should get indexed.

**Comment by pfrazee** [comment]
Got that tracked in another issue
