### ISSUE TITLE
Annoyingly large font size in selected post

### ISSUE THREAD

**Issue by freddyzwo** [bluesky-social/social-app#1590]
I find the large font size of the selected post quite irritating, especially on the smartphone. 
I only have the iOS app and Chrome on the desktop, but I guess it's the same on Android.
Would it be possible to change the template to a smaller size, e.g. from 22px to18px?

**To Reproduce**

Click on a post in the feed, the font size of the post content increases (16px to 22px in Chrome).

**Expected behavior**

The font-size should be slightly larger, currently it is annoyingly huge. I think it would be nice if it was similar to X where it increases from 15px to 17px.

**Screenshot**

left side: current state 22px (Chrome desktop)
right side: proposal 18px
![font sizes in Chrome (desktop)](https://github.com/bluesky-social/social-app/assets/10246518/41140c4f-de8b-4576-af2e-012883e18333)

**Comment by pfrazee** [comment]
Going to put up a PR with a smaller font and discuss with the team. This is a stylistic choice so no promises, but want to give it a look.
