### ISSUE TITLE
Change account directly via hamburger menu instead of via settings

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#1592]
**Is your feature request related to a problem? Please describe.**

When you have more than one account, it is rather complicated to change the selected account. Instead of changing it directly via the Hamburger menu that is visible on the top of the screen, one has to navigate from there to settings, where the available accounts are shown.

**Describe the solution you'd like**
I'd like the existing accounts to be selectable via drop down menu on the account side bar that is shown when clicking the Hamburger menu from the Timeline. This would streamline the user experience in a way several apps for other platforms have implemented account change.

**Describe alternatives you've considered**
I use Tusky for Fediverse and the official app for the platform formerly known as Twitter. Both offer a quick change of user accounts.

**Additional context**

**Comment by pfrazee** [comment]
The next release will have an instagram-style long press on the profile in the bottom right to open an account switcher. Is that what you're looking for? (Closing optimistically)

**Comment by HeyItsLollie** [comment]
The long-press doesn't apply to web clients, and honestly isn't exactly intuitive on mobile. I still encounter users who don't know that the feature exists, and the UI doesn't make this known either.

A simple hamburger menu is immediately visible and easy to understand.

![firefox - 2024-09-12 - 12-35-57](https://github.com/user-attachments/assets/686fd7a9-7191-4b61-869e-6c71acf123fc)
