### ISSUE TITLE
"Also followed by:" - On user profiles

### ISSUE THREAD

**Issue by SaySayTakamura** [bluesky-social/social-app#1610]
**Is your feature request related to a problem? Please describe.**

Something Twitter does is that every Profile (except your own) have a field in the Profile Page that is called "Also followed by" where it lists people that you follow that follow this specific user page.

When none of your followings follow that account it displays: "Not followed by anyone you follow"

This is something i miss from Twitter when using Bluesky and i think it would be useful to find some new people followed by your moots or when you find an account followed by that artist you admire.

**Describe the solution you'd like**

You could iterate the user Following list and take only the handles and check for those handles when the user sees another pages.

When user logs in:
```
   for(int i = 0; i < user.following.size(); i++)
   {
     follows.push_back(user.following[i].handle.string()); //Follows is the variable we use to store the people User follows further ahead we will use it to compare it with AnotherUser follows.
   }
```
When user access other user page

```
   for(int i = 0; i < anotheruser.following.size(); i++)
   {
      for(auto& fb : follows)
      {
        if (anotheruser.following[i].handle.string() == fb)
        {
          followby.pushback(fb); //Followby is the variable used to display the common followers between User and AnotherUser
        }
      }
   }
```

Sorry for the bothering and hope this is useful for anyone else.

**Comment by surfdude29** [comment]
An [update](https://github.com/bluesky-social/social-app/issues/3079#issuecomment-1986730064) from @haileyok in #3079:

> Yea we've had some discussions about this recently. Closing in favor of #1610 but it's on the radar!

**Comment by PSingletary** [comment]
App Version 1.86 ?

**Comment by SaySayTakamura** [comment]
> App Version 1.86 ?

Yup, they implemented it on the then latest version.

Might as well, close this.
