### ISSUE TITLE
Bluesky of the Month

### ISSUE THREAD

**Issue by SaySayTakamura** [bluesky-social/social-app#1611]
**Is your feature request related to a problem? Please describe.**

Something i'd like to see and that would be interesting for the App is to change the Splash Screen from time to time.

Allowing users to show their skills taking Blue skies from their cities and around the world.

**Describe the solution you'd like**

Opening a public pool that selects one of 3 photos, and the most voted photo would be selected to be the Splash Screen for the whole month

**Describe alternatives you've considered**

As said above a public pool would be a good alternative, but some curating/moderation would be required to avoid AI Photos or Plagiarized Works.

You could select someone from the community to do this.

Sorry for the bothering yet again and hope this is a good and useful idea for you guys.

**Comment by pfrazee** [comment]
This is a neat idea but I unfortunately don't think we have the bandwidth for it
