### ISSUE TITLE
Make bsky.social posts visible to non-users

### ISSUE THREAD

**Issue by christiaan2b** [bluesky-social/social-app#1613]
**Problem**

Bluesky posts are not visible to non-users, therefore Bluesky doesn't really contribute to the public conversation in the way that Twitter does.

**Solution**

Support traditional browsing on bsky.social, make posts visible to public.

**Alternatives considered**

There are sites like skeeet.xyz and firesky.tv that can make Bluesky posts visible to non-users, but for Bluesky to be part of the public conversation bsky.social needs to be browsable and easily linked to.

**Comment by deviantsemicolon** [comment]
Not a developer for bluesky, but I'm pretty sure they would have to do something to allow this in the AT Protocol first.

**Comment by pfrazee** [comment]
No this is just an update to the web app we need to make

**Comment by pfrazee** [comment]
This will be releasing quite soon
