### ISSUE TITLE
Left side menu cannot be swiped open initially

### ISSUE THREAD

**Issue by claabs** [bluesky-social/social-app#1620]
**Describe the bug**
On Android, the left side menu cannot be swiped open on fresh launch. You must first manually tap the hamburger menu icon for swiping open to work.

**To Reproduce**

1. Open the app fresh
2. Swipe from the left side of the screen to the right
3. Observe that the menu does not open
4. Tap the hamburger menu icon in the top left
5. Close the menu
6. Swipe from the left side of the screen to the right
7. Observe that the menu opens now

**Expected behavior**

The menu should swipe open from fresh launch. It's a pain to reach that corner of the device.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/6274312/8c21d8cb-6ed6-4d44-9bf2-d6448e9586c6

**Details**

 - Platform: Android 
 - Platform version: Unknown
 - App version: 1.51.0 (39) production

**Comment by pfrazee** [comment]
Can confirm, we ran into this a while back. It's a bad interaction between two gesture systems, IIRC.

**Comment by claabs** [comment]
This is resolved in the latest version of the app.
