### ISSUE TITLE
mute/ turn off reposts for specific users

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#1629]
some people post/repost a lot and I would like to mute certain people I follow from seeing their reposted content to my feed but not everyones. 

currently the only option is turning off reposts from everyone which isnt the idea situation.

Solution - ability to mute (hide seeing specific users reposts on my timeline)

![image](https://github.com/bluesky-social/social-app/assets/66647238/36615444-903d-4031-985a-93a99fc3d56a)

**Comment by mschwendener** [comment]
On the roadmap: https://github.com/bluesky-social/social-app/issues/1116

**Comment by bibble235** [comment]
Be keen for this feature too

**Comment by dark-swordsman** [comment]
Just want to throw in my support for this as well. Lots of scenarios where this could be useful, and it's baffling it's not a feature yet, given the feed customization features that already exist.

**Comment by osydhn** [comment]
hoping this gets added sometime soon

**Comment by Krovasan** [comment]
would love this feature as well

**Comment by deficiencyproductionz** [comment]
This would make bluesky so much better

**Comment by erikdarlingdata** [comment]
Not having this makes me not look at the app.

**Comment by mschwendener** [comment]
Solved, see Solved, see https://bsky.app/profile/bsky.app/post/3msqpuobiwk2t
