### ISSUE TITLE
Modal dialogs make Chrome treat search fields as password inputs

### ISSUE THREAD

**Issue by MarioLiebisch** [bluesky-social/social-app#1648]
**Describe the bug**
It seems that at least some modal dialogs shown inside the app will make Chrome treat search input fields as password inputs, unintentionally offering auto-completion/password generation.

While this might appear as a minor nuisance, it's actually rather disruptive, since this also causes Chrome to offer or directly save the input text as a password, if you try to confirm a search with the return button, potentially overwriting the actual password used for accounts or at least spamming its built-in password manager with non-accounts.

**To Reproduce**

* Refresh the page to start from a clean slate.
* Open the "Settings" page.
* Click a few times into the search input box on the top right.
* The box gains input focus but works as expected.
* Click the link to change your account's email address.
* Cancel editing the email address.
* Click twice into the search input box on the top right.
* Observe the browser suddenly offering autofill options for passwords.

**Expected behavior**

Search input fields should never be interpreted as password inputs by the browser.

**Screenshots**

![Chrome offering to generate a password since it assumes the search input field is actually a password field.](https://github.com/bluesky-social/social-app/assets/1854245/4406688a-556c-48c2-9706-ce39f377fdb5)

![GIF demonstrating the issue/reproduction steps.](https://github.com/bluesky-social/social-app/assets/1854245/b85ab4c4-d81b-42e5-9978-f1e7e1121f8d)

**Details**

 - Platform: Chrome (Windows 11, x64)
 - Platform version: 117.0.5938.150
 - App version: 1.52.0

**Additional context**

**Comment by jonolds** [comment]
still having this issue when I click on some search results.
