### ISSUE TITLE
Links in profiles broken on Android

### ISSUE THREAD

**Issue by Sininini** [bluesky-social/social-app#1649]
**Describe the bug**
@someone_abc123 links in profiles work for a split second and then turn into normal text in the Android app. They work in Chrome.
You can do links to profiles without @, but since it's possible to do it the former way I think it should be functioning correctly.(links without @ don't actually work, my mistake)

Edit: Same behaviour happens to other links as well, but inconsistently. They work in most profiles, but are broken in others.
For example look at this profile on Android: https://bsky.app/profile/brushfeather.bsky.social

**To Reproduce**

1.  Add @someone_abc123 to your profile.
2.  Open profile on Android

**Expected behavior**

I expect the links to stay there after they work for a split second

**Details**

 - Platform: Android
 - Platform version: 12
 - App version: 1.52.0

**Comment by Sininini** [comment]
I noticed it happens to links off-site as well. Rather inconsistently. I'll update the title

**Comment by Sininini** [comment]
Turns out links in bios without @ don't actually work at all. Can't believe it took me this long to find that out.
@ someone in bio is still broken on Android though.

**Comment by pfrazee** [comment]
This should be fixed now
