### ISSUE TITLE
Can't scroll subscribed mute lists in browser

### ISSUE THREAD

**Issue by Sininini** [bluesky-social/social-app#1650]
**Describe the bug**
It's not possible to see mute lists that are hidden below the screen because scrolling doesn't work. 
This is in Chrome, it works fine in Android.

**To Reproduce**

1. Subscribe to enough mute lists to fill the screen, you can probably also just make your window short with less mute lists
2.  Use Chrome and try to scroll down

**Expected behavior**

Being able to scroll down

**Details**

 - Platform: Desktop Chrome Windows
 - Platform version:  Latest Chrome 117.0.5938.150

**Additional context**

Irrelevant to this bug, but I don't feel like making an issue for this: Mutelist page has two buttons for making a new list basically on top of each other. In browser, not in Android app,

**Comment by trantus** [comment]
It seems to be fixed, doesn't it?

https://github.com/bluesky-social/social-app/assets/34245032/020e8a68-fe69-4c1a-8a20-5d738f48c872
