### ISSUE TITLE
Fix/remove the interstitial for internal links

### ISSUE THREAD

**Issue by fenarinarsa** [bluesky-social/social-app#1652]
**Describe the bug**
The interstitial added by #1573 warns that we leave Bluesky even if we actually don't, when making a link to bsky.app with a regular text (not a 'false URL')

**To Reproduce**

1. Create a link to an element of bsky.app (post, feed...) but with a regular text (like : "check my thread here")
2. Click on the link

**Expected behavior**

Either change the text of the card link, or remove the card link? I don't know what would be best.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/17545417/17667720-b5d2-4748-8c31-ed01d06d2a83)
![image](https://github.com/bluesky-social/social-app/assets/17545417/aa922a6b-1b25-43e4-9c8a-c0c10f1990a4)

**Details**

 - Platform: Firefox 
 - Platform version: 118.0.1 Windows
 - App version: 1.5.2 I think?

**Additional context**

This feature could also be used to create abuse (like writing insults that lead to someone's account). That might be taken into consideration.

**Comment by pfrazee** [comment]
Fix on the way
