### ISSUE TITLE
"time to content" change for search page feels a bit misguided

### ISSUE THREAD

**Issue by Sininini** [bluesky-social/social-app#1653]
It's now showing suggested follows at the top which never change and are completely irrelevant to my interests - it's not really helpful/interesting content. I have to scroll down multiple screens every time I want to check if anyone interesting shows up.

I'm not saying it should definitely be reverted, just that it's less useful now and maybe there's better solution to making it useful and performant at the same time.

**Comment by pfrazee** [comment]
I appreciate the feedback and don't disagree. This is just a temporary situation until the backend team can provide some new APIs. It will improve!
