### ISSUE TITLE
Typing << or >> In Compose Post Freezes the App

### ISSUE THREAD

**Issue by jcsalterego** [bluesky-social/social-app#1654]
**Describe the bug**

Attempting to type `<<` or `>>` in a compose post/reply modal on the web hangs the view.

**To Reproduce**

1. Compose Post or Reply to a new post
2. Attempt to type `<<` or `>>`

**Expected behavior**

One can type `<<` or `>>`

**Screenshots**

N/A

**Details**

 - Platform: Safari, Chrome
 - Platform version:
 - App version: 1.52.0

**Additional context**

Feels like an infinite loop is looping.

**Comment by jcsalterego** [comment]
sry esb

**Comment by haileyok** [comment]
>.>
