### ISSUE TITLE
The page does not scroll when hovering some of the side panels

### ISSUE THREAD

**Issue by RobotoSkunk** [bluesky-social/social-app#1678]
**Describe the bug**
When you put the cursor on the left or side panel with a viewport greater than 1300 x 580, the scroll event of the page gets cancelled, making it a little annoying for some people.

**To Reproduce**

1. Open https://bsky.app.
2. Put the cursor over the left or side panel.
3. Try to scroll.

**Expected behavior**
The website scrolls correctly.

**Screenshots**
Not applicable.

**Details**

 - Platform: Desktop Brave Linux
 - Platform version: 1.59.117
 - App version: 1.52.0

**Additional context**
Last month the first time I tried to use Bluesky, the first thing I've seen was that the scrolling didn't work correctly, until I noticed that I just had to move the cursor to another place except one of the sides panels.

I thought that this bug would be fixed later, but it is still there.

**Comment by RobotoSkunk** [comment]
Maybe this line has something to do with?

https://github.com/bluesky-social/social-app/blob/c13b6946bab9600cba670478c2f64771cc75f1af/src/Navigation.tsx#L274

**Comment by pfrazee** [comment]
@gaearon's upcoming updates may fix this

**Comment by RobotoSkunk** [comment]
This has been fixed in the latest update of Bluesky website
