### ISSUE TITLE
Improve the feed outage behaviors in the app

### ISSUE THREAD

**Issue by HenrickTheBull** [bluesky-social/social-app#1685]
**Describe the bug**
Occasionally see this error at the top of the screen

**To Reproduce**

1. Just refresh, it happens sometimes.

**Screenshots**
![image](https://github.com/bluesky-social/social-app/assets/3945192/42c639c6-e7d4-4038-8427-c1cc412f579e)

**Details**

 - Platform: Desktop (Chromium Based Browser/Firefox) , iOS, and Android

**Comment by HenrickTheBull** [comment]
Figured it out: One of my feeds was out, could possibly do with a better error explaining the issue if a feed goes out.

**Comment by pfrazee** [comment]
Yeah we've got work on this planned

**Comment by pfrazee** [comment]
https://github.com/bluesky-social/social-app/issues/1670

**Comment by pfrazee** [comment]
Done
