### ISSUE TITLE
Pinned feeds not recognisable in feeds view

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#1702]
## Describe the bug
Pinned feeds are displayed as registers on the home timeline. On the website they are shown on top and can be sorted there. This used to be the case in the app as well. As of recently the feeds view neglects pinned feeds. Sorting feeds (relevant for the home timeline) is only possible via browser.

## To Reproduce

- Go to feeds
- Feeds are sorted alphanumerically. Pinned feeds are listed inbetweenT
- The pinned property is not visible until a pinned feed is tipped on.

## Expected behavior

Pinned feeds should be displayed on top of all other feeds. The order of feeds in the home timeline should be editable by sorting within the app.

## Details

Platform: Android app

Platform version: 1.53.0

**Comment by ansh** [comment]
Can you try clicking this link on your phone with Bluesky installed? https://bsky.app/settings/saved-feeds 

It should allow you to edit the pinned list order

Alternatively, you can click on the Feeds tab (middle tab in the bottom on mobile) and then click the settings icon on the top right corner.
