### ISSUE TITLE
[mobile] Following feed will not load posts older than a few hours

### ISSUE THREAD

**Issue by joelghill** [bluesky-social/social-app#1704]
**Describe the bug**
Several users in my social circle have reported that their following feed will not load posts more than a few hours old. For some people the feed has always been broken, for others it started doing this recently.

This issue appears to only be present in the official mobile app. Appears to work correctly on the web.

**To Reproduce**

1. Load your following feed

**Expected behavior**

Feed should load

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/1980543/e5f0d3c5-5dd4-4833-9799-03a23e006f3c)

**Details**

 - Platform: mobile
 - OS: Android 14 UP1A.231005.007. 
- App Build: Bluesky Build 1.53.0 (42) production

**Additional context**

Link to person describing the issue: https://bsky.app/profile/becomingkelsey.social/post/3kbsuqr5p2u2p

**Comment by pfrazee** [comment]
Yeah this is a known issue that will be resolved with a rewrite of the backend in the near future. Closing as a duplicate
