### ISSUE TITLE
Desktop left navigation design changes

### ISSUE THREAD

**Issue by LegendEffects** [bluesky-social/social-app#1714]
**Is your feature request related to a problem? Please describe.**

The current design for desktop navigation doesn't sit well with my eyes, I'm unsure if this is a valid issue but hey-ho, I'm happy to attempt a pull request for these changes and create more of these issues if they're helpful.

The spacing around the navigation on desktop is a bit funky:
- The navigation items are stretched to full width (visible on hover) but the new post button is only inlined
- The gap between main navigation and header/footer isn't consistent
- The height of the new post button is much less than the height of navigation items
- I think the gap between the main feed to the left navigation and right navigation is different?
 
**Describe the solution you'd like**

I've whipped up a quick mockup in Figma, only touching the left side of navigation and using a screenshot as a reference. I'm probably not using the right icons, and I couldn't use the system font so it's using Inter.

![image](https://github.com/bluesky-social/social-app/assets/25408153/3f89f08d-98e9-4ce9-be30-37ee116d5530)

The following changes were made:
- The gap between navigation and the feed was increased to 16px
- The gap between header, body, and footer of left nav was increased to 16px
- The new post button now fills its container's width
- The font size of the post button was decreased to 18
- The background colour of the default avatar was changed to match the new post button

**With reference shown**

![image](https://github.com/bluesky-social/social-app/assets/25408153/8201884d-4b8f-46f2-8a0e-9670e31333a7)

**Additional context**

This isn't intended as a dig, I'm loving seeing the progress on Bluesky, any feedback is appreciated :)

**Comment by pfrazee** [comment]
We're going to do a design pass on this in the near future
