### ISSUE TITLE
Invalid Handle for own domain with no DNS panel

### ISSUE THREAD

**Issue by gaardhus** [bluesky-social/social-app#1715]
**Describe the bug**
When I try to update my handle to my domain with the no DNS panel option, the Verify Text File says `Domain verified!` but afterwards my handle says `Invalid Handle` (and my profile url changes to the text in the verification file instead of my domain).

**To Reproduce**

1. Follow the instructions for custom domain handle with no DNS.

**Expected behavior**
I expected my handle to become my domain.

**Screenshots**
Settings
![image](https://github.com/bluesky-social/social-app/assets/46934916/f6368995-7cb3-4d80-bcc0-3deaaed47028)
Profile
![image](https://github.com/bluesky-social/social-app/assets/46934916/cb6e2674-b6bf-43f4-8ba5-e946e45bc7e6)

**Details**
 - Platform: desktop firefox linux, android app
 - Platform version:
 - App version: 1.54.0 (43)

**Additional context**

**Comment by ansh** [comment]
Can you please reach out to support on https://blueskyweb.zendesk.com/hc/en-us ? We will be more than happy to help you there.

**Comment by CoppaMondo** [comment]
> Can you please reach out to support on https://blueskyweb.zendesk.com/hc/en-us ? We will be more than happy to help you there.

Hi Ansh, I've contacted support three times about the incorrect (it isn't) DID file being returned and haven't had a single reply. Is there anything you can do? Thanks, in advance.
