### ISSUE TITLE
Image cropping aspect ratio buttons are invisible in dark mode

### ISSUE THREAD

**Issue by aiakared** [bluesky-social/social-app#1729]
**Describe the bug**

When using dark mode (system or manually selected) the buttons for selecting the aspect ratio on the image cropping modal aren't visible. The buttons are there but are styled black which makes them blend into the background.

**To Reproduce**

1. Change your system theme or web app theme to dark mode
2. Open an image cropping dialog (e.g. upload a profile picture)
3. Aspect ratio icons that aren't the currently selected aspect ratio aren't visible

**Expected behavior**

Icons should be styled in a way that is visible.

**Screenshots**

Dark theme:
<img width="610" alt="image" src="https://github.com/bluesky-social/social-app/assets/70045485/d954dbb7-6a9b-491d-ad76-2e02e40f17b6">
Light theme:
<img width="625" alt="image" src="https://github.com/bluesky-social/social-app/assets/70045485/390fd572-968c-42a5-8c9c-e786f84cccf0">

**Details**

 - Platform:  Desktop all browsers (tested on Chromium (Arc), Firefox, & Safari)
 - Platform version: n/a
 - App version: 1.53.0

**Additional context**

I'm interested in helping fix this bug.

**Comment by pfrazee** [comment]
Thank you very much @aiakared !
