### ISSUE TITLE
Potentially Misleading Link warning doesn't deal with capitalisation in URLs (maybe iOS only?)

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#1731]
**Describe the bug**
See: https://bsky.app/profile/bossett.bsky.social/post/3kc7dpy3yqy2e - this link pulls up a malicious link warning, despite the URL matching the text.

![image](https://github.com/bluesky-social/social-app/assets/114112113/6c272d8f-3c20-47a4-a6ee-06872fae1945)

**To Reproduce**

1. Make a post with http://tEsT.com/ or similar - the link in the post will be lowercased, but in the facet it will not be.

**Expected behavior**

No Malicious Link warning should appear

**Screenshots**

**Details**

 - Platform: iOS
 - Platform version: -
 - App version: 1.54.0 (1)

**Comment by intrnl** [comment]
looks like this might be specific to React Native/Hermes because the URL API is expected to normalize the hostname for Chrome/V8 and Firefox/SpiderMonkey
![image](https://github.com/bluesky-social/social-app/assets/20620901/a053f7f6-5a6e-4496-b649-41bbc6e2eae2)

**Comment by estrattonbailey** [comment]
Filed an issue with our polyfill: https://github.com/charpeni/react-native-url-polyfill/issues/462

Smoothed over this specific issue in #1980, but we should revisit.
