### ISSUE TITLE
Deleting an App Password does not revoke access to an app using that password

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#1733]
**Describe the bug**
Deleting an App Password does not revoke access to an app using that password. I have waited over 30 minutes, which seems like more than enough time. Should really be instant, correct?

**To Reproduce**

1. Create an App Password in my settings, Bsky web app.
2. Sign in to Graysky using that app password.
3. Delete that App Password in Bsky web app.
4. Sign out of Graysky.
5. Sign in to same account on Graysky again, am not prompted for password. I am able to interact with my profile. I have tested Liking a post in Graysky, and can see in Bsky webapp that the Like was recorded.

**Expected behavior**

Deleting the App Password should have caused Graysky, or any other app, to prompt me for a password.

**Details**

 - Platform: I used Bsky webapp and Graysky iOS, but this seems like a Bsky backend issue.

**Comment by adamatic-me** [comment]
OK, so the session expired after 2 hours, and did prompt for a new password.

If this is good enough, then this could be closed.

**Comment by ansh** [comment]
We are working on some potential changes for auth but such a behavior is expected. Closing this issue for now.
