### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by gorlanova** [bluesky-social/social-app#1740]
**Is your feature request related to a problem? Please describe.**

No previous issue yet
I would like to help translating the web app / mobile app to French

**Describe the solution you'd like**

If I can access a file containing all english strings / labels, I will translate them to French (I'm French) and commit them here

**Describe alternatives you've considered**

None (pardon me if there are any, I'm not an i18n expert)

**Additional context**

No additional context to provide, but here's a baguette emoji 🥖

**Comment by iamwinner422** [comment]
Wanna help for French Translation too

**Comment by pfrazee** [comment]
I appreciate it! We have "internationalization" tooling on our roadmap for the next couple months. I'm going to close this issue for now but we'll keep everyone updated.
