### ISSUE TITLE
Broken links from "Copy Post Text"

### ISSUE THREAD

**Issue by YuriGal** [bluesky-social/social-app#1742]
**Describe the bug**

If a post text contains a long URL, using "Copy Post Text" copies text with broken URL.

**To Reproduce**

1. Create post with a long URL in post's text, e.g https://chrome.google.com/webstore/detail/sky-follower-bridge/behhbpbpmailcnfbjagknjngnfdojpko
2. Use "..." -> Copy Post Text
3. Paste the text somewhere

Text will contain a broken link, e.g. in the above example `chrome.google.com/webstore/det...`

**Expected behavior**

Text should contain full unbroken URL

**Comment by intrnl** [comment]
I suppose one question before trying to make this work would be what to do for links that aren't valid, e.g. [this post from Techmeme](https://bsky.app/profile/did:plc:pv7fudnt4dspurzdnyq73pfe/post/3kbzrhz3v3p2p) where it uses a completely different label.

should links from those be copied as well, and how would that look like?

**Comment by YuriGal** [comment]
That is a good question. I can imagine 2 possible solutions:
1. On copying replace the labels with the original URLs. But without labels it might get confusing, and post risks to go over character limit.
2. Add a general markdown support for links. So every link can be represented in post text as `[label](url)`

**Comment by estrattonbailey** [comment]
This will also need to be fixed for, say, when Slack unfurls a URL 👍
