### ISSUE TITLE
Limit replies to followers

### ISSUE THREAD

**Issue by thktkblt** [bluesky-social/social-app#1746]
Often, I just want to talk with my own audience and not random passerby that came from feeds. I've read the proposal about reply-gating, and perhaps it would be nice when that feature becomes available, there's also option to limit replies to followers only.

Of course if some people really insist to troll, they can just follow, reply, and unfollow. If you want extra safety, you can see Tumblr—they allow gating the replies to followers who have followed for a week. But I don't know if in Bluesky it would be viable or computationally heavy.

**Comment by pfrazee** [comment]
This feature is on the way, actually! It's implemented in the API and we just need to catch up.

**Comment by thktkblt** [comment]
Cool! Excited to see it.

**Comment by alexkuz** [comment]
@pfrazee was this feature actually implemented?
I've seen some complaints about this on the app:
https://bsky.app/profile/mattielubchansky.com/post/3lb5q3r6qd22m
https://bsky.app/profile/lackingsaint.bsky.social/post/3ledawcpf5s22
- and it looks like there is indeed no option to exclude non-followers from replying or quoting.
