### ISSUE TITLE
Better control for the "Show Replies" setting

### ISSUE THREAD

**Issue by FlorentDancy** [bluesky-social/social-app#1762]
**Is your feature request related to a problem? Please describe.**

Let's take accounts A and B that I follow, and account C that I don't.
I wish there was a setting:

- preventing me from having in my feed a reply from account A to account C (since I don't follow account C)
- allowing me to have a reply from account A to account B (since I follow both accounts) or from account A to account A (own reply to one's post) in my feed

**Describe the solution you'd like**

I wish the "Show Replies" setting was split into 2 when indicating "Yes":

1. Show "all" replies (current behaviour, with existing Reply Filters)
2. Only show replies to posts from accounts you follow (either post creator or another account you follow)

**Describe alternatives you've considered**

As far as I understand, there's no way to achieve that at the moment

**Additional context**

Related to https://github.com/bluesky-social/social-app/pull/885 and https://github.com/bluesky-social/social-app/issues/791

**Comment by pfrazee** [comment]
Isnt that what this is for?

![CleanShot 2023-10-27 at 09 48 55@2x](https://github.com/bluesky-social/social-app/assets/1270099/f46effc1-b7bf-4f8d-86bd-2440ba37297a)

**Comment by surfdude29** [comment]
It was removed in 1.90 as part of changes to what posts are shown in the Following feed:

https://bsky.app/profile/bsky.app/post/3l2s5vdthls2h

They were somewhat controversial changes, and the Bluesky team have been listening to the feedback from users and have floated some ideas for improvements.

**Comment by HeyItsLollie** [comment]
Oh wow, what. Biased here, but the best improvement would be to simply restore the feature.
