### ISSUE TITLE
Graphic imagery warning coverage is too zealous

### ISSUE THREAD

**Issue by scottdotweb** [bluesky-social/social-app#1770]
If you post a link where the thumbnail is deemed to have graphic imagery, the warning hides the entire link, not just the thumbnail. 

Then, if someone quotes that post, the warning hides the link in the quoted post, as in [this example](https://bsky.app/profile/goingmedieval.bsky.social/post/3kcxi5dbeju22). As a consequence the person reading the quoted post may have no idea that it contained a link. If they do know it does, from the context of the quote, getting to the link requires:
* opening the warning in the quote
* opening the quoted post
* opening the warning in the quoted post. 

The image warning should be applied specifically to the thumbnail within the link preview and only require opening once, including when its parent post is being quoted.

**Comment by pfrazee** [comment]
Yeah it is too intense, thanks for the report
