### ISSUE TITLE
Make "back" button goes to previous page instead of the main page

### ISSUE THREAD

**Issue by thktkblt** [bluesky-social/social-app#1778]
I've looked here to see if someone already talked about it, but seems like there's none yet (sorry if it's double).

Example: I visited an account on my timeline. From that account I clicked on another accounts and so on. Currently, when I tap on the back button, instead of going back to the previous page/account it would go straight to home.

**Comment by estrattonbailey** [comment]
Hey @thktkblt 👋 plz use the provided Issue template in the future 😃 

What platform are you using e.g. web, Android, iOS?

We do have #710 that might overlap with this report.

**Comment by thktkblt** [comment]
Right, sorry and thanks for reminder! After checking it in web version I just realized it's a bug instead of a nonexistent feature. I will close this one and make a proper labeled post. #710 seems to be different issue.
