### ISSUE TITLE
Threaded Mode keeps getting disabled, even when I've already enabled it many times

### ISSUE THREAD

**Issue by onmyouji** [bluesky-social/social-app#1780]
**Describe the bug**

When I enable Threaded Mode (Settings - Thread Preferences), it always gets disabled from time to time.
This is on web app (bsky.app), using Firefox 119.0 on Windows 10.

**To Reproduce**

1. Visit bsky.app on your web browser (I use Firefox).
2. Go to Settings - Thread Preferences.
3. Scroll down and enable Threaded Mode (set it to Yes).
4. Use bluesky as normal. From time to time, the Threaded Mode will revert back to No (disabled).

**Expected behavior**

When I've enabled Threaded Mode, the settings shouldn't revert back to disabled.

**Screenshots**
![2023-10-31_230946](https://github.com/bluesky-social/social-app/assets/8424198/40d9a76a-328d-4919-99b5-1d21721c65f5)

**Details**

 - Platform: Desktop Windows 10 Home 64-bit
 - Web browser: Firefox 119.0

**Additional context**

I just want to confirm if other users are also experiencing this problem. I'm worried that my account is compromised or something. Already reset my password just to be safe, but this issue still happens.

**Comment by mschwendener** [comment]
Happened to me once, some updates ago - stayed put after the last two updates. 

BUT: "Adjust the number of likes a reply must have" **got put back to 2,** instead of 0 - possibly not yesterday, but during an earlier update.

**Comment by pfrazee** [comment]
This _should_ stabilize as clients update to latest. I'm going to optimistically close as fixed

**Comment by mschwendener** [comment]
fwiw: still active in my account, using MacBook and iPhone
