### ISSUE TITLE
Posts are duplicated on the Following feed

### ISSUE THREAD

**Issue by emilyliu7321** [bluesky-social/social-app#1805]
**Describe the bug**
The same thread (two posts) was duplicated on the Following feed 5 times, followed by `Internal Server Error`, and then the rest of the timeline.

**To Reproduce**

Not clear

**Expected behavior**

Posts should appear once in the feed

**Screenshots**
<img width="595" alt="image" src="https://github.com/bluesky-social/social-app/assets/22510954/4b0b94af-7f95-46a9-95ba-cb47869a02ab">
**Details**

 - Platform: Desktop Arc (chromium)
 - Platform version: 1.14 (Chromium Engine Version 118.0.5993.117)
 - App version: 1.55

**Additional context**

N/A

**Comment by pfrazee** [comment]
This is likely due to duplicate react keys slipping through. It apparently still happens on rare occasions (based on some recent reports in the app).

**Comment by pfrazee** [comment]
This should be fixed now
