### ISSUE TITLE
bsky shows inaccurate relative times if the clock on the host is set incorrectly

### ISSUE THREAD

**Issue by jyn514** [bluesky-social/social-app#1812]
**Describe the bug**

If the time zones on the host are set wrong, bsky will show "N hours ago" instead of "ten seconds ago" or "now" immediately after a post is created.

**To Reproduce**

1. Set the time and date manually into the future in Windows 10: 
![image](https://github.com/bluesky-social/social-app/assets/23638587/4688a208-142a-461f-91cf-80e5026e55fc)
2. Make a new post (or just look at an existing post, they have the bug too)
3. Observe that all posts show the relative time as "now".

**Expected behavior**

bsky should either show the absolute time or an accurate relative time.

**Screenshots**

This shows "now" when it should really show "1 hour ago" (notice "8:17 AM" in the bottom right, although I took the screenshot at 11:17 EST).
![image](https://github.com/bluesky-social/social-app/assets/23638587/e57b2449-525c-454a-b84b-5b31c4da0384)

**Details**

 - Platform: Desktop Firefox Windows
 - Platform version: Firefox 119.0, Windows 10 (not sure the patch version, can look it up if you care)
 - App version: Build version: 1.55.0; Platform: web

**Additional context**

I first hit this because dual-booting Linux and Windows screws up the CMOS time (Windows treats it as time-zone aware whereas linux treats it as UTC).

Note that this is *not* specific to setting the time into the future; manually setting it to sometime in the past also shows wrong relative times.

**Comment by jyn514** [comment]
![image](https://github.com/bluesky-social/social-app/assets/23638587/a1785188-89f9-43c9-94f9-c5811c351c06)
lol

**Comment by jyn514** [comment]
here's a possible way this could be fixed:
- server returns the current time
- client records the current time according to the host and measures the difference
- it adds that difference every time it calls Date.now() to update the relative times

then you can still update in real-time, but it's accurate (or at least, as accurate as the ticks on the host, which hopefully are harder to break than timezones).

**Comment by pfrazee** [comment]
We do need to make sure that trusted timestamps are being used (aka the appview) but if the client has it's clock wrong, isn't this a somewhat fruitless effort? I don't want to try to implement a clock sync to the client

**Comment by jyn514** [comment]
yes, that makes sense. i no longer have this problem, i figured out how to get linux's system clock to be timezone-aware.
