### ISSUE TITLE
Pressing tab while tagging a user does not select from the list

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#1831]
**Describe the bug**
When composing a post on Web and attempting to tag a user via an @, pressing tab does not select from the list. Instead, it ignores the list to highlight the file uploader, the emoji selector, and then the language selector in that order prior to highlighting the list. Even when uploading the list, it only sifts through it rather than selecting an entry.

**To Reproduce**

1. Compose a post.
2. Type '@'
3. Press Tab
4. Observe

**Expected behavior**

Similar to GitHub or Discord for comparison, pressing tab with the tag selector pulled up to autofill the top result. e.g: If I were to type `@paul` or `@pfra` prior to pressing tab, I would expect it to then fill the result of `@pfrazee` rather than having to manually click it or press enter. 

**Details**

 - Platform: Desktop, browser independent
 - Platform version:
 - App version:

**Comment by pfrazee** [comment]
Oh yeah this has been annoying the shit out of me
