### ISSUE TITLE
Merge feed not displaying custom feed's name

### ISSUE THREAD

**Issue by emilyliu7321** [bluesky-social/social-app#1848]
**Describe the bug**
The merge feed shows the custom feed's ID instead of the name.

**To Reproduce**

Scroll til you see a merge feed post in your feed.

**Expected behavior**
This should say "From Bluesky Team" but instead says "From bsky-team" 
https://bsky.app/profile/did:plc:z72i7hdynmk6r22z27h6tvur/feed/bsky-team

**Screenshots**
<img width="600" alt="image" src="https://github.com/bluesky-social/social-app/assets/22510954/340f8f71-3283-4331-9240-2c3bfd39d6d8">

**Details**

 - Platform: Desktop
 - Platform version: Arc Version 1.15.1 (43023), Chromium Engine Version 119.0.6045.105
 - App version: 1.56

**Additional context**

My account was migrated to the morel server already

**Comment by pfrazee** [comment]
Should be fixed
