### ISSUE TITLE
Quoted reposts aren't being counted in the repost count of the original post.

### ISSUE THREAD

**Issue by WriterStat** [bluesky-social/social-app#1852]
**Describe the bug**
Quoted reposts aren't being counted in the repost count of the original post.

**To Reproduce**

1. Click the repost button on a post and select 'Quote Post'
2. Fill out text and repost by clicking the Post Button.
3. Check original post's repost count.
4. No change in original post's repost count even though original post was reposted/quote posted.

**Expected behavior**

When an original post is reposted, by 'quote post' the original post's repost count should go up by 1 or by how many times a post was reposted by other users using the 'quote post' choice. 

**Details**

 - Platform: desktop firefox windows browser
 - Platform version: windows 11
 - App version: firefox 119.0.1

**Comment by surfdude29** [comment]
I think this now be closed with the release of 1.90.
