### ISSUE TITLE
internal server error after login

### ISSUE THREAD

**Issue by GuidoDr** [bluesky-social/social-app#1874]
**Describe the bug**

After login into either the web browser at https://bsky.app/ or in the android app an internal server error is shown.
On Thursday November 9th the login was still working fine and I did posts with that login. Yesterday Friday November 10th the error did occur the first time and today the error still remains.
Another private login of myself is still working fine.
(both accounts are domain accounts, just with different domain names)

Has the problems eventually something to do with these migrations?
https://github.com/bluesky-social/atproto/discussions/1832

**Expected behavior**

no more internal error anymore like it has been until Thursday November 9th 14.27 (UTC +1) when I did the last posts with that account.

**Screenshots**

![grafik](https://github.com/bluesky-social/social-app/assets/33029486/5ea1da0c-5b71-477b-9bb4-88077bab23da)

**Details**

 - Platform: 
 - Platform version:
 - App version:

**Additional context**

**Comment by NickPink** [comment]
I have the same issue.

**Comment by GuidoDr** [comment]
The only feedback that I have gotten so far from the Bluesky support is the following.
But the steps did not solve the problem so far as I wrote back to them.
The account cannot be used anymore since November 10th ...

**Comment by GuidoDr** [comment]
I have not gotten any information so far from the Bluesky support that the problem was solved.
But I just noticed that the login is now working again, so it looks like  the Bluesky support has solved the problem.

**Comment by NickPink** [comment]
It’s working for me as well now!
