### ISSUE TITLE
Show number of views for the post

### ISSUE THREAD

**Issue by YuriGal** [bluesky-social/social-app#1883]
**Is your feature request related to a problem? Please describe.**

Currently it's impossible to tell how many times the post has been viewed.

**Describe the solution you'd like**

Add numbers of views next to numbers of likes and reposts. Number of views can be private, visible only to the user on their own posts.

**Comment by pfrazee** [comment]
We're probably not going to do this, I'm afraid. For one, we can't get an accurate count due to the open network. For two, I'm not a big fan of collecting this metric.

**Comment by YuriGal** [comment]
I don't even remember why I opened this issue. Must've been something very specific, because now for the life of me I don't know why I would need this. My bad, sorry.

**Comment by emanuelesan** [comment]
from the technical pov, I guess that if you can view the number of likes across the network you can also have a viewer count. From a use case point of view, number of views is necessary to calculate engagement on a post. if I'm using this for marketing purposes (and ultimately marketing is something that a social network would like to have imho) you need a denominator for your interaction count.

**Comment by kf106** [comment]
I would like to cast a vote for this never to be implemented, even if somehow it becomes technically possible.

One of the things I like about Bluesky is that this metric isn't available. On platforms like LinkedIn it becomes an obsession to measure your post success by it, and it's psychologically damaging.

**Comment by Oracleofbluesky** [comment]
Bluesky needs to add view count, and the longer you wait, the more it costs all of us.
43.5 million registered users sounds impressive until you compare it to ~3.7 million daily actives. Threads has 18x more engaged users. That gap doesn't close by accumulating sign-ups. It closes by giving creators a reason to stay and post consistently.
Right now, creators can't measure reach. Likes, reposts, and replies only tell you who reacted, not how many people actually saw your post. Without impressions, engagement rate is incalculable. And engagement rate is the one number that tells you whether your content is connecting or just disappearing into the void. I built a metrics tracker using the AT Protocol API. Follows, likes, reposts, replies... all accessible. View count: missing. That's the gap between a useful analytics tool and a complete one.
AT Protocol's whole pitch is data ownership and transparency. Withholding basic reach data from the people generating that content contradicts the ethos the platform was built on. Threads shows view counts. YouTube shows view counts. The ask doesn't have to be radical, even exposing view counts privately, visible only to the post's author, would be enough to make this platform viable for creators who take their content seriously. Give creators visibility into their own reach. That's it.
