### ISSUE TITLE
The order in which the four images are displayed in the post is different from the previous version.

### ISSUE THREAD

**Issue by henoya** [bluesky-social/social-app#1895]
**Describe the bug**
The order in which thumbnails are displayed for posts with four images attached is different between bsky.app V1.54 and V1.55 or later.

**To Reproduce**

Sample post URL
https://bsky.app/profile/shoimada.bsky.social/post/3kbroxvwhyo2o

When displayed in the v1.54 version of the web version:
![bskyImageOrder 154](https://github.com/bluesky-social/social-app/assets/143017/758d7e40-7cd4-4024-8728-563100064e5a)

If displayed in v1.55 or later:
![bskyImageOrder 156](https://github.com/bluesky-social/social-app/assets/143017/9032c33b-7a54-4821-b767-1c53e136a0dc)

**Expected behavior**

Even for posts like this post, where images are attached with the order of display in thumbnails also in mind, or when considering the enlarged display of one image at a time, it seems natural for the second image to be displayed to the right of the first image.

I would like to see a return to the order in which images were displayed up to the v1.54 version, as the thumbnail display of previously posted images is different.

**Comment by pfrazee** [comment]
Sorry about that, it's been bugging me too https://github.com/bluesky-social/social-app/pull/1904

**Comment by henoya** [comment]
Wow. Thanks for responding.
