### ISSUE TITLE
Image attachments are desaturated in Firefox beta (Developer Edition)

### ISSUE THREAD

**Issue by scottdotjs** [bluesky-social/social-app#1910]
When adding an image to a post in Firefox Developer Edition, the image becomes slightly desaturated. Here's a side by side comparison in Firefox 120.b9 and 119.0.1 on Windows. It happens both for uploaded files and pasted image data.

![image](https://github.com/bluesky-social/social-app/assets/32358661/5018b879-050a-4c08-b2de-49d74b27c8d9)

It isn't just an issue with the image preview but an actual modification of the file. Here's the uploaded image in a post, viewed in Chrome.

![image](https://github.com/bluesky-social/social-app/assets/32358661/f63090f8-a135-421c-abe9-ca9a308a005d)

This is a niche issue right now, but worth reporting in advance of whatever change has happened in Firefox hitting main at 120 and thus happening for all Bluesky users with Firefox. I searched Bugzilla for bugs matching "washed out" and "desaturated" but couldn't find anything matching this.

Update: I just tried editing an image in OneDrive's web interface and encountered the same issue, so it's clearly an issue in Firefox's current beta. Although I'm not involved with developing it I'm happy to open a bug there and close this issue to update later with any resolution, if you like.

**Comment by pfrazee** [comment]
Ah just saw your update. Okay I'm closing then

**Comment by RichN001** [comment]
@scottdotjs Did you ever find out anything more about this problem, I have a user experiencing similar.

**Comment by scottdotjs** [comment]
Hi Rich, sorry for not getting back to you sooner. I didn't, but I've just tested image attachments [on Firefox 123.0a1 (nightly)](https://bsky.app/profile/xeh.bsky.social/post/3kisaga2x4v2p) and [on Firefox 121.1.0 (main)](https://bsky.app/profile/xeh.bsky.social/post/3kisaim2gqp2i) on Android and I'm not seeing the issue any more.

**Comment by scottdotjs** [comment]
Hi again. I've now had the chance to do another test [on Firefox 122.0b9 (Developer Edition)](https://bsky.app/profile/xeh.bsky.social/post/3kizsrddwff2x) on Windows and there's definitely something wrong in that specific version of the browser. It's like there's a yellow tinge to the whole image. I'll try filing a bug at Bugzilla (link tbd here) but have no idea if/when that might be picked up.
