### ISSUE TITLE
Custom Feed not displaying all posts

### ISSUE THREAD

**Issue by so-asano** [bluesky-social/social-app#1960]
**Custom Feed not displaying all posts**

**To Reproduce**

1. Directly access [this feed generator](https://www.bluefeed.app/xrpc/app.bsky.feed.getFeedSkeleton?feed=at://did:plc:djobdzddoqpwmjbay7prlk6z/app.bsky.feed.generator/18bd5cb57aa140e) and you will see 15 post URIs there.
2. However, when you access [the feed](https://bsky.app/profile/did:plc:djobdzddoqpwmjbay7prlk6z/feed/18bd5cb57aa140e) on the app, you will only get 10 posts.

**Expected behavior**

As 15 URIs are provided by the feed generator, the app should display 15 posts.

**Details**

 - Platform: iOS / Web
 - Platform version: iOS 16.5.1 / macOS 13.4.1
 - App version: iOS 1.56.0 (3) / Web 1.56.0

**Additional context**

I think these lines of `feed-tuners.tsx` are causing the problem.

```
    if (feedDesc.startsWith('feedgen')) {
      return [
        FeedTuner.dedupReposts,
        FeedTuner.preferredLangOnly(langPrefs.contentLanguages),
      ]
    }
```

**Comment by so-asano** [comment]
I noticed that the problem is related to content language, and changed it from Japanese to English. Then, the feed displayed no posts at all. This is really bad...

**Comment by so-asano** [comment]
I forgot to mention Content Language. My Content Language is Japanese, and all posts in the feed are in Japanese.

**Comment by pfrazee** [comment]
Yeah if the post doesnt declare it's language there's going to be some inaccuracies in detection. Unfortunately there's not a fix to this available right now
