### ISSUE TITLE
User re-banned after temporary suspension without any subsequent violations

### ISSUE THREAD

**Issue by TheMattMercy** [bluesky-social/social-app#1972]
My account was temporarily suspended for 72 hours for a very mean-spirited double entendre joke I had posted over a month ago (and had already deleted very quickly because I felt like it crossed the line),  in response to an abusive message I received out of the blue from another user.

I waited my time, and when I came back on, having learned my lesson, the same big account got their followers to all report me for, from what I can tell, the same posts that were also posted & deleted a month ago.

As a result I was banned again within 3 hours.

What's the point of having a temporary suspension if the user can just be suspended for the same thing without repeating that mistake?

Isn't the point of a temporary suspension to be a corrective action for the user to learn & grow?

Shouldn't there be a grandfathered-in or statue of limitations for posts before the original punishment? Removal of older posts I completely understand, but it's nonsensical to ban someone for the same thing when they haven't done anything new in that same category of infractions (or, in my case, at all)

**Comment by Zero3K** [comment]
How is this a bug?
