### ISSUE TITLE
formerly flagged nsfw accounts still have blurry thumbnails 

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#2015]
may be similar to #1572 

- saw an account that has a blurry pfp that was formally nsfw -

- the account is now sfw, and the pfp has a blurry image mask on it -

 - after the label was removed, the pfp still stayed blurry. 

example https://bsky.app/profile/thelusciouslibra.bsky.social/post/3kfbcfmfz5w2t

not sure if this has been reported or not. 

ideally sfw accounts should not have blurry pfp's 

more info: when looking at the profile, and a thread view post - the pfp is blurry
when i click reply to the user- the pfp is not blurry.

**Comment by pfrazee** [comment]
We've added a task to the tracker to give users a way to request a review on labels, to deal with this

**Comment by pfrazee** [comment]
Hopefully not too long to get to it, we've got to wrap the current release

**Comment by pfrazee** [comment]
The "appeal content warning" tool is now available, and we're continuing to work on this
