### ISSUE TITLE
Getting a 500 error trying change my email

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#2027]
**Describe the bug**

I tried to change my email to hello@graysky.app

I got an internal server error.

**To Reproduce**

1. Try and change email to hello@graysky.app

**Screenshots**

<img width="1326" alt="Screenshot 2023-11-29 at 11 12 48" src="https://github.com/bluesky-social/social-app/assets/10959775/6689d07e-a0aa-49b0-a0fd-154538c9c822">

**Details**

 - Platform: desktop firefox macos
 - Platform version:
 - App version: Build version: 1.56.0; Platform: web

**Additional context**

Change it to a different gmail email worked fine

**Comment by pfrazee** [comment]
This is likely a backend issue, assigning to @devinivy
