### ISSUE TITLE
Open the home screen to the most recently selected feed page

### ISSUE THREAD

**Issue by CooperEdmunds** [bluesky-social/social-app#2047]
**Is your feature request related to a problem? Please describe.**

As detailed in #799, it's annoying to have to remember to scroll over to the custom feed I use every time I open the app after quitting. The best solution would be allowing the user to unpin following altogether, but as triage we could just always open the app to the most recently selected page on Home.

**Describe the solution you'd like**

I believe this could be be done by recording feed selections in AsyncStorage and using that value as the initial value for the selected page state.

**Describe alternatives you've considered**

Adding a setting to preferences that allows users to opt into hiding following. If they choose to hide, following is not pinned; if not, following is pinned at the first position (as now).

**Additional context**

I'm happy to implement this.

**Comment by pfrazee** [comment]
Yeah that seems like a good idea

**Comment by pfrazee** [comment]
Added!
