### ISSUE TITLE
Crash when pasting _something_ into the post editor (iOS)

### ISSUE THREAD

**Issue by mstrofbass** [bluesky-social/social-app#2071]
**Describe the bug**

I copied what I expected to be an image (but probably wasn't) from Safari and attempted to paste it into the editor as a reply to a post and the application crashes. 

**To Reproduce**

1. Go to presumably any imgflip.com meme generator page, like this one: https://imgflip.com/memegenerator/335348854/Stop-giving-me-your-toughest-battles

2. Try to copy the meme template (e.g., press and hold on the image). It should look like:

![image](https://github.com/bluesky-social/social-app/assets/20154754/d246f878-964b-48d3-98d1-98458d556170)

3. Click "copy"

4. Go to the BlueSky app

5. Find a post and click the reply button

6. Try to paste the image into the editor

7. Crash

**Expected behavior**

The application should not crash

**Details**

 - Platform: iOS
 - Platform version: 17
 - App version: 1.56.0

**Additional context**

I'm on my phone so I can't verify this but I'm assuming it's not actually copying the image and it's something weird that the app doesn't know how to handle. I was able to click "Generate" without adding anything and copy/paste the resulting image just fine so...

**Comment by mozzius** [comment]
Yeah, that's not selecting the image. When images are selected, it pops out and blurs the backdrop

**Comment by haileyok** [comment]
Doesn't crash anymore at least.
