### ISSUE TITLE
Block/mute account option on post context menu

### ISSUE THREAD

**Issue by scottdotjs** [bluesky-social/social-app#2076]
At present in the Android app and possibly other flavors, blocking or muting an account requires navigating to their profile and using the context menu thereon. It would be good to also have those options on the context menu for a post.

**Comment by wtlgo** [comment]
+ Also adding/removing users to the moderation lists

**Comment by mschwendener** [comment]
> muting an account ... on the context menu for a post

This would also be practical on desktop.

**Comment by Bossett** [comment]
As part of this can we also get unfollow? (or follow/unfollow for consistency, but we have a big follow button already)

**Comment by surfdude29** [comment]
This seems to be a duplicate of #1017.

**Comment by scottdotjs** [comment]
It is, thanks for catching that.
