### ISSUE TITLE
Still receiving push notifications for removed account

### ISSUE THREAD

**Issue by seboslaw** [bluesky-social/social-app#2123]
**Describe the bug**

When using multiple accounts in the app and then removing one account I still receive push notifications (at least for comments and mentions) for that removed account.

**To Reproduce**

1. Have at least 2 accounts within the app
2. Have push notification enabled
3. Remove 1 of the accounts
4. Create a comment or a quote Post with the account you just removed

**Expected behavior**

I would expect to no longer receive push notifications for accounts I have removed from the app. This is a privacy issue since the removed account might have been by a friend who just wanted to checkin on her/his account. 
Ideally I'd also want my device token to be remove from the bsky database, but I'm pretty sure they are shared between accounts.

**Details**

 - Platform: iOS
 - Platform version: 17.1.2
 - App version: 1.56.0 (3)

**Comment by jordijc** [comment]
This issue also reproduces on Android App Version 1.59.

**Comment by haileyok** [comment]
combining into https://github.com/bluesky-social/social-app/issues/1361
