### ISSUE TITLE
Image thumbnails shown on posts in counterintuitive order

### ISSUE THREAD

**Issue by scottdotjs** [bluesky-social/social-app#2158]
**Describe the bug**
Thumbnails of images are shown on posts in column order rather than row. NB when opened the image carousel is in the correct order. 

**To Reproduce**

1. Make a post with four images attached. 

**Expected behavior**

Image thumbnails are shown in this order:
```
1 2
3 4
```

**Screenshots**

The thumbnails in [this post](https://bsky.app/profile/hex.ooo/post/3kg4nfbyq352i) are shown in the wrong order:
![Screenshot_20231210_014419_Bluesky](https://github.com/bluesky-social/social-app/assets/32358661/f32314b3-2d6f-4eee-ba0b-138280ef6040)

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: 1.56.0 (46)

**Additional context**

Also occurs on web version.

**Comment by kapowaz** [comment]
I created [a test post](https://staging.bsky.app/profile/kapowaz.net/post/3kgvmple7k42z) with images in sequential order (as a potential first issue to try and fix), and it appears to be working as intended:

![staging bsky app_profile_kapowaz net_post_3kgvmple7k42z](https://github.com/bluesky-social/social-app/assets/25730/d67b28c2-7d71-4edd-afaf-f14436e72d69)

**Comment by pfrazee** [comment]
Ya this got fixed. Thanks everybody
