### ISSUE TITLE
How to interpret the 'linear' label?

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#2183]
Hi 

While finding timeline information for https://bsky.app/profile/steveharoz.com/post/3kgcdq7tcrb2e / https://docs.google.com/document/d/1aPddaH-d7N53jZm1S3vUrfjVVy5nykPQz6qd7QpPCQE/edit#heading=h.58mkl21vxs3m, I came across https://github.com/bluesky-social/social-app/issues/392 .

I understand that the 'linear' label means 'is being tracked in our internal tool'; is there additional information that I can read into it? Does it mean 'planned' / 'on the roadmap' / 'actively being worked on'? 

I'm just curious :-) 

---

Fingers crossed for the opening of logged-out viewing!

**Comment by pfrazee** [comment]
yeah nah it doesn't mean anything special, especially because we moved off linear (so I'm going to remove the label now)
