### ISSUE TITLE
Replies rapidly jitter up and down after pressing "Load more comments"

### ISSUE THREAD

**Issue by nicko1337** [bluesky-social/social-app#2202]
**Describe the bug**

Replies move up and down rapidly when I press the "Load more posts" button that's at the bottom of a post's replies. For some posts, the jitter only occurs while I scroll through the replies after I've pressed the "Load more posts" button. The bug stops when I scroll back up to the top of the post.

**To Reproduce**

1. Go to a post that has a large number of replies (e.g. [https://bsky.app/profile/bsky.app/post/3kgbyvvbxcg2y](https://bsky.app/profile/bsky.app/post/3kgbyvvbxcg2y), which has 127 replies at the moment).
2. Scroll down through the replies and click the "Load more posts" button.
3. The replies will jitter uncontrollably. If they don't jitter, try scrolling up or down.

**Expected behavior**

The replies should not jitter.

**Screenshots**

Video: https://github.com/bluesky-social/social-app/assets/22125088/714b8021-d478-4d47-a6a5-7b802d1cbb45

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: 1.58.0

**Comment by haileyok** [comment]
This should be resolved now, we've tweaked a lot of things in this area since this report. Do report again though if you're still seeing something similar.
