### ISSUE TITLE
Cannot scroll profile's posts, bio is too long & takes up whole screen

### ISSUE THREAD

**Issue by jakei-bsky** [bluesky-social/social-app#2220]
**Describe the bug**
Since the changes to the iOS app that made it so that swipe/scroll has to be done inside of the boundary of the "posts/replies/media" tabs on the profile, rather than just anywhere on the screen, I've come across profiles that cannot be scrolled at all. Some bios have short descriptions listed vertically, making it long enough to fill the screen.

**To Reproduce**

Here is one example profile (also the screenshot below): https://bsky.app/profile/sarahndipity.bsky.social

**Expected behavior**

Thought I would be able to scroll to see posts, was not able to.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/150558695/3db86163-bcef-4f1f-bd43-bdae2fa0773f)

**Details**

 - iOs app
 - Platform version: latest
 - App version: latest

**Comment by mozzius** [comment]
FYI - if this happens, you can scroll anywhere above the bio, such as the display name, header etc

**Comment by pfrazee** [comment]
Terribly sorry for this irritating issue. We're hopeful to have a fix soon.

**Comment by haileyok** [comment]
This was fixed a while back.
