### ISSUE TITLE
Report/block sheets excess padding when profile sheet is open

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#2231]
**Describe the bug**

When you go to report someone via the profile sheet you get when you tap on a profile picture, there's a huge white area at the bottom. Same applies to blocking, but it's particularly egregious with the report account one because due to the scroll view there is no way to close it. Screenshots below

**To Reproduce**

1. Tap on someone's profile picture to bring up the account sheet
2. Try and report them

**Expected behavior**

Doesn't do that

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/10959775/f030ad44-21f6-4c79-9479-69bd69191f22)

![image](https://github.com/bluesky-social/social-app/assets/10959775/18856d4d-ac47-4193-ae28-80ccb2b1b67a)

**Details**

 - Platform: iOS
 - Platform version: 17
 - App version: 1.59.0 (2)

**Additional context**

n/a

**Comment by pfrazee** [comment]
This should be fixed in the upcoming release
