### ISSUE TITLE
Move search bar to the centre column on web desktop for the search screen

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#2253]
**Is your feature request related to a problem? Please describe.**

I find it strange how the search behaves on web desktop. The search tab isn't actually the place where you go to search - instead, it's always in the right nav. Twitter, which has a similar layout, moves it to the middle column when you go to the "Explore" tab

**Describe the solution you'd like**

![Screenshot 2023-12-20 at 11 04 53](https://github.com/bluesky-social/social-app/assets/10959775/545310fc-a3f0-43ed-8b2b-f4bd9254b90b)

**Describe alternatives you've considered**

Keep it as it is

**Additional context**

I have a PR ready but I thought I'd ask first, to see if you actually want it

**Comment by pfrazee** [comment]
Sure let's take a look at it
