### ISSUE TITLE
[APP-923] Muted & blocked users not showing in the muted & blocked users lists

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2277]
The profilecard moderation filter is incorrectly applying in the moderation screen's listings interfaces

<sub>[APP-923](https://linear.app/blueskyweb/issue/APP-923/muted-and-blocked-users-not-showing-in-the-muted-and-blocked-users)</sub>

**Comment by heikadog** [comment]
i wanna note that it's also not showing in any mod lists !

**Comment by pfrazee** [comment]
This should be fixed
