### ISSUE TITLE
[APP-924] React keys are still duplicating

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2278]
We need to just get a strong defensive Set against that and be done with it

<sub>[APP-924](https://linear.app/blueskyweb/issue/APP-924/react-keys-are-still-duplicating)</sub>

**Comment by estrattonbailey** [comment]
Just noting that the Search screen is an offender as well, re: Slack convo

**Comment by pfrazee** [comment]
Yeah. With the feed views, the way I plan to handle this is with a `Set` on the feed tuner that just super triple checks that no dups get through. (I had that at one point, it's findable in the commit log.) For search, I dunno, I'd have to look at that code
