### ISSUE TITLE
[APP-927] Blank Home tab

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2281]
There is some kind of issue causing the Home screen to bug out entirely until a reset occurs. Bizarrely, the tabs bar stays visible and scrollable but not responsive to taps. The bottom bar also works fine. However, the very top bar and the screen content is totally AWOL.

![CleanShot 2023-12-22 at 13 40 14@2x](https://github.com/bluesky-social/social-app/assets/1270099/8c453814-4ca9-43b7-bd7f-fb95e9c68444)

Why says this has happened _during app usage_ which makes it unlikely that this is caused by the intro animation.

<sub>[APP-927](https://linear.app/blueskyweb/issue/APP-927/blank-home-tab)</sub>

**Comment by Ai-rin** [comment]
For me it looks like this and happens on startup:

![Screenshot_2023-12-23-12-15-03-429_xyz blueskyweb app](https://github.com/bluesky-social/social-app/assets/29887769/b27e0e40-f848-4a43-8069-395e07dce988)

**Comment by SaySayTakamura** [comment]
For me it's the following/followers tab, unless i touch on someone on the list to go to their profiles, the list is invisible.

But clicking on someone profile and going back solves it.

**Comment by pfrazee** [comment]
@Ai-rin that looks like a different issue - the intro animation not finishing. Does it just stay like that forever?

**Comment by Ai-rin** [comment]
@pfrazee Yep, it stays like that forever. I can scroll the timeline, but see only tiny fraction of it in the middle.
It is worth noting, that animation itself is also broken for me.

**Comment by pfrazee** [comment]
@Ai-rin Can you share your device info? OS, version?

**Comment by Ai-rin** [comment]
@pfrazee Sure:
![IMG_20231224_025737](https://github.com/bluesky-social/social-app/assets/29887769/e1dbe723-bc11-4deb-b84e-706d2d0b1cab)

**Comment by pfrazee** [comment]
I don't imagine there's any way up update your OS? Android 7 is pretty far behind

**Comment by Ai-rin** [comment]
@pfrazee That's the latest official version available, and this is the only phone i have, so trying to flash it manually is quite dangerous for me

**Comment by pfrazee** [comment]
@Ai-rin yeah I was afraid that would be the case! I'll see what we can do
