### ISSUE TITLE
"Appeal content warning" is always displayed in post drop down menu on my posts

### ISSUE THREAD

**Issue by tkusano** [bluesky-social/social-app#2286]
**Describe the bug**

**To Reproduce**

1. Display one of my posts (posts posted by myself)
2. Select ellipsis and display "drop down menu"
3. "Appeal content warning" item appears even if the post is not labeled.

**Details**

 - Platform: web, iOS (may be on Android)
 - App version: 1.60

**Additional context**

In `src/view/com/post-thread/PostThreadItem.tsx`, `!isSelfLabeledPost` is always `true` when `moderation.decisions.post.cause?.type !== 'label'`, I think.

So,  when a post is not labeled, 

```typescript
<PostDropdownBtn

    showAppealLabelItem={
                post.author.did === currentAccount?.did && !isSelfLabeledPost
   }
```
becomes
```typescript
<PostDropdownBtn

    showAppealLabelItem={
                post.author.did === currentAccount?.did && true
   }
```
.
.

**Comment by pfrazee** [comment]
Yep yep thanks for the issue, good sleuthing too
