### ISSUE TITLE
Katie Tightpussy's profile view is broken on the web

### ISSUE THREAD

**Issue by aliceisjustplaying** [bluesky-social/social-app#2296]
**Describe the bug**
[@juicysteak117.gay](https://bsky.app/profile/juicysteak117.gay)'s profile view is broken. Maybe others' as well. See attached video.

**To Reproduce**

1. Go to [@juicysteak117.gay](https://bsky.app/profile/juicysteak117.gay)
2. Stare at the webpage having a seizure

**Expected behavior**

The webpage is not having a seizure.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/81575558/3278991b-1ab8-46c3-bcfd-1221a66a9fb5

**Details**

 - Platform: macOS 14.2.1
 - Platform version: Chrome Version 120.0.6099.129 (Official Build) (arm64)
 - App version: 1.6.0

**Comment by aliceisjustplaying** [comment]
Can reproduce in Firefox 121 and Safari 17.2.1. In Firefox the flashing is faster.

**Comment by aliceisjustplaying** [comment]
This is some edge case with the scrolling behavior that loads more posts, here is a screen recording with devtools on the network tab. Do not click play if you are sensitive to flashing images, it gets worse towards the end.

https://github.com/bluesky-social/social-app/assets/81575558/304ae042-5e6f-4108-a03e-fb7f9fe0908d

**Comment by pfrazee** [comment]
ooooof weak, we're looking into it

**Comment by aliceisjustplaying** [comment]
Fascinating, I tried posting her latest image and changing my bio to hers but that still doesn't trigger it, must be an edge case where even more variables need to line up.

**Comment by aliceisjustplaying** [comment]
Oh this happens on mobile too, not just desktop.

**Comment by pfrazee** [comment]
https://github.com/bluesky-social/social-app/pull/2298 yep this was a subtle one
