### ISSUE TITLE
Sometimes one post is the only post shown in the timeline 

### ISSUE THREAD

**Issue by Shelob9** [bluesky-social/social-app#2304]
**Describe the bug**

I just keep scrolling and it's all just the same post:

![Screenshot_20231225-103357](https://github.com/bluesky-social/social-app/assets/1994311/8f05490c-dc70-45fa-89b1-e88915386349)

This happens sometimes 

**To Reproduce**

1. Click on a haunted skeet
2. Click back

**Details**

 - Platform: Android 
 - Platform version: Android 14
 - App version: Build version: 1.60.0 (51); Platform: android

**Additional context**

**Comment by drugaddictedloser** [comment]
I have the same problem on desktop.

This happens to me every day, several times a day, to the point that bluesky on desktop is basically unusable.

MacOS (14.2.1 (23C71) with Vivaldi, Chrome, Safari, AND the Bluesky app installed on MacBook Air M1. It makes no sense that this happens across browsers and the app.

**Comment by pfrazee** [comment]
I can say with high confidence this is solved with https://github.com/bluesky-social/social-app/pull/2309

React native completely freaks out when a rendered component's key gets reused. This manifests as endless duplication as you see here, and also the scroll behavior going crazy

Will get this fix out asap
