### ISSUE TITLE
Profiles have "pointer-events: none !important;" applied to them as an inline stylesheet (not inline style)

### ISSUE THREAD

**Issue by WolfWings** [bluesky-social/social-app#2307]
**Describe the bug**

The web version (at least) of the bsky app prevents all interaction (can't copy usernames, bio details, or even links from bios) currently, as the entire 'profile' block has the CSS "pointer-events: none !important" style applied, and not directly on the element so it's not easily overridden but as a javascript-generated stylesheet embedded into the page instead by the framework so most style-overrides have a very hard time targeting it as well.

**To Reproduce**

1. Go to a profile.
2. Try to select the username or anything else in the profile header box region.

**Expected behavior**

Be able to "select" text that is text and has a higher than baseline reason to copy such as sharing a username to someone else off-site or visiting a link mentioned in a profile bio.

**Details**

 - Platform: Desktop Chrome, Edge, Firefox, Windows, Linux, etc.
 - Platform version: Windows 11 22H2, Debian Bookwyrm (yes I tested Edge here too), I can test on others but it's a CSS issue.
 - App version: N/A

**Additional context**

This is especially badly handled as there's a "sub rule" attempting to apply "pointer-events: auto" on all sub-elements except the actual header-image, but the !important flag on the main element prevents the sub-rule from applying, so it appears to very much not be the intended results of the code in place. A better solution if attempting to make a "safe grab area" for touch interaction scrolling would be to just apply the "pointer-events: none !important" to the banner image itself, not the whole profile bio block.

**Comment by pfrazee** [comment]
Yeah this is temporary and will be removed with https://github.com/bluesky-social/social-app/pull/2126. We're battling with some UI challenges and had to temporarily disable pointer events on profile headers while we work on the long-term fix.

I hope you don't mind, I'm going to close this issue since the fix is on the way. Thank you for the extensive writeup!

**Comment by WolfWings** [comment]
Ah, thank you, I'd tried to search around but pointer-events, select, and a few other things found no issue... which makes since as it's all in a PR instead. My apologies for not finding that first!
