### ISSUE TITLE
[APP-929] Thread screen dimming on android

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2308]
Got multiple reports of this. Description from a user:

> ok I did some tinkering after it happened again just now. i can reliably reproduce it by going to someone's profile page, [@juicysteak117.gay](https://bsky.app/profile/did:plc:ywbm3iywnhzep3ckt6efhoh7)'s for testing as is tradition, and pressing a post that has media and is quote posted. pressing the quote posted media dims the screen

|Normal|Dimmed|
|-|-|
|![image](https://github.com/bluesky-social/social-app/assets/1270099/04902fec-3a9f-4f69-a3da-4cb61d14bd17)|![image](https://github.com/bluesky-social/social-app/assets/1270099/9e6a3aa5-51df-410a-b8ff-6d82a17b4fba)|

This looks like the lightbox dimming mask applying for some reason?

<sub>[APP-929](https://linear.app/blueskyweb/issue/APP-929/thread-screen-dimming-on-android)</sub>

**Comment by MariusVatasoiu** [comment]
I also have a recording with this bug, besides other bugs.

https://github.com/bluesky-social/social-app/assets/18071013/cec58bbc-55f3-40ae-9a20-635929c2e265
