### ISSUE TITLE
Automatic adding of link cards

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#2321]
It would be nice if it could automatically add link cards since that what Twitter does (or make it an option that people can disable/enable).

**Comment by scottdotjs** [comment]
+1 for retaining the current behavior as an option, I frequently edit URLs before grabbing the preview (eg removing tracking parameters).

**Comment by Zero3K** [comment]
In that case, the link card should automatically use the URL after the changes to it are done being made.

**Comment by mschwendener** [comment]
> option

Yes, please. I only add them if the display looks ok.

**Comment by Zero3K** [comment]
bump

**Comment by Zero3K** [comment]
Thanks for adding it :)
