### ISSUE TITLE
Repost menu triggered by scrolling (web)

### ISSUE THREAD

**Issue by creckord** [bluesky-social/social-app#2330]
**Describe the bug**

I use Bluesky exclusively through the browser app. On Chrome for Android, scrolling through the feed very frequently triggers the repost menu. 

This is very annoying, since it stops all subsequent scroll gestures until one closes the menu. And it has gotten worse in the last couple of days, because where it was previously enough to tap the screen somewhere outside the menu to close it, now it only goes away when pressing the exact button on the exact post that ostensibly triggered it (which involves some guesswork, as the menu isn't always attached to the post), or when triggering one of its actions.

**To Reproduce**

1. Scroll through the web app until the repost menu appears

**Expected behavior**

Scroll gestures should not trigger the menu, and the menu should be easily closeable by clicking outside of its area.

**Details**

 - Platform: Chrome on Android
 - Platform version: Chrome 120.0.6099.144, Android 13
 - App version: 1.60.0 (current web app version)

**Comment by pfrazee** [comment]
Closed by #2358 (hopefully)

**Comment by creckord** [comment]
Just gave it a try. Even aiming for the repost button, I wasn't able to trigger the menu with scroll gestures anymore. Greatly appreciated, thanks!
