### ISSUE TITLE
Weird "persistent menu" behavior (web)

### ISSUE THREAD

**Issue by creckord** [bluesky-social/social-app#2332]
**Describe the bug**

Since a couple of days now, the menu behavior in the web app has changed. Where previously menus closed when clicking outside of their content area, you now have to either click the button again that opened them, or trigger one of the menu options.

What makes this worse, is that menus persist across navigation and that tapping outside of the menu will now trigger e.g. navigation from the feed to the selected post.

**To Reproduce**

1. Open a Bluesky feed (e.g. Following) in the web app.
2. On one of the posts, tap the "..." post menu,
3. Click somewhere on the post content area to dismiss the menu.
4. You are now on the post's page, with the "..." menu still open

**Expected behavior**

Menu closes when clicking outside its content area, without triggering whatever action would have happened by the click if the menu hadn't been open.

**Screenshots**
![bsky-menu-bug-1](https://github.com/bluesky-social/social-app/assets/393429/06efcdf6-aaa1-4914-af7e-36e25e35a403)
![bsky-menu-bug-2](https://github.com/bluesky-social/social-app/assets/393429/f25f1dcc-81aa-4253-9026-245eac6b324c)
![bsky-menu-bug-3](https://github.com/bluesky-social/social-app/assets/393429/d7c51cd5-9ec5-4a66-9b13-8ab35b29706f)

**Details**

- Platform: Chrome on Android
- Platform version: Chrome 120.0.6099.144, Android 13
- App version: 1.60.0 (current web app version)

**Comment by estrattonbailey** [comment]
Really appreciate the details here! 🙏 

I think we're tracking the same bug in #2345 and it should be fixed in #2358.

**Comment by creckord** [comment]
Looking good, thank you!
