### ISSUE TITLE
Unable to register on iPhone 15 iOS 17.2.1

### ISSUE THREAD

**Issue by adinic** [bluesky-social/social-app#2333]
**Describe the issue**
When I attempt to create an account via the iPhone app the registration page hangs after I enter the first character of my invite code. I am unable to create an account on iPhone 15 iOS 17.2.1

**To Reproduce**

1. Open Bluesky app
2. Select create account
3. Start to enter invite code
4. Page hangs and I am unable to complete the registration/create an account

**Expected behavior**

I should be able to enter the invite code, addition details and create an account

**Screenshot(s)**

![image](https://github.com/bluesky-social/social-app/assets/22982703/ac2ef20d-fbac-4870-aba8-94c39c10a5a6)

**Platform**

 - Platform: App
 - Platform version: iPhone iOS 17.2.1
 - App version: 1.61

**Comment by pfrazee** [comment]
Yikes. Thanks for reporting, we'll look into this

**Comment by ms-threepwood** [comment]
Im experiencing the very Same issue. iOS 17.1.2 on iPhone 13 mini

occasionally (Like 1/10 tries maybe) I’m able to enter an email Address, Passwort and username and as soon as I try to pick my birthday the page hangs after moving one of the options (e.g. month) once.

**Comment by pfrazee** [comment]
@adinic @ms-threepwood out of curiosity what languages/regions are you in? One theory I have is that date parsing is somehow failing because of a baked in assumption about american-style dates

**Comment by adinic** [comment]
I’m in the UK, so the date format will be day/month/year.

**Comment by ms-threepwood** [comment]
Im in Germany so Date Format is day / month / year

System Language of my Phone is english though (not sure if the App is checking Location or System Language) 

but I only get so far in Like 1/10 or 1/20 times. Most cases the page freezes right after entering my invite code

**Comment by elinscott** [comment]
Same issue here. (Page freezes after entering anything in the invite code field.) iOS 16.1.1 on iPhone SE. I use dd/mm/yyyy formatting.

**Comment by estrattonbailey** [comment]
Just an update: we're actively looking into this, but have so far been unable to reproduce using these device specs and UK/German locales. We'll keep digging 🙏

**Comment by ms-threepwood** [comment]
@estrattonbailey thank you!

maybe to specify: it‘s not just the create account- page itself that freezes, it’s also my keyboard that stops reacting (but just on this specific page, not a general system issue). I cannot click any key on my keyboard anymore as long as I stay on that page. The keyboard is still visible / open, but doesn’t react. 

the cursor however keeps blinking. (Not sure if cursor is the correct term, I’m sorry, I’m referring to the little marker that shows at which point in the box you will be entering the next letter).

**Comment by pfrazee** [comment]
yeah we've been able to reproduce finally. now trying some fixes (not ready to close yet so re-opening). fingers crossed; this one is a bit of a mystery

**Comment by pfrazee** [comment]
Alright fixed. Another react-native core element breaking randomly.

**Comment by ms-threepwood** [comment]
I’m sorry but it’s not solved for me. Same issue.

**Comment by wtlgo** [comment]
Ah, I was just going to open the same issue

> I’m sorry but it’s not solved for me. Same issue. (I deinstalled the app and downloaded it again but it still behaves in the same way)

You should wait till 1.62 is released to the AppStore

**Comment by ms-threepwood** [comment]
Perfect. It works now. Thank you

**Comment by pfrazee** [comment]
Excellent. Sorry again about this issue!
