### ISSUE TITLE
"Subscribed" badge not showing on blocked lists

### ISSUE THREAD

**Issue by imbstt** [bluesky-social/social-app#2335]
**Describe the bug**

On a profile page, on the Lists tab, when you subscribe to a List by muting it, it shows the "Subscribed" badge. This badge does not appear if you instead block the list.

**To Reproduce**

1. Open a user profile, go to Lists tab
2. Open a list, subscribe to it and select Block Accounts
3. Go back to Lists list
4. Observe "Subscribed" badge missing

**Expected behavior**

The "Subscribed" badge should appear. Maybe with an addition indicating which option was chosen (either Muted or Blocked).

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/83777889/95fa775a-6ef1-4e4d-9d5f-e83b664f9d15)

**Details**

 - Platform: Web and Android app 
 - Platform version: Firefox 121.0 on Windows 11; Android 13
 - App version: 1.61

**Comment by pfrazee** [comment]
Oh thanks for reporting, we'll get on that
