### ISSUE TITLE
[APP-936] Add a first-tap consent interface to the embed player

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2338]
On first use of the embed player per device, we need to inform the user that the content is hosted by a third party and the request will be sent to them.

<sub>[APP-936](https://linear.app/blueskyweb/issue/APP-936/add-a-first-tap-consent-interface-to-the-embed-player)</sub>

**Comment by DavidBuchanan314** [comment]
By the way, I like how [iframely](https://iframely.com/) handles their opt-ins, i.e. per-service

![image](https://github.com/bluesky-social/social-app/assets/13520633/9249eba7-c376-48e6-b3bc-725a665e26e0)
