### ISSUE TITLE
Wrong app language

### ISSUE THREAD

**Issue by serjor** [bluesky-social/social-app#2347]
**Describe the bug**
The application is in a language I don't know (my system is in Spanish)

**To Reproduce**

1. Install the application
2. Open the application

**Expected behavior**

The application to be in Spanish, or at least, English

**Screenshots**

![Screenshot_2023-12-27-22-49-11-941](https://github.com/bluesky-social/social-app/assets/6491212/6045a7cc-d49a-4259-a543-286eacbfe5b4)
![Screenshot_2023-12-27-23-16-21-196](https://github.com/bluesky-social/social-app/assets/6491212/c587654f-2c8a-4930-a1f8-63a6c0efb93e)

**Details**

 - Platform: Android
 - Platform version: Mobile -> EMUI 12.0 / Tablet -> Android 12
 - App version: 1.61.0

**Additional context**

On mobile it was on English until updated this afternoon. On tablet it is a fresh install

**Comment by serjor** [comment]
Original post updated with a capture of the language settings

**Comment by madmalkav** [comment]
Same issue on iOS

**Comment by ansh** [comment]
There was a bug where the German localization file was loaded in instead of the Spanish one. Apologies for that. It should be fixed in the next release. Fixed in #2324
