### ISSUE TITLE
Uncaught exception in Invalid language tag causes website to not load

### ISSUE THREAD

**Issue by Scrxtchy** [bluesky-social/social-app#2381]
**Describe the bug**
My Accept-Language header is causing the website to throw an uncaught exception

**To Reproduce**

(firefox)
1. navigate to about:config
2. set `intl.accept_languages` to `en-GB,en-US;q=0.7,en;q=0.3`

**Expected behavior**

Website should catch the error and attempt to load with a fallback 

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/12771982/7f544dd4-8999-4a26-9cf4-ca37210508c1)

**Details**

 - Platform: desktop firefox windows
 - Platform version: firefox 122.0b4 (aurora channel)
 - App version: 1.62? 7634b581dd91ffe99226c578378605af6367a1c1

**Additional context**

```
Uncaught RangeError: invalid language tag: "en-US;q=0.7"
    getLocales https://bsky.app/static/js/436.ff4e2d5e.js:2
    getLocales https://bsky.app/static/js/436.ff4e2d5e.js:2
    18308 https://bsky.app/static/js/main.820b652f.js:1
    n https://bsky.app/static/js/main.820b652f.js:1
    i https://bsky.app/static/js/main.820b652f.js:1
    O https://bsky.app/static/js/main.820b652f.js:1
    <anonymous> https://bsky.app/static/js/main.820b652f.js:1
    <anonymous> https://bsky.app/static/js/main.820b652f.js:1
436.ff4e2d5e.js:2:226372
    getLocales https://bsky.app/static/js/436.ff4e2d5e.js:2
    map self-hosted:221
    getLocales https://bsky.app/static/js/436.ff4e2d5e.js:2
    18308 https://bsky.app/static/js/main.820b652f.js:1
    n https://bsky.app/static/js/main.820b652f.js:1
    i https://bsky.app/static/js/main.820b652f.js:1
    O https://bsky.app/static/js/main.820b652f.js:1
    <anonymous> https://bsky.app/static/js/main.820b652f.js:1
    <anonymous> https://bsky.app/static/js/main.820b652f.js:1
```
![image](https://github.com/bluesky-social/social-app/assets/12771982/7a142ca9-443d-4f03-8d12-a3129ba2350b)
via [manytools](https://manytools.org/http-html-text/browser-language/)

**Comment by GPHemsley** [comment]
The steps to reproduce are misleading, but the underlying issue is valid. Any exception that getLocales() throws will result in the entire app being unusable, and expo/expo#25694 makes that an easy occurrence.

If you add, for example, `en-GB-oed` to your language settings, you can easily trigger the issue.

**Comment by mary-ext** [comment]
Yeah, I was personally waiting on something more concrete to work on, it should be handling `en-GB-oed` properly especially since that's a grandfathered language tag

**Comment by GPHemsley** [comment]
Yeah, expo should be doing a better job of preventing an exception being thrown in the first place, but I think there's still room on the Bluesky side to prevent such an occurrence from causing the whole page to fail to load.

**Comment by estrattonbailey** [comment]
Looks like this may be resolved on Expo's end, gonna close for now. Feel free to comment and we can reassess.

https://github.com/expo/expo/pull/28902
