### ISSUE TITLE
Add additional content warning for self labeling media - for violent/ bloody 

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#2383]
Currently cannot self label media that contains violent/gore/war - from a journalistic point of view. 
Currently only self label options for media are for nsfw related content . 

Ability to have the option to self label violent/bloody content so it shows up in users proper filters. Some may want to and be ok with seeing war/related content but not with seeing adult content. 

**Additional context**
this could also be a general trigger warning, such as protests, police violence, or any other act that fits under this umbrella covering events etc. 

what it could look like 

![image](https://github.com/bluesky-social/social-app/assets/66647238/c77f79a9-253a-4b2b-8f52-5f94e7601677)
![image](https://github.com/bluesky-social/social-app/assets/66647238/24b43a53-6a80-4124-885a-a343a18eb7cd)

**Comment by harkebark** [comment]
Bumping this issue for urgency. With the recent uptick in users some journalists are using the labels intended for sexual content as an interim measure for content warnings. This means feeds like Adult Content and After Dark are showing users graphic violence due to label misuse. This post in particular has been sent to me by some users (warning, graphic violence) https://bsky.app/profile/jnascim.info/post/3l53ur4wzk322.

**Comment by mary-ext** [comment]
We've had the graphic-media label as a selflabel for quite a while now but it's still not been surfaced in the UI

**Comment by harkebark** [comment]
Should this issue be closed? The self labels still have not been surfaced into the UI which was the original intent of the post.

**Comment by monicaellerose** [comment]
> Should this issue be closed? The self labels still have not been surfaced into the UI which was the original intent of the post.
 its coming out in the next update. 
 
![image](https://github.com/user-attachments/assets/35ee4b84-6829-4e22-a2e0-f9f63114c01d)

**Comment by mary-ext** [comment]
There's been a commit that adds it, so it can be closed, just waiting for the next app version to be pushed.
