### ISSUE TITLE
YouTube videos embed at a fixed 16:9 'horizontal' aspect ratio even for vertical or 4:3 videos.

### ISSUE THREAD

**Issue by WolfWings** [bluesky-social/social-app#2386]
**Describe the bug**

The embedded video player for youtube URLs blindly calls YouTube's /embed/ setup with no specific configuration, resulting in non-16:9 videos being forced into 16:9 aspect ratio with letter-/pillar-boxing.

**To Reproduce**

1. [An example BSky post by Joaquin Baldwin demonstrating the issue.](https://bsky.app/profile/joabaldwin.com/post/3khk2nyeml72z)

**Expected behavior**

Video is presented with a fixed width for the timeline and variable height to adapt to the aspect ratio based on the underlying video.

**Details**

 - Platform: Browser, tested Edge/Chrome/Firefox on Windows 11 22H2/Debian Bookworm (yes, including Edge).
 - Platform version: Live website.
 - App version: N/A

**Additional context**

The detail for the aspect ratio is available from the 'oembed' query for youtube videos, but comically only if you explicitly request the it with the 'shorts' URL:

https://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/shorts/6OKUXn-pd6s (Joaquin's URL)
113x200 (~9:16)

https://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/shorts/QK8mJJJvaes (Macklemore's "Thrift Shop" music video)
200x113 (~16:9)

Requesting the oembed with the usual /watch?v= URL locks it to 'horizontal' sizes and breaks on queries against shorts, but requesting a non-shorts URL via the /shorts/ oembed works properly. 🤷

https://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/watch?v=6OKUXn-pd6s
200x150 (3:4!?)

https://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/watch?v=QK8mJJJvaes
200x113 (~16:9)

Note that the above URLs also support "format=json" I'm just using the =xml as most browsers will auto-parse that in a much more displayable format for bug discussion.

**Comment by WolfWings** [comment]
As a simple workaround, yes that would work as well for now. There's also a huge amount of 4:3 videos which the '/shorts/ oembed' query gets 200x150 back for as well though.

Long-term adding some type of metadata field to the URL to specify the aspect ratio on a video embed would be ideal (so clients can specify it but still avoid the pre-query before playback can be initialized) but just making the default for /shorts/ be 9:16 instead of 16:9 would certainly resolve issues short-term.

**Comment by WolfWings** [comment]
A) People have been asking this for LITERALLY a decade.

B) Shorts doesn't, but there's not actually a difference between a short and a normal youtube video except the aspect ratio and time limit on shorts. Every single /shorts/ URL is a valid /watch?v= URL, but /watch?v= ONLY returns 16:9 aspect ratio sizing, while /shorts/ is actually accurate "largest dimension at 200" aspect-ratio-aware sizing.

And yeah the thumbnail is always (even on shorts) 16:9, the YT app crops it down to the reported aspect ratio.

It's a LOT of dumb idiocy accumulated over the last 20 years. XD

**Comment by WolfWings** [comment]
Oh no I meant that **regardless** of the youtube shareable URL (/watch?v= or /shorts/ or /embed/ ) make the oembed query with the /shorts/ URL to get the aspect ratio.

**Comment by WolfWings** [comment]
Oh, yeah, I think we're discussing two different things, my apologies!

1) For the oembed JSON request, always requesting /shorts/ is the only way to get the actual aspect ratio.

2) For a quick fix, yes, just displaying /shorts/ URLs in 9:16 instead of 16:9 fixes everything well enough for now without adding the oembed request.

Sorry for the accidental bifurcation.

**Comment by WolfWings** [comment]
Yeah this looks REALLY good, doesn't need the 'full' 9:16 because yeah most devices even in portrait mode when you take into account the 'chrome' around things having the whole video fit vertically ends up more like 10:16 or even 12:16 being optimal.

Thank you again!

**Comment by sanderrzkelly** [comment]
That's alright. But for the people who may not be very comfortable with coding, I suggest to Check out the YT Portrait Video Embed plugin. This plugin is free and easily available on wordpress. Simply use shortcode and video ID. And its done.

https://wordpress.org/plugins/yt-portrait-video-embed/
