### ISSUE TITLE
Try to detect a post's language and warn the user, if the language setting mismatches

### ISSUE THREAD

**Issue by MarioLiebisch** [bluesky-social/social-app#2387]
**Is your feature request related to a problem? Please describe.**

More than once I've made a quick reply or started a post, just to forget to properly change the post's language. I'm not sure how significant this impact is (considering my default is German, but I sometimes post in English), but I think it would be reasonable enough to look for at least some hints about language mismatches.

**Describe the solution you'd like**

There could be an extra Accessibility option to warn the user, if they're potentially creating a post with the wrong language preset in the dropdown below the input box.

For example, if a text includes common words hinting at a text being English (e.g. "a", "I", "the"), but the dropdown is set to "German", show some warning text below the input box and/or ask the user if the language is really correct, once they try to create the post/reply.

**Describe alternatives you've considered**

The alternative would be to not change anything. It's not directly broken, but I can totally imagine I'm not alone with this "issue".

**Additional context**

Some mockups:

![New Accessibility Settings entry](https://github.com/bluesky-social/social-app/assets/1854245/7089f4b3-6500-4eff-808f-8f7ae9f91d59)
![Potential warning being shown](https://github.com/bluesky-social/social-app/assets/1854245/fd6683f8-7f9e-4b4f-bbd9-4439c9ebca41)

**Comment by pfrazee** [comment]
Had this on my todos for a while

**Comment by kimjamia** [comment]
Would it be an easy first step if the posting language could be automatically to set to language of the post being replied to if it's a language the user also knows?

I post in English and Finnish. If I reply to an English post, I will certainly reply in English. However, if I were to reply to a German post that has been translated to English, I wouldn't be replying in German.

**Comment by pfrazee** [comment]
That's smart, though it relies on the original's language being set correctly heh

**Comment by pfrazee** [comment]
Closed by #2486. Thanks @mary-ext !
