### ISSUE TITLE
Keep web emoji picker open with a shift click

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#2390]
**Is your feature request related to a problem? Please describe.**

I mentioned this in #2367 as a side note, but I figured it would be better to break this out into a feature request. For the emoji picker, it would be nice if `SHIFT+LMB` did not close the emoji picker in order to allow for multiple emojis to be selected similar to how it works in Discord, but I don't know enough about the libraries to tweak `onEmojiSelect` or `onInsert` confidently myself.

**Describe the solution you'd like**

I would like for multiple emojis to be selected without having to repeatedly open the emoji picker poput.

**Describe alternatives you've considered**

The alternative is tedious.

**Additional context**

**Comment by mschwendener** [comment]
Planned: https://github.com/bluesky-social/social-app/issues/1425
