### ISSUE TITLE
Muting thread does not stop push notifications iOS. 

### ISSUE THREAD

**Issue by markaudacity** [bluesky-social/social-app#2412]
**Describe the bug**
Muting a thread hides posts in the notification tab in the app, but does not stop push notifications with previews. 

**To Reproduce**

1. Mute a thread
2. Wait

**Expected behavior**

Never to see muted posts. 

**Details**

 - Platform: iOS
 - Platform version: 16.7.2
 - App version: 1.62.0

**Comment by pfrazee** [comment]
Thank you for the issue. This is a duplicate -- we're already tracking this and will hopefully get to it before too long https://github.com/bluesky-social/social-app/issues/1370
