### ISSUE TITLE
Link from https://bsky.app to https://bsky.app/profile/bsky.app (suggestion)

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#2418]
Just a suggestion: 
 
When somebody is logged out / does not have an account, and lands here https://bsky.app (= first result of the google search for bluesky), there is no link to see any Bluesky posts. 

Could the page link to https://bsky.app/profile/bsky.app? 

Or maybe get the footer from https://blueskyweb.xyz/join? 

---

Also https://blueskyweb.xyz links to https://bsky.app

**Comment by pfrazee** [comment]
Thanks for the suggestion. We'll consider it and likely update that over time. For now going to close
