### ISSUE TITLE
French translation: Make it gender-neutral

### ISSUE THREAD

**Issue by fenarinarsa** [bluesky-social/social-app#2425]
**Is your feature request related to a problem? Please describe.**

The current French translation does not follow the current recommendations for non-sexist and more inclusive French forms.

**Describe the solution you'd like**

Use gender-neutral (epicene) sentences or words when used to describe or talk about people.

The main word to avoid is "utilisateur" which is the generic term for "user" but is a male-gendered word. When used to describe female users, it's "utilisatrice".
It can easily be replaced by either "personne" (person) or "compte" (account) which are both gender-neutral. They must be chosen depending on the context.
But it means stop translating the English word "user" by "utilisateur" as much as possible.

There may be other slight vocabulary changes to make.

**Additional context**

This follows the first step recommended by guidelines for a non-sexist French language published by Canada officials and many other French-speaking organizations.
https://www.noslangues-ourlanguages.gc.ca/fr/ressources-resources/ecriture-inclusive-writing/principes-francais-guidelines-french-fra

**Comment by fenarinarsa** [comment]
Note: I can submit a PR.

**Comment by ansh** [comment]
Thank you for bringing this issue to our notice @fenarinarsa 
Localization is a continuous process and this seems like a change for the better.

Please feel free to open a PR with the necessary changes! 

I do want to note that our current French translation isn't Canadian French. I am not how much of a difference that makes but wanted to only highlight it since you mentioned `.ca` link.

**Comment by fenarinarsa** [comment]
> I do want to note that our current French translation isn't Canadian French. I am not how much of a difference that makes but wanted to only highlight it since you mentioned `.ca` link.

Yes but in this exact case it doesn't make any difference. I linked Canadian official guidelines because Canada is more advanced on this topic than France and I often use them to back this request :)
Their recommendations are perfectly valid in European French and as a matter of fact often applied there.

**Comment by Signez** [comment]
I agree that we should try to use the most gender neutral language possible, for the reasoning explained by @fenarinarsa (i.e. _langage épicène_).

I can also confirm that although Canada (and Québec in particular) tried to deal with this problem earlier than France, the French authorities continue to work effectively to try to eliminate this kind of prejudice from the language. Even [the United Nations is trying to do so](https://www.un.org/fr/gender-inclusive-language/guidelines.shtml).

The only really "sensitive" issue is the use of typographic tools for this purpose, i.e. the use of the interpunct (here, it would be `utilisateur-ice`): even though it's more common than it was a decade ago, it's still _niche_ and not really neutral. It should only be used if the Bluesky team wants to make it known that they are fiercely committed to the fight for gender equality. (Which would be great! But it's not up to an i18n translator/contributor to decide for them.)

_Langage épicène_ doesn't have that baggage, so I think we should tackle it first, and there are more than enough synonyms to improve the situation before we need to use the interpunct :)

---- 

In my first PR I didn't try to address this, as it's quite an undertaking (there are 35 uses of `utilisateur` in the translation file at the moment), but I think it would improve the translation considerably — with the added benefit that it may simplify some localization issues.

(Hey @fenarinarsa 👋 Glad to see you there!)

**Comment by fenarinarsa** [comment]
> In my first PR I didn't try to address this, as it's quite an undertaking (there are 35 uses of `utilisateur` in the translation file at the moment), but I think it would improve the translation considerably — with the added benefit that it may simplify some localization issues.

I'm leaving this to you then if you're working on French i18n.
