### ISSUE TITLE
Cannot select text from profile bio

### ISSUE THREAD

**Issue by bnb** [bluesky-social/social-app#2429]
**Describe the bug**

It's not possible to select text from a bio without starting selection from an element outside the bio.
**To Reproduce**

1. Put mouse cursor over text in bio
2. Try to select text

**Expected behavior**

I should be able to select text from a bio.

**Details**

 - Platform: Desktop Chromium (Arc Browser), Desktop Safari on MacOS
 - Platform version: Latest
 - App version: Latest?

**Additional context**

I copy/paste from bios often, usually my own. The lack of normal web UX in this spot is frustrating.

**Comment by pfrazee** [comment]
This is being actively fixed by @gaearon in a WIP PR
