### ISSUE TITLE
UI Bug: "Scroll to top" button appears half-hidden

### ISSUE THREAD

**Issue by wtlgo** [bluesky-social/social-app#2433]
**Describe the bug**

The circular "scroll to top" button appears half-hidden behind the sidebar on the web version.

**To Reproduce**

1. Open any feed
2. Scroll till the button shows up

**Expected behavior**

The button should be either visible or completely invisible.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/50925676/de7277e1-acd3-4baf-8891-ef03f8fb0aa1)

**Details**

 - Platform: Google Chrome (Windows 10, desktop)  
 - Platform version: 120.0.6099.131
 - App version: 1.62.0

**Additional context**

My screen resolution is 1366x768.

**Comment by Jgr9** [comment]
Not all the time but the scroll to the top button often appears mostly behind the bottom toolbar.
Web version, Firefox
