### ISSUE TITLE
Cannot add a link card for certain links

### ISSUE THREAD

**Issue by venteto** [bluesky-social/social-app#2473]
**Describe the bug**
I try to include a link to a news article from NPR in a new post, and generate a link card, but it fails and I see an error message indicating the operation was aborted, for no specific reason / unknown reasons.

**To Reproduce**

1. Paste the following article link into the compose box
https://www.npr.org/sections/goatsandsoda/2024/01/09/1222952895/why-theres-a-storm-brewing-about-global-food-aid-from-the-u-s

2. click add link card

**Expected behavior**

Expected to have a link card generated just like with other links. For example, pasting this link instead yielded a normal link card as usual:

https://www.euronews.com/2024/01/10/ecuador-labels-20-drug-gangs-as-terrorist-groups-after-live-tv-attack

**Screenshots**

![Screenshot from 2024-01-10 09-49-38](https://github.com/bluesky-social/social-app/assets/7062385/208e4778-0ac2-4336-9ed9-21f3e7a889a7)

**Details**

 - Platform: desktop Firefox on Manjaro Linux

**Additional context**

I noticed two other things yesterday which may be unrelated concidences. A new Bluesky app version (1..63) was released yesterday, and some of the botfrens art bots have been posting the same images over and over since yeterday (the botfrens developer only mentioned something must be happening with the API)

**Comment by pfrazee** [comment]
@Jacob2161 is in charge of cardyb (the link crawler) so I'm going to assign to him to look at 2.

For 1, not sure why we got 5 seconds on that timeout, that's pretty short. Should probably extend to 15 or 30

**Comment by venteto** [comment]
Just wondering if anything changed with this, either on the Bluesky side or the NPR side, as it seems now I can post that NPR article and successfully get a link card

**Comment by haileyok** [comment]
@venteto Yea, there were some changes made for these. Should all be working good now! Thanks!

**Comment by adriancotter** [comment]
We are having a similar issue. However, there's no error message (and no content) coming through when the information is accessed.
https://cardyb.bsky.app/v1/extract?url=https://www.sierraclub.org/articles/2024/06/sierra-club-and-coalition-seek-defend-colorado-building-performance-standards
`{"error":"","likely_type":"","url":"https://www.sierraclub.org/articles/2024/06/sierra-club-and-coalition-seek-defend-colorado-building-performance-standards","title":"","description":"","image":""}`

The pages share fine on X and Facebook directly.

I suspect it is possible its being blocked by our WAF. What is the user agent and/or IP addresses that Blue Sky would use?
