### ISSUE TITLE
After the release of app version 1.63 multiple art bots started posting duplicate posts in rapid succession

### ISSUE THREAD

**Issue by venteto** [bluesky-social/social-app#2474]
**Describe the bug**

Not sure if this is a Bluesky bug or a Botfrens bug, but the BotFrens developer responded that "something must be happening with the API". Some of these duplicate posts have the same minute as a timestamp, or are within a minute of the first post.

**To Reproduce**

1. scroll down either of these art bot curated lists and you'll see multiple accounts affected:
- https://bsky.app/profile/did:plc:6ho3kaxtbju3a5qbdfru7uae/lists/3kh356dnq5k2d
- https://bsky.app/profile/did:plc:6ho3kaxtbju3a5qbdfru7uae/lists/3kh34v5wjq327

**Expected behavior**

Expected to see a different artwork with each post, and for the posts from each individual art bot to be hours apart on their respective profiles, as was the normal flow a couple of days ago.

**Screenshots**

**screenshot 1 of 2**
![Screenshot from 2024-01-09 18-51-33](https://github.com/bluesky-social/social-app/assets/7062385/f46c7760-469a-4ac1-a2fb-1864fe149b21)

**screenshot 2 of 2**
![Screenshot from 2024-01-09 18-44-59](https://github.com/bluesky-social/social-app/assets/7062385/bb04d068-26c6-4dc5-affa-042a1e746b02)

**Details**

 - Platform: desktop Firefox on Manjaro Linux

**Comment by pfrazee** [comment]
Yeah I wish I could help but this is really something the bot dev needs to debug
