### ISSUE TITLE
Link handler for Android

### ISSUE THREAD

**Issue by jaoler** [bluesky-social/social-app#2475]
Sharing links from browser is impossible, because Bluesky doesnt have link handler. Its basic feature in apps. https://support.google.com/pixelphone/thread/232953933?hl=en&msgid=232976571

**Comment by pfrazee** [comment]
Yeah we're tracking this here: https://github.com/bluesky-social/social-app/issues/66. It's another one of those unfortunately frustrating tasks for react-native/expo.
