### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by jaoler** [bluesky-social/social-app#2476]
Please let us translate app to finnish. 🇫🇮

**Comment by surfdude29** [comment]
@ansh [said this](https://github.com/bluesky-social/social-app/issues/2331#issuecomment-1870149196) on the issue asking for an Indonesian translation, so I'm guessing the process would be the same for a Finnish translation?

> Please open a PR with the Indonesian translation. You can see [#2266](https://github.com/bluesky-social/social-app/pull/2266) or [#2003](https://github.com/bluesky-social/social-app/pull/2003) or [#2287](https://github.com/bluesky-social/social-app/pull/2287) for examples on what the PR should do

And for reference, the PR for the Indonesian translation that just got merged is #2356

**Comment by jaoler** [comment]
@ansh , we got .po file allmost ready. Do i create PR over here? https://github.com/bluesky-social/social-app/compare/main...internationalization

**Comment by jaoler** [comment]
PR https://github.com/bluesky-social/social-app/pull/2922
