### ISSUE TITLE
Some news post cards are not showing a thumbnail

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2478]
**Describe the bug**
Some posts made by the official Politico account do not show a thumbnail in the card.

While this may seem like a minor annoyance, I believe that it should receive focus as attracting journalists is a major pillar of BSky. If I worked at a news org, and some of my posts had no thumbail, I would think that the platform was flaky.

**To Reproduce**

1. See all posts made by https://bsky.app/profile/politico.com

2. Note that while most cards in their posts have thumbnails, the following do not. Please note that there are many more examples in their feed.
      
      https://bsky.app/profile/politico.com/post/3kinwoiwgqm2m
      
      https://bsky.app/profile/politico.com/post/3kintjkocgh2g
      
      https://bsky.app/profile/politico.com/post/3kinhfbnul22j

**Expected behavior**

When a major news outlet posts their content, it should consistently show the story's thumbnail.

**Details**

 - Platform: iOS, desktop Firefox windows and MacOS, 
 - App version:  iOS 1.62.0 (2) production, FF: Build version: 1.63.0;

**Additional context**

This seems like it might be related to the [resolved issue](https://github.com/bluesky-social/social-app/issues/2318) where clicking Post prior to the thumbnail being generated could cause this issue. However, when I test the same links in the posts I mentioned above, I am not allowed to Post prior to thumbnail generation.

Is it possible that Politico is using their own UI, or a 3rd party UI, which does not wait for thumbnail generation?

**Comment by pfrazee** [comment]
Ehm. Another challenging one to debug without talking to the people making the post. I'm guessing they're using the app, so I'm unsure why this would be happening

**Comment by adamatic-me** [comment]
@pfrazee, I have a bit of time on my hands. Shall I try to contact OP on your behalf? 

for DM, bsky at adamatic.me

**Comment by pfrazee** [comment]
By all means that'd be great

**Comment by adamatic-me** [comment]
I will close this, as I never got a response from them.
