### ISSUE TITLE
YouTube embedded player gives "Video unavailable" on android

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2487]
![CleanShot 2024-01-10 at 21 35 55@2x](https://github.com/bluesky-social/social-app/assets/1270099/0a01bb24-c582-4286-b940-ffadad199ccf)

This doesn't seem to happen on Web or iOS so we need to figure out why Android is getting this.

**Comment by haileyok** [comment]
odd, i see the same behavior on ios on this one. if you're not, curious what the distinction is.

regardless, i suspect it's the environment. came across something that mentions needing a referrer header. might be worth trying to set the headers in the request in the webview.

**Comment by pfrazee** [comment]
yeah we should take a look at that youtube embed module we dropped and see if there was something they did

**Comment by haileyok** [comment]
Yea, its the lack of the referrer header. Notice that if you navigate to https://www.youtube.com/embed/h81Ojd3d2rY you get the same result. The previously used library doesn't work if you use the local HTML either, only if you use the GitHub hosted HTML page.

They never want to make it easy. I suppose the solution is indeed to have a hosted file. Twitter does this for example: https://twitter.com/i/cards-frame/postId

**Comment by pfrazee** [comment]
Are we not able to manually set a referrer with the webview api?

**Comment by haileyok** [comment]
You can set headers in the `source` but it seems they don't actually get applied to each request, only the initial one (minimal test to be fair, but setting the exact same headers from the web request didn't seem to help).
