### ISSUE TITLE
[iOS] App crashes/restarts after taking photos

### ISSUE THREAD

**Issue by byte-jra** [bluesky-social/social-app#2512]
**Describe the bug**

The iOS app forcibly restarts after having taken a new picture with the iOS Camera app.

**To Reproduce**

1. Focus the Bluesky app (settings, feeds, new post editor... doesn't matter)
2. Switch to the Camera app AND take a new picture (note: just adding items to the gallery isn't enough to trigger the crash, screenshots work)
3. Switch back to Bluesky – app restarts (and kills your new post for which you took the picture)

**Expected behavior**

Just resume state.

**Details**

 - Platform: iOS
 - Platform version: 17.2.1
 - App version: 1.63.0 (also earlier versions)

**Comment by jens-adam-gcx** [comment]
after more testing:
- iPhone 13 mini: affected as above 
- iPhone 11, same iOS and App version: no problems

**Comment by byte-jra** [comment]
after more testing:
- iPhone 13 mini: affected, as above
- iPhone 11, same iOS/app version: no problems

**Comment by surfdude29** [comment]
I don't know if this is helpful as it's such an old iOS version, but I'm unable to reproduce this on my iPhone 7 running iOS 15.8 and Bluesky 1.63.

**Comment by byte-jra** [comment]
Okay… after app removal, phone reboot, app reinstall, allowing photo gallery access – can't reproduce any longer 🤷‍♂️
