### ISSUE TITLE
The word "London" is not searchable

### ISSUE THREAD

**Issue by meicpalmer** [bluesky-social/social-app#2526]
When I search the word "london", it says "No results found for london"

I expect some results because I know people post about London on here, I've seen posts mentioning London.

Search in general is not broken, it just doesn't work for "London" for some reason.

I am using the browser website.

**Comment by mschwendener** [comment]
Yep https://github.com/bluesky-social/social-app/issues/1727

**Comment by pfrazee** [comment]
Yeah going to close as a duplicate. The most likely cause of this is due to spam results which get improperly filtered by the search service and break the results. I am very hopeful this gets resolved soon.
