### ISSUE TITLE
Discover on Following tab

### ISSUE THREAD

**Issue by Zarpyk** [bluesky-social/social-app#2527]
**Describe the bug**

Discover are showing on Following tab on mobile (Android app) and main page on Web when I don't save it or pin it

**To Reproduce**

1. (I don't know if is this) Open BlueSky and don't have anything to show?

**Expected behavior**

Show the normal feed of people that I follow or empty if the time filter remove all post

**Screenshots**
![imagen](https://github.com/bluesky-social/social-app/assets/30746531/eaf18044-10ac-41b0-9924-e0725157e1b8)
![Imagen de WhatsApp 2024-01-14 a las 16 42 25_9bd2e82a](https://github.com/bluesky-social/social-app/assets/30746531/60f525f8-2302-421e-b995-dc0306ae4027)

**Details**

 - Platform: Desktop firefox windows, Android
 - Platform version: Windows 10, Firefox 122.0b9, Android MIUI 14
 - App version: 1.63.0

**Additional context**

**Comment by pfrazee** [comment]
Yeah #2534 gives a more clear UX. Future improvements we intend to make:

1. There's a temporary limitation on the backend that causes posts from follows to only show from the past few days. That will be removed.
2. Better onboarding & feeds UX that will make falling back less necessary
