### ISSUE TITLE
ability to post from a URL

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#2530]
feature request: ability to post from a url

I often find myself using "share this on social media buttons," and i miss having the ability to click share this to 'bluesky' 

ideally it would be able to post from a url so it would look something like this
"bsky .app/post?text=the text i want to post from a url"
and typing that into the browser would generate the post automatically.

i think this was discussed previously but can't find the discussion.

**Comment by pfrazee** [comment]
Yep closing as a dup, but happy to report that this is in progress https://github.com/bluesky-social/social-app/pull/2587
