### ISSUE TITLE
Typing A\x41 on search field crashes Bluesky

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#2535]
**Describe the bug**

A CJS-ESM module confusion in how LinguiJS attempts to import the `unraw` module causes Bluesky to crash if a Unicode escape like `\x41` appears in a localized string 

**To Reproduce**

1. Open Bluesky
2. Type `A\x41` in the search field

**Expected behavior**

There shouldn't be any autocompletion results, so it would show the localized string for "No results found..." 

**Screenshots**

<img src=https://github.com/bluesky-social/social-app/assets/148872143/fe8f8664-b179-48ee-95ab-281280c1346d width=200>

`r` is the function from `unraw` module that LinguiJS tried to import, it's the `default` export specifically.

**Details**

 - Platform: Web, any browser and device
 - Platform version: Chrome 120
 - App version: 1.63

**Additional context**

https://bsky.app/profile/mary.my.id/post/3kix2upox6k23

Web-only bug, does not happen in mobile app.

**Comment by estrattonbailey** [comment]
@mary-ext thank you for compiling the details here!!

**Comment by DavidBuchanan314** [comment]
Just for fun, I added \x41\x41 to the end of my display name, and it breaks my profile when viewed directly: https://bsky.app/profile/retr0.id

(I'm sure this will be fixed once the patch rolls out)
