### ISSUE TITLE
When I choose "Copy link to post" - please let me know if viewing the post requires sign-in

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2538]
**Is your feature request related to a problem? Please describe.**

When the user who created the post has Moderation/Logged out visibility = false, I might unknowingly share a useless link with the public on some other site.

**Describe the solution you'd like**

After I click "Copy link to post," maybe show me a modal stating "Only signed-in users will be able to view this post." If that is indeed the case.

**Describe alternatives you've considered**

I could manually test the link in a private browser window.

I could take screenshots of the app, and share the post that way.

**Comment by mschwendener** [comment]
> I could manually test the link in a private browser window. 

There's already a text when you do that. I agree that it would be nice to see that information at an earlier stage.

**Comment by pfrazee** [comment]
Great suggestion, thanks
