### ISSUE TITLE
Bsky app doesnt send referrer

### ISSUE THREAD

**Issue by jaoler** [bluesky-social/social-app#2540]
You can't track traffic to your website from Bluesky app because of this. In Matomo or Google Analytics you only see visitors who use Bluesky in browser. 

Matomo dev team wrote:

_Our development confirmed the app does not send a referrer, so it is only possible to populate as direct entry unfortunately.

As BS is still in beta development, maybe they will add the information in the future.

Let me know if you have any questions please.

Regards,

--
Ralph Conti
support@matomo.cloud
Matomo Support Team_

**Comment by jaoler** [comment]
Can you please fix this. It hard to show how important Bluesky is, if you cant track traffic to your site.

**Comment by FairgroundTown** [comment]
This feels like it is massively in Bluesky's interests to fix.

**Comment by fwojtan** [comment]
I agree. Although fixing this isn't free - to do it properly you'd need to host a proxy to add the header. There's got to be a strong commercial case for showing downstream sites that Bluesky is driving their traffic, but...
- it's not obvious to me that fixing this in the app is sufficient in the long run, if the network becomes properly federated people may click on a link you posted on the Bluesky app in a different client altogether, so we'd still be undercounting, or at least disaggregating, the impact of Bluesky on traffic
- whoever pays for the proxy would need to decide there's a business case and that this is a priority

**Comment by spectre1989** [comment]
I think the business case for the proxy is that this will drive more users to the platform. People who monetise substacks and the like will be more active on bsky if they see more of their traffic coming from there

**Comment by bthompson-365** [comment]
Sorry but this is not a bug - if you want to track visitors from Bluesky to your site put the appropriate information in the URL you post...

**Comment by jaoler** [comment]
> Sorry but this is not a bug the lack of referrer information is a plus for an awful lot of people
> 
> And there is a simple workaround if you want to track visitors from Bluesky to your site put the appropriate information in the URL you post - in the same way you would when sending an email out..

No, you are wrong. Its totally differend thing put tracker urls to post you personally share.

**Comment by FairgroundTown** [comment]
> Sorry but this is not a bug the lack of referrer information is a plus for an awful lot of people
>
> And there is a simple workaround if you want to track visitors from Bluesky to your site put the appropriate information in the URL you post - in the same way you would when sending an email out..

I agree that it isn't a "bug" per-se, but it is still Bsky's *_problem_* - asking everyone else to change the way they work to fit in with Bsky just isn't going to cut it. For example, people running hosted Wordpress or Substack literally *_can't_* change the way they work to fit in with this, even if they had the technical acumen to do so. They will simply look at their stats, see that Bsky is way, way below Facebook and Twitter and Wikipedia (sic - in my case!) and shug and say "Well... Bsky isn't really getting any traction - I'll focus elsewhere."

**Comment by gaearon** [comment]
I've looked at this today. So far it doesn't seem to be possible to add a `Referer` header on iOS (without dropping down from `SFSafariViewController` to `WKWebView` which I'd rather not do) or on Android (where `CustomTabsIntent` only takes CORS-safelisted headers, which `Referer` is not).

This means, unless I'm wrong, that we're only left with these options:

1. Do nothing (status quo)
2. Set up a redirect service like `https://bsky.app/redirect/...` (which would rely on the browser to fill in`Referer`)
3. Or hijack the link to add `utm_source=bluesky` or something to the links (if missing)

I lean towards (2) with an opt-out in Settings for people who'd rather skip this step. But curious if y'all have other ideas.

**Comment by jaoler** [comment]
How other apps do this? X, Threads, Facebook?

**Comment by FairgroundTown** [comment]
Hijacking the links is going to cause weird bugs in systems which don't use "standard" url parameters. I've literally done this in the past - I added an ID to people's Return URLs in a payment system - and had people get cross with me for messing with their inputs. 

Setting up a redirect service is definitely the better solution; but I appreciate it won't be a cheap - hence I'd understand doing nothing.

**Comment by surfdude29** [comment]
I think X uses their `t.co` link shortening service, which I'm guessing sends a `Referer`.

No idea about Threads or Facebook.

**Comment by FairgroundTown** [comment]
> How other apps do this? X, Threads, Facebook?

They embed a webview in their app, rather than passing out to Safari/ Chrome to handle it.

**Comment by jaoler** [comment]
Heyyyy, is this fixed? 🤩
From Matomo:
![Image](https://github.com/user-attachments/assets/d3e40fe1-c6c0-4507-ab04-2ce9b9f05c04)

**Comment by surfdude29** [comment]
Yep this was fixed in #7857, which was released in 1.99 🙌

https://bsky.app/profile/emilyliu.me/post/3lk27jsfklk2t
