### ISSUE TITLE
Provide an .svg asset for the new logo

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bluesky-social/social-app#2543]
**Is your feature request related to a problem? Please describe.**

Most major tech brands have some kind of "brand kit" available with rasterized versions of their logos. This is useful for folks who want to use the logo in their own images.

**Describe the solution you'd like**

Could Bluesky provide at least a rasterized svg version of the new logo from https://blueskyweb.xyz/blog/12-21-2023-butterfly / #2301 please?

**Describe alternatives you've considered**

We can use the `.png`s checked into the repo, but they're not rasterized so don't scale well to high resolution displays and/or images.

**Additional context**

My personal context is that I have links to my online presence on my site. Each uses an `.svg`  image (https://www.joshuakgoldberg.com/icons/mastodon.svg, https://www.joshuakgoldberg.com/icons/twitter.svg, etc.). https://github.com/JoshuaKGoldberg/dot-com/issues/146 tracks adding one for Bluesky.

**Comment by surfdude29** [comment]
There's a [media kit](https://drive.google.com/drive/folders/16mlJPfWNnc6jj-3vGZ88SFysIY13GBp0) linked from the [Press](https://blueskyweb.xyz/blog/press-faq) page on the Bluesky website that contains an .svg version of the logo, that might work for you?

**Comment by JoshuaKGoldberg** [comment]
Aha! I hadn't seen that 😄 thanks for the pointer. That does work for me!

**Comment by surfdude29** [comment]
Excellent! No worries :)

**Comment by mschwendener** [comment]
Could this maybe also be linked to from https://blueskyweb.xyz/blog/12-21-2023-butterfly ?

**Comment by pfrazee** [comment]
@mschwendener I hope you don't mind if we don't, we're just tight enough on time that I dont have anyone that could spare the 15 for it
