### ISSUE TITLE
Weird graphical glitch when browsing posts on bsky.app with Chromium 119.0.6045.192

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#2551]
Here is a video of the issue:

https://github.com/bluesky-social/social-app/assets/6194332/4d4b4fd6-0546-4d36-be87-b82bf2746ab0

**Comment by mschwendener** [comment]
Related? 
 
 https://github.com/bluesky-social/social-app/issues/1593 
 https://github.com/bluesky-social/social-app/issues/1490 
 https://github.com/bluesky-social/social-app/issues/1752

**Comment by Zero3K** [comment]
I think one or more of those are because of how it displays images. If so, then this issue is related to those.

**Comment by pfrazee** [comment]
This has been fixed in the most recent release
