### ISSUE TITLE
Add direct messages

### ISSUE THREAD

**Issue by ParkerGit2328** [bluesky-social/social-app#2552]
Twitter has a direct message feature, so why not bring it to Bluesky?

**Comment by dolciss** [comment]
Private content including direct message is discussed in the atproto repository
https://github.com/bluesky-social/atproto/discussions/121

**Comment by surfdude29** [comment]
See also #1114

**Comment by pfrazee** [comment]
Yeah this is indeed a goal! It just requires some engineering work that we can't do at this stage.

Closing as a duplicate.
