### ISSUE TITLE
Post displayed twice 

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#2559]
I see https://github.com/bluesky-social/social-app/issues/1805, but it's closed as fixed. 

I have something similar, Firefox on Macbook:

Scrolling through https://bsky.app/profile/indiffe.rent I see a duplicated post. If I like one of them, the other also gets the like. 

Reload does not solve it.

<img width="343" alt="screenshot_4730" src="https://github.com/bluesky-social/social-app/assets/4497705/fa75733d-f790-43bf-b396-2030ff4d362e">

**Comment by surfdude29** [comment]
I just looked at his feed, I think it's showing up twice because the top post is a repost, so liking either the original or the repost will like the other one.

**Comment by mschwendener** [comment]
You're right. Should not post before coffee..!
