### ISSUE TITLE
Offer full-black dark mode setting

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#2595]
**Is your feature request related to a problem? Please describe.**

As of the latest update (On Web at least, I'm unsure if my phone simply has yet to receive the update), the dark mode has changed from being black to being a hazy blueish gray. It's similar to GitHub's dark mode, but distinctly less readable. The contrast ratio for the main post text has only gone from 21 to 19.82, but the perceived contrast difference in context is far worse. It looks like there is a layer of fog on my screen with how much every color blends together because the ratio between the background and the borders is 1.93. Likewise, links on the sidebar to various feeds have dropped to 9.16. I find this much more difficult to read.

Now, aside from this being a personal preference (because with all due respect I find these color choices to be deeply revolting), the lack of a black mode is upsetting for OLED users given that pixels on an OLED screen are off when they are black. This difference in power usage is less appreciated on desktop, but for mobile users with OLED screens, it is absolutely noticeable. 

**Describe the solution you'd like**

Either reverting to the previous dark mode or offering a black mode (the previous dark theme) along side the current light and dark mode options.

**Describe alternatives you've considered**

I have three options:

1. Live with it.
2. Pump in my own CSS via an extension like Stylus.
3. Ask politely on GitHub for a change.

I do not wish to do Option 1, nor do I wish to deal with the tedium of Option 2, so respectfully I am here for Option 3.

**Additional context**

**Comment by quiple** [comment]
I think it has to do with accessibility for users with astigmatism. #647

Personally, I find the gray background a little easier to look at. But I agree with providing an option for a full-black background!

**Comment by Hima-Zinn** [comment]
It appears that such a feature was implemented in build version 1.66.0.

Personally, I liked the traditional black background with white text, but I think it would be better to add a new accessibility setting in the "Basics" section, where background color, text color, and other handicap-accessible settings can be combined and enabled for those who want to enable them, or disabled for those who want to disable them.

**Comment by surfdude29** [comment]
FYI @pfrazee said this on Bluesky:

["yeah we're iterating toward 3 modes, one of which will have the pure black"](https://bsky.app/profile/pfrazee.com/post/3kjm2ksoxcl2g)

**Comment by Juicysteak117** [comment]
@surfdude29 Ah, I must've missed that. That's great to hear, although I would've appreciated had they rolled out both changes simultaneously instead of leaving us stuck with the current colors, but that's how it is sometimes.

**Comment by pfrazee** [comment]
@Juicysteak117 yeah sorry, in code review it didn't set off a bell to me that we changed the background color for dark mode. If I was thinking clearer I would've remembered the discussion around this the last time it happened.

But yes, this is the plan. I'm somewhat inclined to make it a separate toggle than the color mode so that the system option still works, you just choose whether you want dark mode or daaaark mode.

**Comment by surfdude29** [comment]
> I'm somewhat inclined to make it a separate toggle than the color mode so that the system option still works, you just choose whether you want dark mode or daaaark mode.

IIUC what you're proposing is similar to how it is on Telegram and I think it works well. There are prefs for when Night Mode (as they refer to it) is enabled – including an option to just follow the system setting – and then you choose between Night and Dark themes.

![IMG_6246](https://github.com/bluesky-social/social-app/assets/149612116/1b1bc80f-ef5a-46f5-8d98-e2bffdfe8dd4)

**Comment by Juicysteak117** [comment]
@pfrazee No worries, it happens. I think @surfdude29's suggestion is the right one for sure and hopefully it's not too much of a hassle so it's able to happen in the next update or two. Thanks!

**Comment by connie-e** [comment]
I like the idea of following GitHub's appearance section. Offering different color-blind themes and a dimmer dark mode.
