### ISSUE TITLE
Language detection sometimes gets outright offensive

### ISSUE THREAD

**Issue by imax9000** [bluesky-social/social-app#2598]
[https://bsky.app/profile/psyhfuck.bsky.social/post/3kjoea4227q2r](https://bsky.app/profile/psyhfuck.bsky.social/post/3kjoea4227q2r)

![bafkreifzokbcbdbupxr35o5n4vdmiwwq4tb67vnaftw7cdspu6r7xp6pt4](https://github.com/bluesky-social/social-app/assets/654649/2651218d-c8d1-41f8-bdf0-a6abb7d5fd86)

Suggesting "russian" on a text clearly written in Ukrainian is very, very bad (especially if you capitalize "russian"). Please do better.

**Comment by surfdude29** [comment]
There are possible changes to how language detection works in #2582 that might fix this
