### ISSUE TITLE
Jiggling wiggling UI on web

### ISSUE THREAD

**Issue by agentjabsco** [bluesky-social/social-app#2600]
**Describe the bug**

various parts of the UI will start shifting up and down by one pixel when viewing the timeline / feeds. this may or may not be related to the [other reports of unexpected motion](https://github.com/bluesky-social/social-app/issues/2551#issuecomment-1895325741) (those seem to be describing a much more major jump)

**To Reproduce**

a big part of what makes this bug so hard to pin down is that I don't think I've seen anyone find a reliable way to reproduce it, it just sort of tends to happen randomly after you've scrolled a certain amount

**Expected behavior**

the webpage should not get the shakes

**Screenshots**

[Screencast from 2024-01-23 13-22-17.webm](https://github.com/bluesky-social/social-app/assets/136868210/74cde3ed-46de-4947-92c2-8dbc1cfa7c8c)

**Details**

 - Platform: Desktop Chrome (Linux) 120.0.6099.224 (Official Build) (64-bit)
 - App version: 1.66.0

**Additional context**

honestly this is [probably a Blink/Skia bug](https://bsky.app/profile/jabsco.cia.fyi/post/3kjo5z23cdq2u), i'm mostly just reporting it here as an excuse to post that screengrab. [here's that post about the Terminator's junk](https://bsky.app/profile/hypercubexl.bsky.social/post/3kjogcqwvy62e) if you want to see if you can get it to reproduce

**Comment by Zero3K** [comment]
In my case, it looks like part of an image is showing up while scrolling.
