### ISSUE TITLE
Left swipe is buggy under very specific circumstances

### ISSUE THREAD

**Issue by gpp-0** [bluesky-social/social-app#2601]
**Describe the bug**
While on the Following feed or on the Posts tab in someone's profile, if you swipe left on a post with two or more images, instead of switching to the next feed/tab it tries to open the side drawer in a weird way

**To Reproduce**

1. Go to the Following feed, or open up someone's profile and go to the Posts tab
2. Find a post with two or more images in it. Posts with one image (or no images) work as they should
3. Swipe left, starting the gesture at one of the pictures
4. The app gets confused and tries to extend the drawer

**Expected behavior**

No drawer shenanigans, and the timeline should switch to the next feed

**Screenshots**

Showing first how it's buggy under the above conditions, and then how it works fine if you swipe anywhere else

https://github.com/bluesky-social/social-app/assets/52042597/ca8e38a1-70ff-4493-af28-e2973822984e

**Details**

 - Platform: Android
 - Platform version: 10
 - App version: 1.66

**Additional context**

This faulty gesture capturing also randomly happens under different circumstances, but this was the most reliable way to reproduce it, it basically happens 100% of the time. Posts with 2 images are common so I encounter this bug very often when trying to switch feeds

**Comment by pfrazee** [comment]
Seems to be related to https://github.com/bluesky-social/social-app/issues/2677
