### ISSUE TITLE
Support shrinking/expanding comments

### ISSUE THREAD

**Issue by innocenzi** [bluesky-social/social-app#2620]
**Is your feature request related to a problem? Please describe.**

When there are a lot of nested comments under a post, it becomes a bit overwhelming to read.

Sometimes we're not interested in the responses to a response, but if there are a lot we have to scroll a lot to see other top-level responses.

**Describe the solution you'd like**

Reddit solves this by allowing shrinking (hiding) comments and their responses:

https://github.com/bluesky-social/social-app/assets/16060559/9ba55910-4296-482f-ac9a-ce765ed9be71

I think the same functionality would be very welcome on Bluesky.

**Additional context**

Here's a random post I found in Discover. It has a lot of nested comments, which are especially lenghty because they contain images, which makes it hard to navigate comments: https://bsky.app/profile/brainnotonyet.antifa.llc/post/3kjroarzw722h

**Comment by surfdude29** [comment]
See #1547 and maybe #1044 is relevant too
