### ISSUE TITLE
Can't auxiliary click on posts (web)

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#2631]
**Describe the bug**

Clicking on a post body takes you to the post thread, but since the links are are fake (not anchor tags), there's no auxiliary click action on web (aka middle click to open in new tab)

**To Reproduce**

1. middle click on a post
2. observe nothing happening

**Expected behavior**

It opens the post thread in a new tab

**Details**

 - Platform: web
 - Platform version: firefox
 - App version: any

**Additional context**

~~Just need to add an `auxclick` handler (weirdly I can find next to no info on this for RNWeb)~~

Turns out Firefox is the issue here! Doesn't support `auxclick` properly

**Comment by haileyok** [comment]
I actually have a local branch where I fixed this afaik. I'll look and clean it up.
