### ISSUE TITLE
I think my feedgen app returns posts in JSON which randomly do not get hydrated by bsky.app

### ISSUE THREAD

**Issue by venteto** [bluesky-social/social-app#2657]
**Describe the bug**
I have a benchmark curated user list of the MoMA, Guggenheim and Tate art bots. I made a test feed following the same three accounts, and when I look at both side by side, in my feed I notice random posts are missing which are present in the curated user list.

I look inside my database, and I see those posts did in fact get saved to the database by my firehose indexer. I go to the URL on my site where the feed should be getting served to Bluesky, and I see those posts also appear in the generated JSON.

I've been trying to figure out what I've been doing wrong, but considering the posts are in the JSON response, it would seem that for some reason the issue is not on my end but on the Bluesky consumer end?

**To Reproduce**

1. Go open [my feed](https://bsky.app/profile/did:plc:wecucphzbhaznb64qmvto5oj/feed/museums) and my [user list](https://bsky.app/profile/did:plc:wecucphzbhaznb64qmvto5oj/lists/3kjvtzbraol2i) in two windows side by side.
2. Notice that posts in the user list randomly do not appear in my feed.
3. Visit my [feed generator app URL](https://venteto.fly.dev/xrpc/app.bsky.feed.getFeedSkeleton?feed=at://did:plc:wecucphzbhaznb64qmvto5oj/app.bsky.feed.generator/museums) at Fly.io for this specific feed.
4. Notice the post ID's of the missing posts are in the JSON output Bluesky should be consuming.

**Expected behavior**

I expected my feed to have the exact same output as my curated user list, post for post, so my feed could be a drop in replacement for the curated user list.

**Screenshots**

![bsky-json-not-hydrated](https://github.com/bluesky-social/social-app/assets/7062385/194d5adf-0a4f-4677-a0d5-efb720b0a45b)

![bsky-compare](https://github.com/bluesky-social/social-app/assets/7062385/58fc2481-95a6-4817-9330-0a37986a64e0)

**Details**

I'm just looking at the web app version of Bluesky in desktop Firefox.

**Additional context**

My test [app repo](https://github.com/venteto/bfg2/)

**Comment by dolciss** [comment]
Have you set Content Languages to English?
It seems that the Post is not being displayed due to language judgments as in #1960

I have checked and all applicable Posts are judged by lande for language because `post.record.langs` is not set.
Currently, to avoid this, either unset Content Language or set `post.record.langs` correctly

> at://did:plc:z5pxuiispc5yacvofktometn/app.bsky.feed.post/3kjzbhr3yw72o
Alan Cote, Distant Warmth, 1978

-> lande detected 'eng'

> at://did:plc:pa2epocjfar2fzz4symzmb5t/app.bsky.feed.post/3kjzaoqu2v52r
Akram Zaatari, Anonymous. Studio Shehrazade, Saida, Lebanon, 1960s. Hashem el Madani, 2007

-> lande detected 'cat'

> at://did:plc:jx26hj3zymmn53cfjetkmwry/app.bsky.feed.post/3kjz7ol4jm22f
Korn by Gerhard Richter, 1982

-> lande detected 'eng'

> at://did:plc:z5pxuiispc5yacvofktometn/app.bsky.feed.post/3kjz6tqoasa23
Mordecai Ardon, Amulet for a Yellow Landscape, 1966

-> lande detected 'cat'


> at://did:plc:pa2epocjfar2fzz4symzmb5t/app.bsky.feed.post/3kjz6byz2ne2a
Dieter Roth, Hemdenstein, 1971

-> lande detected 'deu'


> at://did:plc:pa2epocjfar2fzz4symzmb5t/app.bsky.feed.post/3kjz3etd2ls2m
William Holman Hunt, Claudio and Isabella, 1850

-> lande detected 'cat'


> at://did:plc:pa2epocjfar2fzz4symzmb5t/app.bsky.feed.post/3kjz23sxq232l
Paula Rego, Drawing for ‘The Dance’, 1988

-> lande detected 'eng'

**Comment by MarshalX** [comment]
@dolciss awesome answer! 

i opened the deployed feed from the issue in ff and got these headers:
<img width="559" alt="image" src="https://github.com/bluesky-social/social-app/assets/15520314/e304bdf9-4b05-41ba-a336-294eca021c21">

i cant see here content-lang header. do i miss something?

**Comment by dolciss** [comment]
> do you mean account settings at https://bsky.app/settings/language?

Opps, yes, the Content Language I am referring to is in the settings, not the header.
I have unchecked all languages, so the corresponding Post is also shown.
![image](https://github.com/bluesky-social/social-app/assets/3786294/7efa0be6-7c13-4c07-8295-ea9501ac7e8b)

**Comment by MarshalX** [comment]
verified. yes, this is why it got filtered!

**Comment by venteto** [comment]
I don't even recall touching this setting in the client app, but changing it seems to solve my problem. Thanks!!

Interesting that this setting only affects feeds, but not curated user lists.

**Comment by surfdude29** [comment]
> I don't even recall touching this setting in the client app

I think it's set by default when you create your account
