### ISSUE TITLE
Navigation drawer behaving in an odd way after clicking on the hamburger icon

### ISSUE THREAD

**Issue by itsWindows11** [bluesky-social/social-app#2677]
**Describe the bug**

Title is enough.

**To Reproduce**

1. Click on the hamburger icon on the top left
2. Observe the bug (note that it's not easily reproducible so YMMV)

**Expected behavior**

Navigation drawer to ~~be less shy~~ stay as is when opening the menu.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/81253203/65bdf080-298a-4d5f-a557-a71da36b12e5

**Details**

 - Platform:  Android
 - Platform version: Android 13
 - App version: 1.66.0

**Additional context**

**Comment by pfrazee** [comment]
Turns out this looks like a dup of https://github.com/bluesky-social/social-app/issues/2601, so closing to consolidate
