### ISSUE TITLE
Use native speakers from community to proof read

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#2681]
The recently added translations to German are terrible. Comments describe them as irritating, confusing and not understandable. Sometimes they worsened by translation because the German word is a loanword from English, so it shouldn't have to be translated at all. Some users said that they have changed back to English in order to understand the functionality at all. Yes, it is THAT bad.

Examples (Englisch -> "German" Translation -> Meaning -> Correct translation): 

Posts -> Posten -> Positions -> Posts
New post -> Neuer Posten -> New position -> Neuer Post
Change handle -> Änderungsgriff andern -> Changinghandle chunge (sic!) ->Benutzernamen ändern
Muted accounts -> Stumme Kontos -> Silent Accounts -> Stummgestellte Konten
Moderation lists -> Moderation Liste -> Moderation, list -> Benutzerlisten
Threaded Mode -> Gewindemodus -> Screwthread view -> Ansicht in Threads
Thread Preferences -> Einstellungen zum -> Settings for -> Thread-Einstellungen
My saved feeds -> Meine gespeicherte Feeds -> My saved feed (wrong genus) -> Meine Feeds
Repost -> Wiederveröffentlichung -> Republication -> Repost
Quote Post -> Angebotsposten -> Position on sale -> Zitat
Follows -> Verfolgt Sie -> Hunts you -> Folgt Ihnen

Language files should be proof read by native speakers before being rolled out.

**Comment by surfdude29** [comment]
New German translations reviewed by native speakers were released in 1.67, available now on the web and coming very soon to iOS and Android. When you've had a chance to review them, maybe this issue can be closed?
