### ISSUE TITLE
Selected text has very low contrast

### ISSUE THREAD

**Issue by imbstt** [bluesky-social/social-app#2687]
**Describe the bug**
When I select text on Bluesky on desktop, the color with which it is highlighted is very light and has low contrast to the background. This applies to both light and dark theme. 

On light theme, in the search input field (both in the right sidebar and on the dedicated search page), the highlight is the same color as the input's background.

**To Reproduce**

1. Open Bluesky in a web browser
2. Select some text with mouse or CTRL+A

**Expected behavior**

Selected text should be clearly visible

**Screenshots**

Light theme, profile bio, second line of text highlighted:

![image](https://github.com/bluesky-social/social-app/assets/83777889/739a73e5-4132-4d50-85bd-586ecc874c60)

Light theme, Search box, all text highlighted:

![image](https://github.com/bluesky-social/social-app/assets/83777889/3154e7b4-52d4-443f-9642-3b1efe03aa79)

**Details**

 - Platform: Desktop Firefox 
 - Platform version: Firefox 122 on Windows 11
 - App version: 1.67.0

**Additional context**

I believe this behaviour was introduced with this commit: https://github.com/bluesky-social/social-app/pull/2596/commits/ffbe5dea8493abef811093d43caf78c25a992343 (https://github.com/bluesky-social/social-app/pull/2596)

**Comment by surfdude29** [comment]
This looks like it is fixed by #2689

**Comment by haileyok** [comment]
Yup, was fixed. Should be released soon.
