### ISSUE TITLE
Scrolling the alt-text text-composer-field affects the whole alt-text popup on mobile

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#2702]
**Describe the bug**
On Android (but maybe iOS too), there's an issue with the text field in the alt text popup for longer alt texts where trying to scroll down in the composer causes the entire field popup to scroll down which closes the popup.

**To Reproduce**

1. Write a lengthy alt text.
2. Scroll to the top of it.
3. Attempt to scroll down in the box.

**Expected behavior**

I expect the text composer to take priority when scrolling down rather than both scrollers moving together.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/20595808/aff8b37a-756e-4391-a03d-bd1110c3f7cf

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: Latest

**Additional context**

**Comment by haileyok** [comment]
I think this may be fixed in https://github.com/bluesky-social/social-app/pull/2690, noticed some jankyness earlier. Will see.

**Comment by Juicysteak117** [comment]
Very possible but I noticed you had resolved a bunch of my other issues so I figured I'd keep you on your toes by finding new ones lmfao. Hopefully that one fixes it!

**Comment by haileyok** [comment]
Finally fixed this jfc
