### ISSUE TITLE
Media in quote post not showing in media tab

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#2723]
**Describe the bug**
Small bug. In the media tab on my profile, I self-quoted a media post (which is in my media tab) with more media, yet that post itself isn't in the media tab. Unclear exactly where the issue lies.

**To Reproduce**

1. https://bsky.app/profile/juicysteak117.gay/post/3kk5juqcukt2x
2. Observe that it is not in my media tab from the past few days.

**Expected behavior**

The post to be there.

**Screenshots**

**Details**

 - Platform: 
 - Platform version:
 - App version:

**Additional context**

**Comment by mozzius** [comment]
Pretty sure that it's AppView v2 only showing image embeds, and not `RecordWithMedia` embeds (i.e. image + quote)

**Comment by haileyok** [comment]
Yup this turned out to be a v2 issue that's been resolved!

![image](https://github.com/bluesky-social/social-app/assets/153161762/ad779737-840d-4ec9-8266-4e57dbc16eda)
