### ISSUE TITLE
Thread screen jumping around on android

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#2728]
A user reported that large threads have a habit of jumping around on them (see https://bsky.app/profile/trisalvagni.bsky.social/post/3kkehebyx7e2g)

It's possible that this is a bug in how the scroll position is maintained on load.

**Comment by mozzius** [comment]
I had this at the bottom of a very long thread on iOS too, I don't think it's Android-specific. I'll try and find the thread and replicate it

**Comment by mozzius** [comment]
Not sure if this is the same bug as what the other person was sharing, but this is the thread: https://bsky.app/profile/mozzius.dev/post/3kjqgddalf22e

https://github.com/bluesky-social/social-app/assets/10959775/4193e68c-840e-431a-8a0a-d2e50732e66d

**Comment by gaearon** [comment]
We've fixed / worked around _some_ of these cases.

Here's the latest on known jumps by type of post.

```
[OK] Timeline -> Text
[OK] Timeline -> QT of Text
[OK] Timeline -> Link
[OK] Timeline -> Image
[OK] Timeline -> QT of QT of Text
[JUMP] Timeline -> QT of Link
[JUMP] Timeline -> QT of Image
[OK] Timeline -> QT of QT of QT of Text
[OK] Timeline -> QT of QT of Link
[JUMP] Timeline -> QT of QT of Image
[JUMP] Timeline -> YouTube
[JUMP] Timeline -> QT of YouTube
[OK] Timeline -> QT of QT of YouTube
```

Other known issues:

- Posts with no likes/RTs jump
  - When navigated from timeline (but we have the metrics, so should be fixable on front-end)
  - When navigated via QT (we don't have the metrics here, might need backend help)

Some unexplained problems:

- Why does [this post](https://bsky.app/profile/haileytesting10.bsky.social/post/3klsh75p4h52q) jump
- Why is `QT of QT of Link` OK but `QT of QT of Image` jumps (aren't both embeds)
- Why doesn't [this post](https://bsky.app/profile/dansshadow.bsky.social/post/3klsh3rezsl2i) jump on native despite YouTube above?

**Comment by gaearon** [comment]
I'm closing this issue as we've resolved most of the related issues (on main — pending the release). There's still more to do for quote posts, but I've opened https://github.com/bluesky-social/social-app/issues/2946 to track that.

Thanks everyone!
