### ISSUE TITLE
@mary-ext, if I may I ask why you think that this is a bad idea? Please entertain me, or destroy me with evidence.

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2737]
@mary-ext, if I may I ask why you think that this is a bad idea?

If this would force some other issues, please let me know. ?
#good vibes

_Originally posted by @adamatic-me in https://github.com/bluesky-social/social-app/issues/2735#issuecomment-1924150860_

**Comment by pfrazee** [comment]
Hey @adamatic-me, this should be a reply to your original post, not a top level issue

**Comment by adamatic-me** [comment]
I'm sorry, this should have been an issue not a bug. I still don't know how I messed up the reply. My apologies.
