### ISSUE TITLE
Feedback and Help links don't respect in-app browser pref

### ISSUE THREAD

**Issue by surfdude29** [bluesky-social/social-app#2746]
**Describe the bug**

Tapping either the Feedback or Help link at the bottom of the navigation drawer opens the relevant page in the user's default browser, even if the 'Open links with in-app browser' preference is toggled on.

**To Reproduce**

1. Go to Settings and toggle on the 'Open links with in-app browser' preference.
2. Open the navigation drawer and scroll down.
3. Tap either Feedback or Help.
4. Observe that the page is opened in the user's default browser app.

**Expected behavior**

The page should open in the in-app browser when the preference for that is toggled on.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/149612116/00a68822-3a72-45a4-b150-dac2161ba35f

**Details**

 - Platform: iOS
 - Platform version: 15.8.1
 - App version: 1.66

**Additional context**

This is similar to #2645, which has already been fixed, thanks! 🙏

**Comment by haileyok** [comment]
My thinking is that these should continue to open in the system browser. In these cases it is possible the user may want to reference something in the app (i.e., submitting attachment images).

**Comment by surfdude29** [comment]
That's a very good point that I hadn't considered and I think you're right, thanks Hailey I'll close it :)
