### ISSUE TITLE
I am not getting notified when someone registers using my invite code

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#2750]
*subject*

It's a regression because I saw it working before.

**Comment by surfdude29** [comment]
@Zero3K: It's not as obvious of course, but just as a reminder in case it's helpful: when you notice that your number of available invite codes has gone down, you can tap that and see who has joined using one of your codes. Tapping their username takes you to their profile where you can follow them if you want.

**Comment by Zero3K** [comment]
I already know about that.

**Comment by Zero3K** [comment]
Okay.

**Comment by Zero3K** [comment]
This issue is no longer valid since invite codes are no longer being used when signing up.
