### ISSUE TITLE
"Show posts from my feed" won't stay on

### ISSUE THREAD

**Issue by steveharoz** [bluesky-social/social-app#2761]
**Describe the bug**
The "Show posts from my feed" option occasionally turns off on its own. Every once in a while, I'll notice that I'm not seeing posts from other feeds. When I check the settings, it's off. But I never turned it off.

When I fix it, it'll be fine for a week or two, and then it'll turn off again.

**To Reproduce**

I cannot reproduce it reliably. It just happens every couple weeks.

**Expected behavior**

It should stay on if I turn it on.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/2257540/5817769a-49cb-4ab4-aa2e-9ac2d0dc2ef4)

**Details**

 - Platform: Web - Windows 11, Chrome
 - Platform version: 
 - App version: 1.67.0

**Comment by steveharoz** [comment]
Would it be helpful to document when notice that it has flipped? I turned it again when I posted this issue 3 days ago. Now it's off again.

**Comment by steveharoz** [comment]
Feb 13. It happened again. The setting was definitely on earlier today. Now it's off.
And this happens for the "Threaded Mode" setting too.

I wonder if the problem is with my using other clients, specifically skyfeed and deck.blue?

**Comment by steveharoz** [comment]
March 1. It happened either today or yesterday. It was definitely on two days ago.
Both "Show posts from my feed" and "Threaded mode" are off.

**Comment by gaearon** [comment]
I haven't looked at how this currently works, but I have a theory that if we try to do the syncing between clients, then the client whose settings are most recently updated can overwrite the previous settings — and that would overwrite the parts that haven't been synced to it.

**Comment by steveharoz** [comment]
Besides the main website, I also use skyfeed (for updating custom feeds) and deck.blue, so maybe jumping between clients plays a role?

**Comment by steveharoz** [comment]
Happened again at some point in the last couple days.

**Comment by haileyok** [comment]
@steveharoz Thanks. I've reached out to a few devs with which this might be related. We'll do some work to prevent this from happening too. Thanks for the heads up though!

**Comment by haileyok** [comment]
@steveharoz Hey, just heard word that this should have been fixed in deck.blue. Keep an eye out and see if it happens again, but it should be good. Going to close this for now but (I think) those issues should go to their repo is there's another issue in the future (assuming you're still using deck.blue).

Thanks!

**Comment by steveharoz** [comment]
@haileyok Thank you for tracking this weird bug down!
