### ISSUE TITLE
Please get rid of the need to supply a mobile phone number when registering

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#2762]
Instead, have the number be sent to the email address that the user has specified.

**Comment by ScareAwayTheNeighbors** [comment]
They won't. It's presumably to stop people from mass creating accounts for use in botting or whatever.
Sure, it sucks for those of us without a phone number we're able to use, but thats life.

**Comment by Zero3K** [comment]
They can use captcha or something.

**Comment by ltsc1980** [comment]
I agree. Phone number shouldn't be needed IMO. They can have different way to prevent bots.

**Comment by Zero3K** [comment]
This seems to have been fixed by a PR that implements CAPTCHA in place of phone verification (which has been merged). Now to wait for a new release.

**Comment by haileyok** [comment]
Captcha verification is now live on web, will roll out to mobile later in the week.
