### ISSUE TITLE
play store still says invite code required

### ISSUE THREAD

**Issue by ameliamnesia** [bluesky-social/social-app#2767]
**Describe the bug**
super tiny thing, but just wanted to give you all an fyi that the app description in the play store still says "invite code required"

![Screenshot_20240206-181644.png](https://github.com/bluesky-social/social-app/assets/133761448/758edb78-7228-415f-94d4-244b6dfa6816)

**Comment by MatrixRave** [comment]
This is also the case in Apples AppStore, there is still a description saying an invite code is needed

**Comment by MatrixRave** [comment]
Well yes but that's not a big thing to change, and not everyone is reading release notes. 
So this is rather important and should at least be stated.

**Comment by mozzius** [comment]
Since it's been removed from the web interface, I'm pretty confident in saying the change has already been made and the mobile versions are just waiting for App/Play Store review

**Comment by haileyok** [comment]
This will be updated once the stores approve the next release. It can't be updated without store review. Thanks!
