### ISSUE TITLE
longer bios preventing scrolling profiles on smaller screens

### ISSUE THREAD

**Issue by ameliamnesia** [bluesky-social/social-app#2785]
**Describe the bug**
reporting for a non-github user, but apparently on smaller screens such as the iphone se, profiles get stuck and can't be scrolled if the bio section is long enough to fill up the screen. 

in the last screenshot, the profile for skeetstats can be scrolled because a post is just barely visible, but mine and bosset's profiles can't be scrolled at all. the navigation buttons work, but don't allow the profile to be scrolled unless at least 1 post is visible.

**To Reproduce**

1. go to a user's profile with a bio long enough to fill the screen (on a device small enough to do that like the iphone se)
2. attempt to scroll down to see posts

**Expected behavior**
from here it looks like an issue partly with the banner displaying fully rather than being cropped to a certain aspect ratio and possibly an issue with the bio and tabs being separated from the user's post feed, but obviously the expected behavior would be to be able to scroll as if it were one combined element

**Screenshots**
![IMG_0057.png](https://github.com/bluesky-social/social-app/assets/133761448/80a0dc69-e51f-4365-a768-5e8f6d71c114)

![IMG_0061.png](https://github.com/bluesky-social/social-app/assets/133761448/32179e76-f579-4011-bb6b-88819a9e53fc)

![IMG_0060.png](https://github.com/bluesky-social/social-app/assets/133761448/51faf327-6a75-4fdf-a1bd-15ce555d49bd)

**Details**

 - Platform: iOS 
 - Platform version: 17.3
 - App version: 1.67

**Comment by surfdude29** [comment]
Yeah this is a very annoying bug, the [workaround posted by mozzius](https://github.com/bluesky-social/social-app/issues/2220#issuecomment-1862400277) is all I can suggest until this gets fixed.

**Comment by haileyok** [comment]
This was fixed a while back.
