### ISSUE TITLE
UI overflow caused by german translation of "Notifications" in sidebar

### ISSUE THREAD

**Issue by lenke182** [bluesky-social/social-app#2793]
**Describe the bug**
When using German as the app language on https://bsky.app, the German translation for "Notifications" in the sidebar causes an overflow that makes the sidebar scrollable.

**To Reproduce**

1. Use "German" as the app language and visit https://bsky.app

**Expected behavior**

The sidebar remains unscrollable and the German term doesn't cause an overflow in the UI.

**Screenshots**

[recording.webm](https://github.com/bluesky-social/social-app/assets/13052748/8edc40e2-6680-4565-a3b2-475538ff33d0)

**Details**

 - Platform: Desktop, Firefox 122.0 (https://bsky.app)
 - App version: 1.68.0

**Suggested action**

- Replace the term "Benachrichtigungen" with the term "Mitteilungen" in the German translation, which is shorter, has a similar meaning and doesn't cause an overflow. (This also what Twitter did in their sidebar.)
- OR change the code for the sidebar to trim the term with "..." to fix the overflow.

**Comment by surfdude29** [comment]
I think this was fixed by #2805
