### ISSUE TITLE
Add app language selection to the signup/login screen

### ISSUE THREAD

**Issue by wtlgo** [bluesky-social/social-app#2801]
**Is your feature request related to a problem? Please describe.**

Currently, the only way to switch the language is when you're logged in, and you can't choose your language before having an account. This leads to the fact that some users aren't aware they can switch the app language at all. For example, there are several Japanese posts in circulation where Japanese users who know English translate all the labels on screenshots for ones who don't, even though the Japanese translation is already available.
Also, navigation to the language setting even when you're logged in isn't trivial if you don't speak English (I know because I tested it on my non-English speaking friends, and it's a separate issue in itself), so being able to switch the language before doing anything else on the platform might help users not deal with this problem as well.

**Describe the solution you'd like**

As stated in the title, just add an option to switch the language before joining the network.

**Describe alternatives you've considered**

I'm absolutely okay with English, this feature request isn't for me.

**Comment by mary-ext** [comment]
The app does try to use a locale matching your system language when available AFAICT, though it's very reasonable that it would be impeded by browser settings etc
