### ISSUE TITLE
Mobile (iOS) reply TextInput now cuts off display of text after line 4

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2825]
**Describe the bug**
Mobile only, and I have only tested iOS. When I input multiple lines of text, all text beyond line 4 is not visible.

**To Reproduce**

1. Reply to a post, write more than 4 lines.

**Expected behavior**

All lines of text should be visible.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/146130101/63872def-b073-4fe0-8430-0dffc8fae1be

**Details**

 - Platform: iOS
 - Platform version: 17.2.1
 - App version: Build version: 1.67.0 (6); Platform: ios

**Additional context**

I cannot always reproduce this!

I believe that my display zoom and text size are both set to default (middle)

**Comment by haileyok** [comment]
This is fixed in https://github.com/bluesky-social/social-app/pull/2764 but stuck in store review right now :( hopefully will be available sometime over the weekend, but anticipating Monday. Thanks!
