### ISSUE TITLE
Firefox: Previously clicking the Home icon might take you out of Bsky, as if user clicked browser's Home function. Very recently this also occurs on click of Notifications icon.

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2827]
**Describe the bug**
As I have seen @pfrazee mention in posts on Bksy, it is known that there is some weird bug with Firefox on desktop, where sometimes clicking Bsky's Home icon will make Bksy disappear, as if user pressed Alt-Home keys (PC) to go to the browser's home page. 

_This has just recently begun to happen when I click on the Bsky Notification icon._ I say this with ~80% confidence.

I raise this issue because maybe you could diff the recent changes to the Notifications click behaviour, and see if anything on your side has changed there. Maybe this could identify the root cause of the Home and Notifications issue.

**To Reproduce**

Cannot reproduce on-demand, this happens often, but only sometimes.

1. Use Firefox on desktop, go about your business interacting with Bsky
2. Click Home icon, or Notifications icon.
3. Bsky disappers, as if I pressed Alt-Home (PC) - this only happens sometimes

**Expected behavior**

This should not happen. I should either go to Bsky Home, or Bsky notifications, not Firefox home.

**Details**

 - Platform: Windows and MacOS, (I have reproduced on both OSes) - Firefox
 - Platform version: Firefox: 122.0.1 
 - App version: Build version: 1.68.0; Platform: web

**Additional context**

I can use browser Forward to get back to where I was. But it takes a lot of browser Forward clicking. So it really is like the history position was manipulated to the original state of the tab being opened or something? 

Sorry that I could not find a previously reported issue on this topic, I  might be bad at searching.

I realize that Firefox users are a tiny percentage, and this might be an upstream RN navigate issue, but I was hoping that this now occurring on click of Notifications might make it easier to figure out. Thanks!

**UPDATE:** I just caught this happening when pressing the browser Back button. Instead of going back 1 step in history, I was sent to browser Home. Again, was able to step all the way forward.

**Comment by MDrollette** [comment]
Im seeing the same behavior with Brave on MacOS.

related #1802 and #710

**Comment by mary-ext** [comment]
Yes, duplicate issue.

**Comment by adamatic-me** [comment]
This issue appears to be entire resolved now thanks to @SlickDomique.
