### ISSUE TITLE
What will happen to unused invite codes?

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#2836]
*subject*

**Comment by surfdude29** [comment]
I don't know if the offer is still valid, but this is what Mr Frazee said:

https://bsky.app/profile/pfrazee.com/post/3kkqyk2ehx22d

**Comment by natewrench** [comment]
convert them to checkmarks

**Comment by natewrench** [comment]
print em out and frame them or turn em into tokens jk

**Comment by Zero3K** [comment]
I am closing this since the UI for them has been removed.
