### ISSUE TITLE
Hover preview for accounts

### ISSUE THREAD

**Issue by BubiBalboa** [bluesky-social/social-app#2861]
**Is your feature request related to a problem? Please describe.**

On the web UI, when I'm reading a conversation I'd like to have a quick way to see whether I'm following an account or not and to have a preview of their bio.

**Describe the solution you'd like**

Hover preview cards i.e. hovering with the mouse cursor over a username brings up a card with the user's bio and the (un)follow button. 

**Describe alternatives you've considered**

Some other follow indicator that's always visible would also work, I guess. It would clutter the UI but might be a good option for the app and mobile view where hover preview isn't possible. 

**Additional context**

I think having as few barriers as possible to (un)following others is good for the users and the social network. Keeps it from getting stale. The bio preview helps to quickly gauge a users background while reading comments.

**Comment by surfdude29** [comment]
This has just been implemented in #3508, thanks @mary-ext and @estrattonbailey! 🙏

**Comment by BubiBalboa** [comment]
Fantastic! Thank you!
