### ISSUE TITLE
Link Card Excerpts Don't Display Curly Quotes Consistently

### ISSUE THREAD

**Issue by jasonmorehead** [bluesky-social/social-app#2877]
If you share a link on Bluesky, and the link card's excerpt/summary contains an encoded curly or "smart" quote, the quote is not displayed properly. Instead of seeing curly quotes, the Unicode decimal codes are displayed, including `&#8217;`, `&#8220;`, and `&#8221;`.

Curly quotes are displayed properly in the link card's title, however.

**To Reproduce**

Create a new post on Bluesky and share a link whose description (e.g., its "og:description" `<meta>` tag) contains encoded curly quotes.

**Expected behavior**

When sharing a link, I expect to see curly quotes rendered correctly in the excerpt/summary like they are in the title.

**Screenshots**

![bluesky-link-preview](https://github.com/bluesky-social/social-app/assets/1703762/da0c42d2-1e33-4724-9223-e9f7e6e24431)

**Details**

 - Platform: This happens on both the web UI as well as the Bluesky app.
 - Platform version: Build version 1.68.0

**Comment by Jacob2161** [comment]
This should be fixed as of a few minutes ago. Please re-open or file a new issue if there are other problems though. Thanks!

**Comment by jasonmorehead** [comment]
Thanks for the quick response.
