### ISSUE TITLE
follow button bug TOO BRIGHT

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#2895]
![image](https://github.com/bluesky-social/social-app/assets/66647238/61ac19b0-e44e-43b9-816f-861d30eb3ce1)

all platforms

problem: eyestrain

the follow button that now appears on posts in the comment section -  on darkmode is too bright

ideal solution: please make it darker

**Comment by ThatOneCalculator** [comment]
Now hear me out, I'm a sucker for gradients...

![image](https://github.com/bluesky-social/social-app/assets/44733677/f71b7555-4646-472c-a217-924523887ccc)

**Comment by ThatOneCalculator** [comment]
Also, text should be flex-aligned with the icon. The fact that both of our screenshots are unaligned in two different directions is kinda :grimacing:
