### ISSUE TITLE
Splash Screen Flash Bang in Dark Mode

### ISSUE THREAD

**Issue by parion** [bluesky-social/social-app#2900]
**Is your feature request related to a problem? Please describe.**

When opening the app from a new Android session in dark mode, the app will briefly show a white screen before showing the splash screen. From here, the butterfly animation expands, leading to another brief white flash. This occurs very briefly after the first white screen, making opening the app uncomfortable on the eyes at night. 

https://github.com/bluesky-social/social-app/assets/4733032/87caf033-4b4b-4887-afb1-885fb819e468

**Describe the solution you'd like**

To improve the user experience for dark users, the first flash should be eliminated, or replaced by a dark screen, and the white butterfly should be reconsidered to be something darker.

**Comment by wu-jiaxi** [comment]
Interesting, Ill see if I can get a fix in

**Comment by dolciss** [comment]
Hi, I was one of the ones whose eyes were hurting.
Perhaps #2892 and #2896 look like related improvements

**Comment by snaka** [comment]
I thought it was probably the same event as discussed in the following Issue.

- https://github.com/bluesky-social/social-app/issues/2292#issuecomment-1948787137

**Comment by mary-ext** [comment]
This is a duplicate issue and should be closed yeah.

**Comment by parion** [comment]
I've confirmed that, while the initial issue posed is for an earlier version of the splash screen, conversation has since been ongoing and the issue I posed is currently under investigation. Can be closed. Thanks y'all!
