### ISSUE TITLE
Posts sometimes cannot be tapped

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#2913]
**Describe the bug**

There are times where the app just doesn't let you tap on posts to view the thread

**To Reproduce**

N/A

Still working on a reproduction, this is *quite* hard to figure out.

**Expected behavior**

It should let you tap on posts.

**Screenshots**

N/A

**Details**

 - Platform: Android
 - Platform version: Android 13
 - App version: 1.68.0 (61)

**Additional context**

What I'm noticing is that this happens when the minimal shell gets half-way stuck, where the navbar becomes half-opaque.

![Screenshot_2024-02-18-09-05-33-23_cb2df8437d99d85560b8f74042fc78eb.jpg](https://github.com/bluesky-social/social-app/assets/148872143/b1331fde-b378-4174-b0fb-88745ba69b01)

When it's half-way stuck like that, it blocks taps on posts entirely. I've been digging at making it reproducible for days now but I just haven't been able to.

**Comment by haileyok** [comment]
Do you see any correlation between any of these?

- Number of feeds you've loaded on your home screen ("loaded" meaning swiped to that feed and let content load into it)
- Length of time you've been using the app before force quitting/OS terminating

I have a hunch this is related to a few performance issues we've found over the past week, but am not certain. I can't repro it myself on android devices but you're not the first person to bring it up.

**Comment by mary-ext** [comment]
I have 2 feeds pinned, but I usually only open 0-1 feed per session. I don't usually keep the app running in the background for too long.

What I'm planning to do is to just poke around with the minimal shell code and force it to get halfway stuck like that first.

**Comment by mary-ext** [comment]
Closing due to #3059, if it happens again after the update I'll reopen it.

**Comment by IArnaut2** [comment]
Did you block someone before that? I have the same issue after muting or blocking an account.
