### ISSUE TITLE
My Replies feed includes simple reposts, it shoudn't, should it?

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2954]
**Describe the bug**
When I click the Replies nav in the profile page, my simple reposts appear in the listing.

**To Reproduce**

1. Open your own profile
2. Click Replies
3. Note that even your simple (non-quote) reposts appear here.

**Expected behavior**

I believe that only posts with my replies should appear here. Correct?

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/146130101/baa4c310-e13c-4616-a8b6-78beab2d679b)

**Details**

 - Platform: desktop chrome windows, desktop firefox windows desktop safari macos, mobile iOS 
 - App version: Build version: 1.68.0; Platform: web,  1.68.0 (7) Platform: iOS

**Comment by mary-ext** [comment]
depends on which way we're going

- Twitter: replies tab shows reposts
- Mastodon: replies tab doesn't show reposts

**Comment by adamatic-me** [comment]
Hmm, so as it is currently: 

Posts = Posts + Reposts + Quote Reposts 

Replies =  Reposts + Quote Reposts + Replies

I would vote for Replies only showing Replies. As it is now, there is too much info shown redundantly in my opinion.

**Comment by adamatic-me** [comment]
Now that I have been living with Bsky more, the one thing that I would love to view when exploring another user's profile is a feed of everything aside from simple Reposts. Meaning, just their actual text contributions. So I would change my vote to [0], above.

**Comment by adamatic-me** [comment]
OK, maybe per usual I'm tripping, and annoying the heck out of y'all, but it appears that in my main Posts user feed, I see all my text contributions now.

Hey, that's pretty cool. Closing this issue.
