### ISSUE TITLE
Style issue: Language selector expand menu does not display text

### ISSUE THREAD

**Issue by mitian233** [bluesky-social/social-app#2963]
**Describe the bug**

Language selector expand menu does not display text

**To Reproduce**

1. Open the SplashScreen on PC

**Expected behavior**

I tried to modify its css to fix this issue

![image](https://github.com/bluesky-social/social-app/assets/13678847/8ffb1c2a-9662-4547-b46a-f0539d8a22cb)

**Screenshots**

Microsoft Edge (121.0.2277.128): 

![image](https://github.com/bluesky-social/social-app/assets/13678847/024a4d8a-ae72-4ef2-b9cf-646e98720d6f)

Firefox (122.0.1): 

![image](https://github.com/bluesky-social/social-app/assets/13678847/9cb51272-1157-4cb4-bfaa-91af7c558090)

**Details**

 - Platform: Desktop
 - Platform version: Microsoft Windows 11 Pro 10.0.22631 build 22631
 - App version: 1.68.0

**Additional context**

**Comment by mary-ext** [comment]
ref: #2952
