### ISSUE TITLE
Notifications on Android show with generic notification icon rather than "butterfly" logo

### ISSUE THREAD

**Issue by Bloonface** [bluesky-social/social-app#2983]
**Describe the bug**
It's hard to identify BlueSky notifications specifically from the notification bar because rather than using the "butterfly" logo, Bluesky notifications just use the generic Android system "circle" icon.

**To Reproduce**

1. Get a notification on Android.

**Expected behavior**

Notification appears with nice branding to allow user to identify Bluesky notifications at a glance.

**Screenshots**

Screenshot here: https://imgur.com/a/IlyQBCf

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: 1.68.0

**Comment by edo-bari-ikutsu** [comment]
I have opened the pull request https://github.com/bluesky-social/social-app/pull/3113 to fix this issue.

**Comment by haileyok** [comment]
Thank you @edo-bari-ikutsu! Merged this fix in.
