### ISSUE TITLE
Muting a word and using it in your own post hides the post entirely in the following feed

### ISSUE THREAD

**Issue by blowdart** [bluesky-social/social-app#3031]
**Describe the bug**

Creating a post containing a mute word from your own muted words list completely hides the post from yourself in the following feed

**To Reproduce**

Steps to reproduce the behaviour:

1. In muted words add ``PaulIsGinger``.
2. Create a post containing ``PaulIsGinger``, it can either be just the hashtag, or text and the hashtag, or the hashtag and text, or the hashtag surrounded by text.
3. Refresh your following timeline.
4. The post does not appear _at all_ in your following timeline, although it does appear in your profile, properly muted.

**Expected behaviour**

I would expect any post that I make, with a word I muted in the post to appear in the following timeline, like any other post I make.

**Details**

 - Platform: Desktop, iOS
 - Build version: 1.70.0; Platform: web

**Comment by mahak-dev** [comment]
I will do this task please assign me

**Comment by haileyok** [comment]
This is resolved in the upcoming version.
