### ISSUE TITLE
Don't parse unviewable characters like zwsp in hashtags

### ISSUE THREAD

**Issue by blowdart** [bluesky-social/social-app#3036]
**Describe the bug**
You can use zero width joiners in hashtags, which, whilst not displayed, do separate your hashtag from a hashtag without them, causing hilarity and confusion

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://zerowidthspace.me/ 
2. Create a hashtag like #hashtag and past in ZWSP where you like
3. Click on the hashtag in the post
4. Giggle at the search results

**Expected behaviour**

Non-printable characters should be stripped in hashtag parsing.

**Details**

Platform: Desktop, iOS
Build version: 1.70.0; Platform: web

**Comment by mary-ext** [comment]
Fixed by https://github.com/bluesky-social/social-app/pull/3063
