### ISSUE TITLE
Latest post/posts aren't visible while searching for a part of word/non word

### ISSUE THREAD

**Issue by RDxR10** [bluesky-social/social-app#3048]
REF: [Issue #581](https://github.com/bluesky-social/indigo/issues/581#issuecomment-1950262492)

If I search for something like "xkc" i.e https://bsky.app/search?q=xkc I get older posts having "xkc". However, the expectation is to get posts in the order of "new" -> "old". As in the newer ones at the top of the feed (Check out the link mentioned above).

**Comment by Zero3K** [comment]
I already made a ticket about it. It is at https://github.com/bluesky-social/social-app/issues/3034.
