### ISSUE TITLE
Hashtags that include numbers don't always work?

### ISSUE THREAD

**Issue by inkygirl** [bluesky-social/social-app#3067]
Yay for hashtags on Bluesky! I've noticed they don't always work, however.

Example: #3tofollow

My first post in this thread using the hashtag DID have a working/clickable hashtag:
https://bsky.app/profile/debbieohi.com/post/3kmlhbzcyg62j

Further down in the thread, however, you'll see that the hashtag stops working (isn't clickable).

Also, I've noticed if I *do* click on the hashtag from the first post, it does NOT show all posts on Bluesky with that hashtag.

As proof, see the custom feed I created via Skyfeed to show #3tofollow posts:
https://bsky.app/profile/did:plc:5amsebbtpuqieuxuqadmmvcv/feed/aaaez5gf22o2e

One user helped me test this and concluded that having a number in the post is the problem:
https://bsky.app/profile/thebarbarienne.bsky.social/post/3kmliwe5so52a

(but this doesn't explain why my first post DOES have a clickable #3tofollow hashtag).
<img width="848" alt="Screenshot 2024-03-01 at 11 02 29 AM" src="https://github.com/bluesky-social/social-app/assets/111646238/1122a3ac-afd1-4cfe-884a-27882b5754ba">

Debbie

**Comment by inkygirl** [comment]
And here's a screenshot showing an example of a reply to the thread shown above. 

#3tofollow hashtag IS clickable in the first post, but not in replies.

<img width="755" alt="Screenshot 2024-03-01 at 11 03 30 AM" src="https://github.com/bluesky-social/social-app/assets/111646238/3c263a78-d4dd-4e36-a09b-04e3af10c5f6">

**Comment by BookshopLeslie** [comment]
I tried to click this hashtag earlier and it didn’t work for me, either.

**Comment by mary-ext** [comment]
Fixed by https://github.com/bluesky-social/social-app/pull/3055

It should be following Twitter's hashtags in the next app update: A hashtag cannot be just numbers, but can start, end, or contain numbers.
