### ISSUE TITLE
Tried to mute all hashtags

### ISSUE THREAD

**Issue by n0vedad** [bluesky-social/social-app#3073]
**Describe the bug**
I tried muting ALL hashtags by adding # to muted words & tags but it shows strange behavior. 

First it doesn't display correctly as a muted string and then it hides random posts that don't contain a #. Adding # to mute only in tags has no effect 

**To Reproduce**

1. Add # to mutelist for muting in text & tags
2. Watch your timeline

**Expected behavior**

Should (only) mute all text (and tags) starting with # 

**Screenshots**

added # to mutelist and it is not displayed as a muted string

<img width="440" alt="ac1" src="https://github.com/bluesky-social/social-app/assets/118539492/d787232e-2acd-4d10-af18-08174a6ef1b9">

example of shown behavior

<img width="381" alt="ac2" src="https://github.com/bluesky-social/social-app/assets/118539492/51b72449-6ec1-41d9-8caa-fb57f2e67953">

Also all posts that contain a link card or a quote post are hidden now

**Details**

 - Platform: Desktop, Windows 11 23H2
 - Platform version: Firefox 123.0
 - App version: 1.70

**Comment by mary-ext** [comment]
Fixed by https://github.com/bluesky-social/social-app/pull/3055
