### ISSUE TITLE
Add "follows you" tag to accounts that follow you

### ISSUE THREAD

**Issue by corrupteddrive** [bluesky-social/social-app#3078]
**Is your feature request related to a problem? Please describe.**

Not really a problem but it would be much more convenient to see if an account follows you just by clicking on their profile instead of scrolling through your followers list.

**Describe the solution you'd like**

A little tag beside the handle would be nice, kind of like on Twitter.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Hanaffi** [comment]
@corrupteddrive Can you assign it to me please?

**Comment by mahak-dev** [comment]
I will do this task could you please assign me

**Comment by PSingletary** [comment]
I believe this exists.

**Comment by haileyok** [comment]
This should exist, and we've also added more social proof info to bios. Feel free to open though if wrong.
