### ISSUE TITLE
Have a "followed by" list on account profiles

### ISSUE THREAD

**Issue by corrupteddrive** [bluesky-social/social-app#3079]
**Is your feature request related to a problem? Please describe.**

Not a problem but it would be nice to be able to see which accounts you follow follow a certain account when you click on their profile.

**Describe the solution you'd like**

A "followed by" list similar to Twitter on account pages

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by mary-ext** [comment]
duplicate of #1610

**Comment by haileyok** [comment]
Yea we've had some discussions about this recently. Closing in favor of #1610 but it's on the radar!
