### ISSUE TITLE
Onboarding UI

### ISSUE THREAD

**Issue by tdhuan** [bluesky-social/social-app#3080]
**Describe the bug**

**To Reproduce**

1. Sign up new account

**Expected behavior**

**Screenshots**

<img src="https://github.com/bluesky-social/social-app/assets/35454344/98301ef9-ba14-42e7-a029-4f83651de409" width="400"/>

**Details**

 - Platform: Android
 - Platform version: Android 10
 - App version: 1.70.0

**Additional context**

**Comment by haileyok** [comment]
Just merged in a fix for this. Thank you!

https://github.com/bluesky-social/social-app/pull/3176
