### ISSUE TITLE
Make tags in profile descriptions clickable

### ISSUE THREAD

**Issue by kawadah** [bluesky-social/social-app#3081]
**Is your feature request related to a problem? Please describe.**

Tags (hashtags) in profile descriptions (BIOs) are not clickable.

![Screenshot 2024-03-03 at 11 52 54](https://github.com/bluesky-social/social-app/assets/45890038/64b7ec05-70f4-47f6-b5e6-8a1963a239ab)

**Describe the solution you'd like**

Parse tags and highlight them just like links and mentions.
When a tag is clicked, it should behave the same way as when you click a tag in a post (Show menu).

![Screenshot 2024-03-03 at 11 51 22](https://github.com/bluesky-social/social-app/assets/45890038/4ff6eeed-3dcb-432e-b644-bed44f9ec7cb)

Links and mentions in profile descriptions are already highlighted, so it would be natural to display tags as well.

**Describe alternatives you've considered**

I've considered opening an issue in [atproto](https://github.com/bluesky-social/atproto). Currently profile descriptions are stored as a single `string`, but I think it's more secure to store profile description facets on the server.

But links and mentions are currently parsed on the client, so I guess it's best to handle tags similarly.

**Additional context**

Related:
- https://github.com/bluesky-social/atproto/issues/1227
- #848
- #2968

**Comment by mary-ext** [comment]
Likely it's because it's using a different RichText component atm, so even if `descriptionFacets` were to be added it still wouldn't show the tags, it *is* being parsed however.

**Comment by kawadah** [comment]
@mary-ext

It might be because displaying tags with the RichText component is disabled by default right now. 

I'll see if I can take a crack at it today.
