### ISSUE TITLE
Add 'infinite' scroll to long threads

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#3083]
**Is your feature request related to a problem? Please describe.**

Most lists in the UI will automatically load the next page when you reach the bottom - threads are unique in that they stop with a 'Load more posts' button.

**Describe the solution you'd like**

The next page should automatically load as you scroll down.

**Describe alternatives you've considered**

This is an alternative to current behaviour. Another approach would be to load everything progressively, so it loads instead of waiting for scroll - this could be combined to improve the responsiveness of the page: initial load 50, display, immediately load and display next 50-200, stop loading and wait for scroll to begin.

**Comment by haileyok** [comment]
Closing, think we did this a while back. Load more shouldn't be a thing now. Thanks.
