### ISSUE TITLE
Android hashtag modal shows wrong thing

### ISSUE THREAD

**Issue by corn-flour** [bluesky-social/social-app#3130]
**Describe the bug**
On Android, after updating the app to 1.71, the first 2 entries of the hashtag modal (when tapping a hashtag) shows some ids instead of the "see \#hashtag posts" and "see \#hashtag posts by user".
It works fine on web.

**To Reproduce**

1. update the app to 1.71
2. find a post with a hashtag and tap on it

**Expected behavior**

Proper text is shown for these entries instead

**Screenshots**
![Screenshot_20240306-113458.png](https://github.com/bluesky-social/social-app/assets/26082352/9c2e5feb-6d4c-4822-a3dc-364387259d82)

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: 1.71.0

**Comment by aliceisjustplaying** [comment]
Can repro. This is fascinating.

**Comment by aliceisjustplaying** [comment]
Even more fascinating that I can't repro it in the emulator, only on my device. Hey @corn-flour what's your phone are are you running LineageOS by some chance?

**Comment by surfdude29** [comment]
FYI there are multiple reports of this in the 1.71 thread too:

https://bsky.app/profile/dlvienna.bsky.social/post/3kn2lj65ns22j
https://bsky.app/profile/aenigmea.bsky.social/post/3kn4zkuruv22g
https://bsky.app/profile/schnauzerface.bsky.social/post/3kn2fpk5r5k2f
https://bsky.app/profile/bigbamboo.bsky.social/post/3kn2fw2x3v22n
https://bsky.app/profile/henkbulder.nl/post/3kn2foafs6k2t
https://bsky.app/profile/therealjimsanto.bsky.social/post/3kn2l3dlci22r
https://bsky.app/profile/beecham.bsky.social/post/3kn2lgjrbol2g
https://bsky.app/profile/ivanbea.bsky.social/post/3kn2gnyty2s2z
https://bsky.app/profile/merafera86.bsky.social/post/3kn2yec2cj22s
https://bsky.app/profile/maikel.dev/post/3kn2rr6bkfk2i

**Comment by corn-flour** [comment]
> Even more fascinating that I can't repro it in the emulator, only on my device. Hey @corn-flour what's your phone and are you running LineageOS by some chance?

My phone is Pixel 6 running Android 14, not LineageOS

**Comment by haileyok** [comment]
Will be fixed this week, was just a bit of a mistake when extracting/compiling the translations.
