### ISSUE TITLE
Pages with URL-encoded characters or non-US-ASCII characters in the path will result in an error

### ISSUE THREAD

**Issue by tkusano** [bluesky-social/social-app#3137]
**Describe the bug**

When clicking on a hashtag that contains non-US-ASCII characters in a post, the browser is directed to bsky.app/hashtag/tag and the browser displays the hashtag page containing that tag. However, when the page is reloaded, an error occurs.

URLs containing percent-encoded strings will also result in an error; profile pages containing percent-encoded colons in the DID will also result in an error.

**To Reproduce**

1. Go to https://bsky.app/profile/tkusano.jp/post/3kn33nqluls2z and click on '#Français'.
2. Select  "See #Français posts."
3. View posts with #Français
4. Click the reload button on your browser to see the error.

I created the test page with direct links.

-> https://tkusano.github.io/test/bluesky-url-test.html 

**Expected behavior****Details**

 - Platform: Firefox 123.0.1 and Chrome 122.0.6261.112
 - Platform version: Windows 11, iOS 17.4
 - App version: Bluesky 1.71.0

**Comment by haileyok** [comment]
Thanks, just merged in the fix for it. This one was one me 🫣

**Comment by tkusano** [comment]
I checked on localhost and confirmed that the problem with the hashtag has been fixed. Thank you.
