### ISSUE TITLE
iOS badge notification for new followers not showing username

### ISSUE THREAD

**Issue by veekaybee** [bluesky-social/social-app#3169]
**Describe the bug**
iOS badge notifications for new followers not showing the username in the notification anymore, only that "X has followed you', where "X" is a blank string. 

**To Reproduce**

1. Create a new test account or trigger a follow from a new test account
2. Trigger iOS notification
3. Check notification text (I'd assume it gets rendered [from here)](https://github.com/bluesky-social/social-app/blob/596e744d4177d3be6defeef68f202a70baaf6e37/src/view/com/notifications/FeedItem.tsx#L166)

**Expected behavior**

Expect to see the user handle in the notification. 

**Screenshots**
Unfortunately haven't been able to grab one yet as not every follow triggers a notification :\ . 

**Details**

 - Platform:  iOS
 - Platform version: 17.3.1
 - App version: 1.71.0(45)

**Additional context**

**Comment by veekaybee** [comment]
Screenshot: 
![IMAGE 2024-03-11 11:42:36](https://github.com/bluesky-social/social-app/assets/3837836/7265a82e-db77-404c-a9ef-50615e4f821d)

**Comment by haileyok** [comment]
Hmm, this is happening multiple times or did it just happen once? It's possible a user or two has some strange characters in their name that are breaking this, but if it's happening every time that would be a problem!

**Comment by veekaybee** [comment]
Yup, this has been happening consistently for every follower notification since this weekend.

**Comment by haileyok** [comment]
Okay thanks! Forwarded it over to someone who can take a look.

**Comment by haileyok** [comment]
Okay, we got a fix made for it. Should make it up soon. Thanks again for the report!

**Comment by veekaybee** [comment]
woohoo thanks!

**Comment by veekaybee** [comment]
what was the code issue if you can share?
