### ISSUE TITLE
Links to feed and list author are being treated as misleading on Android app 

### ISSUE THREAD

**Issue by wire2c7** [bluesky-social/social-app#3171]
**Describe the bug**
On Android app, links to the author of a feed and a list is displayed "Potentially Misleading Link" and do not take you to the author's profile page.

**To Reproduce**

1. Open a feed or a list page.
2. Tap the author's handle following "by" under the feed (list) name. Also, switch to the "About" tab and do the same for the link following "Created by".

**Expected behavior**

Tapping the handle will redirect you to the author's profile page without the "Potentially Misleading Link".

**Screenshots**

![Screenshot_20240312-013959](https://github.com/bluesky-social/social-app/assets/51051751/b622f93a-75f6-49ca-86f8-b64aac973504)

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: 1.71.0

**Comment by haileyok** [comment]
Thanks, this should be fixed this week when we release the update this week!
