### ISSUE TITLE
"Load failed" message prefixed with "TypeError," could be friendlier

### ISSUE THREAD

**Issue by chriszs** [bluesky-social/social-app#3215]
**Describe the bug**
Sometimes I get a "TypeError: Load failed" error in place of my timeline, which I assume is when the server is down or connectivity fails. "TypeError" seems like a internal implementation detail that could be hidden in favor of a user-friendlier message, if this is going to be an error that communicates to users a status issue on a semi-frequent basis.

**To Reproduce**

1. Wait until the server fails
2. Try accessing the timeline

**Expected behavior**

This could be better phrased for user consumption, e.g. something like "Sorry, we failed to load [your timeline]. Please wait, [check the status] [and/or] try again."

**Screenshots**

<img width="642" alt="Screenshot 2024-03-15 at 4 17 02 PM" src="https://github.com/bluesky-social/social-app/assets/1103467/8b74d745-83c3-46b4-bbbe-8023414ce0c8">

**Details**

 - Platform: desktop web Safari Mac
 - App version: 1.72.0

**Comment by haileyok** [comment]
Nice. I've been going through and cleaning up some of these, will add it to the list. Cheers.
