### ISSUE TITLE
Lists and Posts are swapped in the UI for mod services

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#3235]
**Describe the bug**

Posts appear under Lists, Lists appear under Posts when viewing a mod service e.g. https://bsky.app/profile/aegis.blue

**To Reproduce**

1. Visit https://bsky.app/profile/aegis.blue 
2. Click Posts, see lists
3. Click Lists, see posts

**Expected behavior**

2. Click Posts, see posts
3. Click Lists, see lists

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/114112113/18df861a-2afb-4c4f-9cc6-c62ead788ba9)
![image](https://github.com/bluesky-social/social-app/assets/114112113/6db2ad87-aa8c-4355-a44c-b5070776c71d)

**Details**

 - Platform: Web
 - Platform version: Chrome Win 11
 - App version: 1.73.0

**Additional context**

Replies work, as do Labels

**Comment by haileyok** [comment]
👍 Fixed now in main.
