### ISSUE TITLE
Web quote composer exits without prompt by clicking the quoted post in the composer

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#3263]
**Describe the bug**
Extremely wordy title, sorry, but on web if you have a quote post that you are composing and you happen to accidentally click the quoted post, you will navigate to the quoted post which discards the draft that you were typing without even a confirmation. On mobile, tapping does not do this.

**To Reproduce**

1. Draft a quote any post on web
2. Click the quote in the composer
3. Poof, your draft is gone

**Expected behavior**

I expect this to not happen. If anything, I'd expect it to behave like with replies where clicking/tapping expands, but I don't think quotes cut off at all do they? Either way, not losing the draft. Now I have to retype a banger.

**Screenshots**

**Details**

 - Platform: Chromium Web
 - Platform version: Yes
 - App version: Yes

**Additional context**

**Comment by haileyok** [comment]
Fixed 👍

**Comment by Juicysteak117** [comment]
Thank you as always for your quickness, Hailey!
