### ISSUE TITLE
Identity Unknown upon logging in

### ISSUE THREAD

**Issue by TawayDev** [bluesky-social/social-app#3308]
**Describe the bug**
When i log in it does not load anything and displays a red bar saying "identity unknown". I can log in the app but it does not display any page content, my account or anything.

**To Reproduce**

1. Log in

**Expected behavior**

Being able to log into my account and use the app.

**Screenshots**
iOS:
![image](https://github.com/bluesky-social/social-app/assets/44374628/c265b674-9658-4cbb-b664-4147b6b7da6f)
Web:
![image](https://github.com/bluesky-social/social-app/assets/44374628/39a35eac-a20d-46da-8225-0dae718b5df8)

**Details**

 - Platform: iOS & Web
 - App version: 1.7.3

**Comment by hellmrf** [comment]
Can't reproduce.

**Comment by bnewbold** [comment]
Hi @TawayDev, sorry you are seeing that. Can you share some additional information to help us debug?

- what is your account handle (and/or DID if you know that)?
- are you on a self-hosted PDS or the Bluesky (`*.bsky.social`) PDS service? if self-hosted, did you migrate the account?
- roughly when did you create your account? did you change handles recently?
- have you done any DID operations using the API directly? (if you aren't sure, the answer is probably "no")

**Comment by TawayDev** [comment]
Hi @bnewbold, sorry for the late reply. I've figured it out. I viewed my account without logging in and it said `invalid handle` because i'm using my own domain so i changed it back to `.bsky.social` and then again to my own and it fixed the login issue. In console when the issue happened it just wrote `{"error":"AuthMissing","message":"Authentication Required"}`
