### ISSUE TITLE
Content filter label descriptions are unreadable in Ukrainian localisation on some iPhones

### ISSUE THREAD

**Issue by surfdude29** [bluesky-social/social-app#3312]
**Describe the bug**

On some iPhones (I can't test on one with a larger screen) when the app language is set to Ukrainian the content filter label descriptions are unreadable.

**To Reproduce**

1. Set App Language to Ukrainian.
2. Open Moderation settings and scroll down.
3. Try to read the label descriptions for Pornography, Sexually Suggestive etc.

**Expected behavior**

The label descriptions can be read (in English for now, I know).

**Screenshots**

![IMG_9599](https://github.com/bluesky-social/social-app/assets/149612116/298db488-6bed-4e56-a947-92a5e15145ab)

**Details**

 - Platform: iPhone 7 (and will be the same on iPhone 8, iPhone SE 1st, 2nd and 3rd gen)
 - Platform version: 15.8.2
 - App version: 1.73

**Additional context**

I don't know if this approach would be feasible, but perhaps if the translated versions of **Show**, **Warn** and **Hide** in a certain language take up more than a set percentage of screen width, those toggle switches could be wrapped onto a new line? This would mean it would only take up more space for languages where this is needed, and not for languages where it isn't (like English, obviously, but others too).

**Comment by surfdude29** [comment]
And they're not very easy to read in the Indonesian localisation:

![IMG_9644](https://github.com/bluesky-social/social-app/assets/149612116/907b2717-2960-431c-8127-a099247911e1)

**Comment by haileyok** [comment]
Should be fixed thanks to https://github.com/bluesky-social/social-app/pull/3296 🙏 Thank you!

**Comment by surfdude29** [comment]
Great, thanks! :)
