### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by ljstella** [bluesky-social/social-app#3319]
**Describe the bug**
The iOS app appears to crash when opened. 

**To Reproduce**

1. Install Build version: 1.73.0 (72); Platform: ios
2. ????
3. Profit?

**Expected behavior**

The app should open instead of crashing?

**Screenshots**

https://github.com/bluesky-social/social-app/assets/1413514/fc6aa41c-e2a2-4556-b107-b6b752328248

**Details**

 - Platform: iOS 
 - Platform version: 17.4
 - App version: 1.73.0 (72)

**Additional context**

This doesn't happen every time I open the app. But probably 1 in 3 times I try to open, it will refuse to open as depicted in the video until I just... Wait? As far as I can tell there is no rhyme or reason to why.

**Comment by haileyok** [comment]
Feeling confident that this is fixed here https://github.com/bluesky-social/social-app/pull/3315

We're cutting a new release, so once that is available can you please report back if this is/isn't fixed? 🙏

**Comment by ljstella** [comment]
> Feeling confident that this is fixed here #3315
> 
> We're cutting a new release, so once that is available can you please report back if this is/isn't fixed? 🙏

Will do!

**Comment by jslow421** [comment]
Not the reporter, but this seems to be resolved.

**Comment by ljstella** [comment]
Yup, update I pulled this morning seems to resolve this.

Thanks @haileyok!
