### ISSUE TITLE
Open external links in a Custom Tab on Android

### ISSUE THREAD

**Issue by NoahAndrews** [bluesky-social/social-app#3320]
**Is your feature request related to a problem? Please describe.**

It's annoying to click on a link and be switched out of the Bluesky app entirely. It also makes it much easier to end up accidentally leaving a tab open in my main web browser, which I'm trying to de-clutter.

**Describe the solution you'd like**

Open links using [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs). It appears that Expo already has a module for this, that also uses a approximate iOS equivalent: https://docs.expo.dev/versions/latest/sdk/webbrowser/

**Describe alternatives you've considered**

You could also use a WebView, but then users wouldn't be logged into sites and such.

**Comment by mary-ext** [comment]
This is already a solved problem, "Open links with in-app browser" opens links with CCT.
![Screenshot_2024-03-22-04-41-45-72_cb2df8437d99d85560b8f74042fc78eb.jpg](https://github.com/bluesky-social/social-app/assets/148872143/3fa1a0d9-f104-4c87-8565-2e7e7f5ee564)

**Comment by NoahAndrews** [comment]
Awesome, thanks for the pointer. I'll leave this open in case the team wants to consider making it the default.

**Comment by mary-ext** [comment]
Not necessarily, the app asks you if you want to open links in-app when you tap on a link for the first time

**Comment by NoahAndrews** [comment]
Huh, is that a new-ish feature?
