### ISSUE TITLE
Repeated Crashes After Tapping Push Notification

### ISSUE THREAD

**Issue by gooop** [bluesky-social/social-app#3347]
**Describe the bug**
After tapping a push notification, the app attempted to open, but immediately crashed (closed, no longer in recent apps, back to home screen). Any subsequent attempt to open the app also failed (crashed after about .25 seconds on the opening splash screen).

**To Reproduce**

1. From the lock screen on an iPhone, tap a push notification that someone liked your reply.
2. Crash manifests
3. Attempt to open app
4. Crash manifests

**Expected behavior**

I expected the app to open to my notifications pane.

**Screenshots**

Here's a screenshot of my notifications pane.
![IMG_0727](https://github.com/bluesky-social/social-app/assets/56046935/8dd3ee15-0fae-4887-b853-e16889af437e)
.

**Details**

 - Platform: iOS
 - Platform version: iOS 17.4, iPhone 15 Pro Max
 - App version: Build version: 1.73.0 (72); Platform: ios

**Additional context**

I found a workaround. I went to the bluesky settings page (in the settings app on iOS), disabled background refresh, and tried to open the app. The app took slightly longer to crash, displayed a notification badge (which was not present after the initial tap of the push notification) then was able to open again. I have since enabled background refresh and can open the app normally.

**Comment by surfdude29** [comment]
That's good that you found a workaround. Also, version 1.74 has just been released which contains a fix for possible startup crashes so you might want to update to that.

**Comment by gooop** [comment]
Thanks! Updated. I'll update this issue if I see it happen again.

**Comment by gaearon** [comment]
Should be fixed! Sorry for the trouble.
