### ISSUE TITLE
Contractually require @pfraze to change his Bsky username to "Paulo Gato Irresistível"

### ISSUE THREAD

**Issue by consumer451** [bluesky-social/social-app#3443]
**Is your feature request related to a problem? Please describe.**

This is what the people want.

**Describe the solution you'd like**

Addressing what the sexy people want.

**Describe alternatives you've considered**

An alternative super sexy name in Portuguese.

**Additional context**

Brasil!

**Comment by haileyok** [comment]
Thanks for the request! We've implemented this and it should be available now!

![Screenshot 2024-04-07 at 10 59 02 PM](https://github.com/bluesky-social/social-app/assets/153161762/41ced51d-ec76-41aa-9b0d-da960385bf3a)

**Comment by consumer451** [comment]
Amazing.
