### ISSUE TITLE
Removing sharing dialog warning when sharing your own post.

### ISSUE THREAD

**Issue by blowdart** [bluesky-social/social-app#3453]
![image](https://github.com/bluesky-social/social-app/assets/796298/57654b8a-9321-4a3f-b658-9d603a451d6a)

**Is your feature request related to a problem? Please describe.**

I am frustrated to see this dialog every time I go to share my own post. It's my post, I know I set that flag.

**Describe the solution you'd like**

Don't show the warning when a user is generating links for their own posts.

**Comment by heikadog** [comment]
furthermore, maybe it'd be good to have an option to turn off the warning? just a thought

**Comment by blowdart** [comment]
Closing as was fixed in #4495
