### ISSUE TITLE
Add variables to interface strings to support more languages 

### ISSUE THREAD

**Issue by Aonghuso** [bluesky-social/social-app#3481]
Irish has recently been added as an interface language. However, because Irish has verb subject object word order, some of the translations are awkward or just plain wrong because parts of the string are not parts of the message string. 

For example 
#: src/view/com/notifications/FeedItem.tsx:170
msgid "liked your custom feed"
msgstr "a mhol do shainfhotha"

#: src/view/com/notifications/FeedItem.tsx:155
msgid "liked your post"
msgstr "a mhol do phostáil" 

The subject is not part of the the string to be localised. 

This leads to "X a mhol do phostáil" 

But the idiomatic way to say this would be Mhol X do phostáil. 

Using a placeholder for the subject would permit this.

**Comment by kscanne** [comment]
As one of the contributors to the Irish localization, I can confirm that this is a significant problem. There is no way of rephrasing the translation to make it not completely awkward/ungrammatical.

**Comment by quiple** [comment]
PRs related to this issue: #3911, #3912, #3948

**Comment by kscanne** [comment]
This appears to be fixed in release 1.94; we now have the variables we need to provide correct translations.  Thanks to whoever handled this!

**Comment by surfdude29** [comment]
> Thanks to whoever handled this!

Credit to @quiple and @estrattonbailey for fixing this in #5550 🙏
