### ISSUE TITLE
Ability to turn off tactile responses in the app.

### ISSUE THREAD

**Issue by mattisflones** [bluesky-social/social-app#3484]
The Android Bluesky App now has tactile feedback on likes.

The tactile responses cannot be turned off through Android like for example notifications.

I suggest that an ability to turn this functionality off is added as we are used to from other apps.

Android app v 1.76.0 (102, production)

**Comment by haileyok** [comment]
Heh, I literally just did this 😅

https://github.com/bluesky-social/social-app/pull/3482

**Comment by mattisflones** [comment]
Brilliant!
