### ISSUE TITLE
vibration when pressing "Like" (♥)

### ISSUE THREAD

**Issue by Nyx70** [bluesky-social/social-app#3536]
After updating the Bluesky app (Android), my smartphone vibrates every time I press "Like (♥)" on a post. This behavior has been observed not just by me.
This issue occurs only with the Bluesky app.
Bug?

Platform: Android
App version: 1.76.0

**Comment by surfdude29** [comment]
This has been fixed in #3482 and will be available in the next release in the next week or so.

**Comment by haileyok** [comment]
should be early this coming week!

**Comment by mary-ext** [comment]
This is fixed now

**Comment by gaearon** [comment]
Fixed in 1.77
