### ISSUE TITLE
Erratic scroll on the profile page

### ISSUE THREAD

**Issue by Arhan13** [bluesky-social/social-app#3611]
**Describe the bug**
While scrolling on the web app (For example - https://bsky.app/profile/effinbirds.com) the page gets looped into showing a set of posts

**To Reproduce**

1. Go to https://bsky.app/profile/effinbirds.com (on either posts or media tabs)
2. Scroll down on the page and a set of posts start to loop

**Expected behavior**
1. While scrolling down on the page the the posts should load gradually
2. New posts should only be loaded when the last post is reached (infinite scrolling)
3. Scrolling down should not be Erratic, but should be continuous based on the user scroll feedback

**Details**

 - Platform: desktop chrome mac(arm64)
 - Platform version: Version 111.0.5563.64 (Official Build) (arm64)
 
 **Video**
 https://github.com/bluesky-social/social-app/assets/60483503/2dc48370-3bf7-4ba8-9e9b-c078c9d28719

**Comment by Arhan13** [comment]
> **Describe the bug** While scrolling on the web app (For example - https://bsky.app/profile/effinbirds.com) the page gets looped into showing a set of posts
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to https://bsky.app/profile/effinbirds.com (on either posts or media tabs)
> 2. Scroll down on the page and a set of posts start to loop
> 
> **Expected behavior**
> 
> 1. While scrolling down on the page the the posts should load gradually
> 2. New posts should only be loaded when the last post is reached (infinite scrolling)
> 3. Scrolling down should not be Erratic, but should be continuous based on the user scroll feedback
> 
> **Details**
> 
> * Platform: desktop chrome mac(arm64)
> * Platform version: Version 111.0.5563.64 (Official Build) (arm64)
> 
> **Video**

[video](https://github.com/bluesky-social/social-app/assets/60483503/2dc48370-3bf7-4ba8-9e9b-c078c9d28719
)

**Comment by Burstaholic** [comment]
This looks like what I experience on my 1366x768 Chromebook - it may be certain window sizes cause this problem

**Comment by AngeloBonini** [comment]
update on my end, I havent been able to reproduce it, tried on 1440X872 chrome

**Comment by SpiritAxolotl** [comment]
I'm also having this issue. Chromium 116.0
I'll look into upgrading to fix it though

**Comment by haileyok** [comment]
Hey all! This might have gotten fixed, see https://github.com/bluesky-social/social-app/issues/675. Will leave open for a bit for anyone to hopefully reply with a status. Thanks for being patient!

**Comment by Banderi** [comment]
The abovementioned #675 is unrelated, however I think this got fixed along the road by some site updates. I have not cleared my cache, yet on m Chromium v. 114 the erratic scrolling bug is, at least at a cursory check, no longer present 👍

**Comment by sylv256** [comment]
I've been experiencing this exact bug with my Bookmarks, but not profiles.

**Comment by 2004seraph** [comment]
I get this issue on the android app

**Comment by sylv256** [comment]
Yep, same here. The website is fine, but the android app bugs out.

**Comment by AngeloBonini** [comment]
shall reopen this then?

**Comment by 2004seraph** [comment]
Maybe?
