### ISSUE TITLE
On web - embeds are re-added after being removed

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#3665]
**Describe the bug**
If I remove an embed in the composer, it is re-added as soon as I resume typing

**To Reproduce**

1. Create a post with a URL in it, wait for the embed to appear
2. Remove the embed
3. Add text to the composer

**Expected behavior**

Embeds should stay gone when removed

**Comment by Bossett** [comment]
Chrome 124 on Win 10 - seems to be after every 'word'.

https://github.com/bluesky-social/social-app/assets/114112113/745117dc-1621-4ebc-8157-0e744f1db143

**Comment by pfrazee** [comment]
Very much appreciate it. We think we've found a fix.
