### ISSUE TITLE
search field cursor/highlighting on web version

### ISSUE THREAD

**Issue by jonolds** [bluesky-social/social-app#3676]
On the web version:

1. Search (and submit) a term
2. Click on the search box
3. the box highlights the entire word (correct, imo) to indicate it's prepared to overwrite
4. Type a new letter
5. Highlight disappears, cursor is at the end, and it appends instead of overwriting.

**Comment by gaearon** [comment]
Yup will be fixed by https://github.com/bluesky-social/social-app/pull/3663.
