### ISSUE TITLE
when root post deleted, cannot view replies

### ISSUE THREAD

**Issue by ssltny** [bluesky-social/social-app#3686]
**Describe the bug**

when root post of a thread is deleted, users replied to that post cannot view their replies on profile page replies section/tab.

**To Reproduce**

1. post something (root post).
2. reply to root post.
3. delete root post.
4. try to view reply on profile page replies section or on following feed.

**Expected behavior**

to view replies on profile page replies section even if root post is deleted.

**Screenshots**

**Details**

 - Platform: 
 - Platform version:
 - App version:

**Additional context**

i have used a new account to observe postcount. i followed reproduction steps. counter was 2 before i delete root post. after the deletion counter decreased to 1 but i couldn't view the reply. not shown replies are visible on graysky app.

**Comment by gaearon** [comment]
Not able to reproduce.

Reply to own deleted post: https://bsky.app/profile/dansshadow2.bsky.social/post/3kqvonlrmmk2j

Reply to another account's deleted post: https://bsky.app/profile/dansshadow2.bsky.social/post/3kqvolk3ad42s

Both appear in the Replies tab: https://bsky.app/profile/dansshadow2.bsky.social

Can you provide more info (eg specific URLs)? Thanks.

**Comment by gaearon** [comment]
Ahh interesting. This might be related to what @devinivy was fixing last week. Thanks for confirming.
