### ISSUE TITLE
Clicking on an entry in the recent searches list doesn't work

### ISSUE THREAD

**Issue by Zero3K** [bluesky-social/social-app#3700]
When I click on an entry in the recent searches list, I just get sent back to the search box with the suggested followers underneath instead of searching for it.

**Comment by surfdude29** [comment]
Which platform are you seeing this on? I'm unable to reproduce it.

**Comment by Zero3K** [comment]
Via the website.

**Comment by Zero3K** [comment]
Any news?

**Comment by Zero3K** [comment]
I can confirm that it has been fixed. Thanks to whoever committed the fix.
