### ISSUE TITLE
Visual issues with short dates over a year old

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#3717]
**Describe the bug**

The short date format is displayed with insufficient right padding when quoted on iOS (i.e. when posts are old):

![image](https://github.com/bluesky-social/social-app/assets/114112113/eb2517d3-a5dd-41ed-85d8-85b71216a5f3)

**To Reproduce**

1. Quote a post that is over a year old (so the date is the short format - DD/MM/YYY for me here)
2. Observe the post in a feed (profile feed or following feed)

**Expected behavior**

Date should have more padding to the right to give it balance similar to the X hours display:

![image](https://github.com/bluesky-social/social-app/assets/114112113/088bc23a-579e-44c4-b916-1b939ed0d5dd)

**Details**

 - Platform: iOS
 - Platform version: 17.4.1
 - App version: 1.79.0

**Comment by haileyok** [comment]
Fixed in https://github.com/bluesky-social/social-app/pull/3982
