### ISSUE TITLE
Hover card not working

### ISSUE THREAD

**Issue by BagelHero** [bluesky-social/social-app#3744]
**Describe the bug**

Hover card does not appear.

**To Reproduce**

1. Hover over icon, mention, or any other part of the UI intended to display the profile card on hover. 

**Expected behavior**

As shown in the announcement post and PR for this feature (seen here: https://bsky.app/profile/bsky.app/post/3kq7f775wbl2y)

**Details**

 - Platform:  Desktop. Windows 10. Firefox 125.0.2 (64-bit)
 - App version: Build version: 1.79.0; Platform: web

**Additional context**
I use a moderate amount of extensions, but have disabled all styling/scripting/blocking extensions on the website in the hopes it was user error, with no luck yet. Have cleared the cache.

**Comment by okpierre** [comment]
Could it be Firefox 125? I'm using Ubuntu and Firefox 123.0 (64-bit) and it is working

![bskyhover](https://github.com/bluesky-social/social-app/assets/1679025/6d8c560b-3ed6-4e27-83b5-aa86a9ab0eee)

**Comment by BagelHero** [comment]
> Could it be Firefox 125? I'm using Ubuntu and Firefox 123.0 (64-bit) and it is working

Possibly! I tried Troubleshooting mode with no luck just in case, and it works on Chrome.

**Comment by BagelHero** [comment]
I don't know if it's bad form to bump with new info but this issue persists!
Firefox 126.0 (64-bit), Bluesky Build version: 1.82.0; Bundle info: f792bc0 (prod); Bundle date: 24051701; Platform: web

Last time I'll do this, just thought it might be pertinent.

**Comment by surfdude29** [comment]
I don't have a Windows computer to test on, but fwiw hover cards are working for me on Firefox 125.0.3 on Ubuntu 20.04

Bluesky:
Build version: 1.82.0; Bundle info: f792bc0 (prod); Bundle date: 24051701; Platform: web

**Comment by haileyok** [comment]
@BagelHero Thank you, fixed this here! https://github.com/bluesky-social/social-app/pull/4158
