### ISSUE TITLE
Unnecessary <Trans> tag in screens/Messages/Conversation/index.tsx

### ISSUE THREAD

**Issue by tkusano** [bluesky-social/social-app#3787]
I don't think `{profile.displayName}` in src/screens/Messages/Conversation/index.tsx needs to be marked as translatable.

https://github.com/bluesky-social/social-app/blob/b8d8bec388744c95aa84c955849d2bced45daf11/src/screens/Messages/Conversation/index.tsx#L112

**Comment by haileyok** [comment]
Sorry about that, thanks for pointing it out 🙏
