### ISSUE TITLE
Gif display as link on 1.79

### ISSUE THREAD

**Issue by Maxouwell** [bluesky-social/social-app#3788]
**Describe the bug**
On my device, the gif display as link even though I'm in 1.79.

I'm at lost at what settings could do this.
I can always remove the cache or reinstall the app but it may hide the cause of the problem.

**To Reproduce**

1. Open the gif announcement post on the bluesky official account
2. All gif are links

**Expected behavior**

Display as animated gif

**Screenshots**

![Screenshot_20240501-111159](https://github.com/bluesky-social/social-app/assets/13748802/316cef3d-a0ad-45d6-8d21-042eba144fbc)
![Screenshot_20240501-121435](https://github.com/bluesky-social/social-app/assets/13748802/20fc69f5-736c-4afb-bdce-c03774f5fa89)
![Screenshot_20240501-121749](https://github.com/bluesky-social/social-app/assets/13748802/6d8d3442-6cdb-4824-8129-74c44fb77a45)

**Details**

 - Platform: Android 14, Pixel 7a
 - App version: 1.79

**Comment by haileyok** [comment]
Hey @Maxouwell! I remember having a conversation with you on the app about this, but not sure if you responded. My notifications have been a bit full recently 😓 

Were you able to resolve this?

**Comment by Maxouwell** [comment]
Hi @haileyok !

Actually, I'm still waiting for the 1.80 update to hit my phone (or any other update, I'm still on 1.79.0).
I saw you did have some problems with it, so I'm waiting for Google Play updating :)

**Comment by Maxouwell** [comment]
Hello @haileyok, I'm on 1.80 and I still only have the link.
Should I wait for the 1.81 update hitting my phone ?

**Comment by haileyok** [comment]
This is extremely bizarre. Can you try reinstalling the app?

**Comment by Maxouwell** [comment]
Following @haileyok instructions, a wipe of the app'sdata resolved the problem.

**Comment by mirh** [comment]
I can guess this is solved?

**Comment by Maxouwell** [comment]
Yes !
I close the issue
