### ISSUE TITLE
Entering unusual alt-text has broken the site for me

### ISSUE THREAD

**Issue by Anitmata** [bluesky-social/social-app#3865]
**Describe the bug**

I entered unicode -- Babylonian cuneiform -- into the alt-text field. Now when I post Bluesky tells me the post was published, but it doesn't show up. When I like am post, the like disappears on post reload. 

**To Reproduce**

1. Enter weird unicode in the alt-text of an image in a reply. Say, a joke in Old Babylonian you were trying to explain.
2. Post it. Bluesky will tell you your post has been published successfully.
3. The reply, or post, will not appear. No reply or post at all, in fact, will appear, despite Bluesky claiming the post has been published. 

**Expected behavior**

While I expected Bluesky might decline to publish a post with unicode characters in the alt-text, it didn't. Instead I can't post, repost or like anything. 

**Screenshots**

**Details**

 - Platform: desktop Firefox
 - Platform version: 125.0.3
 - App version: I don't know what you mean here. Sorry.

**Comment by Anitmata** [comment]
Note: feed is still readable.

**Comment by haileyok** [comment]
Shouldn't be an issue with the unicode, but rather there's some relay issues going on right now. https://status.bsky.app/

**Comment by Anitmata** [comment]
Ah, thank you. I assumed because I did something very unusual that was the cause

**Comment by haileyok** [comment]
No problem! ❤️
