### ISSUE TITLE
Being able to view the Quote Reposts under the original post

### ISSUE THREAD

**Issue by Jasmine2A** [bluesky-social/social-app#4001]
Sites like Twitter have a section where you can view the quote tweet without going to the person who quote tweeted the account.

I feel like BlueSky needs a feature like this to make what folks are saying in response to a quote post more user friendly and easy to understand. This screenshot shows where a "View Quote Posts" tab can go.

![view quote post](https://github.com/bluesky-social/social-app/assets/81712093/0fa1f9dd-b623-4d9a-965c-ad1e9334609c)

**Comment by surfdude29** [comment]
This is under discussion, see #1050.
