### ISSUE TITLE
See quote-posts on a post

### ISSUE THREAD

**Issue by heikadog** [bluesky-social/social-app#4029]
**Is your feature request related to a problem? Please describe.**

I think there should be an easier way to access quote-posts on Bluesky.

**Describe the solution you'd like**

I would like to see a link to see quote-posts on posts. Maybe a button under the 3-dot menu?

**Describe alternatives you've considered**

- Have a dedicated link on posts to see quote-posts
- Have a way to search for quote-posts related to a specific account

**Comment by mschwendener** [comment]
Ta-dah https://bsky.app/profile/bsky.app/post/3l2s5ocuzyc24

**Comment by gaearon** [comment]
ayy
