### ISSUE TITLE
[APP-438] In-app translation

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#404]
Right now we're leaning on a translate button that takes you to another site. It'd be really nice to do what twitter does -- offer an in-place translation off of a link.

<sub>[APP-438](https://linear.app/blueskyweb/issue/APP-438/in-app-translation)</sub>

**Comment by mschwendener** [comment]
Why is this closed?

**Comment by tomayac** [comment]
I've opened PR https://github.com/bluesky-social/social-app/pull/9070 that implements built-in translation as a progressive enhancement on browsers that ship the [Translator API](https://developer.chrome.com/docs/ai/translator-api) (currently Chrome 138 and later). On non-supporting browsers, it falls back to the present behavior of linking to Google Translate. (I'm [@tomayac.com](https://bsky.app/profile/tomayac.com) on Bluesky.)
