### ISSUE TITLE
Labels *and* label reveal being rendered together

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#4054]
**Describe the bug**

Labels are being rendered alongside 'X labels has been placed...' text (which should be 'X labels **have** been placed...' while I'm here):

![image](https://github.com/bluesky-social/social-app/assets/114112113/06f9bae1-bb39-4490-875d-0950c73c64ef)

**To Reproduce**

1. View your profile while it has been labelled

**Expected behavior**

Either show the labels, or show the reveal.

**Details**

 - Platform: Windows Chrome
 - Platform version: 124
 - App version: 1.83.0

**Comment by haileyok** [comment]
Pretty sure this only applies to your own account, but can you see if it's happening for posts too? It shouldn't but want to make sure before I merge in this fix. Thank you!!!

**Comment by Bossett** [comment]
I think that's right, I can't see it on posts
