### ISSUE TITLE
agent.getTimeline with cursor "..." produces 500 error

### ISSUE THREAD

**Issue by boly38** [bluesky-social/social-app#4095]
**Describe the bug**

Trying to follow the doc, I encounter a (minor) bug from api getTimeline : a backend 500 error
This issue is described here for the doc side : bluesky-social/bsky-docs#146
As this is a 500, I think the backend is not doing enough input validation on `cursor` query param

**To Reproduce**

(using api, node agent example)
````
const { data } = await agent.getTimeline({
  cursor: "...",
  limit: 30,
});
````

**Expected behavior**

I expect a 4xx result

**Screenshots**

**Details**

 - node client `"@atproto/api": "^0.12.10",`
 - use `https://bsky.social` as agent `service` (backend spcification)

**Additional context**

(If I'm wrong and the backend is on another repository, please tell me.

**Comment by mary-ext** [comment]
it's over here yeah
https://github.com/bluesky-social/atproto

**Comment by boly38** [comment]
ok reported here, thanks @mary-ext 👍 
bluesky-social/atproto#2500
