### ISSUE TITLE
Premature Text Sending Issue in DM When Typing in Japanese

### ISSUE THREAD

**Issue by anon5r** [bluesky-social/social-app#4157]
Hello team, I tested social-app's DM locally. I felt that there was a problem with the behavior when using it in Japanese.

**Describe the bug**

When typing in Japanese, the DM sends the message prematurely. This happens because pressing the Enter key to confirm kanji or hiragana conversion also triggers the message send action. As a result, incomplete segments of the message are sent individually, instead of allowing the user to complete and review the entire message before sending it.

**To Reproduce**

1. Open the DM page:
Open the chat where the issue is observed.

2. Select Japanese Input Method:
Ensure that the input method editor (IME) is set to Japanese. You can usually do this by selecting the language bar on your operating system and choosing Japanese.

3. Start Typing in Japanese:
Begin typing the following sentence in Japanese: 「今日はとてもいい天気です。」 (Today is very good weather).

4. Type the Sentence in Romaji:
Type the sentence using Romaji (Latin alphabet) as follows:

 - "kyouha totemo ii tenki desu"

5. Convert the Sentence in Segments:
Convert the sentence in segments, as follows:

  - Type "kyouha" (今日は) and press the space bar to convert it to kanji.
  - Press Enter to confirm the conversion.
  - Notice that the message "今日は" is sent immediately after pressing Enter, which is not the expected behavior.
  - Continue typing "totemo" (とても) and press the space bar to convert it to hiragana.
  - Press Enter to confirm the conversion.
  - Notice that the message "とても" is sent immediately after pressing Enter.
  - Repeat the process for "ii" (いい), "tenki" (天気), and "desu" (です), observing that each segment is sent as a separate message upon pressing Enter to confirm the conversion.

**Expected behavior**

The expected behavior is that pressing Enter confirms the conversion of the current segment (e.g., "今日は") without sending the message. The user should be able to continue typing and converting the next segments ("とても", "いい", "天気です") before sending the entire message at the end.

Reference behavior: https://youtu.be/uC3OprB5IuU

**Screenshots**

The screen was shot as a video

Demonstration video: https://youtu.be/UitLIYBqs6k

**Details**

 - Platform: Chrome macOS
 - Platform version: Sonoma 14.5
 - App version: 
   - Build version: 1.83.0; Bundle info: dev (prod); Bundle date: NaN; Platform: web

**Additional context**

**Comment by haileyok** [comment]
@anon5r Thank you for this report! Great callout. I'll peek at how we can deal with this. If I'm correct, this is only on web correct?

**Comment by anon5r** [comment]
@haileyok 
Thank you for your quick correction.
> If I'm correct, this is only on web correct?
Yeah, I checked on the web. After the fix, I also checked from mac and Android and it worked as expected. 👍 
I haven't checked with the app this time.

Thank you,
