### ISSUE TITLE
ALT compose window for GIFs on iOS 

### ISSUE THREAD

**Issue by JimHasFun** [bluesky-social/social-app#4225]
**Describe the bug**

Compose window for ALT text for GIFs obscures composition after two lines.
**To Reproduce**

1. Select GIF
2. Click ALT
3. Type more than two lines of text

**Expected behavior**
Expect that window would move or expand to show text as it's being composed.

**Screenshots**

**Details**

 - Platform: 
 - Platform version:iOS 17.5.1
 - App version:Build version: 1.83.0.236; Bundle info: 9eed70415 (prod); Bundle date: 24052323; Platform: ios

**Additional context**

**Comment by surfdude29** [comment]
I’m able to reproduce this on
Build version: 1.91.1.464; Bundle info: 49ab4867a (prod); Bundle date: 24091901; Platform: ios
running on iOS 17.7 on iPhone SE (3rd generation).

**Comment by haileyok** [comment]
Fixed by https://github.com/bluesky-social/social-app/pull/5557. Should be out early this week.
