### ISSUE TITLE
Threads should indicate if they're only partially rendered

### ISSUE THREAD

**Issue by mdruker** [bluesky-social/social-app#4242]
**Is your feature request related to a problem? Please describe.**

Longer threads seem to only show 7 posts, with no indication that there's more, and this makes longer threads function very poorly on Bluesky. Even clicking a "View full thread" takes you to a page that shows the first several posts. There is poor discoverability for the fact that the thread continues; you need to click on the last post to see the thread continuing past it.

**Describe the solution you'd like**

The simplest solution is to have an indicator after the last rendered post that the thread continues, e.g. "View full thread" or "Continue thread". If the latter, it would just load the next page of the thread in line.

**Describe alternatives you've considered**

You could always load the whole thread, but that seems impractical. 7 is too small so that should absolutely be raised on the back-end, but for any limit, there needs to be visibility that you're not seeing the entire thread.

**Additional context**

Here's an example thread to see this: https://bsky.app/profile/did:plc:zo4loyx2rtmfw5az6aigi65o/post/3ks2pgebco62k

**Comment by surfdude29** [comment]
There used to be a **More >** indicator that the thread continued. However, that disappeared in December due to a bug. There's more info in #1558.

**Comment by mdruker** [comment]
I think this was basically addressed in release 1.86

**Comment by mdruker** [comment]
I think this was basically addressed in release 1.86
