### ISSUE TITLE
The strings for the settings toggle is unintuitive

### ISSUE THREAD

**Issue by quiple** [bluesky-social/social-app#4274]
**Describe the bug**

![IMG_1181 - 복사본](https://github.com/bluesky-social/social-app/assets/11014257/38abe94b-0dc5-4ca1-8492-be258ebdc3f9)

(In the two settings items below) It's counterintuitive to have a toggle on to disable and a toggle off to enable. Make it default to on and disable when off.

**Comment by surfdude29** [comment]
This has been changed in #6069.
