### ISSUE TITLE
Duplicate posts in feed

### ISSUE THREAD

**Issue by arcalinea** [bluesky-social/social-app#43]
Duplicate posts show up in the feed due to how we handle replies. If there are multiple replies to the same post, we need to figure out how to only show the original post once. Otherwise popular original posts take over a user's entire feed. 

I think a post trending in scenes might also get pushed to the feed twice -- there might be more than one avenue causing the duplicate post issue.

**Comment by mschwendener** [comment]
From 17 h ago https://bsky.app/profile/ghoulpus.bsky.social/post/3k5v73xu6vl2h

**Comment by pfrazee** [comment]
Yes, this darned thing returned with a vengeance, I ran into it myself. I've got an idea for how to permanently fix it.
