### ISSUE TITLE
Add check for threadgate settings before quoting a given post

### ISSUE THREAD

**Issue by n0vedad** [bluesky-social/social-app#4326]
**Is your feature request related to a problem? Please describe.**

There are a lot of people outside who don't want to have quote posts (from strangers) if they set a threadgate.

**Describe the solution you'd like**

Before allowing a quote post threadgate settings of the given post should be checked and handled like:

1 - no threadgate: all people can quote
2 - nobody - nobody can reply, quote option is deactivated
3 - mentioned users: only mentioned can quote
4 - followed users: only followed users can quote
5 - users of a given list: only users of a given list can quote

**Describe alternatives you've considered**

It could be a opt-in feature too.

**Comment by surfdude29** [comment]
This would make it harder to challenge misinformation when someone sets a threadgate.

If a user doesn't like a post that someone else makes quoting their post, they have the option of blocking that account and their post will no longer be accessible from the quote post.

**Comment by n0vedad** [comment]
> This would make it harder to challenge misinformation when someone sets a threadgate.
> 
> If a user doesn't like a post that someone else makes quoting their post, they have the option of blocking that account and their post will no longer be accessible from the quote post.

I think with the ability to place labels there is always a powerful tool for challenging misinformation. We all know this kind of reply guy and I spoke with a few marginalized people who definitely dont't want to have unwanted quote posts. 

And sure, these people could block all day, but the intention is not to have that

**Comment by surfdude29** [comment]
> I think with the ability to place labels there is always a powerful tool for challenging misinformation.

I disagree, I don't think the labelling system – as it's currently implemented, at least – is a powerful tool for challenging misinformation at all. A label cannot explain why something is misinformation nor can it provide links to sources that offer context or refute the post. If Bluesky had something like the Community Notes system (for all its faults) then it would be a different situation.

> We all know this kind of reply guy and I spoke with a few marginalized people who definitely dont't want to have unwanted quote posts.

I can understand some people getting annoyed by unwanted quote posts, but in my view being able to comment on someone else's post (unless you're already blocked, of course) by quoting it is a core feature of a microblogging platform. The lack of a quote post feature is one reason why many people don't like Mastodon (among others).

I don't think we should be restricting the quote post feature any further; I think the balance is currently right where if you block the person the link to the quoted post is removed (unlike on Twitter).
