### ISSUE TITLE
App Crash when tapping on app icon (v1.85.0, Android)

### ISSUE THREAD

**Issue by xtianpu** [bluesky-social/social-app#4385]
**Describe the bug**
App Crash when open with shortcut on Android

**To Reproduce**

1. Update to v1.85.0
2. Tap on app icon

**Expected behavior**

No crashes

**Screenshots**

https://github.com/bluesky-social/social-app/assets/8172235/f43902d7-7fed-4fca-9486-e64952e18745

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: v1.85.0

**Comment by haileyok** [comment]
Hey!

We have a fix pending, just need to get the hotfix into the Play Store. Hit a real unfortunate issue here that doesn't produce very often :(

In the meantime if you either:

a. Open the app through Google Play (yea, I know this is weird...but opening the app from the "Open App" button should actually work!)
b. Downgrade with the APK available here: https://github.com/bluesky-social/social-app/releases/tag/1.85.0

Hoping to have a fix available at some point today.

**Comment by haileyok** [comment]
@xtianpu @brawl345 Play Store update 1.85.1 should be available now! Thank you for the patience! ❤️
