### ISSUE TITLE
Post composer is completely broken on Android

### ISSUE THREAD

**Issue by gpp-0** [bluesky-social/social-app#4396]
**Describe the bug**

After the 1.85 update the post composer is basically unusable on my Android. When trying to make a new post, as soon as the keyboard comes up the composer immediately hides it, so it's impossible to type anything. When replying to a post, it does not hide the keyboard so it's possible to type, but the layout is all bugged and the text field is barely visible

**Screenshots**

https://github.com/bluesky-social/social-app/assets/52042597/68c35b49-bb2c-49ca-af36-1a50c34d5e77

**Details**

 - Platform: Android
 - Platform version: 10
 - App version: 1.85.0.214

**Comment by haileyok** [comment]
Thanks, we have a fix coming out here shortly!

**Comment by haileyok** [comment]
@gpp-0 You should be able to update on the Play Store now to 1.85.1 and this should be fixed!! Please let us know if it isn't <3
