### ISSUE TITLE
[Android] Crash when attempting to launch Bluesky App via Telegram (clicking a Bsky Post URL in a message)

### ISSUE THREAD

**Issue by HeyItsLollie** [bluesky-social/social-app#4424]
**Device details**
Bluesky for Android, 1.85.1.217
Android 14 (Samsung XCover Pro)
Attempting to launch Bluesky App via: Telegram for Android v10.13.4 (4855)

**Describe the bug**
When attempting to open a Bluesky Post URL via Telegram, the Bluesky app will attempt to launch, but then crash immediately.

So far, this crash *only* seems to happen via Telegram for Android (the official app from the Play Store). I've tried Discord (opens links in its own browser) and Twitter (launches the Bluesky app successfully - huge shock tbh), but Telegram is the only app that causes Bluesky to crash with 100% consistency.

**To Reproduce**
1. On any Bluesky post, open the Show More menu, then Share, and Copy URL.
2. Navigate to (in my case) Telegram, Paste the URL in any message (eg: Saved Messages), and Send.
3. Now, attempt to click on the URL.
4. Android will either appear to do nothing, or blink for a split second and return to Telegram.

This crash can also produce one of two system prompts:
- **Something went wrong with Bluesky** (Thank you Android, very helpful)
- **Clear cache for Bluesky?** (Button prompt with "Cancel" or "Clear cache", but has no effect)

**Video**
https://github.com/bluesky-social/social-app/assets/30498581/47727e1a-e788-452c-b0ca-b1f3f85b389c

**Comment by gaearon** [comment]
fixed by https://github.com/bluesky-social/social-app/pull/4425
