### ISSUE TITLE
App crashes when opened from an other app using Chrome Custom Tab on Android

### ISSUE THREAD

**Issue by lanlacope** [bluesky-social/social-app#4428]
**Describe the bug**
When opening the Bluesky by other app using a Chrome custom tab, the app crashes.

**To Reproduce**
1. Send an intent containing Chrome custom tab information to the Bluesky app.
2. Use the specific URI example provided below to reproduce the issue:

`
intent://bsky.app/profile/bsky.app/post/3kufde3xvol2j#Intent;scheme=https;i.android.support.customtabs.extra.TOOLBAR_COLOR=-2236963;i.fwRequestCode=-1;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;i.androidx.browser.customtabs.extra.SHARE_STATE=0;end
`

**Expected behavior**
The app should open successfully without crashing.

**Details**
- Platform: Android Sony Xperia SOG03
- Platform version: Android13 (API Level 33)
- App version: 1.85.1

**Additional context**
The issue appears to be caused by the absence of `android.support.customtabs.extra.SESSION`. When this parameter is added to the URI, the app opens successfully.

`
intent://bsky.app/profile/bsky.app/post/3kufde3xvol2j#Intent;scheme=https;launchFlags=0x3000000;i.android.support.customtabs.extra.SESSION=11;i.android.support.customtabs.extra.TOOLBAR_COLOR=-2236963;i.fwRequestCode=-1;B.android.support.customtabs.extra.EXTRA_ENABLE_INSTANT_APPS=true;i.androidx.browser.customtabs.extra.SHARE_STATE=0;end
`

**Comment by gaearon** [comment]
Can you please verify that this is fixed in 1.86? Thank you.

**Comment by lanlacope** [comment]
Yes, this issue has been fixed in version 1.86.
Thank you for checking!
