### ISSUE TITLE
App crashing when opening shared feed URLs

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#4436]
**Describe the bug**
App crashes when opening a link containg a shared feed

**To Reproduce**

1. Share feed.
2. Open link with shared feed

**Expected behavior**

Feed should be displayed as in profile\feeds

**Screenshots**
![Screenshot_20240608_223839_Device care](https://github.com/bluesky-social/social-app/assets/7019947/bc4d4f43-4cdd-4fb4-a762-f44c8351ba78)

Screenshot of error.

**Details**

 - Platform: Mobile, Samsung Galaxy S24 Ultra
 - Platform version: Android 14
 - App version: 1.85.1

**Additional context**

**Comment by diesocke** [comment]
![IMG_20240608_224624_191](https://github.com/bluesky-social/social-app/assets/7019947/f0ec89e8-c939-45b5-a9ae-5999ebac0679)

This logfile was sent to me by someone who tried to open this link:

[https://bsky.app/profile/did:plc:yye42my4dpoybc67ekaie2ve/feed/aaacswu2l2scw](url)

**Comment by haileyok** [comment]
Thank you! I think we got this one fixed in #4425 

Is there any chance that they were opening the link from Telegram?

**Comment by gaearon** [comment]
Fwiw @foysalit said he also can repro this with Slack links, but the message seems 99% likely to come from the place we fixed.

**Comment by gaearon** [comment]
Can you please verify that this is fixed in 1.86? Thank you.

**Comment by foysalit** [comment]
I'm on 1.86 and confirming that I can't repro this anymore 🎉

**Comment by diesocke** [comment]
Same here.
