### ISSUE TITLE
[APP-420] Emoji picker for desktop web

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#451]
Desktop web users are asking for an emoji picker in the composer

<sub>[APP-420](https://linear.app/blueskyweb/issue/APP-420/emoji-picker-for-desktop-web)</sub>

**Comment by mbevc1** [comment]
Was this completed? Canot find it via https://staging.bsky.app/

**Comment by pfrazee** [comment]
No it was moved to the internal tracker

**Comment by mbevc1** [comment]
Gotcha, thanks. Any updates on when it's planned for implementation?
