### ISSUE TITLE
RTL auto-detection makes PostMeta messy

### ISSUE THREAD

**Issue by jgarplind** [bluesky-social/social-app#4529]
**Describe the bug**
RTL auto-detection causes `@`-character in PostMeta to be misplaced.

**To Reproduce**

See https://bsky.app/profile/pastures.bsky.social for example.

**Expected behavior**

`@`-character should always precede the handle, since the handle is inherently LTR-text, event if the display name is RTL-text.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/10069144/834bb1ab-91b8-4d43-8fea-83ceb79a3390)

**Details**

 - Platform: Android and Windows Edge. Presumably iOS also.
 - Platform version: 13 / 126
 - App version: 1.86

**Additional context**

This behavior appears to be the output of the BIDI algorithm, see [this post](https://bsky.app/profile/jgarplind.bsky.social/post/3kuyrou25bc23) for a link to the spec and a playground.

I consider this a minor inconvenience considering the overall state of Bluesky RTL support, but have a fix in mind that I will contribute soon.

**Comment by mary-ext** [comment]
Here's how Signal handles Unicode bidi, seems worth taking a look
https://github.com/signalapp/Signal-Desktop/blob/ce0fb220411b97722e1e080c14faa65d23165784/ts/util/unicodeBidi.ts#L124

**Comment by haileyok** [comment]
Merged this in, thank you!
