### ISSUE TITLE
Kawaii Logo Truncated

### ISSUE THREAD

**Issue by andwhyisit** [bluesky-social/social-app#4536]
**Describe the bug**
The kawaii logo is cropped on the left, right, and bottom sides. This seems to be caused by "object-fit: cover;" in the stylesheet.

**To Reproduce**
Enter https://bsky.app/?kawaii=true into your browser address bar when logged in, hit enter, and look up.

**Expected behavior**
An uncropped logo. I should be able to see the whole logo.

**Screenshots**
![image](https://github.com/bluesky-social/social-app/assets/1041815/73120655-2470-45e8-9e89-26c7fa98f2a0)

**Details**
 - Platform: Desktop Firefox Windows
 - Platform version: 127.0
 - Platform: Desktop Opera Windows
 - Platform version: 110.0
 - App version: 1.86

**Additional context**
This doesn't affect the logo when logged out.

**Comment by dolciss** [comment]
This issue is a duplicate of #4498 and has been fixed in #4505, perhaps it will be ok in the next release :)

**Comment by andwhyisit** [comment]
Oh. Whoops. I forgot to remove the "is:open" from the search box when I was checking to see if this issue already existed.
