### ISSUE TITLE
Tapping Unfollow on the Followers you know page doesn't change the button

### ISSUE THREAD

**Issue by surfdude29** [bluesky-social/social-app#4552]
**Describe the bug**

If you tap an **Unfollow** button on the **Followers you know** page, the button doesn't appear to do anything as it doesn't change to **Follow**, however you have actually unfollowed the user.

**To Reproduce**

1. Visit the **Followers you know** page from someone's profile where it's shown.
2. Tap the **Unfollow** button next to one of the accounts.
3. Observe that the button does not change to **Follow**.
4. Visit the user's profile and see that the **Follow** button is shown, confirming that the user has, in fact, been unfollowed.

**Expected behavior**

Tapping the **Follow** button should change it to **Unfollow**, which would give the user a visual confirmation that they have successfully unfollowed the user.

**Details**

 - Platform: iPadOS
 - Platform version: 16.6
 - App version: Build version: 1.86.0.290; Bundle info: 6736384 (prod); Bundle date: 24061123; Platform: ios

**Comment by gaearon** [comment]
yup, should be fixed on main (you can verify on https://main.bsky.dev/)

**Comment by surfdude29** [comment]
> yup, should be fixed on main (you can verify on https://main.bsky.dev/)

Yep working for me fine there, thanks
