### ISSUE TITLE
Continue Thread Button Doesn't Work

### ISSUE THREAD

**Issue by Juicysteak117** [bluesky-social/social-app#4594]
**Describe the bug**
On Web, I encountered an instance of the "Continue Thread" button at the bottom of a thread (go figure), however attempting to click it does not show the remaining two posts. It is unclear if these remaining posts are deleted (and thus, the bug is that the button still exists) or if the button itself is broken.

**To Reproduce**

1. Go here: https://bsky.app/profile/pookleblinky.bsky.social/post/3kvgj27dsav2l
2. Click "Continue thread"
3. URL changes to https://bsky.app/profile/pookleblinky.bsky.social/post/3kvgjaqtipu25
4. Visibility of the thread does not change outside of now being in an overview state where no replies are shown.

**Expected behavior**

The button to work.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/20595808/f41f32a5-b40b-43f9-8d5e-4bf1f3435b4e)

**Details**

 - Platform: Chromium web
 - Platform version:
 - App version:

**Additional context**

**Comment by gaearon** [comment]
Can't seem to reproduce on this URL: https://bsky.app/profile/pookleblinky.bsky.social/post/3kvgj27dsav2l

Is this selecting the right post?

![Screenshot 2024-06-21 at 20 27 10](https://github.com/bluesky-social/social-app/assets/810438/a663ecc7-1b69-45c9-b6cd-5a3326791dbc)

I can't repro even if I select the root post though.

![Screenshot 2024-06-21 at 20 27 38](https://github.com/bluesky-social/social-app/assets/810438/7c6652be-50b8-4d4d-8ff6-1c404cf9780c)

The problem _could_ be this one though, which is resolved on main: https://github.com/bluesky-social/social-app/pull/4559

**Comment by Juicysteak117** [comment]
Hmm. I can consistently repro with my main account but on an alternate account the issue does not persist, even on the same browser after refreshes and after re-signing in. 

Upon further examination, it does appear to be related to #4559, although maybe the same issue entirely? There's a user who blocks me that is replying to the final post in the thread (with OP responding, so presumably #4559), but I still cannot see the final post in the thread even though OP does not block me. A suggestion maybe would be to have the thread continue to automatically unroll if you're clicking part way down into the thread? Like if if it only shows until the nth post and you navigate from 0 to n-1, it should show 2n - 1 if that makes sense (since I think preserving post visibility upthread is very good for navigation purposes).

**Comment by gaearon** [comment]
Does it repro on https://main.bsky.dev?

**Comment by Juicysteak117** [comment]
Does not repro on main. Good to see.

**Comment by gaearon** [comment]
Ah great, that was it then. Thanks for the report!
