### ISSUE TITLE
Copy/paste images

### ISSUE THREAD

**Issue by YuriGal** [bluesky-social/social-app#4656]
**Describe the bug**

Copying a image from a Web page, and pasting it to a Bluesky post doesn't work in desktop browsers

**To Reproduce**

1. Using a Windows or a MacOS computer browse to any page with images
2. Copy an image from the page into clipboard
3. Paste image into a Bluesky post

**Expected behavior**

Image should appear in the post

**Details**

 - Platform: On desktop (Windows or Mac) Chrome or Firefox
 - App version: 1.87.0

**Additional context**

It used to work, but now is broken.

**Comment by gaearon** [comment]
cc @mary-ext might be related to https://github.com/bluesky-social/social-app/pull/4327?

**Comment by mary-ext** [comment]
oops thought I had covered this pretty well but it appears not, sorry!
