### ISSUE TITLE
Old Data and Preferences Still Exist When Uninstalling and Reinstalling On Android

### ISSUE THREAD

**Issue by xtianpu** [bluesky-social/social-app#4679]
**Describe the bug**
Old Data Still Exist When Uninstalling and Reinstalling On Android

**To Reproduce**

1. Sign in to the app
2. Switch display to dark
3. Uninstall
4. Reinstall

**Expected behavior**

Old Data and Preferences should be totally deleted when user reinstalling the app

**Details**

 - Platform: Android
 - Platform version: 14
 - App version: Build version: 1.87.0.255; Bundle info: f6b138f70 (prod); Bundle date: 24062702; Platform: android

**Comment by haileyok** [comment]
Is this actually the expectation? My understanding is that there is that there are two different "stores" of data that need to get cleared on Android. Do other apps behave the way you're describing? Not really sure what control we have over this in all honesty, though I do know that it's a thing as I've had to explain it while debugging some problems before...

**Comment by xtianpu** [comment]
> Is this actually the expectation? My understanding is that there is that there are two different "stores" of data that need to get cleared on Android. Do other apps behave the way you're describing? Not really sure what control we have over this in all honesty, though I do know that it's a thing as I've had to explain it while debugging some problems before...

It seems, I can’t reproduce anymore on this bundle Build version: 1.87.0.255; Bundle info: 58a9dce (prod); Bundle date: 24062517; Platform: android

now when I reinstalled the app, all data cleared.
