### ISSUE TITLE
Signing out an account is signing out all accounts

### ISSUE THREAD

**Issue by xtianpu** [bluesky-social/social-app#4683]
**Describe the bug**
Signing out an account is signing out all accounts

**To Reproduce**

1. Press sign out button on settings

**Expected behavior**

Should be only one account to be signed out, and switch to another signed in account

**Details**

 - Platform: All platform
 - Platform version: -
 - App version: v1.87.0

**Comment by swar00p** [comment]
Is this the expected behavior? I tried it on my iOS app and confirmed that I get signed out of both my accounts if I click on Sign Out on one of them. I'm a complete newbie but I cloned the code base on my laptop and took a quick look. I may be mistaken but it looks like the logout method in https://github.com/bluesky-social/social-app/blob/ea0586cd67427ce68f867ee25e03bb92169f23c3/src/state/session/index.tsx#L117 doesn't accept an account parameter.

I'm happy to dig in a bit more to see what's going on.

**Comment by haileyok** [comment]
@swar00p Definitely is not expected behavior. Feel free to do some digging on it if you feel like it! ❤️

**Comment by xtianpu** [comment]
@swar00p @haileyok oh sorry, this should be feature request, my bad assigned it as label bug. Should I close this and create a new one?

**Comment by haileyok** [comment]
I think bug is fine - it feels like a bug to me 🙃

**Comment by xtianpu** [comment]
Just create a new one with feature request label https://github.com/bluesky-social/social-app/issues/4775

**Comment by swar00p** [comment]
> Just create a new one with feature request label #4775

@xtianpu I think @haileyok said that this should remain open. There was no need to create a feature request. Can you please close the feature request and reopen this bug?

**Comment by swar00p** [comment]
@haileyok I think I was wrong. The way it's been implemented in https://github.com/bluesky-social/social-app/blob/7c1c24ef1badb746ecbe707d390bec4934940ced/src/state/session/reducer.ts#L145 and judging by the comment, it looks like it was deliberately implemented this way (to sign out of all accounts). Who makes the decision (one way or another) whether it should continue to work this way or if it should be implemented as a sign out for the selected account only?

**Comment by haileyok** [comment]
@swar00p Yea, that is the way it was implemented, though we are fine with changing it. It's something that we'll change at some point, but do feel free to look into it yourself and PR if you want to! Also can just take the discussion to the other issue (either label really works here, it _does_ seem like a bug and I personally would consider it one, but I digress 😆)

**Comment by haileyok** [comment]
(To clarify, we did discuss this a bit internally and are fine with making the change)

**Comment by swar00p** [comment]
@haileyok I'm using Android Studio as my IDE. My current set up is that I have cloned the social-app project from the repository. I read the instructions in Github to submit PRs and it says that I have to fork the project and then clone it. Is it mandatory to fork the repository or is it sufficient if I just clone it?

**Comment by haileyok** [comment]
Looks like you figured this out ^, looks like the right idea. Just submit a PR from that fork whenever.
