### ISSUE TITLE
Starter pack user list allows creating a follow record for users blocking you

### ISSUE THREAD

**Issue by str4d** [bluesky-social/social-app#4689]
**Describe the bug**
The user list view in a starter pack shows "Follow" buttons for all users in the list, regardless of whether those users block the current user.

**To Reproduce**

1. User A blocks user B.
2. User C creates a starter pack containing user A.
3. User B opens user C's starter pack.
4. User B can see a "Follow" button next to user A, despite their profile image being blurred due to the block.
5. User B clicks on the "Follow" button for user A, and sees user B's following count increase (and thus presumably also user A's followers count).

**Expected behavior**

The "Follow" button should not appear beside user A.

**Details**

 - Platform: desktop Firefox Windows
 - Platform version: 127.0.2
 - App version: Build version: 1.87.0; Bundle info: f6b138f (prod); Bundle date: 24062702

**Additional context**

AFAICT the usual blocking behaviours are still present: even after following user A, user B can't see user A's posts, and user B doesn't show up in user A's following list.

**Comment by surfdude29** [comment]
I think this might be fixed when #4715 is merged.

**Comment by haileyok** [comment]
Yea, this should be fixed in tomorrow's release. Thanks!
