### ISSUE TITLE
Starter Packs' QR codes do not always work on iPhone

### ISSUE THREAD

**Issue by fenarinarsa** [bluesky-social/social-app#4740]
**Describe the bug**

My iPhone can't lock on a QR code generated for a Starter Pack. Most work, but I found one that doesn't.

**To Reproduce**

1. Try to get a lock on the following QR code.

![image](https://github.com/bluesky-social/social-app/assets/17545417/5911b5ed-ee60-4366-bf1f-f180019efbd9)

(this is the QR code for https://go.bsky.app/RpVVuXC )

**Expected behavior**

The phone should be able to lock on any generated QR code.

**Details**

 - Platform: web browser
 - Platform version: Windows 11 Firefox 127.0.2
 - App version: Build version: 1.87.0; Bundle info: fe01f32 (prod); Bundle date: 24062805; Platform: web

iPhone 12 Pro Max with iOS 17.5.1
Tested with the Photo app and the Scanner decode app

**Comment by surfdude29** [comment]
I'm able to reproduce this on my iPhone 7 running iOS 15.8.2. Using the Camera app, I'm unable to get a lock on the above QR code.

However, I looked at QR codes for several other starter packs and I'm unable to get a lock on any of the ones I tried. So this might be a wider issue, perhaps only for some phone/OS combinations.

My phone is able to correctly recognise standard QR codes; perhaps the issue is the non-standard QR codes that Bluesky is using?

**Comment by haileyok** [comment]
Really bizarre! I was only able to find two that didn't scan, but it seems like it's completely dependent on the data in the QR code. I guess some combinations might be sticking one of the QR code "eyes" underneath the logo?

Anyway, can you try this one here? Seems to work fine for me now

![Japan_Expo_Starter_Pack_Share_Card](https://github.com/bluesky-social/social-app/assets/153161762/900cf1be-9243-4a12-99cb-0fd740c0d797)

**Comment by surfdude29** [comment]
That one scans perfectly for me, both in the Camera app and in a third-party app 👌

**Comment by fenarinarsa** [comment]
It also works for me. I tried to remove the butterfly on the first pic, it also works.

**Comment by haileyok** [comment]
@fenarinarsa Oh interesting...so just removing the butterfly from the image by itself fixed the problem? As in used a photo editor to do it? Or did you inspect-element to remove the butterfly?

**Comment by fenarinarsa** [comment]
> @fenarinarsa Oh interesting...so just removing the butterfly from the image by itself fixed the problem? As in used a photo editor to do it? Or did you inspect-element to remove the butterfly?

I removed it with Photoshop but yes I just tested, removing the image by inspecting the page also works.

**Comment by haileyok** [comment]
Wow! That's really weird...good to know, thanks!

**Comment by fenarinarsa** [comment]
It's really strange because I checked with other QR code generators with logos and they work (with other logos).

**Comment by surfdude29** [comment]
> It's really strange because I checked with other QR code generators with logos and they work (with other logos).

Same here, for example, my phone was able to easily recognise all the QR codes generated on this site (for Telegram username links):

https://qr.tginfo.me/

**Comment by haileyok** [comment]
Thanks, we should have this fixed in production at some point today.
