### ISSUE TITLE
Validate user external site settings when embedding a post.

### ISSUE THREAD

**Issue by vantubbe** [bluesky-social/social-app#4751]
When embedding posts on a external site you will often get "The author of this post has requested their posts not be displayed on external sites." message in the iframe. I assume this privacy setting resides within the user's account. 

Is there an API endpoint that would return the value of this flag for a given user? This way we could know ahead of time whether a post, when embedded, will show up with content or not?

**Comment by mary-ext** [comment]
You'd check for this by seeing if there's a `!no-unauthenticated` label on the profile

**Comment by vantubbe** [comment]
Thank you very much!
