### ISSUE TITLE
Sign out for each signed in account

### ISSUE THREAD

**Issue by xtianpu** [bluesky-social/social-app#4775]
**Is your feature request related to a problem? Please describe.**

It was inconvenient when signing out is signing out all of signed-in accounts

**Describe the solution you'd like**

Separation of sign out button for each signed in account

**Describe alternatives you've considered**

Signing out, then sign in again to specific account I wanted

**Comment by gaearon** [comment]
not quite like this issue described, but https://github.com/bluesky-social/social-app/pull/4941 fixes this.
