### ISSUE TITLE
reading refs during render 

### ISSUE THREAD

**Issue by rortan134** [bluesky-social/social-app#4845]
The react docs recommend against reading refs during render as it might break concurrency/other optimizations. I wonder if this is an exception?

https://github.com/bluesky-social/social-app/blob/43ba0f21f6796ebbdd0156c9fa89ebc7d56376e7/src/lib/hooks/useDedupe.ts#L6-L16

**Comment by gaearon** [comment]
In this case it’s ok because the ref never changes but this should really just be useCallback
