### ISSUE TITLE
Some quote embeds aren't displaying in logged out view until you click the post

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#4959]
**Describe the bug**

Opening this feed in the logged out view: https://bsky.app/profile/did:plc:oio4hkxaop4ao4wz2pp3f4cr/feed/aaag2mdct6ntq

There are some posts that quote some other post with just the text "👀", but they're displaying as just a "👀" without any quote embed. If you click on the post, then the quote is shown.

**To Reproduce**

Open the feed in the logged out view: https://bsky.app/profile/did:plc:oio4hkxaop4ao4wz2pp3f4cr/feed/aaag2mdct6ntq and scroll down.

**Screenshots**

<p>In the feed:<br> <img width="625" alt="Screen Shot 2024-08-20 at 02 47 40" src="https://github.com/user-attachments/assets/8d9cac44-724d-4d9d-a7d6-aa6ade444386"></p>
<p>Details: <br><img width="602" alt="Screen Shot 2024-08-20 at 02 47 45" src="https://github.com/user-attachments/assets/9ca8c37f-893f-4ab6-8842-7e887c17015f"></p>
<p>In the feed: <br><img width="644" alt="Screen Shot 2024-08-20 at 02 47 55" src="https://github.com/user-attachments/assets/5cdfb98c-e5fc-46a8-b8bf-944d0221f972"></p>
<p>Details: <br><img width="656" alt="Screen Shot 2024-08-20 at 02 48 04" src="https://github.com/user-attachments/assets/7d62d4b7-2b7e-4d48-8af9-65f17d5ce364"></p>

**Details**

 - Platform: Webkit (Orion), macOS Monterey

**Comment by surfdude29** [comment]
I'm able to reproduce this in Safari on iPadOS.

Also, looking at which embeds show up in that feed and which don't, it seems like the ones that show up are embeds of small to medium size (in terms of number of lines) rather than the larger ones? Maybe that has something to do with it? 🤔

**Comment by mackuba** [comment]
I was thinking it were the ones where the quote text was literally one emoji, although I haven't spent much time analysing this (since like I mentioned it was 3 am ;)

**Comment by surfdude29** [comment]
> I was thinking it were the ones where the quote text was literally one emoji, although I haven't spent much time analysing this (since like I mentioned it was 3 am ;)

That's a good working theory for 3am 😅

That might be part of the issue, but I think it might be wider than that. Because these two embeds don't show up, which aren't a single emoji:

![IMG_4887](https://github.com/user-attachments/assets/b1ca4cd9-01f7-468f-aaca-5e1953da0a0e)
![IMG_4888](https://github.com/user-attachments/assets/ccc17b17-e241-4810-bf0f-28dc17840d72)

and this embed does show up, even though it's just a single emoji:
![IMG_4889](https://github.com/user-attachments/assets/5c5e746f-205a-4eab-87f0-0cc39b7cb39f)

**Comment by mackuba** [comment]
Ah, ok, so not that

**Comment by surfdude29** [comment]
It seems like this also affects Discover:

https://bsky.app/profile/surfdude29.ispost.ing/post/3l2bfdyz7l52f

**Comment by surfdude29** [comment]
This seems fixed, presumably by #5329, and I can now see the embeds for all the examples here in [the feed on main.bsky.dev](https://main.bsky.dev/profile/did:plc:oio4hkxaop4ao4wz2pp3f4cr/feed/aaag2mdct6ntq).
