### ISSUE TITLE
Tapping the dropdown on a currently signed in account results in unwanted navigation

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#4985]
**Describe the bug**

As described in title, clicking the dropdown button in the currently signed in account results in both the opening of the dropdown and an unwanted navigation to my profile page.

**To Reproduce**

1. Open main.bsky.dev
2. Go to settings
3. Tap the ellipsis button on the right of currently signed in account

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/67e94577-714f-4fca-89ed-c6cba9d36b6f

**Details**

 - Platform:  Chrome Android
 - Platform version: Android 14, Brave 1.71.12 Chromium: 128.0.6613.40 (Official Build) canary (64-bit) 
 - App version: Build version: 1.90.0; Bundle info: dev (prod); Bundle date: 24082301; Platform: web

**Additional context**

N/A

**Comment by mary-ext** [comment]
Culprit might be https://github.com/bluesky-social/social-app/pull/4980

**Comment by surfdude29** [comment]
I can reproduce this in Safari on iPadOS.

**Comment by mary-ext** [comment]
Commit reverted, closing for now
