### ISSUE TITLE
No easy way to delete listblock records when list creator deletes/is suspended

### ISSUE THREAD

**Issue by mm14kwn** [bluesky-social/social-app#4994]
**Describe the bug**

When someone creates a block list, and users subscribe to it, if that person then deletes their account or is suspended, there's no way in app for those users to then access the list and unsubscribe/unblock. The list persists after account suspension, the list creator is suspended so can't log in to delete it, and in-app users cannot access the list to unblock it (i.e. delete the app.bsky.graph.listblock record) because the profile associated with the list creator returns an error (account taken down).

The only way currently to fix this is with direct API access - I've done it in python fairly simply (listing listblock records for a user with com.atproto.repo.listRecords, finding the ones related to the lists from suspended accounts, and running com.atproto.repo.deleteRecord from a logged in client), and there's a tutorial here on how to do it with browser API calls and a CURL client online

https://cohost.org/signpostkw/post/7429398-how-to-unblock-one-o

**To Reproduce**

1. User A creates a mod list
2. User B subscribes to that mod list with the "block" option
3. User A deletes or is suspended 
4. User B can now no longer access user A's list to unblock, but anyone on the list is still blocked

**Expected behavior**

Make the "view moderation lists" dialogue in app properly display the results of com.atproto.repo.listRecords with the app.bsky.graph.listblock NSID, even the ones from invalid/suspended DIDs, and provide a button next to each to run com.atproto.repo.deleteRecord.
Alternatively, properly delete all user lists when an account is deleted or suspended.
Alternatively alternatively, don't spuriously ban users for "harrassment " when they're trying to curate their experience by blocking lots of people, then have those same users have to write methods to fix the results of this on your buggy af website when this causes problems.

**Comment by surfdude29** [comment]
> Alternatively alternatively, don't spuriously ban users for "harrassment " when they're trying to curate their experience by blocking lots of people, then have those same users have to write methods to fix the results of this on your buggy af website when this causes problems.

GitHub doesn't seem the appropriate place to complain about moderation decisions on Bluesky, I think you need to email moderation@blueskyweb.xyz

**Comment by mm14kwn** [comment]
Yes because that's the main takeaway from this post 🙃

**Comment by stella3d** [comment]
>Alternatively alternatively, don't spuriously ban users for "harrassment " when they're trying to curate their experience by blocking lots of people, then have those same users have to write methods to fix the results of this on your buggy af website when this causes problems.

Kinew, I'd encourage you to take a more constructive tone if you're going to bring this campaign of yours here. 
The consequences of being rude and negative on here can be worse long term because you're letting everyone know they shouldn't work with you. 
 
I asked you to stop harassing me & my friends, and for that matter stop harassing the bsky devs too. This behavior is what got you banned in the first place. Please respect the ban and stop, or at least take the advice above to email the mod team instead of doing this.
