### ISSUE TITLE
Can’t override App Language anymore

### ISSUE THREAD

**Issue by bernd289** [bluesky-social/social-app#5045]
My OS/Browser language is German, but for some reason I prefer to use Bluesky in English.

https://main.bsky.dev/settings/language -> set App Language to English, everything  stays German. 

Works fine on https://bsky.app btw. 

**main.bsky.dev**
<img width="600" alt="image" src="https://github.com/user-attachments/assets/1be0cd63-c57b-43a8-a0ec-a763eddca42d">

**bsky.app**
<img width="597" alt="image" src="https://github.com/user-attachments/assets/b85ea969-5606-464a-ad56-1320df9d0e52">

**Details**

 - Platform: iPad Pro 11, iPadOS 17.6.1

**Comment by surfdude29** [comment]
I can confirm this too.

**Comment by estrattonbailey** [comment]
Probably broke in #5040, thanks for the report 👍 we'll get it fixed.

In general, we recommend using bsky.app for the most stable experience 😉
