### ISSUE TITLE
"View profile" not working

### ISSUE THREAD

**Issue by ddanielsantos** [bluesky-social/social-app#5062]
**Describe the bug**
The "View Profile" button does not seem to perform any action.

**To Reproduce**

1. Enter someone's profile
2. Go to the "Posts" tab
3. Scroll until you find a repost
4. Click on the "+" sign
5. Click on the "View profile" button

**Expected behavior**

To go to the another person's profile 

**Screenshots**

https://github.com/user-attachments/assets/1960d70e-efa7-4e50-82e8-a17c373fa8d7

**Details**

 - Platform: Android
 - Platform version:
 - App version: 1.90.1

**Additional context**

**Comment by h0lkz** [comment]
Just tested it on iOS version and it is working fine

**Comment by lukeacl** [comment]
Tested on Android. Could not replicate.

**Comment by ddanielsantos** [comment]
I tested again and could not replicate too
