### ISSUE TITLE
ios: crashing when opening the app with notifications allowed

### ISSUE THREAD

**Issue by teidesu** [bluesky-social/social-app#5100]
**Describe the bug**
/subj. no extra actions needed, it crashes as soon as the app is opened when notifications are allowed

crash log: [Bluesky-2024-09-03-040430.ips.json](https://github.com/user-attachments/files/16842272/Bluesky-2024-09-03-040430.ips.json)

**To Reproduce**

- log into the app
- allow notifications

**Expected behavior**

it doesn't crash

**Details**

 - Platform: ios
 - Platform version: iOS 18.0 (22A5350a)
 - App version: 1.90.1

**Additional context**

disallowing notifications in ios settings fixes the crash on startup, but it still crashes when opening the notifications tab

**Comment by teidesu** [comment]
this might be related to the fact that i use a `did:web` account:

- download the app
- log into `did:web:tei.su` account
- it crashes on launch

- download the app
- log into a `did:plc` account on the same pds
- log into `did:web:tei.su` account
- log out of the `did:plc` account
- everything works fine

**Comment by haileyok** [comment]
is this still happening to you? i am unable to repro

**Comment by teidesu** [comment]
> is this still happening to you? i am unable to repro

yep, still happening on iOS 18.1 (22B5045g), app 1.91.1.464 2feb5be.

screencast: https://github.com/user-attachments/assets/15b8bbf3-0292-4cb2-b4cb-1c3463b6a264

**Comment by haileyok** [comment]
Are you able to scroll down the notifications at all on web to see if there's a weird post or anything?

**Comment by haileyok** [comment]
Ah, never mind. I'm able to see some logs now, though this is quite bizarre. Need to figure out how to possible reproduce this, not entirely sure how yet... Will keep you posted.

**Comment by Erisa** [comment]
This happens to me exactly as described on my account with handle `@erisa.mraow.party` (using my own PDS) but not on my account `@erisa.uk`. Web works perfectly fine. Would be more than willing to provide any debug information or logs if you can share how I can do that!

**Comment by teidesu** [comment]
yep, im using my own pds as well. though i did test with a bsky.social account and it happened it there as well so i figured it's not that relevant

**Comment by haileyok** [comment]
@Erisa @teidesu Yea, that's what I observed as well. I'm trying to get to the bottom of that, but there's pretty much nothing that stands out as to why it would be effecting only your own PDSes...Still digging at it though!!

**Comment by haileyok** [comment]
The strange thing is that I'm running my own PDS as well and don't have any issue there. What PDS versions are you all running? (https://pds.haileyok.com/xrpc/_health will tell you)

It's definitely something with the `registerPush` endpoint. If either of you could use something like Proxyman to see what the response is for that request it would be super helpful!

**Comment by teidesu** [comment]
> What PDS versions are you all running?
0.4.51 for me

> It's definitely something with the `registerPush` endpoint. If either of you could use something like Proxyman to see what the response is for that request it would be super helpful!

<img width="561" alt="image" src="https://github.com/user-attachments/assets/ab1a8cd7-964a-4f59-9e49-79c86d1ba048">
with notifications disabled i don't see a registerPush at all

with them enabled the app seems to crashes before the `registerPush` returns anything. the request also seems to be fine?
<img width="803" alt="image" src="https://github.com/user-attachments/assets/d5903dc0-bc6f-46dd-bb08-ea046ad56269">

**Comment by haileyok** [comment]
Yea, that could actually be useful if you don't mind.

**Comment by teidesu** [comment]
dmed on bluesky

**Comment by haileyok** [comment]
So strange! Was able to get a backtrace now though, thank you! Going to start digging

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1e007fa58'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804b70ec __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008ede8 objc_exception_throw + 72
	2   CoreFoundation                      0x00000001804ccc54 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001804bb3ec ___forwarding___ + 1268
	4   CoreFoundation                      0x00000001804bdb0c _CF_forwarding_prep_0 + 92
	5   Bluesky                             0x00000001024317c8 __52-[RCTFileReaderModule readAsDataURL:resolve:reject:]_block_invoke + 152
	6   libdispatch.dylib                   0x0000000104714ec0 _dispatch_call_block_and_release + 24
	7   libdispatch.dylib                   0x00000001047167b8 _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x000000010471eaac _dispatch_lane_serial_drain + 912
	9   libdispatch.dylib                   0x000000010471f7b0 _dispatch_lane_invoke + 420
	10  libdispatch.dylib                   0x000000010472c1f0 _dispatch_root_queue_drain_deferred_wlh + 324
	11  libdispatch.dylib                   0x000000010472b75c _dispatch_workloop_worker_thread + 732
	12  libsystem_pthread.dylib             0x0000000103cc7b74 _pthread_wqthread + 284
	13  libsystem_pthread.dylib             0x0000000103cc6934 start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by haileyok** [comment]
Well, I found the issue - at least, what's causing the crash. I'm not sure what exactly is going on aside from that yet.

Anyway, there are two endpoints that are causing the crash: `registerPush` and `updateSeen`. Both of these have an empty response body.

There's a check in https://github.com/facebook/react-native/blob/1288e38423f93ed57737dd9b40ad55696494d6f4/packages/react-native/Libraries/Blob/RCTFileReaderModule.mm#L76 for `type` (I have not dug closely yet to see where exactly it comes from yet) which for me is `text/plain`. However, on your PDS the `type`  is `NSNull`.

Note that the `type != nil` check won't do anything here because its `NSNull` rather than `nil` 🙃. Wondering if something might have changed in `RCTConvert` that ended up causing this, not quite certain yet. This seems like a weird RN bug in general anyway regardless of what else we find out...

Anyway, I'm also curious why `type` is different for the two of us (and I'm assuming also for @Erisa). Not sure if you have any ideas.

**Comment by haileyok** [comment]
After more closely looking, it looks like there's a `x-content-type-options nosniff` header on the response from your PDS @teidesu. This is probably what's tripping up ^

@Erisa, I'd be curious if you see the same header in your response. I'm going to patch/PR a fix for the RN crash itself, but also trying to figure out where that header is coming from since it shouldn't be there for these responses.

**Comment by teidesu** [comment]
> trying to figure out where that header is coming from since it shouldn't be there for these responses

i believe it's being added by cloudflare, since accessing the reverse proxy directly doesn't return that header:
<img width="569" alt="image" src="https://github.com/user-attachments/assets/bad08a08-dcf2-456b-ab37-cb1b2ecb626f">

**Comment by haileyok** [comment]
Interesting! Well, if you figure out how to remove that header in the short term then that should fix the problem. Otherwise, I'm going to write a fix and it'll come out in the next release. Thanks for all your help in debugging this!

**Comment by Erisa** [comment]
I have no idea why Cloudflare adds that header, but this works: 
![image](https://github.com/user-attachments/assets/0aa71c81-0e4e-4f08-b32c-bc460b9c00b0)

on https://dash.cloudflare.com/?to=/:account/:zone/rules/transform-rules/modify-response-header

**Comment by haileyok** [comment]
Also fixing this in https://github.com/bluesky-social/social-app/pull/5475. Will be a couple days at least before it makes it out. Seriously appreciate all your help in getting this debugged.

@teidesu You can go ahead and delete that test account or whatever. Shouldn't need it anymore 🙏 (I can actually repro myself now by adding this header 😆)
