### ISSUE TITLE
Hashtags not turning into links when sent from API

### ISSUE THREAD

**Issue by jesusjimsa** [bluesky-social/social-app#5111]
**Describe the bug**

I created [@beatleslyricsb.bsky.social](https://bsky.app/profile/beatleslyricsb.bsky.social), a bot that posts beatles lyrics every hour. At the end of every message, I add a #TheBeatles hashtag but it is not turning into a link to other messages with the same hashtag.

**To Reproduce**

**Expected behavior**

I send a message with the hashtag text and the client turns it into a link to other messages with the same hashtag.

**Screenshots**

These posts from my account have the hashtag but it is not a link:
![image](https://github.com/user-attachments/assets/c0528544-d40c-40d8-a354-35ed6a1ae54e)

This other post from Astronomy Picture Of the Day shows the hashtag as a link:
![image](https://github.com/user-attachments/assets/c6a6a635-aa00-4d92-ae52-a43bfaa54f44)

**Details**

 - Platform: 
 - Platform version:
 - App version:

**Additional context**

This is the code I use for sending the posts:
https://github.com/jesusjimsa/beatles-lyrics-every-hour/blob/master/beatles_lyrics_bot.py#L67-L83
```python
    post = {
        "$type": "app.bsky.feed.post",
        "text": text,
        "createdAt": now,
    }
    post["langs"] = ["en-US"]

    resp = requests.post(
        "https://bsky.social/xrpc/com.atproto.repo.createRecord",
        headers={"Authorization": "Bearer " + session["accessJwt"]},
        json={
            "repo": session["did"],
            "collection": "app.bsky.feed.post",
            "record": post,
        },
        timeout=10,
    )
```

**Comment by matheusrod92** [comment]
Hi @jesusjimsa, I think that for you problem you might need to use [facets ](https://docs.bsky.app/docs/advanced-guides/post-richtext#rich-text-facets) to enrich the content you're sending to create the post. Looking at the docs I could find three facet options and for your case you would need to use the tag one `app.bsky.richtext.facet#tag`.

The only problem is that [here](https://docs.bsky.app/docs/advanced-guides/posts#mentions-and-links) they say that the facets are only working for `mentions` and `links` but I would give it a try anyway.

In the last link I've sent they show some examples on how to send a payload containing facets, good luck man 😉

**Comment by jesusjimsa** [comment]
Thank you very much @matheusrod92, that fixed it. 👏 👏

**Comment by ds4cabs** [comment]
I would like to know if links posted using this method will generate a preview. While the posts I create using the API are clickable, they do not display a preview. Could you clarify whether link previews are supported or if there are specific requirements to enable them? 

Thanks,

**Comment by HelloPackets89** [comment]
Similar to @ds4cabs  I would also like my posted links to produce link cards
