### ISSUE TITLE
Rich Text profile name bug in (reposted by) section - maybe in other places as well

### ISSUE THREAD

**Issue by whoisanku** [bluesky-social/social-app#5114]
**Describe the bug**

**Details**

 - Platform: 

**screenshot**

![image](https://github.com/user-attachments/assets/eb6b25a8-0353-4def-9460-db5dca836396)

**Comment by fabiohcnobre** [comment]
@whoisanku  
Help us better identify your error.
Because I tested via iOS and web I was unable to reproduce it.
We need more details about the error.

**Comment by whoisanku** [comment]
@fabiohcnobre hey sorry. I'm putting up an issue from my mobile GH app so probably my detailed info hasn't gotten there in an issue. 

But it seems like accounts with Profile Name which has rich text format (probably called like it) has some issues while displaying on iOS app (not sure on other devices or about web app).

Here is another screenshot while searching such accounts:

![image](https://github.com/user-attachments/assets/8b15a849-db95-498e-99ed-52d0ff70cfd5)

**Comment by fabiohcnobre** [comment]
Now I have managed to replicate the error.

However, there is something about your special characters.

If you write normally, Maria will adjust it.

**Comment by whoisanku** [comment]
Yeah I mean it's not me. But found a bug and thought to create an issue here.

**Comment by gabrieleiro** [comment]
The character from this example that triggers the bug is "꧑". It displays normally on web and after some investigation I suspect this is a bug in React Native (https://github.com/facebook/react-native/issues/29507). There's people working on a PR for it, so this can get solved in their end.

**Comment by whoisanku** [comment]
Ah nice! @gabrieleiro re-looking over this & closing this issue now.
