### ISSUE TITLE
[Embeds] Dark/night theme

### ISSUE THREAD

**Issue by ghost** [bluesky-social/social-app#5119]
I'm testing Bluesky embeds, and unless I'm missing something, there doesn't seem to be any support for a 'dark' or 'night' theme:

![image](https://github.com/user-attachments/assets/6adaaa4a-c3e1-48b2-998a-28e306738852)

This results in embeds looking quite garish when on pages with dark themes.

**Describe the solution you'd like**

Ideally I would like for embeds to respect the light/dark theme setting of the page/browser/system, like Twitter/X embeds do:

![image](https://github.com/user-attachments/assets/eb8d345f-8ead-4d94-aad0-f8b819f6c893)

![image](https://github.com/user-attachments/assets/5db8f63d-7b3a-4c87-8c2c-5c7d549c418b)

Bluesky's clients already have a good 'dim' theme that color values can be borrowed from for this.

**Comment by benharri** [comment]
would very much like to see this
