### ISSUE TITLE
search language filter stopped working

### ISSUE THREAD

**Issue by jonolds** [bluesky-social/social-app#5161]
**Describe the bug**
non-english posts are showing up in searches with "lang:en"

**To Reproduce**

Search for a proper noun and see that it returns results in multiple languages. then search it again with "lang:en" and see that a lot of non-english results are still there.

I'm using the latest version of web.

**Screenshots**

![image](https://github.com/user-attachments/assets/8f408293-e5f2-4ee8-8192-4e69c762fee6)

**Comment by mary-ext** [comment]
Unfortunately that's correct, the posts are being tagged with the English language code

**Comment by vvvvvvitor** [comment]
> Unfortunately the search is correct, it's the posts are being tagged with the English language code

How does the tagging work? Does it just take  the system's language and tags the post the same?

**Comment by mary-ext** [comment]
Correct, default post language is system locale.

We do use an [NLP model](https://www.npmjs.com/package/lande) to guess what the post is written in and show a banner recommending to switch language if the confidence is high, but it's not very reliable unfortunately.
