### ISSUE TITLE
Starter Pack limited scroll

### ISSUE THREAD

**Issue by ljstella** [bluesky-social/social-app#5174]
**Describe the bug**
There appears to be an issue with the list of users in a starter pack preventing you from scrolling all the way to the bottom of the list.

**To Reproduce**

1. Go to this starter pack: https://go.bsky.app/JvFS98y
2. Scroll to the bottom
3. Observe the last person is partially cutoff (this may be dependent on screen size or the length of bio of the last person, or the height of all of the boxes, haven't reproduced yet with other feeds), which can be observed on mobile by scrolling past the end.

**Expected behavior**

Each row will have a full height that includes the user's bio without it being hidden behind other UI elements

**Screenshots**

https://github.com/user-attachments/assets/05145fd0-586e-4364-b611-289f867ed17a

**Details**

 - Platform: iOS
 - Platform version: 17.6.1
 - App version: Build version: 1.90.1.417; Bundle info: 5f2c81ca6 (prod); Bundle date: 24090211; Platform: ios

**Comment by swxxii** [comment]
I have this bug as well. 
iOS 18.0 beta(22A5350a). 
iPhone 15.
