### ISSUE TITLE
Cards fail to generate for my website on bluesky and only bluesky (CardyB issue?)

### ISSUE THREAD

**Issue by Kayinnasaki** [bluesky-social/social-app#5249]
This occurs on the web version of blueskys, both in firefox and chrome, as well as the app.

For the sake of an example I am using the article https://kayin.moe/funeral-song but this applies to anything I try to link from there.

![image](https://github.com/user-attachments/assets/54057a88-b2bc-47ea-b943-2fcd1278f49e)

Originally there were CORS issues that I had to fight around which got things partially working a few months ago, but now cardyb returning.

```
https://cardyb.bsky.app/v1/extract?url=https%3A%2F%2Fkayin.moe%2Ffuneral-song
{"Error":"invalid URL: host IP"}
```

I am at a loss. The website works. I tested the link cards on every service I had easy access too, working on twitter, tumblr, cohost*(rip)*, discord, and mastodon.social, as well as any random card checkers I could find on the internet, with no issue. I can link to other sites fine. I've had someone on the other side of north America try my stuff on their end, so clearly this is a bluesky issue.

**Comment by Kayinnasaki** [comment]
Messing around on my end to at least try and get stuff to work, regardless of any underlying implementation bug like "okay maybe I have have the IP be a valid server alias that redirect, even though this should not be a problem??" and yeah sure that didn't work, but I find out that it'll take the IP address raw and generate a card, but not off the URL 🙃

I have wasted far too much time, and risked breaking too much stuff randomly changing server variables for something that should just work. This is extremely frustrating.

**Comment by Kayinnasaki** [comment]
So this turned out to come from an IPV6 misconfiguration. While it's good that this helped me eventually id a problem, the fact this was not a problem anywhere else seems not great still. I'm not sure how other sites do it -- do they poll IPV6, see a problem, then try 4? Or do they skip 4 in general? I feel like staying close to results other websites get is the best move here.

Oh well, at least I managed to fix my cors issue too while I was at it.

**Comment by miyurusankalpa** [comment]
neither cardyb.bsky.app or kayin.moe have AAAA records with IPv6 address. I don't think this was IPv6 related.

**Comment by Kayinnasaki** [comment]
That's because my IPv6 address was wrong and instead of adding the correct IPv6 address, I simply removed the record.

**Comment by Djmill** [comment]
@Kayinnasaki thanks for posting about this, I finally was able to track down the root cause of why Slack and Bluesky would not allow URL unfurling, but Facebook and other 3rd-party services did. This saved me a lot of time after spending way too much time previously debugging with no luck 🎉 

For other folks who come across this, check your DNS settings on your host and Cloudflare (if you use that), as AAAA records might be defined in both places. To check that it's been fully cleared you can run the following command after your default TTL has expired:

`dig AAAA <domain_name> @8.8.8.8`

If `ANSWER: 0` is returned, your AAAA record has been cleared from the cache and requests should start flowing again.

**Comment by miyurusankalpa** [comment]
To anyone confused, they both had private IPv6 address in the AAAA records.

From: https://dnshistory.org/dns-records/myhikes.org
![Image](https://github.com/user-attachments/assets/90ed408a-7a5c-4f7f-b459-4b903db0dd67)

![Image](https://github.com/user-attachments/assets/5fb6bb5c-422e-47ea-ba6e-9b5b91e3e67a)

I made a tool to check such issues easily. https://v6check.miyuru.lk/
