### ISSUE TITLE
"Following Feed" is showing replies between Followed users and strangers in specific case: when the original post belongs to a Followed user

### ISSUE THREAD

**Issue by HeyItsLollie** [bluesky-social/social-app#5288]
Bluesky on Web and Mobile, 1.91.

I follow User A, but do not follow User B.

**Case 1:** User B makes a post, and User A replies to it.
I do not see this interaction on my timeline. Based on recent changes to how the Following Feed works, this is working as expected. ([Context](https://bsky.app/profile/bsky.app/post/3l2s5t6op2w2x) — Users should only see interactions between other users when they follow two or more of them.)

**Case 2:** User A makes a post. User B replies to the post, and User A responds.
I see this interaction between User A and User B on my timeline. I see this occurring consistently, but the behavior itself is inconsistent with the change described above.

This is likely contributing to a lot of the confusion that users have regarding these recent changes. (including myself, as it initially sparked me to post #5262)

**Comment by surfdude29** [comment]
Posts that fit **Case 2** show up in Following as a result of the changes in #5049, but note that they will only show up if the post from User B that User A is replying to has at least 1 like.

**Comment by HeyItsLollie** [comment]
This seems counter-intuitive to how it was described on Bluesky, and I'd argue it undermines why this change was made in the first place. If I don't follow User B, I shouldn't be able to see their reply on my feed — period. I should have to focus on User A's post directly in order to see it.

(The obvious exception here is is if User A were to repost User B's reply - This interaction makes it explicitly clear to me AND to User B that their reply has been given more exposure.)

**Comment by surfdude29** [comment]
I'm not sure I can explain the reasoning better than @gaearon did.

I guess to me it feels like because it's a reply by the OP (User A) in a thread that they started to a post that has at least 1 like, it feels like it would be more likely to be relevant and to be of interest, and therefore it seems to make sense to show it in Following.

**Comment by HeyItsLollie** [comment]
Honestly, I don't think many users would connect "I like this post" to "I am actively choosing to broadcast this post to my followers." That like could be given out simply due to User A being the kind of user who uses likes as an acknowledgement or throwaway engagement. And if it's just 1 Like regardless of who gives it, then that like could be given away by anyone, making it completely irrelevant to the conversation. This check just feels kind of meaningless.

And then again, it goes against how the Following Feed's behavior has been supposedly tweaked. It should be as straight-forward as it was described. It just doesn't make a lot of sense to add this additional, effectively-invisible filter to have Bluesky guess what counts as a "relevant" post that deserves more exposure, when there's already clear and intentional ways for both User A and User B to achieve this:

- If I'm User A, and User B has said responded with something that I want to share with my followers, I can repost their reply.
- If I'm User B, and I want to respond to User A in a more public manner, I can quote User A's post with my reply.

**Comment by meh424242** [comment]
Thankfully, they are reverting #5049 change with #5301
