### ISSUE TITLE
Video downloads when autoplay is off

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#5290]
**Describe the bug**
Even when autoplay is off, videos are downloaded to the device. This is significant where a device is on a metered/low bandwidth connection, incl. mobile.

**To Reproduce**
Turn off autoplay and browse to any video.

**Expected behavior**
Video should not download automatically; or this should be manageable somehow.

It does seem like `preload="none"` is set on the video, so this may be a platform behaviour bug, reproduced on Chrome and not sure of the behaviour on mobile (though it does seem to be preloading - I have <1Mbit/s on my device and it immediately struggles scrolling past video). The spec recommendation is `preload="metadata"` which may be worth looking at?

**Details**
 - Platform: Chrome
 - Platform version: 128
 - App version: 1.91

**Comment by haileyok** [comment]
Yea, we didn't have much control over this in the library we eagerly shipped. I've addressed this here.

https://github.com/bluesky-social/bluesky-video/commit/af97cda8d352187adfefdba252f67278f6aefc4d
https://github.com/bluesky-social/bluesky-video/commit/b8c8a99e8aff09d08d7167180861c8b05b1b46fa

Will get it out in next release 👍 appreciate it
