### ISSUE TITLE
Share Extension only accepts photos

### ISSUE THREAD

**Issue by knotbin** [bluesky-social/social-app#5309]
**Describe the bug**

Although video is now supported, the iOS Share Sheet Extension still only accepts photos and when sharing a video, Bluesky's extension does not show up. 

**To Reproduce**

1. Tap "Share" on any video (eg. in the photos app)
2. Scroll the app extensions and tap "More"
3. Bluesky is not listed

**Expected behavior**

Bluesky's extension should accept videos when a user has access to video.

**Details**

 - Platform: iOS
 - Platform version: 17.6.1
 - App version: 1.91

**Comment by AdrianoCahete** [comment]
Same for Android (Galaxy Gallery)

Details
    Platform: Android
    Platform version: 14 (OneUI 6.1)
    App version: 1.91.0
