### ISSUE TITLE
Pause button does not appear for videos in feed in Android

### ISSUE THREAD

**Issue by erinleeryan** [bluesky-social/social-app#5325]
**Describe the bug**
If a user with an Android device with autoplay turned OFF clicks play on a video in their feed, only the video time counter appear along with the mute/unmute status icon, but importantly the pause button does not appear (see screenshot)

**To Reproduce**

1. Find video in feed, click play
2. As video plays see there is no pause button!

**Expected behavior**

As a user I expect a pause button so I can stop the video from playing.

**Screenshots**

![SmartSelect_20240913_120531_Bluesky](https://github.com/user-attachments/assets/84b1e177-b69d-41be-83ed-c272ac48b0db)

**Details**

 - Platform: Android
 - Platform version: Android Version 14 on a Samsung Galaxy S24
 - App version: 1.91.0.307 85acda13f (prod)

**Additional context**

Also: when video selected/embiggened option buttons appear such as pause and minimize, but if a video is paused and then minimized to go back to feed the video continues playback in the feed.

**Comment by haileyok** [comment]
We added this in 👍 should be available on monday.
