### ISSUE TITLE
Add audio volume slider to videos

### ISSUE THREAD

**Issue by netux** [bluesky-social/social-app#5336]
**Is your feature request related to a problem? Please describe.**

Currently, the video player only has a mute and unmute button. This works well, however, some videos may be too quiet or too loud, and there is no way to adjust their volume on the app.

Audio sliders are pretty much standard for video players. YouTube has them, Discord has them, and even the browser's native \<video> and \<audio> elements have them. 

This is more a problem on the web in desktop, where there isn't usually quickly accessible button to lower the volume of the device. Browsers don't tend to have a per-tab/domain volume slider, and the OS volume sliders either let you semi-quickly lower the volume of the whole OS (which is overkill), or have you going through submenus to lower the volume of a specific app (browser).

**Describe the solution you'd like**

- Design
  - **On the web**:
    ![Volume slider on YouTube](https://github.com/user-attachments/assets/bd7c52b5-cd48-4f44-b243-db3bf615c291) ![Volume slider on the browser native \<video> element](https://github.com/user-attachments/assets/5fe2a383-838f-4f0f-9d14-6e812eeb6668) ![Volume slider on Discord](https://github.com/user-attachments/assets/0ad0a5cd-cfbd-4f23-a309-58d550b0d2fd)

    Volume slider is positioned next to the speaker icon (which doubles as a quick mute/unmute button). The slider is usually hidden by default, only appearing when user hovers or focuses over the speaker icon.

  - **On mobile**:
    Due to the cramped nature of mobile screens, sites don't tend to show volume sliders for them. This is not much of a problem because there are usually quickly-accessible side buttons on device to change the volume of the entire OS (sometimes, like on modern Android versions, also providing a volume slider for the currently open app).
   I think its fine if the volume slider is not present on mobile, and people in general are used to this design too.

- Functionality
  - Clicking anywhere on the slider immediately changes the volume of the video to the equivalent position of the cursor. Additionally, putting the cursor over the slider and using mouse wheel increases/decreases the volume accordingly as well.
    For accessibility, the slider can be focused. In which case, the arrow keys can also be used to move the slider and change the volume.
  - One important factor that a lot of places miss is that audio perception isn't linear. And by making it linear, most of the slider becomes useless.
    There is a great blog post by Dr. Lex explaining the issue in detail, and providing the following simple, cheap logarithmic conversion:
    ```ts
    video.volume = Math.pow(slider.value /* in the range [0, 1] */, 4);
    ```
  - The volume set on one video should sync with any other videos watched in the future. It could be either stored forever (i.e. in `sessionStorage`), or only for the current session (i.e. stored in `sessionStorage`) and returned to a default value next time the user loads the app.
  - Default value could be whatever. Personally, I think 50% is a good spot, but most other webapps use 100%.

**Describe alternatives you've considered**

I normally either use a browser extension called [Volume Master](https://chromewebstore.google.com/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke) (which resets after the tab is closed, and screws with fullscreening) or, if the site is particularly egregious in its lack of volume controls, I create my own userscript to add a volume slider myself.

Both options work for me, but it is cumbersome and annoying that websites tend to not provide volume controls on their own.

**Additional context**

Lack of volume slider in BlueSky:
![Hovering over the speaker icon on video players in BlueSky doesn't show any volume controls](https://github.com/user-attachments/assets/fa5dea59-11ed-4f50-b0e9-b91cd93fbfb1)

**Comment by dolciss** [comment]
same #5285

**Comment by netux** [comment]
GitHub's search is so bad, I completely missed that 🤦
Closing this in favor of the other #5285 .
