### ISSUE TITLE
[Video][Android] Player instance itself with non-muted then change

### ISSUE THREAD

**Issue by AdrianoCahete** [bluesky-social/social-app#5350]
**Describe the bug**

Player seems to instance itself with default settings, then load settings and change to muted. Not a problem if you're not hearing anything, but a problem if you're hearing podcasts or any music that pauses when other media starts. 

**To Reproduce**

1. Open any media player that stops if any other media starts (~~I'm using Podcast Addicted, but I think that YouTube do the same, need to test~~. Tested with YouTube and Spotify either. Both has the same behavior) 
2. Go to App, find any video on feed, then mute it. 
3. Continue scrolling now with first audio playing
4. You can see that in any new video that shows on timeline, media will pause for a second or two, then will start again, after video in app starts to play in mute. 

**Expected behavior**

If player is muted, it needs to start muted so does not interrupt other media played by user. 

**Video**

I will record as soon I'm back home because upload will be a hell to make in mobile connection 

**Details**

 - Platform: Android
 - Platform version: 14 (OneUI 6.1.1)
 - App version: 1.9.0

**Comment by haileyok** [comment]
I think this might be fixed in https://github.com/bluesky-social/social-app/pull/5373, we'll see! (Will try to get the update out today)
