### ISSUE TITLE
Video on mobile becomes squished

### ISSUE THREAD

**Issue by SpriterGors** [bluesky-social/social-app#5382]
**Describe the bug**
On mobile: The thumbnail on the video when it is not playing displays correctly. Upon playing it, however, it will play in a squished format. Fullscreen mode functions as intended. This happens either in a Feed, or viewing a single post.

**To Reproduce**
Simply find a video that is taller than wide and start playback.

**Expected behavior**
If the video size does not trigger any crops, then it should play without being squished.

**Screenshots**

1. Video thumbnail displaying correctly:
![Sem título](https://github.com/user-attachments/assets/112f02d6-9f54-4bed-bf8f-0d98966c30e4)

2. Upon clicking it, the video is noticeably squished.
![Sem título](https://github.com/user-attachments/assets/dd4b6c96-d46b-4892-bdd9-c3e2b2d0ae77)

**Details**

- Mobile (Android J7)
- App version: 1.91.1.317 fb71fffb3 (prod)

**Comment by haileyok** [comment]
Yea, this is fixed here https://github.com/bluesky-social/social-app/pull/5373. Will try to get it out today. Sorry bout that.

**Comment by haileyok** [comment]
@SpriterGors fixed now in the latest release (1.91.2)!
