### ISSUE TITLE
Clearer content warning button in the composer

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#5383]
**Is your feature request related to a problem? Please describe.**

It's not immediately clear that you can manually add content warning to images and videos, lots of NSFW content gets posted to Bluesky without the appropriate content warning attached.

While Bluesky's auto-moderation can usually get to them, we shouldn't teach users to heavily rely on this behavior. **_Automod does not happen immediately, and it's also not perfect_**.

**Describe the solution you'd like**

Move the content warning button to be below the image/video, and make it really apparent. Below is an example.

<img src=https://github.com/user-attachments/assets/bf08e88d-3983-4db1-ac2b-621f115bc731 width=300>

**Describe alternatives you've considered**

NUX might teach users but I don't think it's something that should only be shown once kind of thing.

**Additional context**

N/A

**Comment by brawaru** [comment]
This is needed right now more than ever, with so many artists rushing from X, where people used to not label anything. The feeds are drowning in unlabelled NSFW, and automod doesn't seem to catch up, especially with arts. According to Bluesky Terms of Service, it allows minors to use the platform, and this is kinda horrifying considering the current state of things.

For suggestion, I think it would be worth changing icon to something better though, the shield kind of gives some privacy/security vibe and not as catchy, easy to gloss over. Maybe [`siren`](https://lucide.dev/icons/siren) (this one seems to be the best option), [`message-circle-warning`](https://lucide.dev/icons/message-circle-warning) or [`eye`](https://lucide.dev/icons/eye) + [`eye-closed`](https://lucide.dev/icons/eye-closed)?

**Comment by mary-ext** [comment]
Fixed in https://github.com/bluesky-social/social-app/pull/5780
