### ISSUE TITLE
Chat is missing from the drawer

### ISSUE THREAD

**Issue by electricduck** [bluesky-social/social-app#5413]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

This is one of these incredibly nit-picky issues, but on mobile view, **Chat** is not duplicated in the drawer like other items in the snackbar. (**Home**, **Search**, **Notifications**, **Profile**). Do sometimes open this sidebar looking for stuff and stumble trying to open Chat.

**Additional context**

##### Drawer (`1.91.1`)

![image](https://github.com/user-attachments/assets/b772cfc2-4737-480f-a5c4-7d4adb185d94)

> **Chat** is missing here

##### Snackbar (`1.91.1`)

![image](https://github.com/user-attachments/assets/725e2501-120b-45c1-b114-f3930a550860)

**Comment by surfdude29** [comment]
Fixed by #5761
