### ISSUE TITLE
2FA code received in email is formatted incorrectly.

### ISSUE THREAD

**Issue by damiensedgwick** [bluesky-social/social-app#5448]
**Describe the bug**
If I try to sign into an application, in a browser on iOS and using oauth, the 2FA code that gets sent through to my email has incorrect letter casing so when I copy and paste it, the UI just tells me the code is in an incorrect format.

**To Reproduce**

1. Try to sign in on https://frontpage.fyi using a mobile browser
2. Enter your handle
3. Enter your password
4. Await the 2FA code to arrive in your emails
5. Try to use the code

**Expected behavior**

The 2FA code should be provided in a format which means I can simply copy and paste it.

**Screenshots**

![image](https://github.com/user-attachments/assets/3cd362be-f132-4618-bb1b-15cfde0fe926)

![image](https://github.com/user-attachments/assets/00c7573b-a3d4-4e85-8c5b-e29daf4034a4)

**Details**

 - Platform: 

Using iOS and chrome browser. 

**Additional context**

**Comment by tom-sherman** [comment]
It's so weird to me that iOS seems to copy the display value (post `transform-content: lowercase`) and not the underlying markup.

**Comment by tom-sherman** [comment]
Tbf it's also weird to me that the email includes it in lowercase but this isn't accepted by that UI.

**Comment by tom-sherman** [comment]
This is only an issue with the oauth login flow right? Lowercase codes work on the regular login page?

**Comment by damiensedgwick** [comment]
I also get the same on macOS using safari:

![image](https://github.com/user-attachments/assets/67cadd32-07c6-4c0b-ae40-bc3414e9fea8)

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/1ebf6eb7-ecdc-435c-893e-4c19583a48c6">

**Comment by damiensedgwick** [comment]
@MarshalX I assume not as I tested shortly after the merge and it was still an issue. I imagine the next release should deploy it.
