### ISSUE TITLE
More powerful mute

### ISSUE THREAD

**Issue by goeo-** [bluesky-social/social-app#5455]
Hey all! This is a feature request, but I'm also happy to take a crack at it myself if the team would consider the feature being included in the app - this issue is very much in the spirit of "Open an issue and give some time for discussion before submitting a PR." from the readme.

**Is your feature request related to a problem? Please describe.**

Mutes are a very cool client side tool for not just personalised moderation, but also for curating your content experience, allowing you to choose what you want to see and what you prefer to avoid, even if it’s not inherently harmful.

One argument against making mute more powerful might be the existence of labelers. If anything, they can have access to more information to make their judgement. However,
- they require some technical knowledge to make, meaning this is not an option for most users (I expect my proposal to be more approachable for power users who may not be programmers, for example), and
- as the network grows and the rate limits stay the same, just labeling every post that matches some criteria is becoming less and less feasible.

**Describe the solution you'd like**

My current proposal is adding more options to "Mute in" (currently limited to "text and tags" and "tags only"):
- post record
- app.bsky.feed.defs#postView as received from the app view
- possibly also feedViewPost, threadViewPost

These would search all of the data represented as JSON by default, and optionally take a jq filter (or something similar) to search a specific part. 

Additionally, I would propose adding a "muteword is regex" option for even more flexibility.

**Describe alternatives you've considered**

I haven't considered too many alternatives if we agree that making mute more powerful is a good idea - definitely open to ideas here.

I've mentioned why I don't see labelers as an alternative.

**Additional context**

[The GIF labeler](https://bsky.app/profile/did:plc:mjyeurqmqjeexbgigk3yytvb) has been dead since Brazil joined the website, and I really don't like Tenor. If this was implemented, a mute filter for it could look like:

**Mute in:** post record
**jq filter:**  .embed.external.uri
**mute word:** media.tenor.com
**regex?:** no

As another example, I'm always frustrated when I try to link a post and its author happens to have the !no-unauthenticated label. If my friends without accounts shouldn't see the post, I don't want to either. Here's a mute filter for that:

**Mute in:** postView
**jq filter:**  .author.labels[].val
**mute word:** !no-unauthenticated
**regex?:** no

**Comment by goeo-** [comment]
Looking a bit more at the options something like https://github.com/jg-rp/json-p3 might be better

**Comment by imax9000** [comment]
Overall I don't think it's a good idea. Filters that can have large variation in CPU cost make the service more susceptible to performance issues: now your latency greatly depends on the specifics of the data, not just the volume.

Data model here is known in advance and controlled, so addressing specific issues more directly is feasible and less likely to backfire.

-----

> Additionally, I would propose adding a "muteword is regex" option for even more flexibility.

I'd strongly advice against using regexps. They can be very expensive to evaluate, and in 99% of cases [glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)) would suffice.

> As another example, I'm always frustrated when I try to link a post and its author happens to have the !no-unauthenticated label. If my friends without accounts shouldn't see the post, I don't want to either. Here's a mute filter for that:

This is better solved by converting these "magic" labels into proper labels, and providing appropriate UI for self-labels.

**Comment by goeo-** [comment]
Maybe it's a good idea to try to be explicit about performance implications, but this is all happening on the client, and imo the user should be given the option.

**Comment by goeo-** [comment]
I seriously think this is a non issue, have you seen how they do the following feed
