### ISSUE TITLE
Share Extension - some images show up as file URLs

### ISSUE THREAD

**Issue by jaronheard** [bluesky-social/social-app#5492]
**Describe the bug**

Some images images show up as file URLs instead of images when shared through the share extension. Note, I have a fix shared in additional context.

**To Reproduce**

1. Open a photo in iMessage by tapping on it
2. Share to Bluesky from that view
3. Observe that the share content is file:///... and not an image

**Expected behavior**

The image shared is the image and not a file:/// link

**Screenshots**

<img src="https://github.com/user-attachments/assets/b53442f5-90b4-42b9-9797-d0b63a03d8d1" height="450">

**Details**

 - Platform: iOS
 - Platform version: 18.1
 - App version: 1.91.1.464 2feb5be (prod)

**Additional context**

I am using an adopted version of the bluesky share extension code for my app and fixed this by reordering the if statement that checks the content type to put the URL check last ([PR](https://github.com/jaronheard/soonlist-turbo/pull/219))

Tagging @haileyok since this is your work and saw in an in-flight PR [in-flight share extension PR](https://github.com/bluesky-social/social-app/pull/5466)... hope this is helpful since your code helped me!

**Comment by surfdude29** [comment]
I can reproduce this on iOS 15.8.3 and iOS 17.7.

**Comment by haileyok** [comment]
Lets try to fix...

**Comment by haileyok** [comment]
Got it! Thanks for flagging that @jaronheard!
