### ISSUE TITLE
Round down follower count instead of up

### ISSUE THREAD

**Issue by vertigris** [bluesky-social/social-app#5538]
**Is your feature request related to a problem? Please describe.**

Right now the app rounds up follower counts leading to situations where someone celebrates a milestone even though they have't reached it yet. As an example, my app says I have 15k followers but when I check on web it says 14.987. Which isn't a huge problem but it's kind of weird.

**Describe the solution you'd like**

Instead of rounding up, it should round down. So when I'm at 14.987, it should say 14.9k instead of 15k.

**Comment by mary-ext** [comment]
This is supposed to have been fixed but for some reason the polyfill that's being used to get proper NumberFormat functionality on mobile is uh.... not working?

https://github.com/bluesky-social/social-app/commit/4d39ef2e19632eddc1a31a5b41078f6e40b92fbc

**Comment by mary-ext** [comment]
This should be fixed with https://github.com/bluesky-social/social-app/pull/6384
