### ISSUE TITLE
Known followers line may contain "NaN" if app language is German

### ISSUE THREAD

**Issue by knieriem** [bluesky-social/social-app#5559]
### Steps to Reproduce

In settings, select German as app language for default text. In someone's profile in the known followers info line
you should observe something like

    Gefolgt von X, Y and NaN andere

where it should, for example, be:

    Gefolgt von X, Y und 5 anderen

(for "Followed by X, Y, and 5 others")

In the translation the effective third value appears to be a non-number, which results in `NaN` instead of the expected `5`.

### Attachments

![Screenshot from 2024-10-01 23-51-30](https://github.com/user-attachments/assets/c23cb355-e16f-44c0-a252-5c6df5102a41)

### What platform(s) does this occur on?

Android, Web (Desktop)

### What version of the app are you using?

Build version: 1.91.1; Bundle info: 49ab486 (prod); Bundle date: 24092017; Platform: web

### Additional Information

I suppose the bug is in line 2690, where it should read `und {2, plural` instead of `und {1, plural`:

https://github.com/bluesky-social/social-app/blob/5a98ea684d90526e80b8b3ef7554452c4f8db53b/src/locale/locales/de/messages.po#L2688-L2690

Probably after copying the line from 2682 and extending it, it has been forgotten to adjust `1` to `2`.

I'll provide a pull-request if needed.

**Comment by knieriem** [comment]
Oh, I found there already exists a pull-request by #5451 that addresses this. I missed it because there doesn't seem to be an issue accompanying that pull-request, so when searching within _Issues_ for the term `NaN`, I got no results.

**Comment by surfdude29** [comment]
Oops, sorry about that!

Yes it looks like #5451 will fix this.
