### ISSUE TITLE
Self hosted PDS crashing iOS app

### ISSUE THREAD

**Issue by therobbiedavis** [bluesky-social/social-app#5600]
### Steps to Reproduce

1. Setup your own PDS using 0.4.47 (latest)
2. Login with account credentials
3. See app crash

### Attachments

https://github.com/user-attachments/assets/9a2c4fef-b93e-46da-8871-c3d311d309c9

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 13 Pro Max. iOS 18

### What version of the app are you using?

Latest. Can’t access app

### Additional Information

Relevant logs: https://pastebin.com/5X1YYg4Hh

**Comment by haileyok** [comment]
@therobbiedavis Check out the discussion in this issue: https://github.com/bluesky-social/social-app/issues/5100

This'll be fixed in the next release (sometime next week I assume) but you can modify that header as well to fix the problem (I assume you might be using Cloudflare).
