### ISSUE TITLE
Circular outline on rectangular profiles (feeds and moderation services)

### ISSUE THREAD

**Issue by knotbin** [bluesky-social/social-app#5613]
### Steps to Reproduce

1. Go to a feed profile or moderation service profile
2. Notice there is a small grey circle in the rectangular profile photo.
3. Click on the photo
4. Notice, the circle is not included in the profile image itself

### Attachments

![IMG_4487](https://github.com/user-attachments/assets/654cd20b-1a9f-412d-86fb-822f6d641518)
![IMG_4488](https://github.com/user-attachments/assets/71b0a051-1eb2-41a3-8e51-b7401bcf1f90)

### What platform(s) does this occur on?

iOS, Web (Desktop)

### Device Info

iPhone 15 Pro (iOS 18) and Safari on MacBook Pro (macOS 15)

### What version of the app are you using?

1.91.1 and web

**Comment by surfdude29** [comment]
This has been fixed on main, not sure by which PR, maybe #5392? So it will be fixed in the next release 👍

**Comment by haileyok** [comment]
Yep, this one is fixed. Available soon.
