### ISSUE TITLE
Bluesky web - Main column, moves left when pressing on any ellipsis (1.92.0)

### ISSUE THREAD

**Issue by layeredstrange** [bluesky-social/social-app#5681]
### Steps to Reproduce

On the Bluesky web (Desktop) implementation, there's a weird left nudge of the main content column, appearing when pressing the ellipsis in all places across the platform, tested on the Chrome browser.

Profile:
1. Go to profile.
2. Press the ellipsis.

Feed:
1. On the main feed.
2. Press the ellipsis on a post.

### Attachments

https://github.com/user-attachments/assets/8d70b369-72f8-442e-81be-5d142805259b

https://github.com/user-attachments/assets/ca56d5c8-73b5-497d-966a-8a388ca4eb95

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Dell XPS 15, Windows 11 Pro (64bit), Intel Core i7-8750H CPU @ 2.20GHz/2.21GHz, 16GB RAM - Google Chrome

### What version of the app are you using?

Build version: 1.92.0; Bundle info: 3b44ea2 (prod); Bundle date: 24101017; Platform: web

**Comment by SpriterGors** [comment]
This nudge is also happening when clicking on the Repost button.

**Comment by haileyok** [comment]
Fixed here, thanks! https://github.com/bluesky-social/social-app/pull/5710
