### ISSUE TITLE
Bluesky Web - GIF Browser no longer scrolls up and down (1.92.0)

### ISSUE THREAD

**Issue by layeredstrange** [bluesky-social/social-app#5688]
### Steps to Reproduce

1. Click "New Post"
2. Press GIF icon
3. Try scrolling
---
Searching for something doesn't change the result.

### Attachments

![New Post - GIF Button - Browser doesn't scroll - 1](https://github.com/user-attachments/assets/6222f40b-7c48-4481-bbaa-e9ddcbbc981a)
![New Post - GIF Button - Browser doesn't scroll - 2 - Searching Doesn't Change Result](https://github.com/user-attachments/assets/e190788d-5f04-4ff2-bc95-fb13d792e07b)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Dell XPS 15, Windows 11 Pro (64bit), Intel Core i7-8750H CPU @ 2.20GHz/2.21GHz, 16GB RAM - Google Chrome

### What version of the app are you using?

Build version: 1.92.0; Bundle info: 3b44ea2 (prod); Bundle date: 24101017; Platform: web

**Comment by surfdude29** [comment]
I can reproduce this in Safari on iPadOS 16.6.
