### ISSUE TITLE
Regression: Context menu(s) jump in position on Android

### ISSUE THREAD

**Issue by cyrneko** [bluesky-social/social-app#5689]
### Steps to Reproduce

1. Click any context menu. Preferably the repost menu as it's the most evident there.
2. See issue

### Attachments

1. Example found on bsky: https://bsky.app/profile/iggy.kawaii.social/post/3l66xgundcx22
2. Example by me:
  

https://github.com/user-attachments/assets/a3579191-63ee-433c-b6e2-b475a206d62a

### What platform(s) does this occur on?

Android

### Device Info

Android 14, Xiaomi/Poco F3

### What version of the app are you using?

Build version: 1.92.0.350; Bundle info: da28c56 (prod); Bundle date: 24100902; Platform: android

**Comment by haileyok** [comment]
Thanks, fixed in https://github.com/bluesky-social/social-app/pull/5684
