### ISSUE TITLE
REGRESSION - Keyboard obscures the text entry box when adding alt text in app.

### ISSUE THREAD

**Issue by blowdart** [bluesky-social/social-app#5705]
### Steps to Reproduce

1. Write a post
2. Attach an image
3. Go to write alt text
4. Scream because you can't see what you're writing

### Attachments

![20241011_031507000_iOS](https://github.com/user-attachments/assets/adac47f3-c771-45b9-be53-98868b2843e3)

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 16 Pro, iOS 18.0.1

### What version of the app are you using?

1.92.0.2526 94cfc84 (prod)

**Comment by haileyok** [comment]
Going to try and test this, https://github.com/bluesky-social/social-app/pull/5727. Hopefully this will prevent that from happening for the moment until there's a clear repro (on my list of things to try and find).

**Comment by surfdude29** [comment]
After not being able to repro this before, I just ran into it again with the alt text composer for a GIF.

**Comment by haileyok** [comment]
"Fix" is live, let's see if it helps people with this.

**Comment by mdruker** [comment]
This is still happening for me. What I noticed is that you don't see this right after restarting the app, so it may require opening the alt text entry screen a couple of times for the problem to appear. (And probably the image needs to be a taller one.)

**Comment by haileyok** [comment]
Ah, I have a clear repro now. If you open a DM then try to make a post and add alt text this will happen. I'll look closely on Monday, thanks.
