### ISSUE TITLE
Sharing feed does not work on iOS

### ISSUE THREAD

**Issue by yordiak** [bluesky-social/social-app#5719]
### Steps to Reproduce

I use the latest version of the Bluesky app and I cannot share a feed on an iphone 11.

Steps to reproduce the problem:

1. Navigate to a feed (anything you want)
2. Click on the three dots and choose "share feed"
3. Nothing happens

I don't know if the problem appers in older versions, as welll

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

1.92

**Comment by haileyok** [comment]
What version of iOS are you using?

**Comment by yordiak** [comment]
I am using the latest one (18.0.1)

**Comment by haileyok** [comment]
Interesting! I'll have to try and play with it a bit, appreciate the report. By chance do you have reduced motion enabled? (shot in the dark, but there's one thing i can think of that might cause problems there)

**Comment by yordiak** [comment]
I don't know... how can verify if i have enable such a setting?

**Comment by haileyok** [comment]
@yordiak Hmm, no I tested with that setting enabled and it still works fine for me. Can you let me know if sharing a post works if you do so from the `...` on a post and hit "Share"?

**Comment by yordiak** [comment]
@haileyok I tried that, and I cannot share a post either...

**Comment by surfdude29** [comment]
I'm seeing this too sometimes on iOS 17.7, where after tapping **Share feed** the sharing sheet simply never opens, and also sometimes on iOS 15.8.3, where after tapping **Share feed** the Bluesky sheet never closes, the iOS sharing sheet opens and then quickly closes again.

However, sometimes on both iOS versions it works just fine; I haven't been able to find a way to reliably reproduce it so far.

**Comment by surfdude29** [comment]
I’ve also run into this today on iOS 17.7 while trying to share a link to a labeller profile and while trying to share a link to a post.
