### ISSUE TITLE
Empty post check doesn't account for Tenor embeds

### ISSUE THREAD

**Issue by elfprince13** [bluesky-social/social-app#5720]
### Steps to Reproduce

Replying to a post with no text and only a Tenor embed causes "Did you want to say anything" error to appear and prevent posting until I insert a dummy character (like `.`)

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

1.92.0.526 94cfc84 (prod)

### Additional Information

Offending code appears to be here:
https://github.com/bluesky-social/social-app/blob/cca344a3d1cdca3d4e63806a9bd5f7867f8961d4/src/view/com/composer/Composer.tsx#L359-L368

**Comment by surfdude29** [comment]
Will be fixed by #5725

**Comment by haileyok** [comment]
Fixed now in prod!

**Comment by elfprince13** [comment]
Cheers 🥂
-- 
~Thomas
