### ISSUE TITLE
Profile information missing after 1.92

### ISSUE THREAD

**Issue by felixnogueira** [bluesky-social/social-app#5721]
### Steps to Reproduce

1. Update mobile app manually to 1.92 or automatically on web browser
2. Try to access profile

### Attachments

As soon as I updated to the latest version I noticed I couldn't access my profile (https://bsky.app/profile/devilsminion.bsky.social), and I found one other user this happened to after updating (https://bsky.app/profile/tailspr.bsky.social). No one who updated can access my profile but those who haven't updated yet can. Profile info such as followers, following, icon and display name are missing. I have not tried on iOS.

I tried logging out and logging back in, and uninstalling and reinstalling the app.

This is the affected profile open on the older bluesky version (mobile app):
![WhatsApp Image 2024-10-11 at 12 09 20](https://github.com/user-attachments/assets/4da17aeb-9b14-4965-90ae-6cd7283ff921)

This is the affected profile open on the newer (1.92) version (mobile app):
![WhatsApp Image 2024-10-11 at 12 09 20 (2)](https://github.com/user-attachments/assets/74c2e256-74f7-4bea-bd96-02b11a10708c)

On the web browser (Opera GX):
![imagem_2024-10-11_121139997](https://github.com/user-attachments/assets/4cd31523-7482-4663-a95a-5fd1e32eaf57)

Trying to see my profile info on sidebar menu on a mobile browser (Opera):
![WhatsApp Image 2024-10-11 at 12 09 20 (1)](https://github.com/user-attachments/assets/2c7de347-1844-4a6c-9cb0-73437f975eaa)

Videos trying to open on both web browser and mobile app:

https://github.com/user-attachments/assets/95ec43dc-1295-4890-8ce8-c61bb6194496

https://github.com/user-attachments/assets/ed58af03-0f4e-4404-9244-218e5278972e

### What platform(s) does this occur on?

Android, Web (Desktop), Web (Mobile)

### Device Info

Android app v1.92, web browser Opera GX, mobile browser Opera

### What version of the app are you using?

1.92

### Additional Information

On developer tools, getProfile, getPreferences and getAuthorFeed are getting 200 OK.

**Comment by dolciss** [comment]
I checked your profile record and only the URI is registered in pinnedPost.
https://atproto-browser.vercel.app/at/did:plc:ldh2ei4x5pfjus6ii4hmzykx/app.bsky.actor.profile/self

Perhaps you did set up a fixed post before with a third party client such as TOKIMEKI?
The fixed post format implemented officially this time is different from the previous format, so an error occurs on loading.

The current client supports the official format, so I think it will be resolved if you reconfigure it.

**Comment by felixnogueira** [comment]
@dolciss I completely forgot I had pinned a post with TOKIMEKI (and probably wouldn't think of that either if I remembered), thank you! I redownloaded and it didn't register any pinned post, but thankfully I remembered which post was, looked it up and deleted it, and it worked! Thanks a lot!
