### ISSUE TITLE
Android - GIF panel won't allow scroll ups when scrolling through GIFs

### ISSUE THREAD

**Issue by layeredstrange** [bluesky-social/social-app#5728]
### Steps to Reproduce

On Android...
1. Click on "New Post"
2. Press "GIF" icon
3. Scroll down the list and then try to scroll back up.

The result will allow you to scroll up briefly before trying to close the bottom sheet.
A forced swipe up, to try and quick scroll back up the GIFs will actually close the GIFs Bottom Sheet.

Also, slight 1-3px edge by the right side of the GIF search bar, where GIFs travelling behind are very slightly visible.

### Attachments

1. Controlled swipes back up after swiping to view more further down the list.

https://github.com/user-attachments/assets/377d75bf-18a1-452f-a863-7710ef1b2088

2. Forced swipe back up after swiping to view more further down the list.

https://github.com/user-attachments/assets/5d593f0c-344c-4c9c-bae4-16802a912843

Both videos also show that small visual opening on the right of the search bar.

### What platform(s) does this occur on?

Android

### Device Info

Honor 90 (REA-NX9), Android 14, Magic OS 8

### What version of the app are you using?

Build version: 1.92.0.350; Bundle info: 6a4c692ac (prod); Bundle date: 24101021; Platform: android

### Additional Information

I think implementing a freezing on the bottom sheets movement might be required, once open. With a removal when a gif is selected or an escape using the back button or direct swipe from the line/bar at the top of the sheet.

**Comment by haileyok** [comment]
About to deploy this in an OTA btw, so will be fixed after an app restart or two 👍
