### ISSUE TITLE
Desktop Web videos never switching to 720p

### ISSUE THREAD

**Issue by Paarsec** [bluesky-social/social-app#5746]
### Steps to Reproduce

1. post video on Bluesky Web version
2. notice video quality doesn'ìt switch to higher (720p) quality

### Attachments

https://github.com/user-attachments/assets/9eba0715-8b79-4ef2-8046-36ba6bb1d3bd

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Firefox web, Chrome web

### What version of the app are you using?

Version 1.92

### Additional Information

Video quality on desktop now seems to be permanently stuck on 240p/360p, even after clicking play to watch. Confirmed with other people so seems to be widespread. I would exclude any internet speed issues as all people I've asked have very fast connections.

It used to switch to 720p around 9seconds, but now it always stays very very low res, which makes video inaccessible for text, for art watermarks and not visible enough for artists, gamedevs sharing clips etc. 

I'm wondering if there's any threshold we could set so that, for example, videos under a certain file size don't get streamed at a lower quality on web. 
link to test video of the post I shared: https://bsky.app/profile/video-testing.bsky.social/post/3l6cz5dndrr2b

Thank you for your time

**Comment by TheShankar** [comment]
On my end, things have been unpredictable about it. Before I had reported that videos first 9 seconds (later 7) would be always in minimal res, while the rest would be at 720p.

Now, it varies from video to video:
Some, start in low res and after the 7 seconds mark, go to 720. After looping once or twice, then the first seconds are flushed out and the whole video plays at 720p.
Others, are always in low-res no matter how many times I let it loop.

I really think the ideal solution would had been to allow people who disable auto-play to simply select the quality of the video.

**Comment by surfdude29** [comment]
> I really think the ideal solution would had been to allow people who disable auto-play to simply select the quality of the video. Because even when it works properly, having to slog thru 7 seconds of blurry imagery and then having to wait for the video to loop to see the beginning 'properly' is sort of a turn-off.

This would be perfect for me. I'm usually watching videos on Bluesky with autoplay off and on a good connection, so I'd prefer to just set the quality in settings to 720p and then I'm happy to wait a second or two for the better-quality version to load.

**Comment by Paarsec** [comment]
> On my end, things have been unpredictable about it. Before I had reported that videos first 9 seconds (later 7) would be always in minimal res, while the rest would be at 720p.
> 
> Now, it varies from video to video: Some, start in low res and after the 7 seconds mark, go to 720. After looping once or twice, then the first seconds are flushed out and the whole video plays at 720p. (which I assume is the correct, post-fix behavior) Others, are always in low-res no matter how many times I let it loop.

This has been my experience as well, but in my case I've only seen the videos play in 720p twice or so in ~20 plays so far.

**Comment by Invertex** [comment]
I have a Userscript that enforces the highest resolution playback at the web-request level, for those that want to browse with good quality.
https://github.com/Invertex/BSKY-Enhancer
 
But a real big issue also, but should be a separate complaint from this one, is the overly aggressive compression despite a video being nowhere near the size limit. It makes many videos look absolutely terrible when watched in full screen, despite being 720p, looking more like 360p due to all the compression blocking...

**Comment by WinterPhoenix** [comment]
Kinda glad to find out this is a bug. I thought it was just Bluesky's limits being unreasonably low/not playing well with converting from HEVC.

A 6 second test video that NEVER stops looking crunchy (at least not without a workaround like Invertex's script):
https://bsky.app/profile/winteris.moe/post/3l4yme35x532w
