### ISSUE TITLE
Posts show ambiguous time under Chinese localization

### ISSUE THREAD

**Issue by Aaron-212** [bluesky-social/social-app#5801]
### Steps to Reproduce

Scroll through timeline to see a post that is posted several months ago. The time shows "x月" which is highly ambiguous. Under Chinese language, "x月" could either mean "x months" (a span of time) or "x-th month of the year", but not "x months ago", making users hard to understand.

### What platform(s) does this occur on?

iOS, Android, Web (Desktop), Web (Mobile)

### What version of the app are you using?

Build version: 1.92.1; Bundle info: 1557a19 (prod); Bundle date: 24101702; Platform: web

### Additional Information

My suggestions:
- Append a "前" which means "ago" to the time
- Another solution would be, for posts that are too old, just show the date of the post, instead of showing how many months ago

**Comment by auroursa** [comment]
1.93.0 has been officially released and includes a fix for this issue. Thanks again for your report.
