### ISSUE TITLE
Viewing likes on a profile that doesn't have any results in an infinite XHR loop

### ISSUE THREAD

**Issue by Gargaj** [bluesky-social/social-app#5828]
### Steps to Reproduce

1. Open a profile who doesn't have any liked skeets
2. Click the "Likes" tab
3. Observe the spinner keeps flickering; opening the browser network inspector shows a continuous stream of loading requests

### Attachments

![likexhr](https://github.com/user-attachments/assets/72de8a3c-e581-4330-8fe6-a78f7014c6e7)

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

Build version: 1.92.1; Bundle info: 3fd8c06 (prod); Bundle date: 24101721; Platform: web

**Comment by surfdude29** [comment]
See #4879
