### ISSUE TITLE
threads and polls 

### ISSUE THREAD

**Issue by averageluadev** [bluesky-social/social-app#5839]
### Describe the Feature

polls - another way to interact  with posts allowing people  to see consensus on things quicker than scrolling through 100's of replys 
- useful in lists / communities 
threads- add a button by the side of new post so you can 'add' (comment) a post to the original post at the same time 
 - this is also  useful in lists / communities  as info threads are popular 

these are the 2 main features I am missing from twitter and with the massive influx of users are probably  not a major concern at the moment (i imagine scaling is unless you setup lots of horizontal scaling) 
but this would be a nice feature to have in the near future

**Comment by surfdude29** [comment]
For polls, please see #1098 and https://github.com/bluesky-social/atproto/discussions/1310.

There’s an open PR to add a threaded composer in #4163. The Bluesky team have been taking inspiration from that PR and, as a step towards adding threading capabilities, have recently been reworking the composer code.

**Comment by averageluadev** [comment]
thank you surfdude29 
sorry for not checking other issues and prs before making an issue

**Comment by surfdude29** [comment]
> thank you surfdude29 sorry for not checking other issues and prs before making an issue

No worries :)
