### ISSUE TITLE
When a user has no liked posts, likes page constantly sends GET request

### ISSUE THREAD

**Issue by Karolinskis** [bluesky-social/social-app#5844]
### Steps to Reproduce

1. Create a new account
2. Go to the user's profile page
3. Click on "Likes"

### Attachments

![firefox_Yd1rWHWMxu](https://github.com/user-attachments/assets/55f393f8-86f3-459f-a543-6b03acc719f2)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Firefox 131.0.3

### What version of the app are you using?

1.92.1 89cff31

**Comment by surfdude29** [comment]
Please see #4879
