### ISSUE TITLE
Missing content warning for graphic content

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#5848]
### Describe the Feature

in the update we are now able to hide or show graphic content, but we are not able to add a content warning for graphic content (ourselves) 

### Attachments

![image](https://github.com/user-attachments/assets/c71ab6af-7a3f-410e-b15d-297abca60839)
this attachment is missing the label for graphic media for adding a self content warning. 
![image](https://github.com/user-attachments/assets/ff5fb714-22d2-4e01-b178-7f02f45c6540)

**Comment by surfdude29** [comment]
This has been added on main, but hasn't been released yet. You can try it out on the dev server ([main.bsky.dev](https://main.bsky.dev/)) if you want :)

**Comment by monicaellerose** [comment]
> This has been added on main, but hasn't been released yet. You can try it out on the dev server ([main.bsky.dev](https://main.bsky.dev/)) if you want :)

thank you..
