### ISSUE TITLE
"and X others" in follower list on profile displays NaN instead of a number on the iOS App

### ISSUE THREAD

**Issue by NaraDevStuff** [bluesky-social/social-app#5872]
### Steps to Reproduce

1. Open iOS App
2. Go to a Profile that has a bunch of Mutuals Following
3. Look at the listed followers right below the bio

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

Build version: 1.92.1.530; Bundle info: 89cff31b6 (prod); Bundle date: 24101917; Platform: ios

**Comment by surfdude29** [comment]
Thanks for reporting this. Are you seeing this in the German localization? If so, it’s been fixed by #5795 which will be in the next released version.

**Comment by NaraDevStuff** [comment]
Yes, in the german version. Glad it's already been fixed :)
