### ISSUE TITLE
Accessibility: Blocking from feed

### ISSUE THREAD

**Issue by Dead-Dev** [bluesky-social/social-app#5907]
### Describe the Feature

Blocking should ideally be listed under the hide from me button, not needing me to go to their profile to block them.

**Comment by surfdude29** [comment]
This is a much-requested feature, please see #1017 for the issue tracking it.

Also, I asked @/pfrazee about this recently and he confirmed that [it’s still on their radar](https://bsky.app/profile/pfrazee.com/post/3l6bii2z52c2i).

**Comment by Dead-Dev** [comment]
Thank you, didn't find someone talking about it while browsing on mobile; good to see it's on the works!
