### ISSUE TITLE
NSFW shield icon should be more recognizable

### ISSUE THREAD

**Issue by beholdnec** [bluesky-social/social-app#5918]
### Describe the Feature

I have noticed that many artists are failing to properly mark their images NSFW. Part of the problem (subjectively) is that the shield icon is not easily recognizable. To me it is not obvious that the icon will lead to options for marking NSFW. My eyes tend to dismiss the shield as a meaningless "hi, your post is secure!" message, similar to the lock icon in the browser's address bar, I think people tend to forget it's there.

Perhaps adding the text "NSFW" near the icon or adding a popup tip for new users would help.

### Attachments

![1000063697](https://github.com/user-attachments/assets/9ef6b2ec-c304-4ce7-926f-284a99112349)

**Comment by surfdude29** [comment]
This has already been changed on main by #5780 and related PRs. You can test out how it looks now on the dev server ([main.bsky.dev](https://main.bsky.dev/)) or you can just wait until 1.93 is released :)

**Comment by beholdnec** [comment]
Thanks!
