### ISSUE TITLE
Make follow button states more consistent

### ISSUE THREAD

**Issue by vertigris** [bluesky-social/social-app#6010]
### Describe the Feature

Currently we get different visual feedback when tapping the follow button depending on whether we follow from profile view or post view. 

On profile view it turns into a dark gray button with a checkmark.

https://github.com/user-attachments/assets/a78cca32-42f6-4d1d-9938-22d8cc89ac78

 While on post views it remains white. 
 
 https://github.com/user-attachments/assets/676ca39d-00f5-4bad-856e-6dca552fdf33

In my opinion that‘s not enough visual feedback,  the „Following“ state of the button should be consistenr with the profile view. It leads to double tapping as the only thing that changes is appending an ”-ing“ (which ends up being covered by my finger) 

### Describe Alternatives

It doesn’t need the checkmark necessarily if space is a concern, just using the gray button state would be enough.

**Comment by surfdude29** [comment]
This will be fixed by #6059.

**Comment by gaearon** [comment]
https://github.com/bluesky-social/social-app/pull/6059
