### ISSUE TITLE
[Feature Request] In App Translation

### ISSUE THREAD

**Issue by ThePsyKai** [bluesky-social/social-app#6019]
### Describe the Feature

Have the "translate post" button/UI interaction display the translated text in app rather than opening up Google translate. Please and thank you

**Comment by dolciss** [comment]
This seems similar to #1327 (DeepL), #2863 (Google), #5077 (Integrate App)

**Comment by ThePsyKai** [comment]
> This seems similar to #1327 (DeepL), #2863 (Google), #5077 (Integrate App)

Didn't see those ones, my bad
