### ISSUE TITLE
Post Interaction Settings Selectables' text are clipped/overflowed

### ISSUE THREAD

**Issue by merojosa** [bluesky-social/social-app#6026]
### Steps to Reproduce

1. Open modal to create new post
2. Click the post interaction settings

### Attachments

![image](https://github.com/user-attachments/assets/24a595fd-efde-4c03-85a7-5035c4daf1f1)

### What platform(s) does this occur on?

Android

### What version of the app are you using?

Build version: 1.92.1.355; Bundle info: 89cff31b6 (prod); Bundle date: 24101917; Platform: android

### Additional Information

Hi, I just saw that the selectable components ("Everybody", "Nobody", "Mentioned users", "Followed users") for the post interaction settings are cutting their text on Android due to the height or padding.

This PR https://github.com/bluesky-social/social-app/pull/6027 tries to fix this issue by increasing the height of the components. I chose 43 to have the same height as the "Save" button. Feel free to disregard the PR if you don't need it.

**Comment by auroursa** [comment]
It has been fixed in #6527.
