### ISSUE TITLE
"CocoaPods CLI not found in your PATH, installing it now." when setting up iOS development

### ISSUE THREAD

**Issue by taobojlen** [bluesky-social/social-app#6078]
### Steps to Reproduce

1. Follow the [build instructions](https://github.com/bluesky-social/social-app/blob/main/docs/build.md) up to and including `bundler install`
2. Confirm that CocoaPods is installed: `./vendor/bundle/ruby/2.7.0/bin/pod` should exist
3. run `yarn ios`

The output is
```
yarn run v1.22.19
$ expo run:ios
(node:9306) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  CocoaPods CLI not found in your PATH, installing it now.
› Attempting to install CocoaPods CLI with Gem
```

It seems that Expo is not detecting the CocoaPods that's been installed with bundler, and it tries to install it via `gem` (which fails) and then via homebrew (which installs Ruby 3 along with it). This will later fail. I've attempted to add the `vendor/bundle/ruby/2.7.0/bin` folder to my `PATH`, and `alias pod="bundle exec pod"`, but either way I get the same log lines when calling `yarn ios`.

<details>
<summary>Full logs</summary>

<pre>
❯ yarn ios
yarn run v1.22.19
$ expo run:ios
(node:10718) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  CocoaPods CLI not found in your PATH, installing it now.
› Attempting to install CocoaPods CLI with Gem
› Failed to install CocoaPods CLI with Gem
Failed to install CocoaPods CLI with gem (recommended)
└─ Cause: gem install cocoapods --no-document exited with non-zero code: 1
› Attempting to install CocoaPods CLI with Homebrew
==> Downloading https://ghcr.io/v2/homebrew/core/cocoapods/manifests/1.16.2
Already downloaded: /Users/tao/Library/Caches/Homebrew/downloads/708ed9dc70bece0bc0f16d8739590ce0e1ec035e296982a274aea36ad178538e--cocoapods-1.16.2.bottle_manifest.json
==> Fetching cocoapods
==> Downloading https://ghcr.io/v2/homebrew/core/cocoapods/blobs/sha256:68781e12612d0cfa292ad6e983a2711fcba61c31ff4f2cdfd01cfb80be2dfae0
Already downloaded: /Users/tao/Library/Caches/Homebrew/downloads/591beb0b0a3011db97ac96f7080ae7d2b262d8902b8cb7832c1354f33ac1658c--cocoapods--1.16.2.arm64_sonoma.bottle.tar.gz
==> Pouring cocoapods--1.16.2.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/cocoapods/1.16.2: 13,112 files, 22.5MB
==> Running `brew cleanup cocoapods`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
1.16.2
› Successfully installed CocoaPods CLI with Homebrew
✔ Installed CocoaPods CLI.
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Consistency issue: no parent for object `AppDelegate.swift`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`

/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in `parent'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/build_file.rb:77:in `ascii_plist_annotation'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:365:in `block in save'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/opt/homebrew/Cellar/ruby/3.3.5/lib/ruby/3.3.0/tempfile.rb:371:in `open'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:364:in `save'
/Users/tao/dev/social-app/node_modules/react-native/scripts/cocoapods/utils.rb:153:in `block in fix_library_search_paths'
/Users/tao/dev/social-app/node_modules/react-native/scripts/cocoapods/utils.rb:144:in `each'
/Users/tao/dev/social-app/node_modules/react-native/scripts/cocoapods/utils.rb:144:in `fix_library_search_paths'
/Users/tao/dev/social-app/node_modules/react-native/scripts/react_native_pods.rb:290:in `react_native_post_install'
/Users/tao/dev/social-app/ios/Podfile:53:in `block (3 levels) in from_ruby'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-core-1.16.2/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:149:in `message'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:183:in `integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:170:in `install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'

pod install --repo-update --ansi exited with non-zero code: 1
✨  Done in 65.93s.
</pre>
</details>

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

Latest commit on `main`

**Comment by taobojlen** [comment]
I was able to move forward using a very hacky solution: creating `/usr/local/bin/pod` with the following, and then making it executable:
```
#!/bin/bash
bundle exec pod "$@"
```

This tricks Expo into thinking that CocoaPods is globally available (i.e. not via bundler). I was able to see how Expo detects CocoaPods in their source code, and it looks like it just executes [`pod --version`](https://github.com/expo/expo/blob/main/packages/%40expo/package-manager/src/ios/CocoaPodsPackageManager.ts#L161) -- this makes sense, but it's not compatible with bundler-installed CocoaPods, which requires you to run it with `bundler exec pod`, I think.

**Comment by taobojlen** [comment]
I missed the part of the README that says that build issues will not be supported. Fair enough! I'll close this issue, and maybe someone else comes across it if they have the same problem.

**Comment by airowe** [comment]
@taobojlen Did you end up getting the project built?

**Comment by FidFenix** [comment]
I installed cocoapods and afterwards it worked
```
brew install cocoapods
sudo xcodebuild -license accept
```
