### ISSUE TITLE
Count of "and N others" in user profile appears as NaN when my app language is German on Android app

### ISSUE THREAD

**Issue by stephanietuerk** [bluesky-social/social-app#6106]
### Steps to Reproduce

In the Android app, set App-Language (first selection in language settings page) to German. View any user's profile page who has followers who you follow. The last part of the phrase says, "und NaN andere". 

Switch App-Language to English and the count is a number.

### Attachments

![Screenshot_2024-11-04-12-55-06-19_cb2df8437d99d85560b8f74042fc78eb](https://github.com/user-attachments/assets/5e491156-be9d-4301-903f-43067111c2bb)
![Screenshot_2024-11-04-12-55-39-06_cb2df8437d99d85560b8f74042fc78eb](https://github.com/user-attachments/assets/b7c53824-f816-4071-9649-d23c99599021)

### What platform(s) does this occur on?

Android

### Device Info

OnePlus 11

### What version of the app are you using?

1.92.1.355 89cff31b6 (prod)

**Comment by surfdude29** [comment]
Thanks for reporting! This has been fixed by #5795 which will be in version 1.93, which should be released any day now :)

**Comment by Akeuuh** [comment]
If this has been fixed, the issue should be closed 😉
