### ISSUE TITLE
Like button has thin red ring around it on iOS

### ISSUE THREAD

**Issue by surfdude29** [bluesky-social/social-app#6118]
### Steps to Reproduce

1. Go to your profile.
2. Tap on the **Likes** tab.
3. Tap on any post that you have previously liked.
4. Observe the thin red ring around the **Like** button.

### Attachments

![IMG_1982](https://github.com/user-attachments/assets/4b072af1-a8a6-4dcc-8156-751097fbc1dc)

### What platform(s) does this occur on?

iOS

### Device Info

iPhone SE (3rd generation), iOS 17.7.1

### What version of the app are you using?

Build version: 1.92.1.530; Bundle info: 89cff31b6 (prod); Bundle date: 24101917; Platform: ios

### Additional Information

As noted, I only see this issue when looking at a post that I have already liked, it doesn't appear immediately after liking a post.

**Comment by khuddite** [comment]
I am looking into the issue
