### ISSUE TITLE
Mojibake in Icelandic alt text on Android

### ISSUE THREAD

**Issue by scottdotweb** [bluesky-social/social-app#6145]
### Steps to Reproduce

In the Android app, Icelandic letters in the alt text of images on [this post](https://bsky.app/profile/baldurbjarnason.com/post/3lae3sd45pt2b) are being displayed incorrectly - it looks like the wrong character set is being applied. 

### Attachments

Screenshot of alt text of 4th image in post linked above:
![Screenshot_20241107_150918_Bluesky](https://github.com/user-attachments/assets/ad948b30-6e64-4c19-a6ef-eb9843626ad1)

### What platform(s) does this occur on?

Android

### What version of the app are you using?

Build version: 1.92.1.355; Bundle info: 89cff31b6 (prod); Bundle date: 24101917; Platform: android

**Comment by Tamschi** [comment]
I don't think that's a display issue. The same mojibake appear on https://atproto-browser.vercel.app/at/did:plc:cfcnluzwlof3qkppfmlmuxhm/app.bsky.feed.post/3lae3sd45pt2b.

The post's formatting makes me think it was created by an automatic blog post announcer. Maybe it got the encoding wrong.

**Comment by scottdotweb** [comment]
Great. Thanks for checking that out, I'll bookmark that app for future testing as well 👍🏻
