### ISSUE TITLE
Clicking search icon again should focus search box and cause the keyboard to pop up

### ISSUE THREAD

**Issue by wojtekmaj** [bluesky-social/social-app#6149]
### Describe the Feature

When hitting 🔍 icon on X or Spotify twice, it's going to navigate to Search page on the first tap and focus search input on the second tap. Great UX improvement, especially on large phones.

**Comment by surfdude29** [comment]
This would be fixed by #3065 or #5732.

**Comment by wojtekmaj** [comment]
Working in today's release!
