### ISSUE TITLE
Add Localizations for Context Menus in TextInput(Copy, Paste, AutoFill, etc) in CFBundleLocalizations for iOS

### ISSUE THREAD

**Issue by lucalencar** [bluesky-social/social-app#6162]
### Steps to Reproduce

1. Go to Bluesky App in iOS 
2. click in any TextInput and press for context Menus(copy, paste, autofill) 
3. it stays in english even if iOS is set to another language 

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 13

### What version of the app are you using?

1.92.1.530

### Additional Information

Need to add all languages available for localization in info.plist file

CFBundleLocalizations

**Comment by surfdude29** [comment]
I had no idea this was an issue, good catch 👍
