### ISSUE TITLE
Label "Show Badge" is cut off

### ISSUE THREAD

**Issue by victor-ponamariov** [bluesky-social/social-app#6185]
### Steps to Reproduce

1. Go to any labeler, e.g. https://bsky.app/profile/did:plc:zal76px7lfptnpgn4j3v6i7d
2. You'll see that "Show badge" is cut off

![CleanShot 2024-11-09 at 13 48 19@2x](https://github.com/user-attachments/assets/8ee0d70d-78a8-4772-b55f-905ab190d842)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

MacOS Sonoma 14.3.1 (23D60)

### What version of the app are you using?

Chrome, Version 130.0.6723.70 (Official Build) (arm64)

**Comment by khuddite** [comment]
I am fixing it

**Comment by surfdude29** [comment]
This was fixed by #6302 which was included in 1.94, released yesterday.
