### ISSUE TITLE
Copied notice on app passwords doesn't take reduced motion into account

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#6199]
### Steps to Reproduce

1. Enable reduced motion
2. Open app passwords settings screen
3. Create a new app password
4. Copy the app password

The copied notice should remain on screen for a little bit, but it does not, it pops in for 0.75s and immediately disappears afterwards.

### What platform(s) does this occur on?

Web (Desktop), Web (Mobile)

### Device Info

Firefox 134 (nightly); Linux (Arch Linux; `Linux aster 6.11.7-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:23:46 +0000 x86_64 GNU/Linux`)

### What version of the app are you using?

Build version: 1.94.0; Bundle info: dev (prod); Bundle date: 24111000; Platform: web; Platform version: undefined

**Comment by khuddite** [comment]
I will look into this issue

**Comment by khuddite** [comment]
I am not able to reproduce the issue. I've tested it on my macOs with on/off reduced motion and it seemed the copied notice stayed for a few secs. 

https://github.com/user-attachments/assets/e83366c3-3a57-4ae1-b2ad-3b026d7bfd07

**Comment by mary-ext** [comment]
New app passwords screen, the one that's currently on main branch, https://main.bsky.dev
