### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by bnb** [bluesky-social/social-app#622]
**Describe the bug**
There is currently no license for this code

**Additional context**

Ideally this would have a license to make it easier to judge how someone's code will be used when contributing, what rights they have to that code, and how others could use this code for their own purposes.

**Comment by bnb** [comment]
ah, it was pointed out that there is a license, it's just in the readme. Including the actual LICENSE file is still helpful since it'd be picked up by GitHub's tooling (and other automated tooling!) :)

**Comment by ansh** [comment]
Fixed by #623
