### ISSUE TITLE
Empty states on post likes/reposts/quotes screen don't span the full height

### ISSUE THREAD

**Issue by mary-ext** [bluesky-social/social-app#6226]
### Steps to Reproduce

1. Find an empty post (or find a post who has blocked everyone who liked/reposted/quoted it, I suppose)
2. Manually redirect to their likes/reposts/quotes page

### Attachments

![image](https://github.com/user-attachments/assets/dc452908-91c4-4444-ac35-0037d6a3755b)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Firefox 134 (nightly); Linux (Arch Linux; Linux aster 6.11.7-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:23:46 +0000 x86_64 GNU/Linux)

### What version of the app are you using?

Build version: 1.94.0; Bundle info: dev (prod); Bundle date: 24111110; Platform: web; Platform version: undefined

**Comment by khuddite** [comment]
@mary-ext Can you help attach the link to the page throwing this issue? Thanks

**Comment by mary-ext** [comment]
https://main.bsky.dev/profile/alicewastaken.bsky.social/post/3lai4cj6t2c22/reposted-by
