### ISSUE TITLE
Rotate images on mobile.

### ISSUE THREAD

**Issue by changeling** [bluesky-social/social-app#624]
**Is your feature request related to a problem? Please describe.**

Opened images currently don't rotate upon device rotation on mobile devices. Without this ability, text can be difficult to read.

**Describe the solution you'd like**

I'd like images to rotate when expanded and mobile device is rotated.

**Comment by williaia** [comment]
Very irritating to have to view a landscape image in portrait mode

**Comment by chrismarquardt** [comment]
+1 
Especially when screenshots of text are involved, not being able to rotate them to landscape is a serious usability issue, I'd really love for Bluesky to be consistent with other social media apps in this regard

**Comment by simonkbike** [comment]
+1
For reasons stated above. Don't understand why app is locked to portrait orientation

**Comment by briankkeyser** [comment]
Many text images are too small to read unless rotated to landscape. Need this feature often.

**Comment by drussellmrichie** [comment]
Just commenting that I still think this would be a great feature to add.

**Comment by Viexi** [comment]
Commenting because I can't fathom how this hasn't been added already

**Comment by mr-mac-chs** [comment]
Yup, still an issue. This is absolutely a serious useability issue that needs a fix.

**Comment by chrismarquardt** [comment]
It has been over a year and images are still portrait only. Like many others, I consider image rotation essential and I don't get why it is being ignored. Feels as if BlueSky aren't using their own mobile app.

**Comment by mr-mac-chs** [comment]
I also posted a "complaint" to @bsky.app about this. If you have a visual disability, this is really tough. I don't and I still find it challenging.

**Comment by samuelgoff** [comment]
My only regret is that I have but one +1 to give for this PR.

In many cases, the **only** way to read landscape content in portrait mode is to zoom way in, cutting off 2/3 of the image which then necessitates scrolling 3 times per row, or save the image to smartphone so you can then open the image in a native image viewer so you can view it in landscape mode.

The is both an accessibility & just basic usability issue.
