### ISSUE TITLE
web: Set a more informative html `title`

### ISSUE THREAD

**Issue by llllvvuu** [bluesky-social/social-app#626]
**Is your feature request related to a problem? Please describe.**

"Profile" is not a very informative title when looking at my tabs.

**Describe the solution you'd like**

See Twitter: "($NUM_NOTIFS) $NAME ($HANDLE) / Twitter"

**Describe alternatives you've considered**

N/A

**Additional context**

I would probably be able to implement this if people think it's a good idea.

**Comment by bnewbold** [comment]
See also https://github.com/bluesky-social/social-app/issues/599 which has some context and a reference link. That task was moved to an internal issue tracker.

**Comment by llllvvuu** [comment]
Thanks for the reference! Just gave it a shot: #655
