### ISSUE TITLE
Viewing a video in landscape mode causes layout shift.

### ISSUE THREAD

**Issue by BradEstey** [bluesky-social/social-app#6269]
### Steps to Reproduce

1. Click into a video to view in full screen.
2. Rotate device to view in landscape.
3. Click the `×` to close video (While still in landscape).
4. The entire app will shift to the left by about 1/3 width.

### Attachments

https://github.com/user-attachments/assets/ffa45a72-5333-48a1-bc0b-1788060fb917

### What platform(s) does this occur on?

iOS

### Device Info

iPhone SE (MX992LL/A) - iOS v18.0.1

### What version of the app are you using?

1.93.0.548 0ac7c0962

### Additional Information

Note, there is a single frame of the video where the app is rotated 90 degrees before the layout shift occurs.

**Comment by khuddite** [comment]
I can reproduce the issue, investigating what's happening
