### ISSUE TITLE
Browser "back" button navigates page without dismissing displayed image

### ISSUE THREAD

**Issue by str4d** [bluesky-social/social-app#627]
**Describe the bug**
When a post image has been displayed by tapping on it, using the browser's "back" button causes the webpage to navigate backwards, but leaves the image from the post displayed over the (now potentially unrelated) content.

**To Reproduce**

1. Navigate in a browser to a feed of posts.
2. Tap on a post containing an image.
3. Tap on the image.
4. Click the browser's "back" button.

**Expected behavior**

The image is dismissed, as if the "X" button in the top right had been clicked.

**Details**

 - Platform: Windows 11, Firefox 112.0.2
 - App version: Latest (settings tab says `Build version TODO (TODO)`)

**Comment by renahlee** [comment]
This should be addressed when https://github.com/bluesky-social/social-app/pull/677 is merged 🙏

**Comment by renahlee** [comment]
This will go out with next release :)

**Comment by tilse** [comment]
what happened to this issue? i keep using my muscle memory from birdsite and hit the back button but it doesn't close the image...

**Comment by gaearon** [comment]
It's a different issue — the issue here is that the lightbox used to get _stuck_ (despite clicking Back). What you're complaining about is the lightbox not getting its own entry in the history stack, which we're tracking in https://github.com/bluesky-social/social-app/issues/5434.
