### ISSUE TITLE
[security issue] Sentry Auth token exposed in eas.json

### ISSUE THREAD

**Issue by TowhidKashem** [bluesky-social/social-app#630]
**Describe the bug**

89c975413cd543fbb683b11bec984fc2163d9a77312c41c0b4480a570f3daa65

According to this thread:

https://github.com/expo/sentry-expo/issues/321 

you don't want to expose the auth token and use env variables instead. The thread is about using it in app.json but I think it applies here as well since the the security vulnerability is in others knowing the token first and foremost.

**To Reproduce**

1. Check eas.json
2. Confirm token is there

**Expected behavior**

Use env variables that are loaded via dot env where needed and not committed to the repo.

**Comment by alimony** [comment]
You should send potential security issues directly to security@bsky.app rather than opening an issue, per README.

**Comment by TowhidKashem** [comment]
> You should send potential security issues directly to [security@bsky.app](mailto:security@bsky.app) rather than opening an issue, per README.

nice catch, I emailed them. Will keep the issue open and they can close it after resolving...

**Comment by pfrazee** [comment]
Ah lovely -- I was under the impression only public tokens were in the repo. I've deauthorized this auth token. Thanks for raising the issue.

**Comment by TowhidKashem** [comment]
Looks good!
