### ISSUE TITLE
Accessibility bug: buttons are spamming aria-pressed but they are not toggle buttons

### ISSUE THREAD

**Issue by SleeplessByte** [bluesky-social/social-app#6325]
### Steps to Reproduce

This is probably a bug in react-native-web, but that's no excuse.

1. Go to https://bsky.app/
2. Find any `<button>`
3. It will have `aria-pressed="false"`
4. Clicking it (mouse down / keyboard hold down) will switch it to `aria-pressed="true"`
5. Releasing will switch it back to `aria-pressed="false"`

This one is easy. It's wrong.

From https://w3c.github.io/aria/#aria-pressed and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed

> Adding `aria-pressed` to an element with a role of [button](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) turns the `button` into a toggle button. The `aria-pressed` attribute is only relevant for toggle buttons. It represents the button's current "pressed" state.

These are not toggle buttons. 

- [ ] `aria-pressed` is not added to buttons that are not toggle buttons

### Attachments

Relevant html

```html
<button aria-pressed="false" role="button" tabindex="0"></button>
```

### What platform(s) does this occur on?

Web (Desktop), Web (Mobile)

### Device Info

Not Relevant

### What version of the app are you using?

Web

### Additional Information

The problem here is that people may have turned on options that announce something when the button becomes "toggled-on". You don't want that.

**Comment by PaulACoroneos** [comment]
I would like to get my feet wet contributing to OSS and don't mind contributing this one liner if its okay with the Bsky team.

**Comment by auroursa** [comment]
These accessibility improvements looks a lot of sense.

**Comment by SleeplessByte** [comment]
@PaulACoroneos the bug is probably this line of code (it should be removed):

https://github.com/bluesky-social/social-app/blob/5f7caf30105569fe02cda2b029d3e6cb1e4e4780/src/components/Button.tsx#L461

**Comment by PaulACoroneos** [comment]
> @PaulACoroneos the bug is probably this line of code (it should be removed):
> 
> 
> 
> https://github.com/bluesky-social/social-app/blob/5f7caf30105569fe02cda2b029d3e6cb1e4e4780/src/components/Button.tsx#L461

Yep thus me mentioning 1 liner 😊.

**Comment by wires5210** [comment]
the fix for this seems to have been reverted in #6887 as part of [this commit](https://github.com/bluesky-social/social-app/commit/1831167aac6eb0aef51171cd3c8725b2790c2fd0#diff-1e4ab16772826f4d218576ae2acae4e6ab1c99196422e2eecd23db06ff869357R471) - is there any reason for that? seems wrong as far as i can tell

**Comment by SleeplessByte** [comment]
@wires5210 I have no clue why it was reverted. There doesn't seem to be a good commit message for the reversal. Perhaps @haileyok can let us know (or re-open this issue).

I don't expect too much though. I [stopped reporting issues](https://github.com/bluesky-social/social-app/issues?q=is%3Aissue%20state%3Aopen%20author%3ASleeplessByte) as accessibility is not a priority or even part of their test suite & release plan.

**Comment by PaulACoroneos** [comment]
I can probably re apply the fix if this was reverted my mistake.
