### ISSUE TITLE
Content filtering sync between devices

### ISSUE THREAD

**Issue by l2eza** [bluesky-social/social-app#633]
**Describe the bug**

#### While the feature is enabled on the web platform, I initially assumed it would also be enabled within the application.
**Screenshots**

![app-bug](https://github.com/bluesky-social/social-app/assets/106398462/1f887d47-4bd0-4c22-8581-35598b4c080e)

**Details**

 - Platform: Mobile 
 - Platform version: iOS 16.3
 - App version: 1.28

**Comment by HeyItsLollie** [comment]
It seems as though content filter settings are tied to the login device, rather than the account.

**Comment by bsawicki** [comment]
Related to the above comment about this being tied to the login device, a workaround is to force close the app, open the mobile web version of the site on your iOS device (I used Safari 16 on iOS 16.6 so I can only validate this works there), toggle off all adult content with the "Enable Adult Content" toggle switch, then toggle it back on and set your preferred settings.  Open the app back up and it should be set the same in the app.
