### ISSUE TITLE
'ALT' doesn't fit on a single line.

### ISSUE THREAD

**Issue by fabricedesre** [bluesky-social/social-app#636]
**Describe the bug**

Running in Firefox Nightly, the 'ALT' text on images is wrapped on 2 lines.

**To Reproduce**

1. Open eg. https://staging.bsky.app/profile/ashleywillis.bsky.social/post/3jvsiuljthq2k

**Expected behavior**

ALT should be `ALT`, but it is
```
AL
T
```

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/984767/cae13665-a086-4592-9d3b-1daf645c9f1c)

**Details**

 - Platform: Firefox Nightly, Ubuntu Linux 23.04
 - Platform version: Gecko 115
 - App version:

**Additional context**

**Comment by pfrazee** [comment]
Should be fixed by https://github.com/bluesky-social/social-app/pull/618 (unfortunately screenshots got nuked when the repo went public). Please reopen if not fixed by the next major release

**Comment by fabricedesre** [comment]
> Should be fixed by #618 (unfortunately screenshots got nuked when the repo went public). Please reopen if not fixed by the next major release

Cool. When can we expect the next release?

**Comment by pfrazee** [comment]
it kind of varies, we tend to do 2 or 3 a week
