### ISSUE TITLE
Free ratio image cropping distorts images

### ISSUE THREAD

**Issue by timonsku** [bluesky-social/social-app#637]
When you use crop handles when posting an image the image will be posted in the original image ratio rather than the new ratio defined by the crop, this causes the image to be distorted.
This does not happen if you use the scale slider which retains the original ratio.

I could not find an existing issue for this, is this already being worked on? If not do you want a PR?

Here an example posted from the android client:
![image](https://github.com/bluesky-social/social-app/assets/2370185/547770bd-0f2a-44c5-b905-53ce6278227c)

**Comment by pfrazee** [comment]
I've seen this issue. Do you know which platform was used to upload the images?

**Comment by timonsku** [comment]
The latest Play store version of the Android app

**Comment by pfrazee** [comment]
Okay we'll dig into this, appreciate it

**Comment by corneliusroemer** [comment]
Same issue here, Android 13 on OnePlus

Build version: 1.51.0 (39); Platform: android

Really weird that it distorts rather than crops

Here is an example: https://bsky.app/profile/corneliusroemer.bsky.social/post/3kb6a5otm3d2l

**Comment by corneliusroemer** [comment]
There seem to be a lot of reports of this in skeets. Please fix 🙏

https://bsky.app/profile/tlbjames.bsky.social/post/3k3wm6mpqgn2d

https://bsky.app/profile/circusmaximus.bsky.social/post/3k4xqyjewuf2g

https://bsky.app/profile/nastyriff.bsky.social/post/3k6adabdq4z23

https://bsky.app/profile/djstrap.bsky.social/post/3kaudewlkh32y

This is just a quick subset of posts I found via a search for "cropping bug"

**Comment by halka** [comment]
Same for me.
I confirmed that on Android 12, 13, and 14.

**Comment by pfrazee** [comment]
Should be fixed in the upcoming release by https://github.com/bluesky-social/social-app/pull/1525

**Comment by corneliusroemer** [comment]
Thank you so much @pfrazee!

**Comment by halka** [comment]
Thank you!! @pfrazee

**Comment by pfrazee** [comment]
No prob! Sorry it took so long!

**Comment by corneliusroemer** [comment]
I only joined Bluesky a week ago or so, so for me the fix was very quick. Good job making an app that runs so smoothly at scale.
