### ISSUE TITLE
Translate causes navigation back to feed view

### ISSUE THREAD

**Issue by TheNikomo** [bluesky-social/social-app#6375]
### Steps to Reproduce

1. Find post on Following or Discover feed that has the Translate button
2. Press/click on Translate button
3. New tab/Google Translate is opened correctly
4. In background, Bluesky navigates forwards back to the feed you came from
5. Post is still in history - back button will navigate back to post

### Attachments

https://github.com/user-attachments/assets/af1ba50a-4965-4236-9fe0-f75c4e445402

https://github.com/user-attachments/assets/a67ad3bb-8718-4e5d-9cbb-eb80156c80ff

### What platform(s) does this occur on?

Android, Web (Desktop), Web (Mobile)

### Device Info

Firefox 132.0.2 Win11, Firefox for Android 132.0.2, Samsung Galaxy A33 5G, Android 14

### What version of the app are you using?

1.93.0.373 0ac7c0962 (prod)

### Additional Information

I believe 1.92.1 didn't have this issue, but don't quote me on that.

**Comment by surfdude29** [comment]
This looks like it will be fixed by #6289.

**Comment by TheNikomo** [comment]
I concur, I'll close this with the anticipation that the PR will be merged, or the issue is rectified in another way.
