### ISSUE TITLE
The "three dots" options on feed posts are not keyboard-accessible on web app

### ISSUE THREAD

**Issue by hs4man21** [bluesky-social/social-app#638]
**Describe the bug**
I can use [keyboard-only controls](https://build.washingtonpost.com/resources/accessibility/keyboard-accessibility#Keyboard%20focus) (e.g. "tabbing" through the page) to reach most of the buttons on the web app, but clicking the "three dots" button for more options on a feed post opens a pop-up that is not keyboard/screen reader-accessible.

See the video below, in which I can open these extra post options but cannot access any of them. A fun side-effect is that I can actually keep clicking the button with my keyboard to darken the screen entirely, as shown in the video.

The buttons have `tabIndex="0"`, but it looks like they are rendered out of order in the DOM and absolutely positioned, meaning a user has to tab through all other content on the page (including feed) before reaching those buttons.

**To Reproduce**

1. Run the web app locally.
2. Using keyboard controls, tab into the feed and press either the "space" or "enter" key on the three dots button shown in the screenshot below.
3. Now, try to enter the pop-up using your keyboard only. You will find that it is impossible.

**Expected behavior**

Pressing `tab` again after opening the three dots menu on a feed post should enter the pop-up and allow the user to tab through (and press "enter" or "space" to click) each item in the pop-up.

The issue appears to be that the pop-up is rendered out of order in the DOM. It should be conditionally rendered right after the three dots button to preserve the correct tab order.

**Screenshots**
<img width="322" alt="Screenshot 2023-05-15 at 8 18 41 PM" src="https://github.com/bluesky-social/social-app/assets/38192823/47c5a055-9f5c-4637-98f3-8b3dae31567d">
<img width="590" alt="Screenshot 2023-05-15 at 8 28 36 PM" src="https://github.com/bluesky-social/social-app/assets/38192823/0b87ef77-a36f-447c-b726-70766de2b9e8">

https://github.com/bluesky-social/social-app/assets/38192823/c49f850f-e5c1-4232-8ac4-e136e8752e40

**Details**

 - Platform: Desktop Chrome MacOS
 - Platform version: MacOS: Ventura 13.1, Chrome: 112.0.5615.137 
 - App version: 1.28(?), not sure where to find web app version number

**Comment by renahlee** [comment]
Adding to this discussion: another way I can think of handling this is to default to semantic `select` and `option` elements (may impact iconography).

**Comment by ansh** [comment]
That menu is now keyboard accessible with arrow buttons (up & down) after #988
