### ISSUE TITLE
Web app pop-ups/modals are out of order in DOM, hindering keyboard & sr accessibility

### ISSUE THREAD

**Issue by hs4man21** [bluesky-social/social-app#643]
**Describe the bug**
This is a follow-up to #638. Other modals throughout the web app are positioned absolutely via CSS, but they have incorrect [tab index](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) because they are rendered out of order in the DOM. This makes them extremely difficult to enter with keyboard-only and using a screen reader.

e.g. in the video below, I would expect after opening the various pop-ups that my next "tab" key presses would move me into the pop-ups, but they don't. I have to tab through the whole page to get back to the start of the tab order, where the pop-up lives.

**To Reproduce**

1. Run the web app locally.
2. Using [keyboard-only controls](https://build.washingtonpost.com/resources/accessibility/keyboard-accessibility#How%20to%20navigate%20with%20a%20keyboard%20only), open various pop-ups such as "edit profile" or "content filtering" in the moderation menu, or some of the settings menus ("content languages," "change handle," "delete account," "invite codes"). Then keep pressing the tab key to observe how long it takes to navigate through the other elements on the page before entering the pop-up.

**Expected behavior**
I should enter an opened pop-up with the next press of the `tab` key.

**Screenshots**
https://github.com/bluesky-social/social-app/assets/38192823/b740e697-db7b-4511-b3c9-6b4d36179983

<img width="1469" alt="Screenshot 2023-05-15 at 9 32 10 PM" src="https://github.com/bluesky-social/social-app/assets/38192823/b45eef53-4871-455a-9e4f-172f24dc9fa3">

**Details**

- Platform: Desktop Chrome MacOS
- Platform version: MacOS: Ventura 13.1, Chrome: 112.0.5615.137
- App version: 1.28(?), not sure where to find web app version number

**Comment by ansh** [comment]
They have all been given the correct tab index now via various different PRs. I'm closing this issue now but if you can reproduce the issue on Build version: 1.49.0 or above, please comment here or open a new issue.
