### ISSUE TITLE
For non-signed in users, do something better than sort by newest reply 

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#6442]
### Describe the Feature

Currently, when signed in, there is a complex and well thought out sorting of the replies on a post. Bsky users + algo make the top reply cool.

However, if I share a link to users who might not have an account, then they see the most recent reply on top, and it is likely to be not cool at this scale.

Let's use this post as an example: https://bsky.app/profile/aoc.bsky.social/post/3lazuxw3iys24

Signed in: 
![image](https://github.com/user-attachments/assets/ba6c3433-1647-442b-b8ab-3b9bd3eebb03)

Non signed in:
![image](https://github.com/user-attachments/assets/755cdd9f-1914-4be2-b374-f05e7603ddc4)

**Comment by surfdude29** [comment]
I think this has now been fixed after #6649 has just been merged. The default thread sort method for users who aren't signed in and for users who are but who haven't changed their thread preferences is now a "hotness" ranking.

Compare the PWI (public web interface) view of your example:

https://bsky.app/profile/aoc.bsky.social/post/3lazuxw3iys24

with the same post in PWI view on the dev server:

https://main.bsky.dev/profile/aoc.bsky.social/post/3lazuxw3iys24

**Comment by adamatic-me** [comment]
@surfdude29 Thanks for noticing this and letting me know! Sometimes I feel like I'm screaming into the void, so I really appreciate your response.

**Comment by surfdude29** [comment]
@adamatic-me No worries! I think the team finds it hard to keep up with all the issues that are opened these days, there are *a lot*... 😮‍💨

And it was just good timing tbh as I saw that PR merged and remembered reading this :)

**Comment by gaearon** [comment]
consider this fixed :)
