### ISSUE TITLE
Some threads are broken — only top post displays

### ISSUE THREAD

**Issue by mdruker** [bluesky-social/social-app#6444]
### Steps to Reproduce

Go to the starting post in this thread: https://bsky.app/profile/safety.bsky.app/post/3layun7r3ek2x — only the first post is shown.

The full thread is visible if opening up the last post: https://bsky.app/profile/safety.bsky.app/post/3layun7rh3k2x

### Attachments

![IMG_1842](https://github.com/user-attachments/assets/c2aa82fd-0b22-457a-bf4e-a7efbfa12295)

### What platform(s) does this occur on?

iOS, Web (Mobile)

### What version of the app are you using?

Build version: 1.93.0.548; Bundle info: ee184d2cd (prod); Bundle date: 24111518; Platform: ios

### Additional Information

For that thread, I’m seeing this across platforms, logged-in and logged-out, and others are reporting the same thing.

**Comment by surfdude29** [comment]
Yes, I'm seeing this too.

**Comment by mdruker** [comment]
It does seem to be working now
