### ISSUE TITLE
Timeline scroll reset when going back from translation

### ISSUE THREAD

**Issue by 4skl** [bluesky-social/social-app#6446]
### Steps to Reproduce

On the timeline translate a post, get back from the Google translate view, the timeline will be scrolled to the top thus "loosing" the original translated post

### What platform(s) does this occur on?

Android

### What version of the app are you using?

Build version: 1.93.0.373; Bundle info: ee184d2cd (prod); Bundle date: 24111518; Platform: android

### Additional Information

Need to use the back button to come back to the app from Google translate opened inside the app (perhaps loss of a state)

**Comment by auroursa** [comment]
Related issue #6287 and Fix PR #6289
