### ISSUE TITLE
Likes tab loops network requests

### ISSUE THREAD

**Issue by korywka** [bluesky-social/social-app#6448]
### Steps to Reproduce

1. Switch to likes tab
2. If it is empty, network requests are in the loop
3. I did not check for not empty tab. Just started to use this app 😄 

### Attachments

https://github.com/user-attachments/assets/c603c017-8faa-4c7a-893c-dccda058a2d5

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Chrome

### What version of the app are you using?

web

**Comment by surfdude29** [comment]
Please see #4879 and #4831

**Comment by korywka** [comment]
@surfdude29 ops. closed as duplicate. thanks.
