### ISSUE TITLE
Remove usused direct dependencies on `webpack`

### ISSUE THREAD

**Issue by trivikr** [bluesky-social/social-app#6461]
### Describe the Feature

The direct dependencies for webpack were added on migrating from "react-scripts" in https://github.com/bluesky-social/social-app/commit/d6ec627c8cd32836e5ed494606318959ca17fca1.
However, they weren't removed when we target moved to expo in https://github.com/bluesky-social/social-app/pull/288

The following dependencies can be removed as they're imported elsewhere:
* babel-loader
  * Now imported from `@expo#webpack-config#babel-loader`
  * No direct use in webpack config.
* babel-plugin-react-native-web
  * Now imported from `@expo#babel-preset-expo#babel-plugin-react-native-web`
  * No direct use in webpack config.
* html-webpack-plugin
  * Now imported from `@expo#webpack-config#html-webpack-plugin`
  * No direct use in webpack config
* webpack
  * Now imported from `@expo#webpack-config#webpack`
* webpack-dev-server
  * Now imported from `@expo#webpack-config#webpack-dev-server`

Following dependencies can be removed as they're no longer used:
* @tsconfig/react-native
* url-loader
* webpack-cli

**Comment by gaearon** [comment]
If you remove them, please do verify that the build actually works — see https://github.com/bluesky-social/social-app/pull/6459 for context.

**Comment by trivikr** [comment]
Thanks for providing a fix!

I just created a bug report when testing removal of webpack dependencies at https://github.com/bluesky-social/social-app/issues/6462

**Comment by trivikr** [comment]
> please do verify that the build actually works

ToDo: Run `yarn web` and verify whenever this task is taken up.
Instructions: https://github.com/bluesky-social/social-app/blob/main/docs/build.md#running-web-app
