### ISSUE TITLE
Reposting and liking not working, posts are delayed

### ISSUE THREAD

**Issue by w-biggs** [bluesky-social/social-app#6468]
### Steps to Reproduce

Trying to like or repost anything seems to silently fail -- reloading the page afterwards does not show the like or repost as having applied, and going to my profile does not show the repost happening.

Posts themselves seem to be sending in a significantly delayed way.

### What platform(s) does this occur on?

Android, Web (Desktop)

### What version of the app are you using?

Build version: 1.93.0; Bundle info: 5f449e3 (prod); Bundle date: 24111700; Platform: web

### Additional Information

Liking, reposting, and replying are having the same issues for me on `1.93.0.373 ee184d2cd (prod)` on Android.

On desktop, I keep also getting CORS Failed errors on the OPTION request to `https://events.bsky.app/v2/rgstr`, but unsure if this is related.

Thought this might be related to which PDS the account was on but this is happening on both of my accounts, one of which is on `porcini.us-east` and the other on `shiitake.us-east`

**Comment by pfrazee** [comment]
This is due to some datacenter issues we're diagnosing (specifically -- delayed processing in the relay). It's getting resolved.

Ultimately we plan to rearchitect the system so that user actions go directly to the appview and can be passed along to the pds while also injected directly into secondary indexes. This will cause this issue to be much less severe.

**Comment by m-a-sch** [comment]
On Safari MacOS 
<img width="202" alt="image" src="https://github.com/user-attachments/assets/a7349ea9-2c8a-4399-b847-fee1258bf441">
always fail. quite a bit of traffic for nothing I guess

**Comment by m-a-sch** [comment]
Not ideal when the error monitoring platform (sentry) it-self is producing errors ... @pfrazee let me know if you'd like that I send those that my browser got. Maybe you already have enough.
