### ISSUE TITLE
Use native equivalents of lodash

### ISSUE THREAD

**Issue by trivikr** [bluesky-social/social-app#6471]
### Describe the Feature

As per the source code, ten different utilities of lodash are being used
https://github.com/bluesky-social/social-app/blob/0b38c77faa71dbc777d3d0162b86cb3e8695ff99/package.json#L152-L161

Up to five of them can be replaced by native code
* `chunk`: https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_chunk
* `debounce`: https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_debounce
* `omit`: https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_omit
* `random`: https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_random
* `throttle`: https://you-dont-need.github.io/You-Dont-Need-Lodash-Underscore/#/?id=_throttle

These replacements can be used to reduce the number of lodash dependencies.

**Comment by trivikr** [comment]
I noticed that 5 of the lodash dependencies weren't used.
Posted PR to remove them in https://github.com/bluesky-social/social-app/pull/6472

**Comment by PaulACoroneos** [comment]
Left a comment on your PR but I think moving to lodash-es may be nice move as well

**Comment by trivikr** [comment]
Closing as not planned, as example PR was closed https://github.com/bluesky-social/social-app/pull/6545
