### ISSUE TITLE
Post share button sometimes doesn’t work when viewing a feed or account.

### ISSUE THREAD

**Issue by Fenekhu** [bluesky-social/social-app#6479]
### Steps to Reproduce

1. Be in a feed or account posts page.
2. Click the “…” next to the like button
3. Click “Share”
4. Nothing happens. No iOS share menu. But sometimes it does work. (It always works if I click the “…” after clicking on the post, to view comments etc.)

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 15 Pro, iOS 18.0.1

### What version of the app are you using?

Build version: 1.93.0.548; Bundle info: ee184d2cd (prod); Bundle date: 24111518; Platform: ios

### Additional Information

I think it doesn’t work until I get it to pop up once, such as by clicking on the post and then the “…” and “share”. Then the share button from feeds will work. Even after fully closing the app, it still works after relaunching. Now I can’t figure out how to make it not work.

**Comment by surfdude29** [comment]
I think this might be describing the same issue as #5719? If so, there's a simple workaround which is to use the lightest touch possible when tapping **Share**.

There's a fix waiting to be merged in #5849.

**Comment by Fenekhu** [comment]
> I think this might be describing the same issue as #5719? If so, there's a simple workaround which is to use the lightest touch possible when tapping **Share**.
> 
> 
> 
> There's a fix waiting to be merged in #5849.

Ah yes, it does seem to be that. Thank you.

(Wow, it's strange how I would be so consistent in tapping it long until I would be so consistent in tapping it short...)
