### ISSUE TITLE
Keyboard  automatically hides when clicking "Join Waitlist" button on Android

### ISSUE THREAD

**Issue by sijan2** [bluesky-social/social-app#648]
**Describe the bug**
When I open the app and click on the "Join Waitlist" button, the keyboard automatically hides and I can't type any email to join the waitlist. A lot of similar low star review in play store too.

**To Reproduce**

1. Open the app.
2. Click on the "Join Waitlist" button.
3. Observe that the keyboard automatically hides and you are unable to type any email to join the waitlist.

**Expected behavior**
Expected to have responsive keyboard avoiding view

**Screenshots**

https://github.com/bluesky-social/social-app/assets/48212803/38f3ad38-6ecf-4c1c-8f12-b80a698fc06f

**Details**

 - Platform:  Android 
 - Platform version: Android 13
 - App version: 1.28.0

**Additional**
This bug exist in all the input field which is implemented inside bottom sheet

**Comment by ansh** [comment]
This was fixed in #777
