### ISSUE TITLE
useAnimatedReaction in imageitem.android.tsx and imageitem.ios.tsx have logic bug

### ISSUE THREAD

**Issue by PaulACoroneos** [bluesky-social/social-app#6499]
### Steps to Reproduce

While I was working on Eslint v9 upgrades one of the rules exposed the following logic bug in both imageitem.android.tsx and imageitem.ios.tsx

<img width="434" alt="code snippet with unreachable code" src="https://github.com/user-attachments/assets/b2102f6d-347f-4bef-b8c4-26cce8d0f5c3">

I'm struggling to understand how we would ever reach the else if since the logic condition is the same. If I understand right this was introduced with #6159. I would propose I just remove the else if but I need confirmation from @gaearon whether I have not missed something here.

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

n/a

**Comment by gaearon** [comment]
Yea that looks like a bug.
