### ISSUE TITLE
Middle click/ctrl click to open post in new tab

### ISSUE THREAD

**Issue by foxydevloper** [bluesky-social/social-app#650]
**Is your feature request related to a problem? Please describe.**

Middle clicking/ctrl clicking to open a post in a new tab is a very very useful shortcut, available on most websites (like twitter) and in html, however this app doesn't appear to support it. It makes opening multiple posts a pain with no clear easy way to get around it.

**Describe the solution you'd like**

Middle click & ctrl click to open post in new tab, which is standard web behavior

**Describe alternatives you've considered**

**Additional context**

Supported by most websites, even electron applications will literally open up a new tab in your browser if you middle click on something

**Comment by Nazeeh21** [comment]
Would like to work on this issue. Can you please assign me this?

**Comment by benharri** [comment]
as a workaround for now you can middle click on the timestamp

**Comment by Shohreh** [comment]
What's middle click? My mouse has two buttons and a scroll wheel.

The lack of the usual CTRL+left click on a link to open a thread in a new tab is really annoying.

**Comment by benharri** [comment]
> What's middle click? My mouse has two buttons and a scroll wheel.

click with the scroll wheel

**Comment by Shohreh** [comment]
Doesn't work on the mouse I have.

I'll just wait until BS adds this common feature.

**Comment by icecube45** [comment]
+1ing this, it's a shortcut I'm sorely missing. 
The referenced PR does not seem to have addressed this.

**Comment by icecube45** [comment]
Both chrome (120.0.6099.130) and firefox (117.0) don't work for me (windows 10)

**Comment by benharri** [comment]
seems to be working with firefox 121 on win 11

**Comment by icecube45** [comment]
Very happy to have this working on the main feeds now! I did notice it doesn't work on search results, though

**Comment by haileyok** [comment]
@icecube45 feel free to open up an issue, i'll get that working whenever i have some time!
