### ISSUE TITLE
"followers" and "following" should be <a> elements

### ISSUE THREAD

**Issue by llllvvuu** [bluesky-social/social-app#651]
**Is your feature request related to a problem? Please describe.**

<a> have additional functionality such as link preview (bottom left of Chrome) on hover, open in new tab, probably some a11y benefits, etc

**Describe the solution you'd like**

Change or wrap <div> in <a>

**Describe alternatives you've considered**

Chrome "duplicate tab"

**Additional context**

I can implement this if people think it's a good idea. Actually I reported a similar issue prior to open-source, and it seems to have been fixed. So we can probably `git blame` and follow the same pattern.

**Comment by llllvvuu** [comment]
Ah, I see that the stack navigation is not initialized if you navigate to some of these pages directly via URL. So this actually slightly a bit more work

**Comment by mschwendener** [comment]
> if people think it's a good idea

Yes, it needs to be more obvious that the follower / following counts are clickable. 

([https://bsky.app/profile/alexpenname.bsky.social/post/3k4oasrqfq72j])

In twitter on desktop, they have hover = underline
