### ISSUE TITLE
Android: direct message , UI issue for textfield + send

### ISSUE THREAD

**Issue by crazycoder1999** [bluesky-social/social-app#6522]
### Steps to Reproduce

The attachment is clear:
- open messaging
- click on a contact
- click on the textfield to send a message
- go back
- open the conversation again
- the input field to send a message is in the wrong place

### Attachments

https://github.com/user-attachments/assets/af0d9013-8b1f-401c-bf9b-7e36a6a02689

### What platform(s) does this occur on?

Android

### Device Info

Samsung Galaxy Fold 3

### What version of the app are you using?

1.93.0

### Additional Information

It is probably related to the fact the component for sending the message is moved up when the keyboard is shown but if you go back, the keyboard is hidden but the component is not moved again at the bottom of the window

**Comment by crazycoder1999** [comment]
@marcomaroni-github thanks :D

**Comment by crazycoder1999** [comment]
I should consider to test it also on IOS to confirm is not available also there.

**Comment by khuddite** [comment]
I am no longer able to reproduce the issue on Android devices (both emulator and physical device). I presume the issue has been fixed in the latest version.

@crazycoder1999 can you please confirm if it's still an issue and close out the ticket if it's already fixed? Thanks.

**Comment by gaearon** [comment]
Maybe either https://github.com/bluesky-social/social-app/pull/6739 or https://github.com/bluesky-social/social-app/pull/6727 helped.

**Comment by khuddite** [comment]
I believe so, I used to be able to reproduce the issue and it's no longer happening.

**Comment by crazycoder1999** [comment]
Well done! it works correctly now!
