### ISSUE TITLE
None of my likes are working and none of my posts are showing up despite the fact that the blue skt server says it is up and running. This is the second time this has happened. Last time I just went to sleep. It's a little early for that at the moment. 

### ISSUE THREAD

**Issue by CharlesAgainstFascism** [bluesky-social/social-app#6528]
### Steps to Reproduce

None of my posts are showing up? None of my likes are sticking? 

Like and post I guess? 

### Attachments

I have no attachments for you I don't know how to show you that my posts are not showing up or working. 

### What platform(s) does this occur on?

Android, Web (Desktop), Web (Mobile)

### Device Info

I have tried multiple devices

### What version of the app are you using?

I have tried multiple versions of the app

### Additional Information

This is the second time this has happened.

**Comment by CharlesAgainstFascism** [comment]
Copy that, thank you 🙏

**Comment by Enitoni** [comment]
I know you're working on it, but I just wanted to chime in and say I'm having the exact issue. I made a reply on a post, and I can see the reply even after refreshing, but opening the post in incognito reveals that nobody else can see it. And likes are not sticking.

**Comment by sudoWright** [comment]
Hello, bsky social contributors! 

I, too, am having issues using "LIKE" and "FOLLOW" successfully. I see the web request POST-- but there is no error response on the action server-side... https://lionsmane.us-east.host.bsky.network/xrpc/com.atproto.repo.createRecord

**Comment by gaearon** [comment]
There are going to be delays until the backend team is able to roll out some improvements, sorry!

**Comment by wendyjf** [comment]
I see this is more than a month ago, but just want to add that I am having this problem too. 
Since the recent upgrade, +- 10 days now, I block, follow, like or post and all my interactions disappear (no error msg) with any kind of screen refresh
not "sticking" - on browser/web (not using app)

**Comment by oosterhagen** [comment]
Same here, posts aren't published. Interaction with users impossible.  Same bug as #7288

**Comment by gaearon** [comment]
Please add any details about ongoing issues to https://github.com/bluesky-social/social-app/issues/7288. This one is unrelated and has been solved.
