### ISSUE TITLE
Reddit link cards are not working correctly

### ISSUE THREAD

**Issue by jimsimon** [bluesky-social/social-app#6538]
### Steps to Reproduce

_Full transparency: I work for Reddit_ :smile: 

1. Create a new post
2. Paste almost any Reddit URL into the post (e.g. https://www.reddit.com/r/DetroitRedWings/comments/1guqp02/post_game_thread_detroit_red_wings_at_san_jose)
3. The link card is not formatted correctly

Current link card:
![image](https://github.com/user-attachments/assets/e747aef2-8d44-4320-bc25-0add27f04b2e)

Expected link card:
![image](https://github.com/user-attachments/assets/c36c22a0-976e-4119-84ea-4ca50dbb365c)

### What platform(s) does this occur on?

iOS, Android, Web (Desktop), Web (Mobile)

### What version of the app are you using?

Latest web version as of 11/19/2024, Android app version 1.93.0

### Additional Information

I had previously reached out to @haileyok to get the appropriate user-agent being used for link previews so that we could properly allowlist and identify Bluesky's requests. The user agent I was provided was:
```
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Bluesky Cardyb/1.1; +mailto:support@bsky.app) Chrome/W.X.Y.Z Safari/537.36
```
 but after doing a ton of debugging on our end, it looks like we're getting:
```
web:app.bsky:v0.0.1 (by support@bsky.app)
```

I noticed there have been a handful of other issues opened around link previews, so I figured I'd open an issue here to hopefully resolve this where others can see the answer as well. Could we get confirmation on what the user agent should be? It's not clear if the user agent we're getting is correct or if there is some bug and it's supposed to be the one that Hailey provided. Thanks!

**Comment by andresochoas** [comment]
The endpoint https://cardyb.bsky.app/v1/image?url= is responsible for doing this. Would love to help, but I'm unable to find the source code. Any help will be welcome!

**Comment by surfdude29** [comment]
It's one of the few parts of Bluesky (the video processing service is another) that hasn't been open-sourced.

**Comment by amhyder** [comment]
> The endpoint https://cardyb.bsky.app/v1/extract?url= is responsible for doing this. Would love to help, but I'm unable to find the source code. Any help will be welcome!

I was also unable to find references to that endpoint while trying to debug an [encoding issue](https://github.com/bluesky-social/social-app/issues/6309). If it is a section that has not yet been open-sourced, that would explain why finding ways to fix these issues with the endpoint are challenging.

**Comment by jimsimon** [comment]
We ended up working around the inconsistent/unknown user agent string, so this is resolved now.

**Comment by brianolson** [comment]
bsky developer here: @jimsimon  I found in our internal code where _special just for reddit_ we send that weird user agent; at one point in our development (2023-08-22, a prior developer, according to git) it seemed needed. Which User-Agent would you like?

**Comment by jimsimon** [comment]
@brianolson Either way works so long as it's one of the two mentioned above. You should be able to get you rid of the special case if you'd like. Are there any more details as to why we had a special case just for Reddit?

**Comment by brianolson** [comment]
@jimsimon alas, I dug further and got only the comment "fixed reddit" on Jun 3, 2023.
I'll take out the special case and you'll get our new default user agent. I'll add a note that Reddit (and a couple other orgs) are now matching on it and we should keep it stable _a long time_
`Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Bluesky Cardyb/1.1; +mailto:support@bsky.app) Chrome/W.X.Y.Z Safari/537.36`
This will probably launch today or tomorrow.

**Comment by jimsimon** [comment]
@brianolson One other request we have would be to set up a shared secret between Bluesky and Reddit. We want to ensure that it's actually your servers hitting us and not bots spoofing your user agent. If you all are willing, is there a more private means for me to contact you about this?
