### ISSUE TITLE
Whats hot page doesn't recognize Turkish

### ISSUE THREAD

**Issue by tcgumus** [bluesky-social/social-app#654]
**Describe the bug**

**To Reproduce**

Choose turkish in "Content Languages" page. Go to whats hot page. No turkish popular posts seen. I'm following turkish accounts and posts with 50 likes but it doesn't show these post in "whats hot".

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/2714346/1df14a42-a8db-4c08-8951-d9bfbbe35535)
![image](https://github.com/bluesky-social/social-app/assets/2714346/9a824612-a9df-4ea3-89e2-67eb7be0b906)

**Details**

 - Platform: iOS
 - Platform version: iphone 14 pro
 - App version: latest

thank you

**Comment by pfrazee** [comment]
This is definitely an issue with the language detection

We're going to solve this by moving away from language detection and instead having posts declare the language they're written in

**Comment by tcgumus** [comment]
Thank you for the clarification. 👍🙂

**Comment by ansh** [comment]
Posts can now declare which language they are written in with #982
