### ISSUE TITLE
Make pictures visible while adding their alt text

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#658]
**Is your feature request related to a problem? Please describe.**

It would be nice if you could see the picture you are currently adding alt text to.

Original idea here: https://staging.bsky.app/profile/cooperstreaming.bsky.social/post/3jvsvboakec2i

**Comment by renahlee** [comment]
Platform: iOS / Android 🙏

**Comment by jetpacktuxedo** [comment]
@renahlee I think this applies to desktop as well, see this example: 
![image](https://github.com/bluesky-social/social-app/assets/3813932/62335688-7f60-4bf1-b38c-d3d664d39243)

You can sort of see the picture behind the window there, but it would be nice to have a clearer view of it.

**Comment by renahlee** [comment]
@jetpacktuxedo Ah! Thank you for flagging mobile web! I'd updated desktop web to look like the following but will go ahead and update my comment to reflect that 🙏 

<img width="518" alt="Screenshot 2023-05-16 at 6 53 59 PM" src="https://github.com/bluesky-social/social-app/assets/12389148/655fd719-8af0-439c-b86e-e26155459ce8">

**Comment by str4d** [comment]
This appears to have been fixed. Tested on web (build version: 1.37.0), both the "ALT" menu and "Edit" menu show an alt text field alongside the image:

![image](https://github.com/bluesky-social/social-app/assets/4993799/95f087c3-fd1f-4d21-97a1-7f575f5f6627)
![image](https://github.com/bluesky-social/social-app/assets/4993799/97c2ccb5-c5c3-49de-8660-38bdd408ce41)

I also checked Android (build version: 1.37.0 (23) production), and its "ALT" menu does the same thing (the "Edit" menu on Android doesn't have an alt text entry box).

**Comment by pfrazee** [comment]
Yep should be all set. Cheers
