### ISSUE TITLE
[APP-482] Add Bluesky as a "share to" target

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/social-app#66]
null

<sub>[APP-482](https://linear.app/blueskyweb/issue/APP-482/add-bluesky-as-a-share-to-target)</sub>

**Comment by revanmj** [comment]
How is it completed when Android app does not have such option. Tried with sharing text or images from other app, in both cases Bluesky did not show up as a target.

**Comment by pfrazee** [comment]
This isn't completed, it just got moved to the internal tracker when we were adding that

**Comment by Splunger** [comment]
> This isn't completed, it just got moved to the internal tracker when we were adding that

Any updates? This is a pretty critical feature.

**Comment by pfrazee** [comment]
Internal tracker didn't work out, reopening

**Comment by jhwheuer** [comment]
So a year and no resolution. Facepalm.

**Comment by Splunger** [comment]
Open to the public but still no fix to quick share in Android. I'm a little confused by these tactics.

**Comment by jhwheuer** [comment]
Nothing confusing. Somebody's bonus depended on going GA, and did not on being feature-complete.

**Comment by MarkBennett** [comment]
Does anyone know of a way to add this? I'm a dev with lots of react experience but none with React Native.

Would be happy to make a PR if the team is open and someone could point me in the general direction of how best to start implementing this.

**Comment by MarkBennett** [comment]
Just did a quick search and React Native has a Linking API:

https://reactnative.dev/docs/linking

I assume implementing this would work? Thoughts @pfrazee?

**Comment by haileyok** [comment]
@MarkBennett Thank you! We actually have this in a branch right now but just need some time to review it. Hoping we get it done soon. https://github.com/bluesky-social/social-app/pull/2587

**Comment by jhwheuer** [comment]
Not to sound alarmist.... I stopped using Blue sky (no not BS, bad acronym) because sharing is simply painful

**Comment by MarkBennett** [comment]
> @MarkBennett Thank you! We actually have this in a branch right now but just need some time to review it and hash out a few things. Hoping we get it done soon. #2587

Thanks @pfrazee! Will definitely make sharing easier once that's enabled. 😄
