### ISSUE TITLE
web: use slug instead of did wherever possible

### ISSUE THREAD

**Issue by llllvvuu** [bluesky-social/social-app#660]
**Is your feature request related to a problem? Please describe.**

Notifications > click a notification, takes you to a did link. Makes it hard to share. Lists also have did links. There may be other spots as well

**Describe the solution you'd like**

Links have handle in URL instead of did if possible

**Describe alternatives you've considered**

Just deal with long links

**Additional context**
N/A

**Comment by pfrazee** [comment]
The issue is that people may change their handles after a link is shared, which would then cause the link to 404. We put up with the did to ensure links dont break
