### ISSUE TITLE
e2e: do not upload Sentry source maps in local e2e dev

### ISSUE THREAD

**Issue by llllvvuu** [bluesky-social/social-app#661]
**Is your feature request related to a problem? Please describe.**

`yarn e2e:metro` was failing for me because I did not have a Sentry API key configured. I do not want to add one, since I am just looking to drive-by contribute.

Doing:

```
diff --git a/app.json b/app.json
index 8a2fe039..4e42f486 100644
--- a/app.json
+++ b/app.json
@@ -79,24 +79,12 @@
         {
           "username": "blueskysocial"
         }
-      ],
-      "sentry-expo"
+      ]
     ],
     "extra": {
       "eas": {
         "projectId": "55bd077a-d905-4184-9c7f-94789ba0f302"
       }
-    },
-    "hooks": {
-      "postPublish": [
-        {
-          "file": "sentry-expo/upload-sourcemaps",
-          "config": {
-            "organization": "blueskyweb",
-            "project": "react-native"
-          }
-        }
-      ]
     }
   }
 }
```

and then running
```
rm -rf ios
yarn e2e:metro
```

resolved it for me. But there is probably a cleaner way to configure it to be smart about it.

**Describe the solution you'd like**

`yarn e2e:metro` just works

**Describe alternatives you've considered**

Workaround mentioned above

**Additional context**

N/A

**Comment by llllvvuu** [comment]
> `e2e:metro` creates the simulator build with some workarounds for detox; you want to use `yarn ios`

Would probably apply to `yarn ios` as well since the commands are nearly identical (I believe app.json is an expo thing). Minor issue though IMO, just wanted to report it for tracking.

**Comment by nucleartux** [comment]
Probably fixed in https://github.com/bluesky-social/social-app/commit/6d73ed96e1d6bccfa60113727571411f06a2b172

**Comment by pfrazee** [comment]
Ya
