### ISSUE TITLE
Users timeline not showing all posts

### ISSUE THREAD

**Issue by jamesleesaunders** [bluesky-social/social-app#6613]
### Steps to Reproduce

1. View user profile: https://bsky.app/profile/jamessaunders.bsky.social

2. When looking at this users timeline there appears to be some posts missing. Example, notice there is no post for dates:
```
04/11/2024 22:12 "All the electricity in the internet weighs as much as a plum. #fact"
...
29/10/2024 10:10 "Woke up for an early morning dip in the freezing swimming pool. Refreshing and awake now!"
```

3. It is expected that these would appear here:
<img width="620" alt="Screenshot 2024-11-21 at 21 14 44" src="https://github.com/user-attachments/assets/01b18b9d-732d-4ceb-bbb7-80f2b8088b97">

There is a gap between 29th Oct and 4th Nov ??

4. The posts does exist when viewed in atproto browser:
https://atproto-browser.vercel.app/at/did:plc:o5nklumeeim3vtsxlyczaeag/app.bsky.feed.post/3laxytu4mgz2e
or with direct link:
https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytu4mgz2e
It is simply nowhere to be seen when viewing all the users timeline posts?

### Additional Information

Here is a list of further missing ones:
* 04/11/2024 22:12,All the electricity in the internet weighs as much as a plum. #fact
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytu4mgz2e
* 01/11/2024 23:50,Sadly the end of our #GreekHoliday We have landed back in good old Blighty! It has been a bit of an emotional day feeling sick and anxious!
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytuob332x
* 01/11/2024 07:14,Not fun! I have been sick all night! Want to be at home :-( #GreekHoliday
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytuxgk425
* 31/10/2024 11:28,"Yesterday we went on a beautiful cruise to Spinalonga Island, where a leper colony was setup early 20th century #GreekHoliday"
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytvcpum25
* 29/10/2024 14:16,"Visit to Knossos Palace ruins, then mooch round town of Heraklion. I had Liver for lunch. #GreekHoliday"
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytvty5a2z
* 29/10/2024 10:10,Woke up for an early morning dip in the freezing swimming pool. Refreshing and awake now! #GreekHoliday
  * https://bsky.app/profile/jamessaunders.bsky.social/post/3laxytwd4ja2z

### What platform(s) does this occur on?

iOS, Web (Desktop), Web (Mobile)

### Device Info

MacOS

### What version of the app are you using?

Build version: 1.93.0; Bundle info: 7731136 (prod); Bundle date: 24110818; Platform: web

**Comment by jamesleesaunders** [comment]
I also note that they do show up it filtering by hashtag. This only affects the home timeline.

**Comment by itsajay1029** [comment]
I'd like to work on it.

**Comment by jamesleesaunders** [comment]
Partially worked it out and fixed for the above user. There seems to be a bug if there are two or more posts with the exact same timestamp it displays neither post on the users timeline.

This situation duplicate timestamps could happen if posts are imported via the API.

I uploaded a few posts with different text but the same date, these upload successfully in the API but don't display properly on the users timeline.
