### ISSUE TITLE
Ability to make private lists

### ISSUE THREAD

**Issue by julianmorley** [bluesky-social/social-app#6625]
### Describe the Feature

It would be nice if a list could be set so that it is only visible to the user who created it. I want to organize people I follow (and not follow, but want to keep an eye on) into lists, without having the list name, membership or existence visible to anyone else.

I might, for example, wish to have a list called 'trash pandas' containing people that I don't want to know that I consider them to be a trash panda. Despite trash panda being an honorable calling.

**Comment by surfdude29** [comment]
Please see #1056

**Comment by julianmorley** [comment]
Thanks! I didn't search that far back when looking to see if it was an existing issue. Closing this as duplicate.
