### ISSUE TITLE
clicking on hashtag causes layout shift of feed (safari)

### ISSUE THREAD

**Issue by syhner** [bluesky-social/social-app#6659]
### Steps to Reproduce

1. open safari
2. go to https://bsky.app/search?q=%23bluesky
3. click on any hashtag (opens `TagMenu`)
4. observe layout shift of feed

this bug does not happen in google chrome

### Attachments

https://github.com/user-attachments/assets/e6ac9144-f1f9-445f-94ff-ce2d1f851782

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

1.94.0

**Comment by khuddite** [comment]
@syhner Unfortunately, I was not able to reproduce the issue on v1.95.0 (Safari, macOS Sequoia v15.1.1). Maybe that's been fixed recently. Can you re-try and see if it's still happening on the latest version?

**Comment by syhner** [comment]
@khuddite seems to be fixed!
