### ISSUE TITLE
Dark/light mode toggle should use opposite labels

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#668]
I find it a bit strange that when in dark mode, the toggle says "Dark mode" and vice versa. I would expect the toggle to say "Light mode" when in dark mode since its action is to switch to light mode. Maybe even "Switch to Light mode" for clarity, but it might be too long of a label.

**Comment by Nazeeh21** [comment]
Can I work

**Comment by thepudds** [comment]
See also #700 and #688, including https://github.com/bluesky-social/social-app/pull/688#issuecomment-1550796109.

**Comment by alimony** [comment]
> Did this already get changed? Because the described behavior is what I am seeing on desktop right now 🤔
> 
> ![image](https://user-images.githubusercontent.com/3813932/239978450-24afc4ea-1280-492b-8f75-97326f167125.png) ![image](https://user-images.githubusercontent.com/3813932/239978512-cfc365bb-069b-4148-8541-0d3da4851b65.png)

Are you sure this wasn't on localhost?

**Comment by jetpacktuxedo** [comment]
> Are you sure this wasn't on localhost?

I'm positive, I haven't even pulled the code yet lol

**Comment by alimony** [comment]
I currently see this on https://staging.bsky.app:

<img width="143" alt="Screenshot 2023-05-23 at 13 45 22" src="https://github.com/bluesky-social/social-app/assets/331091/1024260c-4703-4e22-8591-40b4eac25487">

<img width="134" alt="Screenshot 2023-05-23 at 13 45 25" src="https://github.com/bluesky-social/social-app/assets/331091/dc261969-e860-48e6-8b63-edc34bff7916">

It could be a feature flag so different users see different things, but I don't think they do those at the moment.

**Comment by alimony** [comment]
I had no idea these were separate and run different code, that's interesting.

Hey @pfrazee, which instance should people in general use by now?

**Comment by jetpacktuxedo** [comment]
I just checked this on staging.bsky.app and can confirm that the labels seem "backwards" in staging and "correct" at bsky.app.

**Comment by pfrazee** [comment]
This control has been replaced
