### ISSUE TITLE
Can't join waitlist

### ISSUE THREAD

**Issue by XahidEx** [bluesky-social/social-app#669]
![20230516_201926](https://github.com/bluesky-social/social-app/assets/88249321/e0225995-9922-4e4e-8a98-62e6a465b9b3)

Fix this please. I can't even join the waitlist. Or give me an invite code

**Comment by renahlee** [comment]
Hi @XahidEx 🙏  Apologies you're experiencing this.

As a workaround, please feel free to sign up for the waitlist using [the website](https://bsky.app/).

As for the join flow itself, would you be willing to provide additional detail, such as the device you're using and which app version you're on? Thank you so much 🙏

**Comment by XahidEx** [comment]
> Hi @XahidEx 🙏 Apologies you're experiencing this.
> 
> As a workaround, please feel free to sign up for the waitlist using [the website](https://bsky.app/).
> 
> As for the join flow itself, would you be willing to provide additional detail, such as the device you're using and which app version you're on? Thank you so much 🙏

I'm already using the website. (tried again now)
