### ISSUE TITLE
Screen context and scrolling are lost after launching translate intent

### ISSUE THREAD

**Issue by pdandradeb** [bluesky-social/social-app#6695]
### Steps to Reproduce

(I'm using Android and I have Google translate installed)

# With the app closed
1. Make sure the app is closed
2. Open a skeet, [like this one](https://bsky.app/profile/sugyan.com/post/3lbp64jc53s2p).
3. Click "Translate"
4. Hit back button twice to return to the app (that's another issue)
5. Notice that you will return to Home instead of to the skeet screen

# From timeline
1. Find a skeet in a different language and open it
2. Click "Translate"
3. Hit back button twice to return to the app (that's another issue)
4. Notice that you will return the Home *at the top of scrolling* instead of to the skeet screen

i.e: you always returning to the beginning of scrolling after using the translation feature.

### What platform(s) does this occur on?

Android

### Device Info

Android 14; Motorola edge 40

### What version of the app are you using?

Build version: 1.94.0.402; Bundle info: c59dc0d8e (prod); Bundle date: 24112017; Platform: android; Platform version: 34

### Additional Information

In-app translation sould not fix the bug but would be a great UX improvement.

**Comment by surfdude29** [comment]
This should be fixed by #6657 which will be in 1.95, hopefully available within the next few days.

**Comment by surfdude29** [comment]
Forgot to add: as a workaround until the new version is released, try using the Translate option in the post context menu, that doesn't seem to trigger the bug.

**Comment by gaearon** [comment]
let's assume it's fixed
