### ISSUE TITLE
Add feature to mute words on the skyline

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#670]
**Is your feature request related to a problem? Please describe.**

There are some topics you just want to ignore, and muted words is a simple mechanism for doing that.

**Describe the solution you'd like**

The moderation panel could have a new tool called "Muted words". You would simply input words or phrases that you don't want to see, and the skyline would hide any skeets containing those.

**Comment by scottdotjs** [comment]
Hello, sorry to piggyback on an existing issue but just want to comment that Mastodon has the best interface for handling keyword muting that I've seen so far - they let you group muted words for manageability. That would be really nice to see for Bluesky too. Thank you.

**Comment by laurengore42** [comment]
Yeah, without this feature the site is unusable.

**Comment by pfrazee** [comment]
Not 100% sure how long but this is high up on my todo list now

**Comment by 8ullyMaguire** [comment]
This is related to [custom feeds](https://github.com/bluesky-social/social-app/issues/1532).

- **Custom feeds**: Allow users to create custom feeds that combine posts from multiple users, instances, include/exclude keywords, hashtags. A weighting system to control how much of each source is shown. Sharing custom feed settings easily with other users. This is similar to Reddit's multireddit, Kbin magazines and Firefish antennas. Firefish antennas allow users to specify keywords to include/exclude in categorized feeds.

**Comment by tvanantwerp** [comment]
This is the feature I miss most from Twitter. Without the ability to mute certain keywords, my level of enjoyment on the platform varies wildly depending on The Discourse of the day. I would love the ability to have a global muted words list to filter certain types of posts from any feeds I view.

**Comment by colemantrenton** [comment]
Any estimations on when this will be picked up?

**Comment by surfdude29** [comment]
> Any estimations on when this will be picked up?

The latest that I've seen is this post from @pfrazee:

["mute words are definitely on the near term list. not sure when but they’re high up"](https://bsky.app/profile/pfrazee.com/post/3kg66pdhamu2w)

**Comment by surfdude29** [comment]
Now that the muted words feature has shipped in 1.70, I think this can probably be closed now and any enhancements filed as separate issues?

**Comment by haileyok** [comment]
Yep, closing this in favor of smaller issues for suggestions/bugs.
