### ISSUE TITLE
Word count circle can go over the most right of layout

### ISSUE THREAD

**Issue by albilaga** [bluesky-social/social-app#6713]
### Steps to Reproduce

1. Create new post
2. Choose language with multiple language. In my case (English + Indonesian)
3. Without text is fine. But when writing text, the circle go to the right and over the layout
![IMG_4926](https://github.com/user-attachments/assets/748df8ef-a77c-4a50-89d6-9d2057c31909)

### Attachments

https://github.com/user-attachments/assets/98dcac25-b1bb-46b8-9ac4-0d7614459eed

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 15 pro iOS 18.1.1

### What version of the app are you using?

Build version: 1.94.0.602; Bundle info: 3c30bb1 (prod); Bundle date: 24111623; Platform: ios; Platform version: 18.1.1

**Comment by khuddite** [comment]
It's a duplicate of https://github.com/bluesky-social/social-app/issues/6178. And there's already a PR that will fix the issue - https://github.com/bluesky-social/social-app/pull/6252

**Comment by albilaga** [comment]
You are right. Closing it

**Comment by albilaga** [comment]
You are right. Closing it
