### ISSUE TITLE
Surface the keyword mute list functionality.

### ISSUE THREAD

**Issue by changeling** [bluesky-social/social-app#672]
**Is your feature request related to a problem? Please describe.**

Keyword mute lists are becoming a much-requested feature. Putting this up here as a please-pop reminder. https://kite.black has a good working example.

**Describe the solution you'd like**

Surfaced keyword muting.

**Additional context**

As I post this, [a Twitter owner] is being widely discussed, as is a desire to simply not hear about ... him. Just for a [n unneeded, I know] use-case example.

**Comment by alimony** [comment]
Issue already open for this: https://github.com/bluesky-social/social-app/issues/670

**Comment by renahlee** [comment]
Will close as duplicate so issues can be better tracked but appreciate you filing ❤️

**Comment by changeling** [comment]
> Will close as duplicate so issues can be better tracked but appreciate you filing ❤️ 

Coming fast and furious! 😃

I _did_ check first. Thanks for closing. @alimony posted as I was writing. I'll recheck after filing in the future. Cheers!

**Comment by changeling** [comment]
> Issue already open for this: https://github.com/bluesky-social/social-app/issues/670

Best me by _this_ much. 😀 Cheers.
