### ISSUE TITLE
DM text field can "float" in the wrong place

### ISSUE THREAD

**Issue by rock3r** [bluesky-social/social-app#6722]
### Steps to Reproduce

1. Go to a DM convo
2. Start DMing
3. Switch to another app
4. Switch back to bsky
5. Sometimes (not sure how often) the input bar floats a way away from the bottom edge, as if the IME were visible (but isn't)
6. The problem persists even when going back to the DM list and than into another convo

### Attachments

![adf5dbdb-6466-44fb-a14e-9fac9af7e629](https://github.com/user-attachments/assets/a16e8e7f-c2af-4361-ba0c-eec179dd8231)

### What platform(s) does this occur on?

Android

### Device Info

Pixel 9 Pro, Android 15

### What version of the app are you using?

Build version: 1.94.0.402; Bundle info: c59dc0d8e (prod); Bundle date: 24112017; Platform: android; Platform version: 35

**Comment by crazycoder1999** [comment]
Duplicate of this
https://github.com/bluesky-social/social-app/issues/6522

**Comment by rock3r** [comment]
Ah yeah, indeed. Hadn't found that existing bug because it wasn't worded too clearly.

**Comment by gingerbeardman** [comment]
I'm getting something similar.

New issue required?

The little black marks are the bottom of the window, so we can see the field is raised from the edge.

Safari and Chrome.

<img width="599" height="265" alt="Image" src="https://github.com/user-attachments/assets/1aaa6471-0699-430e-a2c0-342882f5bbda" />

**Comment by crazycoder1999** [comment]
@gingerbeardman are you able to replicate?

**Comment by gingerbeardman** [comment]
Yes, I took the above screenshot! :)

Here's a new screenshot from Chrome.

<img width="1312" height="1059" alt="Image" src="https://github.com/user-attachments/assets/6ad48f24-9c73-4cef-b3a2-feb7dc208ad7" />

**Comment by surfdude29** [comment]
I sometimes see this on my iPad in Safari (but not consistently):

https://bsky.app/profile/surfdude29.ispost.ing/post/3lthkal6zos2i

**Comment by gingerbeardman** [comment]
It does seem like some sort of edge case, as it does vary. 

I can consistently reproduce it in one app, whilst in other apps/browsers it comes and goes.

**Comment by crazycoder1999** [comment]
I think it worth to reopen this than, ideally it would be great to have reproduction steps.
