### ISSUE TITLE
Post time in Chinese cannot be localized on Android

### ISSUE THREAD

**Issue by auroursa** [bluesky-social/social-app#6728]
### Steps to Reproduce

1. Switch the app language to any Chinese language (zh-CN, zh-TW, or zh-HK).
2. Open the details of a post.

Post time displayed in English format, instead of Chinese.

### Attachments

Android:
![IMG_2295](https://github.com/user-attachments/assets/fa763a07-4077-45f4-85d4-699fe5a43240)

iOS:
![IMG_2294](https://github.com/user-attachments/assets/a224df3f-24c3-4067-986e-50984f20d85d)

### What platform(s) does this occur on?

Android

### Device Info

Pixel 8, Android 15

### What version of the app are you using?

Build version: 1.94.0.402; Bundle info: 3c30bb1 (prod); Bundle date: 24111623; Platform: android; Platform version: 34

### Additional Information

I have no idea, but it seems to only happen on the Android platform. It works fine on iOS and Web.

Tested on the Android emulator as well, and the issue persists.

**Comment by surfdude29** [comment]
Maybe a lingui bug? 🤔

**Comment by auroursa** [comment]
> Maybe a lingui bug? 🤔

I think you're right. After checking the code, I found that it directly outputs the date format from lingui.

Honestly, the confusing Chinese language tags are really frustrating. I guess it’s something similar to the #6621 issue.🙃

**Comment by auroursa** [comment]
While working on the fix, I found it doesn't only affect Chinese but also Japanese and Korean, so I will reopen the issue.
