### ISSUE TITLE
There is no way to get the URL to a mute list on mobile

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#674]
**Describe the bug**

The only way to get the URL to a mute list is to copy the URL, it seems. This also means you cannot do so in the mobile app.

**To Reproduce**

1. Go to one of your mute lists on your profile.

**Expected behavior**

I'd expect some button or similar to copy the link to the mute list I'm viewing.

**Details**

 - Platform: iOS
 - Platform version: 16.4.1
 - App version: 1.28

**Comment by ansh** [comment]
There is a share button now #863 and #1438
