### ISSUE TITLE
[iOS] When closing the Google Translate screen, it does not return to the previously opened screen.

### ISSUE THREAD

**Issue by nnabeyang** [bluesky-social/social-app#6741]
### Steps to Reproduce

1. Launch the app and open the timeline or feed.
2. Open a thread with a post written in a language different from the one set as Primary Language.
3. Tap the Translate button to open the Google Translate screen.
4. Tap Done in the top left corner of the screen.

### Attachments

https://github.com/user-attachments/assets/f5c15ac8-03a6-41f7-9098-2e9ec28d832e

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 14 Pro

### What version of the app are you using?

Build version: 1.94.0.602; Bundle info: 3c30bb1 (prod); Bundle date: 24111623; Platform: ios; Platform version: 18.1.1

**Comment by nnabeyang** [comment]
@surfdude29 
Since version 1.95 of the iOS app is not yet available, I would like to wait until it's released and verify that the issue is resolved before closing this issue. Would that be okay with you?

I’m not entirely familiar with how issues are handled in this project. If the Bluesky team usually handles closing issues, I don’t mind if you go ahead and close it.

**Comment by surfdude29** [comment]
> Since version 1.95 of the iOS app is not yet available, I would like to wait until it's released and verify that the issue is resolved before closing this issue. Would that be okay with you?

@nnabeyang Of course, that's totally fine, I just wanted to let you know what the status was and that it should be fixed soon :)

> I’m not entirely familiar with how issues are handled in this project. If the Bluesky team usually handles closing issues, I don’t mind if you go ahead and close it.

To be clear, I'm just a volunteer contributor, so I can't close other people's issues in any case 😅

**Comment by nnabeyang** [comment]
@surfdude29 
Got it, thank you for the clarification.

**Comment by auroursa** [comment]
I have conducted initial tests on Android and iOS, and the translation feature works well after this PR. But hey, I agree that we should perform a secondary confirmation after the official release.


As a temporary workaround, you might want to try [this](https://github.com/bluesky-social/social-app/issues/6287#issuecomment-2487721453).

**Comment by nnabeyang** [comment]
I have confirmed that the bug has been fixed in version 1.95.

**Comment by nnabeyang** [comment]
I have confirmed that the bug has been fixed in version 1.95.
