### ISSUE TITLE
Automatically Open Keyboard on Double-Tapping the Search Button in the Mobile App

### ISSUE THREAD

**Issue by rosarioterranova** [bluesky-social/social-app#6749]
### Describe the Feature

Enhance the user experience by automatically opening the keyboard when the search button is double-tapped in the mobile app. This intuitive functionality will streamline access to the search feature, allowing users to begin typing immediately without requiring an extra tap to activate the keyboard. It aligns with common user expectations for modern mobile apps and improves efficiency for frequent searches.

**Comment by surfdude29** [comment]
A PR implementing this – #5732 – was actually just merged last night, so this feature will likely not be in the next release (1.95) but it should be in the one after that (1.96).

**Comment by rosarioterranova** [comment]
@surfdude29 that's awesome! Thanks, you are the best guys :) closing the PR

**Comment by surfdude29** [comment]
@rosarioterranova No worries! Just to be clear, I'm not one of the devs – I agree they are the best though! – just a volunteer contributor :)
