### ISSUE TITLE
Website randomly starts scrolling out of control 

### ISSUE THREAD

**Issue by shirriff** [bluesky-social/social-app#675]
**Describe the bug**

I clicked the back arrow and the feed started continuously scrolling without stopping, flashing posts for about 1/10 second each.
It seems like it would go on forever until I clicked on the page and it returned to normal. It's kind of a cool effect but not what should happen.

**To Reproduce**

This has happened to me twice, but I don't have a reproducible case.

**Expected behavior**

The feed should be stationary.

**Screenshots**

I took a video showing the behavior: https://photos.app.goo.gl/oJ6qA41jZeVqqVFo8

**Details**

 - Platform: https://staging.bsky.app/ using Chrome 113.0.5672.92 on MacBook Pro Ventura 13.3.

**Comment by vajlex** [comment]
does exactly the same thing on my Mac OSX with any browser.   does not happen on iPad iOS.   wish this could be fixed, since it is convenient to use bsky on a regular machine (not tablet or phone) for some of us.

**Comment by haileyok** [comment]
@vajlex Do you have any idea on how exactly we could repro this? I.e. is there some flow (home -> profile -> feed, etc.) that you're following that triggers this?

**Comment by vajlex** [comment]
hi Haileyok,   as mentioned above, (using an older Mac OS X and Chrome Browser) if I simply begin to scroll down through the posts, the screen will begin to flash downward, jumping randomly through the posts without stopping.  this happens regardless of whether the feed is my own, someone else's or the "discover" and "following" feeds.   and the flashing downwards makes it impossible to see anything earlier than the latest few posts.     soon I will upgrade to a new Mac laptop and see if it behaves the same (though I am not the only user reporting this).  meanwhile, on an iPad OS scrolling works normally.  so, if I actually want to see anything, I must use an iPad instead of a laptop.   thanks much for replying.

**Comment by haileyok** [comment]
@vajlex We're about to deploy https://github.com/bluesky-social/social-app/pull/4752. Can you test again when you get a chance and see if this helps? (Make sure the cache is cleared before testing too please!)

**Comment by vajlex** [comment]
hi Hialeyok,  thanks much for reply!   

I have tested again on chrome (older Mac OS X).  When viewing my own profile or any other person's profile, including likes or replies, the bsky app if I begin to scroll downward, after several items, the screen will suddenly accelerate past many posts, flashing them without any way to stop the scroll.  After a while the scroll comes to rest randomly, then it will begin again with any further scrolling attempt.  

Here is a video capture of the screen (using a phone camera).  https://youtu.be/WBpMDJejD60

It would be very cool to fix this.  thanks!

**Comment by vajlex** [comment]
hello, folks!   After reading Hialeyok's message I tried clearing all time cache (including hosted app settings) and relaunched Chrome.   After testing my own profile and several others, I am now able to scroll down normally without the flashing occurring!   Very excellent!   Hopefully this is fixed and the issue closed.  you can see what was happening immediately before I did the cache clearing and relaunch of chrome at the link to youtube above.  best regards!

**Comment by haileyok** [comment]
Awesome! I'll close this for now but do feel free to @ me and we'll re-open. I'm fairly confident though that it was fixed in #4752 - we saw some similar but unrelated problems from that CSS style - so hoping that wraps it up.
