### ISSUE TITLE
Custom domain handle no longer working on other ATProto services

### ISSUE THREAD

**Issue by ivanbea** [bluesky-social/social-app#6782]
### Steps to Reproduce

From issue https://github.com/bluesky-social/indigo/issues/833 I am stuck with invalid handle https://bsky.app/profile/ivanbea.eu, I tried several times changing back and forth to .bsky.social with no luck. It is not a temporary glitch like other times, something is failing now.

The debug page confirms that my DNS is ok https://bsky-debug.app/handle?handle=ivanbea.eu
The DNS are ok and all the app worksm but I get invalid handle, also my posts at whitewind https://[whtwnd.com/ivanbea.eu](https://whtwnd.com/ivanbea.eu) don't work.
Can someone have a look at it please? @pfrazee 

Thank you

### What platform(s) does this occur on?

Android, Web (Desktop)

### What version of the app are you using?

1.94.0

**Comment by ivanbea** [comment]
Solved. I had to change to another handle (not my original ivanbea.bsky.social) and then back again to @ivanbea.eu

**Comment by ivanbea** [comment]
Still with problems, I have changed to random .bsky.social names and all is ok (as you can see on https://clearsky.app/ivanbea.eu), but when I return to @ivanbea.eu (my wanted handle) I can use bsky.app correctly but with invalid handle and problems with other ATproto services like:

https://whtwnd.com/ivanbea.eu/entries/Primers%20passos%20a%20Bluesky
https://blueskyroast.com/roast/ivanbea.eu
https://skylights.my/profile/ivanbea.eu

My DNS records are Ok https://bsky-debug.app/handle?handle=ivanbea.eu

I am out of ideas and I don't want to start again with a new handle, please help @pfrazee

**Comment by ivanbea** [comment]
Hi @surfdude29, as a man of contacts and knowledge, can you draw attention to this poltergeist? It's driving me nuts. 

Thanks

**Comment by surfdude29** [comment]
@ivanbea Sorry you're dealing with this, it must be very frustrating. I'm afraid my knowledge doesn't help at all in this situation as I don't have a clue what the problem might be, but I'll post about this later in the day and tag some devs in the hope that they'll see it.

Could I suggest that you might want to update the first post in this issue with the info in [this post](https://github.com/bluesky-social/social-app/issues/6782#issuecomment-2509648103)? Just to make clear for anyone reading this for the first time that the problem isn't that you're stuck with "Invalid handle" on bsky.app anymore, it's that the problem is showing up on other ATProto services.

Also, you might want to update the title to something like "Custom domain handle no longer working on other ATProto services" to make it clear what the current problem is.

**Comment by ivanbea** [comment]
Thanks for your help!

**Comment by ivanbea** [comment]
In https://bsky.app/profile/divy.zone/post/3lcnhb4h45k2z @devinivy reply with this" my understanding is that we're in a place where bluesky services treat your handle alright, but other services are failing to resolve it. i think the handle was provided via cloudflare. is there any chance that services resolving your handle got rate limited or otherwise denied by you/cloudflare?"

Right now I alfso get invalid handle at bluesky services.
Just to check it, I created a brand-new account with did:plc:2pea6di6p6hj5cqpxb4bd3xg and changed the handle to [bsky.app/profile/ivan...](https://bsky.app/profile/ivanbea.eu) and I also get an Invalid Handle https://bsky.app/profile/did:plc:2pea6di6p6hj5cqpxb4bd3xg, so it seems that something is wrong with Cloudfare.

The TXT records for the new account are correct, as you can see on [bsky-debug.app/handle?handl...](https://bsky-debug.app/handle?handle=ivanbea.eu) (just TXT with the new did), and the only rule in cloudfare is for AI scrappers (with 0 hits).

Cloudfare is widely used, I don't know if anyone else has this problem

**Comment by ivanbea** [comment]
New developments, I have disabled Cloudflare and now I use the default DNS, and link the new account https://bsky.app/profile/did:plc:2pea6di6p6hj5cqpxb4bd3xg
![image](https://github.com/user-attachments/assets/eb5abd83-9156-469e-9529-88810e6ab562)

I am also getting invalid handle, even when I can change my handle with my domain and it say it's ok, and in https://bsky-debug.app/handle?handle=ivanbea.eu also
![image](https://github.com/user-attachments/assets/c5e59c4b-6711-4f11-a33e-2fd0484839cf)

So, nothing to do with cloudfare, or my account did:plc, my domain ivanbea.eu is somewhat invalid for bluesky.

**Comment by ivanbea** [comment]
It works again after disabling DNSSEC on my domain, let's call it a temporary fix and move on.
