### ISSUE TITLE
Language picker doesn't respect device dark mode

### ISSUE THREAD

**Issue by skipness** [bluesky-social/social-app#6803]
### Steps to Reproduce

1. go to splash screen / sign up / language setting page / Search
2. trigger the language picker

### Attachments
| Splash Screen  | Sign Up Page  | Languages Setting Page  | Search |
|---|---|---|---|
| <img src='https://github.com/user-attachments/assets/661c257f-7e82-41ec-8699-6bbd7d3b6d6c' width = 450 />  | <img src='https://github.com/user-attachments/assets/bdce127e-20a9-4505-b0d5-f56a746c5f3d' width = 450 />  | <img src='https://github.com/user-attachments/assets/25724447-2c83-4c35-bbee-be0c723f1b64' width = 450 />  | <img src='https://github.com/user-attachments/assets/52793d8b-0620-46f8-96f9-d1621aad7ae0' width = 450 />  | 

### What platform(s) does this occur on?

iOS

### Device Info

iPhone 14 Pro

### What version of the app are you using?

Build version: 1.95.0.634; Bundle info: 2a575ad (prod); Bundle date: 24112703; Platform: ios; Platform version: 18.0

**Comment by skipness** [comment]
I can submit a PR to fix this if needed

**Comment by auroursa** [comment]
> I can submit a PR to fix this if needed

I think this is a reasonable improvement, please do so

**Comment by SilverPlate9938** [comment]
Same issue with Android as well![Screenshot_2024-11-29-14-21-47-94_cb2df8437d99d85560b8f74042fc78eb](https://github.com/user-attachments/assets/2dbe5337-cd79-4ebb-a9b3-b4417d505dea)
