### ISSUE TITLE
Drag-and-drop doesn't work for posting images

### ISSUE THREAD

**Issue by shirriff** [bluesky-social/social-app#681]
**Is your feature request related to a problem? Please describe.**

On the website, I would like to be able to add an image to a skeet by dragging-and-dropping it. 

**Describe the solution you'd like**

Dragging-and-dropping an image onto the New Post dialog should add it to the skeet. (The same way most websites support dragging-and-dropping.)  Currently, dragging-and-dropping an image causes the browser to open a new tab with the image instead of adding it, which is undesirable.

It's inconvenient to click the image icon and then navigate through the filesystem.

**Comment by Zero3K** [comment]
Any news regarding this?

**Comment by ansh** [comment]
Closing this in favor of #1257 as it is a duplicate
