### ISSUE TITLE
Re-using a did:web handle on a new did:web fails

### ISSUE THREAD

**Issue by electricduck** [bluesky-social/social-app#6864]
### Steps to Reproduce

If I try to re-use a handle that was already associated with a `did:web` account (but that account is deleted), Bluesky seems to hang onto the old record.

This should be returning `did:web:yot.wtf`, but its returning the previous `did:web:ducky.ws` (on both DNS and `/.well-known/atproto-did` entries): almost as if its caching the value and never attempting to retry it.

![image](https://github.com/user-attachments/assets/3d08ab78-8f69-402e-80a5-2afac4ab6582)

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

Build version: 1.95.0; Bundle info: c9d86de (prod); Bundle date: 24112719; Platform: web; Platform version: undefined

**Comment by oestradiol** [comment]
https://bsky.app/profile/yot.wtf 🥺

**Comment by electricduck** [comment]
apparently i'm just an idiot, its working now

:man_shrugging:
