### ISSUE TITLE
Likes feed in profile page keep fetching

### ISSUE THREAD

**Issue by skipness** [bluesky-social/social-app#6875]
### Steps to Reproduce

1. go to profile page
2. click likes feed

### Attachments

| Web | iOS App | 
|---|---|
| <video src='https://github.com/user-attachments/assets/77b06578-88f5-4320-b209-e9509124132a' /> | <video src='https://github.com/user-attachments/assets/f4b0f5f7-609f-4b0f-8650-4d6d930b3fb6' /> |

### What platform(s) does this occur on?

iOS, Web (Desktop)

### Device Info

Arc 1.70.0, iPhone 14 Pro

### What version of the app are you using?

Build version: 1.95.0; Bundle info: c9d86de (prod); Bundle date: 24112719; Platform: web; Platform version: undefined, Build version: 1.95.0.634; Bundle info: 2a575ad (prod); Bundle date: 24112703; Platform: ios; Platform version: 18.0

### Additional Information

I can see other feeds response didn't included `cursor` except for the likes feed even it doesn't need pagination?

**Comment by SpriterGors** [comment]
referenced in https://github.com/bluesky-social/social-app/issues/4879
