### ISSUE TITLE
Text showing when a post was made is read incorrectly by screen readers

### ISSUE THREAD

**Issue by hs4man21** [bluesky-social/social-app#691]
**Describe the bug**
Abbreviated units of time are read incorrectly to screen readers, making it difficult or impossible for these users to know when posts were made. This issue is across all platforms, but the video below shows how the issue manifests with VoiceOver on iOS.

Examples: The abbreviation representing "40 seconds ago" is read like the "40s" in "1940s." The abbreviation representing "1 day ago" is read as "1D" (like the boy band). The abbreviation representing "1 minute ago" is read as "1 meter" (upside down smiley).

**To Reproduce**

1. Use your preferred device/screen reader (I use VoiceOver on iOS, but TalkBack on Android and desktop options also work).
2. If you're using VoiceOver, turn on [the VoiceOver screen reader](https://build.washingtonpost.com/resources/accessibility/screen-readers#iOS) in your iPhone's accessibility settings.
3. Open the Bluesky app.
4. Tap a feed post in the app to hear it read by VoiceOver, as shown below (turn on your audio as the videos below have volume).
Note that the time is read incorrectly.

**Expected behavior**

I expect to hear the units of time read aloud by the screen reader correctly e.g. ("40s" becomes "40 seconds ago," "1d" becomes "1 day ago" and "1 meter" becomes "1 minute ago").

[This graysky PR](https://github.com/mozzius/graysky/pull/13/files#diff-ea480df8020617fbbe7038a60aef5e72d8ca079034661c05f8f09f8f5d9b19f9) demonstrates how the time logic could potentially look. The screen reader-friendly time string is rendered as an `accessiblityLabel` whereas the abbreviation is still all that's visible.

**Screenshots**

(Turn on audio to hear the screen reader attempt to read the timestamps.)
https://github.com/bluesky-social/social-app/assets/38192823/0d18ae93-3426-4925-a488-88e70c7b403f

**Details**

- Platform: iPhone XR, iOS 16.4.1, using VoiceOver screen reader
- Platform version: MacOS: Ventura 13.1, Chrome: 112.0.5615.137
- App version: 1.28

**Comment by alimony** [comment]
@pfrazee What would be the license implications of implementing this using similar or almost identical code as the linked Graysky PR?

**Comment by pfrazee** [comment]
This should now be fixed
