### ISSUE TITLE
"New Post" hotkey can trigger in "Reply" mode, detaching the reply.

### ISSUE THREAD

**Issue by WolfWings** [bluesky-social/social-app#6951]
### Steps to Reproduce

1. Click 💬
2. Change focus away from the text-entry field; there are many ways to do this, clicking where the 💬 was (so an accidental double-click) or hitting tab/shift+tab or many, Many, MANY other things can cause this.
3. Press the 🅽 key on your keyboard, virtual or otherwise.

Suddenly you're no longer 'replying' but 'making a new post' instead.

This will even happen if you're several + posts deep trying to make a concise multi-part reply all at once, if focus EVER leaves active text-entry boxes the 🅽 key blows away the whole reply structure.

### Attachments

https://github.com/user-attachments/assets/023b5abe-dd48-4afb-a9a0-911bc7e04edf

### What platform(s) does this occur on?

Web (Desktop), Web (Mobile)

### What version of the app are you using?

Build version: 1.95.0; Bundle info: c9d86de (prod); Bundle date: 24112719; Platform: web; Platform version: undefined

**Comment by monicaellerose** [comment]
I have the same issue on iOS and Firefox and it's annnoying
