### ISSUE TITLE
Fonts loading incorrectly and duplicating downloads

### ISSUE THREAD

**Issue by tunetheweb** [bluesky-social/social-app#6992]
### Steps to Reproduce

As noted at: https://bsky.app/profile/screenspan.net/post/3lcnm3xpza225

1. Open DevTools
2. Got to https://bsky.app/
3. Notice the following errors in the console:

> A preload for 'https://bsky.app/static/media/InterVariable.c9f788f6e7ebaec75d7c.ttf' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.Understand this warningAI
3lcnm3xpza225:1
> A preload for 'https://bsky.app/static/media/InterVariable-Italic.55d6a3f35e9b605ba6f4.ttf' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

4. Note in the Network track the Intervariable font is downloaded twice.
5. This is use to the lack of `crossorigin` in the preload lines ([needed despite it being same origin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload#cors-enabled_fetches) because... fonts).

Additional issues:
- The fonts are loaded as OTF fonts even though woff2 is [widely supported](https://caniuse.com/woff2) and the only things you need to use. This is 520 KiB instead of 346 KiB for the normal font.
- The italic font is preloaded but then not used (at least not quickly) and that's another 558 KiB unnecessary download (and this italic font would automatically be downloaded later if needed).

### What platform(s) does this occur on?

Web (Desktop), Web (Mobile)

### Device Info

MacOS 15.1.1 (24B91)

### What version of the app are you using?

1.95.0

**Comment by stoyan** [comment]
For some more supporting info... here's a WebPageTest run:
https://www.webpagetest.org/result/241206_BiDc96_9SQ/1/details/#waterfall_view_step1

And the behavior in Chrome and FF

## Chrome

<img width="1379" alt="Screenshot 2024-12-06 at 11 42 27 AM" src="https://github.com/user-attachments/assets/315dc46a-bcd4-4509-bc36-1206ea132820">

## Firefox

<img width="1384" alt="Screenshot 2024-12-06 at 11 36 03 AM" src="https://github.com/user-attachments/assets/f10609ef-d0fc-45b6-af51-d382a1ee7651">
