### ISSUE TITLE
Sometimes I cannot navigate to my profile until I reload the page (web)

### ISSUE THREAD

**Issue by ichthyos** [bluesky-social/social-app#707]
**Describe the bug**
Sometimes after browsing bluesky on the web, I click on Profile but my profile data does not load. I can reload the page to fix this.

**To Reproduce**

Unclear on reproduction steps right now. I tend to try to go to my profile sometime after making a post, but I'm not sure whether that's required to reproduce this bug.

Known reproduction steps:

1. Click on Profile in the navigation on the left.

**Expected behavior**

My profile should load.

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/140249/f87cf39e-4b57-453e-9ab1-6fa0e601f251)

**Details**

 - Platform: Desktop Chrome Windows
 - Platform version: Version 113.0.5672.93 (Official Build) (64-bit)
 - App version: Latest on https://staging.bsky.app/

**Additional context**

This has been happening since I joined bluesky in late April.

**Comment by Zero3K** [comment]
This seems similar to the blank page issue.

**Comment by ansh** [comment]
@Zero3K Which blank page issue are you talking about?

**Comment by ansh** [comment]
Similar to #710
