### ISSUE TITLE
Harmonise capitalisation of various labels

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#709]
Capitalisation of labels (e.g. buttons and titles) is not consistent across the app which gives a slightly confused impression (unless you are a normal person that did not grow up with a typographer parent). It would be nice with explicit guidelines on how and when to capitalise, and I'd be happy to submit a PR harmonising accordingly. Some current examples:

- In settings, the option says "App passwords", but the resulting dialogue has "App Passwords" as title.
- In settings, the options says "Change my handle" and the resulting dialogue too has "Change my handle" as title (compare to above)
- Button to edit profile says "Edit Profile" but resulting dialogue has title "Edit my profile"

I have various other tiny wording/label fixes that I'd like to include in the same PR to avoid tiny patches.

If you do not want to spend any time on coming up with guidelines, I could suggest them instead.

**Comment by renahlee** [comment]
Big fan of this and think it does push the app's polish further  🙏 

For posterity, I'd suggested sentence casing in the past, save for cases like proper nouns or product branding. There's studies with conflicting results for types of casing which is additionally hampered by sparse evidence for sentence casing versus title casing. A close study was [this one](https://link.springer.com/content/pdf/10.3758/BF03333407.pdf) (though  alternating case != title case) but generally, I find sentence casing is more consistent as a guideline 🖖

**Comment by alimony** [comment]
> Big fan of this and think it does push the app's polish further 🙏
> 
> For posterity, I'd suggested sentence casing in the past, save for cases like proper nouns or product branding. There's studies with conflicting results for types of casing which is additionally hampered by sparse evidence for sentence casing versus title casing. A close study was [this one](https://link.springer.com/content/pdf/10.3758/BF03333407.pdf) (though alternating case != title case) but generally, I find sentence casing is more consistent as a guideline 🖖

Sentence casing for everything? E.g. "New post" button, "Edit profile" button, "Invite a friend" title, "Enable adult content" toggle etc.

**Comment by renahlee** [comment]
Sentence casing where something is not a product or particularly unique to the product, i.e. I'd likely capitalize "What's Hot" but sentence case "New post".

That said, I'm not particularly married to one direction -- it was just something I'd historically suggested. Like you mentioned, consistency would be the big win here 👍

**Comment by alimony** [comment]
Pure sentence casing sounds good to me as a starting point, how can I get the go-ahead on this?

**Comment by renahlee** [comment]
You're looking for sign off from @pfrazee or @ansh ❤️

**Comment by pfrazee** [comment]
There are actually rules in the current build, though there may be some places they're wrong:

- Actions/buttons and page titles should be title case
- Links should be sentence case

**Comment by alimony** [comment]
Sounds good to me. Would the desirable PR be one that audits according to those rules? (Plus various related fixes, like I mentioned.)

**Comment by alimony** [comment]
I've started a PR here and will make some line comments to clarify: https://github.com/bluesky-social/social-app/pull/757

**Comment by alimony** [comment]
Maybe this can be closed, for now, since the PR was merged last month.

**Comment by pfrazee** [comment]
Cool 👍
