### ISSUE TITLE
Image upload broken on main

### ISSUE THREAD

**Issue by benharri** [bluesky-social/social-app#7097]
### Steps to Reproduce

1. Try to post an image on https://main.bsky.dev or a local build
2. It fails with the message "Unable to compress image" or "Invalid uploadBlob input: string" depending on the size of the image file.

### Attachments

https://bsky.app/profile/benharri.org/post/3ld2bx43ips2l

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

firefox and chromium

### What version of the app are you using?

add7a91d5

### Additional Information

https://github.com/bluesky-social/social-app/blob/356dad1932c3404f581b747127ae251dbe165bb3/src/state/gallery.ts#L209-L246

**Comment by benharri** [comment]
I did a bit of digging and logged the compressed size in each loop iteration and it's not changing at all with the new `factor`.

Relatedly, `manipulateAsync()` is marked as deprecated in expo-image-manipulator.

**Comment by gaearon** [comment]
Any ideas when/how this broke?

**Comment by benharri** [comment]
First thought is RN 0.76 but I haven't done a bisect yet.

**Comment by gaearon** [comment]
Could be this commit, easy way to test is maybe to downgrade this package alone to previous version.

https://github.com/bluesky-social/social-app/blame/main/package.json#L134

**Comment by gaearon** [comment]
We're pretty slammed right now with feature work, would appreciate if you could look into a fix.

**Comment by benharri** [comment]
Initial testing looks good, I'll do a PR

**Comment by gaearon** [comment]
Well I'm not sure we can just downgrade it safely, so I think we'd have to use the new API? https://github.com/expo/expo/pull/30194

**Comment by benharri** [comment]
Oh right I noticed the deprecation warning in there. I will have a look at switching the usage to the new API as well

**Comment by gaearon** [comment]
Would be good to understand what exactly broke,

**Comment by gaearon** [comment]
Upgrading the API doesn't help. https://github.com/bluesky-social/social-app/pull/7104

**Comment by gaearon** [comment]
https://github.com/bluesky-social/social-app/pull/7105

**Comment by benharri** [comment]
Just got to the same spot as #7104 myself and found the `blob:` URLs. Will test the changes in #7105
