### ISSUE TITLE
API key for hugging face is exposed

### ISSUE THREAD

**Issue by akanoonAB** [bluesky-social/social-app#7106]
![image](https://github.com/user-attachments/assets/1fa8d8ab-7486-41a4-9c99-1b0cccb28b0b)

I was testing TruffleHog against public repos and found that your hugging face API key is in the code.

**Comment by akanoonAB** [comment]
https://github.com/bluesky=social/social-spp/blob/975accaeffbb4e2422a4b585fd0s27b35c32bSc7/src/view/screens/Search/AlModels.ts0LS

**Comment by surfdude29** [comment]
Does Bluesky have a huggingface API key? 🤔

> https://github.com/bluesky=social/social-spp/blob/975accaeffbb4e2422a4b585fd0s27b35c32bSc7/src/view/screens/Search/AlModels.ts0LS

That link gives me Not found

**Comment by surfdude29** [comment]
The screenshot seems to be from 975accaeffbb4e2422a4b585fd0a27b35c32b5c7 which was part of #4786. It's unclear what the purpose of that PR was but in any case it was closed and the code was not merged into the Bluesky repo.

So, I think everything is fine :)
