### ISSUE TITLE
Delete app password confirmation uses browser alert instead of "nice" dialogue

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#714]
**Is your feature request related to a problem? Please describe.**

The alert dialogue to confirm deleting an app password uses a standard browser alert, unlike all other parts of the UI:

<img width="579" alt="Screenshot 2023-05-17 at 17 44 48" src="https://github.com/bluesky-social/social-app/assets/331091/39d660aa-88aa-48f2-839d-5ff1520fda58">

**Describe the solution you'd like**

It would be nicer if this dialogue looked like all other parts of the UI.

**Additional context**

The only other place in code that uses a standard browser alert is photo library permissions, see `src/lib/hooks/usePermissions.ts`

**Comment by jaysoni-ash42** [comment]
@alimony can i work on this issue ?

**Comment by alimony** [comment]
I'm not affiliated with Bluesky, so I can't give any advice on that.

**Comment by jaysoni-ash42** [comment]
> I'm not affiliated with Bluesky, so I can't give any advice on that.

sure @alimony i see there is a component modal with confirm modal which works great for both mobile version and web version should we use that

**Comment by jaysoni-ash42** [comment]
@pfrazee can i pull up a pr for this issue ?
