### ISSUE TITLE
Tapping profile tab/icon while active should scroll to the top

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#719]
This is for the iOS mobile app, might apply to Android too (I can't test it).

**Is your feature request related to a problem? Please describe.**

Not so much a problem as an expectation. All other main tabs do some version of this:
- Home: When active and scrolled down, tapping home scrolls back to the top and loads new content.
- Search: Scrolls back to the top.
- Notifications: Scrolls back to the top and loads new content.

**Describe the solution you'd like**

When the profile tab is active, tapping it should scroll back to the top of your profile.

**Comment by kadikraman** [comment]
Same! Just raised a PR to hopefully fix it, it was bugging me as well 🙌
