### ISSUE TITLE
Navigation bar under android navigation buttons in latest updates

### ISSUE THREAD

**Issue by Adamkadaban** [bluesky-social/social-app#7199]
### Steps to Reproduce

Open the app

### Attachments

![image](https://github.com/user-attachments/assets/18fbfc9d-1bdf-47a2-b128-5690e3f51cd3)

### What platform(s) does this occur on?

Android

### Device Info

Pixel 7 Pro

### What version of the app are you using?

Version 1.96.0.538 - c2ca84c (prod)

### Additional Information

I'm unsure of the previous version of the app on my phone, but this issue did not exist before I updated

**Comment by gaearon** [comment]
Yeah that's already fixed on main and we're rolling an OTA fix. Which should mean that you'll get it on next restart (or next after next).

**Comment by Adamkadaban** [comment]
Wow, super speedy! Thanks @gaearon!
