### ISSUE TITLE
Emoji Picker doesn't allow text input

### ISSUE THREAD

**Issue by ljstella** [bluesky-social/social-app#7200]
### Steps to Reproduce

1. Open either a new post or reply (doesn't seem to matter)
2. Open the emoji selector
3. Try to insert text in the Search box of the emoji selector

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

MacOS 15.2, tested in Firefox (133.0.3) & Safari

### What version of the app are you using?

Build version: 1.96.0; Bundle info: a3031de (prod); Bundle date: 24121905; Platform: web; Platform version: undefined

**Comment by fto-dev** [comment]
+1

**Comment by Tim-Gra** [comment]
+1

**Comment by gaearon** [comment]
We're aware of the issue, I'm looking into it.

**Comment by ljstella** [comment]
This appears to be fixed in 1.96.2

Full version:
`Build version: 1.96.2; Bundle info: 3aa1a5f (prod); Bundle date: 24122022; Platform: web; Platform version: undefined`
