### ISSUE TITLE
Web: Profile button doesn't work when on someone else's profile

### ISSUE THREAD

**Issue by AshleyYakeley** [bluesky-social/social-app#722]
To Reproduce:

1. Go to some else's profile
2. Click on the "Profile" button

Results: nothing happens

Expected: go to your own profile

Note that from any other page, the "Profile" button takes you to your own profile.

Platform: https://staging.bsky.app/ on Firefox on Linux

**Comment by llllvvuu** [comment]
#722

**Comment by ansh** [comment]
Fixed in #764
