### ISSUE TITLE
Splash screen animation is gone on Android 

### ISSUE THREAD

**Issue by RaiHormo** [bluesky-social/social-app#7234]
### Steps to Reproduce

1. Open app on Android 
2. Observe

### Attachments

https://github.com/user-attachments/assets/df7dd45d-4a0a-43b7-9416-5d28af049634

### What platform(s) does this occur on?

Android

### Device Info

Pixel 8, Android 15

### What version of the app are you using?

1.96.1

### Additional Information

Unsure if this was an intentional regression or a bug. If it's intentional it looks pretty ugly.

**Comment by gaearon** [comment]
Unfortunately Android forced our hand here, they’re changing the design system and the new one is much less customizable. It’s possible to animate the icon itself a bit (we’re not doing that right now) but that’s about all we can do. There’s no ability to set a custom background or animate the icon all the way in like it was before. 

https://developer.android.com/develop/ui/views/launch/splash-screen

**Comment by gaearon** [comment]
To clarify, previously we used a custom splash on Android but we can’t align the system and the custom splashes well because the size of the system splash icon seems device-specific and is difficult to predict. So we had to get rid of the custom one.

**Comment by RaiHormo** [comment]
I'm not familiar with android development, but would it not be possible to show a simmilar animation after the app has loaded?

**Comment by gaearon** [comment]
It’s hard to align them visually because the way Android renders the system splash is a bit unpredictable. And if we can’t align them visually, it’s just two different splash screens. That would make it feel even longer because multiple phases are noticeable and jarring.

**Comment by Rexogamer** [comment]
one thing I _would_ suggest is perhaps tweaking the colours? at least in dark mode, the logo feels weirdly dark - and without the animation, it isn't animating into the feed - so would it be worth making it brighter?
