### ISSUE TITLE
Implement embed cards - so they show content

### ISSUE THREAD

**Issue by ianklatzco** [bluesky-social/social-app#724]
I'd like to stop maintaining [psky.app](https://github.com/ianklatzco/psky.app) at some point, so interested in #609 -- just needs HTTP routes.

**Comment by bnewbold** [comment]
these seem to be mostly working? at least in, eg, signal

**Comment by ianklatzco** [comment]
they don't actually show post content
![image](https://github.com/bluesky-social/social-app/assets/1487413/fbdb1d48-c1f2-49d7-986d-e2029d70dc7b)

**Comment by ianklatzco** [comment]
And in Discord, they're only working sometimes:

![image](https://github.com/bluesky-social/social-app/assets/1487413/4db69a40-436e-45b9-a5d2-10835e868ced)

https://discord.com/channels/1097580399187738645/1097580399187738648/1108602956602945607

![image](https://github.com/bluesky-social/social-app/assets/1487413/d200edf4-2f40-471c-bf2b-8a04db1b2e51)

https://discord.com/channels/1097580399187738645/1097580399187738648/1108725030352867349

**Comment by ianklatzco** [comment]
They seem to work now in Discord & Telegram  -- maybe I just caught it in the deploy window.

Maybe this means I can kill psky!
