### ISSUE TITLE
Release v1.96.1 on Github for GH and Obtainium users

### ISSUE THREAD

**Issue by techmagus** [bluesky-social/social-app#7244]
Hi,

It has been a few days now but the fix release v1.96.1 is yet to be released here on Github. GH releases are also used for Obtainium installation/updates.

Thank you.

**Comment by haileyok** [comment]
My bad, been a bit busy and it slipped my mind. Thanks for the nudge, its up now!

**Comment by techmagus** [comment]
Hi,

No worries. Thank you and enjoy the holidays!
