### ISSUE TITLE
social cards: no summary in Slack for posts w/o an image

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/social-app#727]
Social cards are mostly-sorta working since https://github.com/bluesky-social/social-app/pull/609

However, at least in Slack specifically, a link to a post with no image does not get a card/summary. I think this is because the "card type" is different? Behavior has definitely been pretty different between various platforms.

This isn't a priority for me to work on right now, just filing to track the issue.

**Comment by bnewbold** [comment]
Also top-level https://bsky.app/ works in signal (with default card image), but not in Slack.

**Comment by ianklatzco** [comment]
telegram, discord, signal work correctly (but only show the first of N images). 

discord is capable of showing 4 images, as is telegram. both do it for twitter.

**Comment by monicaellerose** [comment]
this seems to be inconsistently working in discord

**Comment by ansh** [comment]
This has been fixed on Slack

<img width="909" alt="CleanShot 2023-09-11 at 13 37 13@2x" src="https://github.com/bluesky-social/social-app/assets/8207733/4dc761d9-de32-4e91-8dce-a0e570470d2e">
