### ISSUE TITLE
Close an image with the back button

### ISSUE THREAD

**Issue by jeffmallozzi** [bluesky-social/social-app#7303]
### Describe the Feature

Currently to close an image you click on the X in the upper right corner. I find it natural to use the browsers back button to close out of the image and return to the feed or post I was viewing but currently the back button navigates back a page. I suggest capturing the back button to just close an image when one is being viewed.

**Comment by surfdude29** [comment]
Please see #5434 for discussion of this

**Comment by jeffmallozzi** [comment]
Thanks, I'll close this one as duplicative
