### ISSUE TITLE
Content trimmed in server input modal when text input is focused

### ISSUE THREAD

**Issue by skipness** [bluesky-social/social-app#732]
**Describe the bug**

**To Reproduce**

1. Press "Sign In"
2. Press the box under "Sing into"
3. Press the text input under "Other service" 

**Expected behavior**

Can see all the content when text input is focused

**Screenshots**
<img src="https://github.com/bluesky-social/social-app/assets/8035517/48cd018b-7dc5-4c8b-a015-cd1da0dae374" width="400" alt="Screenshot_20230518-152956_Bluesky" />

**Details**

 - Platform: Android
 - Platform version: Android 11
 - App version: 1.28.0

**Additional context**

N/A

**Comment by pfrazee** [comment]
Ah yeah, this is an issue with Android and bottom-sheet. The keyboard pretty much never works with modals.
