### ISSUE TITLE
Translate to user's locale, rather than English

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#741]
**Is your feature request related to a problem? Please describe.**

The translate feature currently opens Google Translate in the browser, telling it to translate a given text to English from an unknown language. It would be great for non-English-speaking users if the translate feature would translate to their language instead

**Describe the solution you'd like**

Graysky uses expo-localization to detect the user's language and uses that as the target language when opening Google Translate. I understand from @renahlee that the bluesky app has some sort of abstraction layer for dealing with locales but the same idea applies.

https://github.com/mozzius/graysky/blob/main/apps/expo/src/app/translate.tsx

**Describe alternatives you've considered**

Presumably the Google Translate method is temporary, so perhaps it may not be worth the effort if a more permanent solution is on the way.

**Additional context**

n/a

**Comment by renahlee** [comment]
For context, [this is what I was referencing ](https://github.com/bluesky-social/social-app/blob/main/src/state/models/ui/preferences.ts#L45) but there's a chance you're in the clear. I'll let Paul confirm :)

**Comment by mozzius** [comment]
Ah ok looks like a very thin abstraction indeed - easy peasy

**Comment by pfrazee** [comment]
Yeah we've already got device language detection so this should be an easy task

**Comment by renahlee** [comment]
❤️

**Comment by Toff-kun** [comment]
Sorry if this is a wrong place to report this. Bluesky "Translate" feature always opens Google Translate with Japanese as the target language for me. My phone's locale is set to English as default. I do have Japanese keyboard installed and Japanese as a secondary language. Is there any way to change this behavior and make it translate into English? I'm on Android, if that matters.

**Comment by renahlee** [comment]
Hi @Toff-kun! You might consider opening a new issue so that the team can triage :) There's no guarantee the issue will be fixed but at least there will be better tracking for your problem!
