### ISSUE TITLE
No notifications, and no what's hot

### ISSUE THREAD

**Issue by YuriGal** [bluesky-social/social-app#742]
**Describe the bug**

1. When someone joins Bluesky using my invite code - I don't get a notifications anymore
2. None of my posts that managed to get over 12 likes ever appear on What's Hot page, even though as far as I know my account @ygalanter.bsky.social doesn't have any labels.

**To Reproduce**

Since it's something that is not happening - n/a

**Expected behavior**

1, When someone joins using my invite code - I should get a notification
2. When my post reaches 12 likes  - it should appear on What's Hot list.

**Details**

 - Platform:   Desktop Chrome MacOS
 - Platform version: 113.0.5672.126
 - App version:  TODO (TODO)

**Additional context**

Account handle originally @ygalanter.bsky.social, for a while was renamed @yuriy.galanter,net, now back to the original handle.

**Comment by pfrazee** [comment]
In the future please don't bundle together issues!

We know about issue 1, it's in the internal tracker to solve. For issue two, we're replacing what's hot next week so the dynamic is going to change soon.
