### ISSUE TITLE
Better inform users of future invites

### ISSUE THREAD

**Issue by ljstella** [bluesky-social/social-app#748]
**Is your feature request related to a problem? Please describe.**

The user interface could more accurately provide the user with information about their invites. I've observed the team spending a ton of time dealing with folks on the skyline that are very confused about why they don't have invites, many of whom previously received :sparkles: bonus gifts :sparkles:. Those are not accompanied by an explanation that it delays future invite earning, so the better solution involves not telling people only that "You get an invite every two weeks" in the UI. 

**Describe the solution you'd like**

Replace the static text that discusses the invites-every-two-weeks rate with a dynamic timer showing the days/hours until the user's next invite is available. I have absolutely no idea if that data is currently available to the front end in an easy to consume manner (presumably a future-dated time that you could update the timer with the difference between **futuretime** and **now** would be great but I haven't dug into the invite code on the back end). This also allows for the invite earn rate to change in the future without needing to manually update the modal's text.

**Describe alternatives you've considered**

Updating the modal to reference the loans-against-future invites scheme would take the least amount of work overall, as it reduces the amount of time the team needs to repeatedly answer the "Its been 15 days, where are my invites!?!" question, without the need to change much more than static text. It is unclear to me at this point in time how to accurately word this new message while also keeping it as short as possible so as not to crowd the modal. 

**Additional context**

Modal reference:
https://github.com/bluesky-social/social-app/blob/211fce47ce566fb5703be0019ba587150ff043b3/src/view/com/modals/InviteCodes.tsx#L60

**Comment by haileyok** [comment]
This can be closed now since invites were removed. Depending on how invites end up working with PDSs, can revisit the UI for that.
