### ISSUE TITLE
Upgrade Reanimated from 2.14.4 to 3.1.0

### ISSUE THREAD

**Issue by tboba** [bluesky-social/social-app#751]
**Is your feature request related to a problem? Please describe.**

Currently, Bluesky app uses Reanimated v2. As there's an update to v3, bumping to the major version should be considered, as there's no changes between both APIs. After bumping the version on local environment, an app works as usual.

**Describe the solution you'd like**

I'd prefer to update the version of Reanimated from v2 to v3 for better stability and support. It also fixes a problem with using legacy implementation on Drawer - see #585.

**Comment by tomekzaw** [comment]
+1 from Reanimated maintainers 😄
