### ISSUE TITLE
Display the post publication date after 7 days

### ISSUE THREAD

**Issue by mzarchi** [bluesky-social/social-app#754]
In [the program source](https://github.com/bluesky-social/social-app/blob/15c1b6ee157471807a723161066ba4ce5e12c0b5/src/lib/strings/time.ts#L25), if the post made by the user exceeds the interval of one month, the program only displays the number of months that have passed, but in my opinion, displaying the date after 7 days like 19/05/2023 from the publication of the post is more acceptable, because the number of days or months is not important. The publication date is important

**Comment by pfrazee** [comment]
I'd be fine with that
