### ISSUE TITLE
Banner aspect ratio can not be changed on Linux/Firefox

### ISSUE THREAD

**Issue by smoyer64** [bluesky-social/social-app#760]
**Describe the bug**

On Firefox (Linux) 114.0b4, there is no way to change the aspect ration of a banner image.

**To Reproduce**

1. Attempt to load an image suitable for a banner (say 3:1).

**Expected behavior**

I expected to be able to change the aspect ratio.  On Chromium (Linux), there are in fact three buttons but the horizontal and vertical aspect ratios provide very slight changes from a plain square.  In the Android app, loading the same image results in the expected banner orientation (though my banner is a bit too large and does in fact get clippted

**Screenshots**

![bluesky-banner-square-linux-20230519](https://github.com/bluesky-social/social-app/assets/328333/ceb20810-b222-4d57-9ac4-a5247c291684)

**Details**

 - Platform: Xubuntu Linux with the latest Firefox and Chromium
 - Platform version: 22.04
 - App version: Build version TODO (TODO)

**Comment by pfrazee** [comment]
Ah, yes indeed this is not the right behavior

**Comment by pfrazee** [comment]
The cropper should be in the correct aspect ratio for the banner

**Comment by wrthfl** [comment]
This is an issue on Windows too.
Firefox 114.0.2 (64-Bit)

**Comment by mschwendener** [comment]
I used Chrome on Mac when I signed up a few days ago (because it seemed to work better than Firefox), but it's not behaving yet as it should.

**Comment by mschwendener** [comment]
https://bsky.app/profile/marbules.bsky.social/post/3k3cto7gbvj2y

**Comment by mschwendener** [comment]
Uploading / replacing the banner picture should have a cropping option that fits with the banner picture dimensions.

<img width="522" alt="screenshot_4597" src="https://github.com/bluesky-social/social-app/assets/4497705/41828aed-f217-4e3d-b906-efa49096c0d4">

<img width="531" alt="screenshot_4598" src="https://github.com/bluesky-social/social-app/assets/4497705/9098dda7-7c2d-4ed7-8fea-c928e3f3bb72">

**Comment by mschwendener** [comment]
At least let me open somebody's banner picture in a new tab so I can see what's on it? 
 
<img width="586" alt="screenshot_4715" src="https://github.com/bluesky-social/social-app/assets/4497705/7f257114-817e-498c-bf0b-b9b363583b6f">

**Comment by nicole-ashley** [comment]
@pfrazee This is an issue in the profile picture cropper too: it requires you to fill the aspect ratio of the uploaded image rather than the actual square crop (meaning you have to zoom in to crop anywhere other than centre).

**Comment by mschwendener** [comment]
Adding a banner picture still doesn't work as it should. What are the dimenstions my picture needs so it is displayed as I intent? 

![20240305](https://github.com/bluesky-social/social-app/assets/4497705/953be21c-c37a-4360-a5d8-875a30fde91a)

**Comment by piotrpalek** [comment]
Is this something that I could try to work on if I want to try my hand at hacking on the bluesky app or is it already WIP internally?

**Comment by pfrazee** [comment]
> Is this something that I could try to work on if I want to try my hand at hacking on the bluesky app or is it already WIP internally?

Actually this would be a great one to hit, it's not on our TODOs and pretty straightforward in its scope

**Comment by piotrpalek** [comment]
@pfrazee not sure how it works here, but PR is ready for review ✅ (hope pinging isn't bad form here 😅)
