### ISSUE TITLE
All platform : What's hot confuses Portuguese with Spanish 

### ISSUE THREAD

**Issue by Nehemoth** [bluesky-social/social-app#771]
It looks like that when you selected Spanish in your content languages, it get confuses with Portuguese.

I'd never seem an Spanish post in my what's hot feed but usually see Portuguese (and English but that one it's expected)

**Comment by Nehemoth** [comment]
Fixed?
Today when opening the Bluesky app (on iOS) saw a message indicating that I should change my content language settings as there's was not enough content in my desired languages to show me something.

When refreshed there was enough content as I'd English selected too, maybe a couple of hours ago we didn't have content no even in English.

Thank you.

**Comment by pfrazee** [comment]
This will get fixed when we introduce the ability to declare a post's language
