### ISSUE TITLE
All platforms: While visiting a profile new post should automatically mention the account

### ISSUE THREAD

**Issue by Nehemoth** [bluesky-social/social-app#779]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If I go to a profile in Bluesky and then select the option new post it should automatically add @theaccount_visiting

**Comment by pfrazee** [comment]
Yeah sure, I'd be +1

**Comment by Zero3K** [comment]
this feature has been added, so this issue should be closed.
