### ISSUE TITLE
An option to report a user for hate speech

### ISSUE THREAD

**Issue by deviant-semicolon** [bluesky-social/social-app#780]
**Is your feature request related to a problem? Please describe.**

A problem with social media is that it opens the ability for the worst kinds of people to voice their opinions, and the nature of social media amplifies them. This sadly includes bigoted people, like racists, sexists, homophobes, transphobes, etc. These types of people already exist on bluesky, and there's no real way to report them aside from pressing "other".

**Describe the solution you'd like**

I, and several other people on the platform, would appreciate the ability to report users for hate speech, or for speech that has a negative impact on minorities.

**Describe alternatives you've considered**

Blocking them is definitely an alternative, but blocking doesn't always work when you have a platform with thousands, or even millions, of people. You're not able to block every single bigot on a platform, even if you use community moderation. This is made even worse by the fact that posts can still technically be seen through the protocol, even if you block the user who is trying to access the information.

**Additional context**

Bluesky is a good platform, but I think it would be even better if hate speech was explicitly banned.

**Comment by alimony** [comment]
No idea, I'm not affiliated with Bluesky.

**Comment by deviant-semicolon** [comment]
Ok. Thank you 🙏
