### ISSUE TITLE
web app: not-logged in (eg, login page) should not show "0 invite codes"

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/social-app#781]
![2023-04-09T19:27:11,546077957-07:00](https://user-images.githubusercontent.com/130077/230813309-0e2eec84-a4da-4cf7-92cc-f5cf554d5ce8.png)

**Comment by loganrosen** [comment]
This seems to have been fixed by [this commit](https://github.com/bluesky-social/social-app/commit/e77c6169706640ea95129d8ee26bb022af419374).

**Comment by ansh** [comment]
This has been fixed! @loganrosen thanks for pointing out the commit.
