### ISSUE TITLE
Android + iOS: if app is opened via deep link, home button doesn't work

### ISSUE THREAD

**Issue by snarfed** [bluesky-social/social-app#783]
Thanks in advance for looking at this!

**Describe the bug**

On Android, if the app isn't running in the background, and I open a bsky.app link to a post, the app starts and opens that post correctly, but then the home button doesn't work. The stack, notifications, and profile buttons work, but the home button always goes back to the deep linked post instead of my timeline.

**To Reproduce**

1. Make sure the app isn't running.
1. Open a post link, eg https://bsky.app/profile/werd.io/post/3jwi6qxe2u22f , that opens the app.
1. Tap the home button.

**Expected behavior**

Home button works.

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: 1.28.0

**Additional context**

**Comment by snarfed** [comment]
Also, since this is React Native, I wonder if this happens on iOS too? Might be worth checking.

**Comment by alimony** [comment]
Can confirm this happens on iOS too, good find.

**Comment by that-gai-gai** [comment]
I found a fix to this problem

**Comment by snarfed** [comment]
@that-gai-gai do tell!

**Comment by that-gai-gai** [comment]
@snarfed 
https://github.com/bluesky-social/social-app/pull/785

**Comment by ansh** [comment]
Confirmed this is a known issue. It is being worked on.

Thanks for opening the PR @that-gai-gai

**Comment by that-gai-gai** [comment]
I'm happy to help @ansh
