### ISSUE TITLE
Show/hide replies toggle in feeds

### ISSUE THREAD

**Issue by scottdotjs** [bluesky-social/social-app#791]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to choose whether or not feeds include posts that are replies. 

**Describe the solution you'd like**

A toggle switch at the top of each feed for replies, the state of which persists when navigating away and back. In other words, a per-feed preference. Ideally applying to all posts in the feed as you scroll down, not just as new ones arrive. 

**Describe alternatives you've considered**

N/a

**Additional context**

**Comment by ansh** [comment]
This was completed in #885
