### ISSUE TITLE
"edit my feeds" is broken in dark mode

### ISSUE THREAD

**Issue by leif** [bluesky-social/social-app#792]
**Describe the bug**

When scrolling down in "edit my feeds" in dark mode, there is no dark background, so, text becomes unreadable.

1. enable dark mode
2. go to https://bsky.app/settings/saved-feeds
3. scroll down

**Expected behavior**

black background should remain

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/22132/08559946-905d-4dc2-8463-fb153b14d62c)

**Details**

 - Platform: Firefox on Linux
 - Platform version: Firefox 113.0.2
 - App version: :man_shrugging: i just hit reload, and it's still happening. settings says "Build version TODO (TODO)" :)

**Comment by pfrazee** [comment]
Ah, this is a scroll overflow issue

**Comment by ansh** [comment]
This has been fixed.
