### ISSUE TITLE
Server reports wrong image size for picture and blocks post

### ISSUE THREAD

**Issue by TiiaAurora** [bluesky-social/social-app#804]
**Describe the bug**
Uploading images via the webclient (especially jpgs) will give an error message about the image being too big dispite being 10% the size/limit. 

**To Reproduce**

Upload an image via the webclient. 
It will be returned as too big. 

**Expected behavior**

Pictures below the size restriction should be uploaded. 

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/6146434/fd119820-db95-4862-b105-3900437140d8)

**Details**

 - Platform: Desktop Chrome (the same image will go through without problems on mobile)
 - Platform version:
 - App version:

**Additional context**

It just appeared recently.

**Comment by renahlee** [comment]
Hi there! https://github.com/bluesky-social/social-app/pull/737 got merged so this should hopefully be fixed now!
