### ISSUE TITLE
iOS [maybe Android]: No sound in notifications & must click to remove app notification counter

### ISSUE THREAD

**Issue by Nehemoth** [bluesky-social/social-app#808]
**Describe the bug**

1. When you received a notification you won't hear any sound, like it's a silence notification [sound settings checked and enabled].
2. Also, when a notification it received a notification counter appears in the app, to disappear you must enter the app and click the post that generated the notification.

**To Reproduce**

Problem 1
1. Receive a notification on iOS, you only will know if the screen light up while you watching it.

Problem 2
1. Received a notification.
2. A notification counter has been created.
3. Go inside the app and go to notifications.
4. You will see every new notification it's highlighted in blue.

**Expected behavior**

Problem 1
1. You should received a sound notification when a notification it's received when you have sounds notification enabled.

Problem 2
1. When you go to notifications, the counter should disappear as soon as you see your notifications without go to every one of them. 

**Screenshots**

**Details**

 - Platform: iOS 
 - Platform version: 16.5 (20F66)
 - App version: 1.29.0 (3)

**Additional context**

**Comment by ansh** [comment]
This has been fixed in #1095 and #1340

**Comment by valynor** [comment]
@ansh 
Actually .. the "no notification sound" issue has not been fixed. 
No version of the iOS and iPadOS Bluesky app has ever played a notification sound for me, ever - it's not my notification settings, sound is on for bsky. 

Should I open a new issue about this perhaps?

**Comment by darlosworld** [comment]
Can confirm with @valynor, I'm not getting any kind of sound notification on iOS.

**Comment by surfdude29** [comment]
Afaik the only notification sound supposed to be played by the iOS app is when you get a DM

https://github.com/bluesky-social/social-app/blob/a729efc3b654a3086bb4216f9f9fae74f622e57c/modules/BlueskyNSE/NotificationService.swift#L77-L88

https://github.com/bluesky-social/social-app/blob/a729efc3b654a3086bb4216f9f9fae74f622e57c/modules/expo-background-notification-handler/ios/ExpoBackgroundNotificationHandlerModule.swift#L5-L12

You could open a feature request for playing sounds for other notifications 🔔

**Comment by jordanekay** [comment]
Because the Apple Watch will only vibrate for notifications with sounds, we need an option in the app to play sounds for all notifications. Currently, the Apple Watch will only let you know about DM notifications, not any others.
