### ISSUE TITLE
Deleting posts from profile view doesn't seem to persist

### ISSUE THREAD

**Issue by str4d** [bluesky-social/social-app#809]
**Describe the bug**
A bot I run (https://bsky.app/profile/eprint.bsky.social) posted several dozen duplicate posts (unsure why, but that cause is unrelated to this issue). I tried deleting them manually via the web app from the profile view, but the deletion only appeared to occur in the window; upon refreshing the page, the posts reappeared.

**To Reproduce**

1. Make several posts using `com.atproto.repo.createRecord`.
2. Open the profile page.
3. Click the menu for each posts, select "Delete", and confirm. Wait for the profile to be updated with the post removed before deleting the next post.
4. Navigate away from the profile and then back to the profile.

**Expected behavior**

The posts are deleted and do not appear on the profile.

**Details**

 - Platform: desktop Firefox macOS
 - Platform version: Firefox 113.0.1
 - App version: TODO (TODO)

**Additional context**

If I instead click on each post to navigate to its per-post URL, delete the post from its menu, and then click "back" or navigate back via the browser to return to the profile, the post remains visible in the profile but clicking on it again shows "Post deleted", and after refreshing the page the deleted post is gone from the profile view.

**Comment by tlasmanbotch** [comment]
This is still happening as a behavior. Same as described above --> deleted the post where it is confirmed deleted on the page. When clicking away, the post reappears. 

Platform: Google Chrome 105 (macOS)

**Comment by ProkoCat** [comment]
I'm experiencing this same issue. I have two posts that won't stay deleted. I've tried deleting in the iOS app and on the web app, and in both scenarios, refreshing the page brings the deleted posts right back.

**Comment by ivanamat** [comment]
I'm experiencing this same issue. ¿Some news? I migrated from vps the PDS, i made tes to check new VPS works and now i have one post that i can not delete. I tested with more posts and i can delete them.

**Comment by ivanamat** [comment]
I'm experiencing this same issue. ¿Some news? I migrated from vps the PDS, i made tes to check new VPS works and now i have one post that i can not delete. I tested with more posts and i can delete them.

**Comment by Steven-Jones911** [comment]
yeah, still refuses to delete some posts, mainly replies.
yet another fail for this product.

**Comment by squelfland** [comment]
This exact issue continues for me, on 3 replies, Bsky staff has confirmed this is a current bug via email communication, perhaps this issue should be reopened? Or can it be tracked elsewhere?

**Comment by squelfland** [comment]
I apologize, I don't understand Github very well, but why is this issue marked as closed? I have a reply from Bluesky staff where they acknowledged it was being worked on, yet the issue persists, and no one was assigned to it. Is there any hope of this being fixed? :(
