### ISSUE TITLE
"Fewer hooks" error when I deleted a post

### ISSUE THREAD

**Issue by chriszs** [bluesky-social/social-app#816]
When I delete a post by clicking the contextual menu on the post from my feed on the web app, I get a minified React error that when decoded translates to, "Rendered fewer hooks than expected. This may be caused by an accidental early return statement."

**To Reproduce**

1. Go to the web app
2. Find one of your posts
3. Delete it
4. Get an error

**Expected behavior**

No error, ideally.

**Screenshots**

<img width="655" alt="Screenshot 2023-05-31 at 8 24 48 PM" src="https://github.com/bluesky-social/social-app/assets/1103467/598eea64-f899-4dcc-8cf4-8fce99efdd19">

**Details**

 - Platform: Desktop Chrome Mac
 - Platform version: Okay, you got me, it's actually Arc 0.105.3, which is based on Chromium 113.0.5672.126
 - App version: 1.29.0

**Additional context**

I assume an alligator ate it. Or a crocodile?

**Comment by ansh** [comment]
Thanks for reporting this bug! We should get to it pretty soon.

**Comment by ansh** [comment]
I got #823 in to fix this. Should be part of the next release. @chriszs Thanks for reporting!
