### ISSUE TITLE
[Android] Feed name bar doesn't scroll when feeds are scrolled

### ISSUE THREAD

**Issue by scottdotjs** [bluesky-social/social-app#841]
**Describe the bug**

The bar with names of feeds doesn't move when you love between feeds meaning that you can end up on a feed without knowing which one you're looking at. 

**To Reproduce**

1. Swipe feeds to left

**Expected behavior**

Feed names bar scrolls to left and keeps names associated visibly with feeds. 

**Screenshots**

**Details**

 - Platform: Android
 - Platform version: Android 13 on a Samsung Galaxy S21 Ultra 
 - App version: 1.30.0

**Additional context**

**Comment by ansh** [comment]
I am unable to reproduce this issue. If it still exists, can you please comment here or open a new issue? Thanks!
