### ISSUE TITLE
Like notifications for deleted posts are not filtered out

### ISSUE THREAD

**Issue by loganrosen** [bluesky-social/social-app#842]
**Describe the bug**

Notifications for people liking posts you've deleted are not filtered out.

**To Reproduce**

1. Write a post
2. Wait for someone to like it
3. Delete the post
4. Check notifications

**Expected behavior**
There is no notification for someone liking the deleted post (as clicking it takes you to a post not found page, which is not optimal).

**Details**

 - Platform: Firefox on Windows 11
 - Platform version: 113.0.2
 - App version: 1.30.0

**Comment by pfrazee** [comment]
This will likely need to get handled in the backend @dholms
