### ISSUE TITLE
[iOS] System Theme Not Applied for Dark Mode

### ISSUE THREAD

**Issue by parion** [bluesky-social/social-app#845]
**Describe the bug**
A "dark" theme appearance is not applied when the default "system" theme appearance is chosen in the app settings. 

**To Reproduce**

1. Verify the iOS device has a system theme of "Dark" under the "Display & Brightness" system setting. 

2. Open Bluesky and go to app settings. 

3. Choose "System" under Appearance. 

**Expected behavior**

When a dark system theme is chosen, a dark app theme should be applied when "system" appearance is set in the app settings. 

**Screenshots**
![image](https://github.com/bluesky-social/social-app/assets/4733032/6df947df-475e-4885-81a5-303a4595bc25)
**Details**

 - Platform: iOS
 - Platform version: iOS 16.5
 - App version: 1.3

**Comment by loganrosen** [comment]
This is also broken on Android. I believe the fix is to do what's described [here](https://docs.expo.dev/develop/user-interface/color-themes/#configuration); the referenced configuration value is currently set to `light`. I'm testing out that change now.
