### ISSUE TITLE
"Load new posts" and top feed bar is "jumping"

### ISSUE THREAD

**Issue by str4d** [bluesky-social/social-app#846]
**Describe the bug**

On the main web app view of a feed, I scrolled down a bit, and the bar started "jumping" (see the video). The app was in desktop mode (main nav bar on the left, feed in central column).

I was able to stop the effect by opening the developer tools menu (changing the height of the website's page). I could also stop it by scrolling away, but scrolling back to that part of the feed caused it to resume.

**To Reproduce**

IDK

**Expected behavior**

The feed chrome is less exciting.

**Video**

https://github.com/bluesky-social/social-app/assets/4993799/e5844524-83ad-4a3b-bb67-148d2f3ecfe9

**Details**

 - Platform: desktop Firefox macOS
 - Platform version: Firefox 113.0.1
 - App version: 1.29.0

**Additional context**

It's not present in the video, but I noticed that the Firefox scrollbar was also jumping in time with this.

**Comment by pfrazee** [comment]
Yeah I was able to reduce how often this happens by tuning parameters around this trigger. Might just need more tuning.

**Comment by w-biggs** [comment]
Seeing a similar issue pretty often in Firefox 117 on Windows, but it jumps slightly differently:

https://github.com/bluesky-social/social-app/assets/3406010/b90ef219-a2ec-4d53-9a08-300f89d7b347

Not sure exactly what triggers it.
