### ISSUE TITLE
Add support for ”from:username” search operator

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#849]
It would be nice if I could search only for posts from a specific user, most often myself. A simple interface for this would be the search operator ”from:” which is familiar from several other platforms.

**Comment by HeyItsLollie** [comment]
I often do this on other platforms when I'm trying to find one of my own posts to re-share or reply to, it's extremely useful.

If "from:" is implemented as a search operator, I'd also like to request "self:" as additional shorthand for "from:`your.username`"

**Comment by potatoqualitee** [comment]
Looking forward to this one! Thank you

**Comment by OmarShehata** [comment]
Tried this today and was surprised that it isn't supported yet! Would like to add that it is critical for me when finding both my own posts to link back to as well as others' posts from a few days ago I want to respond to

**Comment by tkasci** [comment]
I agree, it would be very useful.

**Comment by mschwendener** [comment]
In the meantime, there's https://oyin.bo/receipts 

(via https://bsky.app/profile/rvbdrm.com/post/3kg7iz6ztct23 )

**Comment by brendanjones** [comment]
> If "from:" is implemented as a search operator, I'd also like to request "self:" as additional shorthand for "from:your.username"

`from:me` is even simpler, and arguably more intuitive. Would definitely want this, I use it all the time on Mastodon.

**Comment by mschwendener** [comment]
> you should be able to do from:bsky.app etc 

Interesting. 

I can search within the account bsky.app, for example 
from:bsky.app rolling 

(This does not change the URL)

But when I want to search in my own posts or some random other example, I get no hits, although I know the posts are there. 

from:manuschwendener.bluesky.social paris
should find 
https://bsky.app/profile/manuschwendener.bsky.social/post/3ki6b7lpriw2a 

from:geeka.bsky.social
should find 
https://bsky.app/profile/geeka.bsky.social/post/3ke3tn4l6tt2p

**Comment by mschwendener** [comment]
Oh, wait: it works if I use the search field in the right column, but not in the left column? 

<img width="1064" alt="screenshot_4716" src="https://github.com/bluesky-social/social-app/assets/4497705/f1c4faa2-ecbf-4fab-a22f-ac07ad8ce099">

**Comment by mschwendener** [comment]
Yeah, it's strange. I now get the hits for both examples, from both search places. 

But it really didn't work just a few seconds ago. I can still reproduce it when I search via the search field in the middle column, which gets visible _after_ a search. 

<img width="557" alt="screenshot_4717" src="https://github.com/bluesky-social/social-app/assets/4497705/630a3639-b1fc-4ac5-9d91-31b0074c19d6">
 
<img width="559" alt="screenshot_4718" src="https://github.com/bluesky-social/social-app/assets/4497705/c41c36de-9acb-4d43-83c5-7f02c2d423eb">

**Comment by mschwendener** [comment]
> different 

You are right. I'll remove the link to 1853.

**Comment by mschwendener** [comment]
Could 
No results found for _from:geeka.bsky.social protip_ 

be changed to 
No **users** found for _from:geeka.bsky.social protip_, press enter to search for posts 

?

**Comment by putsan** [comment]
In general about core team prioritates

> What we have now is very minimal, and will probably stay that way until we deliver on our core priorities like composable moderation, federation, and improved auth (eg, OAuth, 2FA).

[source](https://github.com/bluesky-social/atproto/discussions/2079#discussioncomment-8243560)

**Comment by putsan** [comment]
> Could No results found for _from:geeka.bsky.social protip_

Now it working GREAT!!! Thanks!)

![image](https://github.com/bluesky-social/social-app/assets/11944886/30178a32-8d0d-451f-a335-aec553d076ac)

![image](https://github.com/bluesky-social/social-app/assets/11944886/7857e80b-7de0-4de3-a366-1d2f454786be)

**Comment by mschwendener** [comment]
I think this can be closed?

**Comment by gaearon** [comment]
yes!
