### ISSUE TITLE
Make "Discover Feeds" more discoverable

### ISSUE THREAD

**Issue by BadPirate** [bluesky-social/social-app#873]
**Is your feature request related to a problem? Please describe.**

New users to bsky are auto-subscribed to "Following" and "Whats Hot" feeds.  Activity with the App depends on them finding content that is engaging quickly, currently it's not obvious how to find content outside of the most popular content on the site (Whats Hot).  There are a bunch of great Custom Feeds, but hey are buried 4 clicks in:

Menu Hamburger -> My Feeds -> Settings Gear -> Discover New Feeds

**Describe the solution you'd like**

Add a Discover tab to the Feeds Hotbar:

![Feeds Hotbar with Discover](https://i.imgur.com/FqJYyrk.png)

**Describe alternatives you've considered**

On first launch of the App, ask the user to follow some feeds that seem interesting and show them the discover list

**Comment by ansh** [comment]
It's now at the top of the My Feeds section. It will also be on the right side with #1403 

We have also added feed discovery as an onboarding step #1284 

If you have any more suggestions, please open a new issue or email me at ansh (at) blueskyweb (dot) xyz
