### ISSUE TITLE
Add instructions for verifying domains using the .well-known/atproto-did method.

### ISSUE THREAD

**Issue by haideralipunjabi** [bluesky-social/social-app#877]
**Is your feature request related to a problem? Please describe.**

Add instructions for verifying domains using the `.well-known/atproto-did` method.

**Describe the solution you'd like**

In the "Change Handle" modal, the app should have a button which says something like "I don't have access to DNS settings" to switch to a different view which has the instructions to use the `.well-known/atproto-did` method.

**Additional context**

I don't think a lot of users know about this method. I would like to work on this if the idea is approved.

**Comment by ansh** [comment]
We do have instructions on the [blog here](https://blueskyweb.xyz/blog/4-28-2023-domain-handle-tutorial)

However, you proposal for adding it in the app sounds good. Feel free to create a PR.

**Comment by mozzius** [comment]
This can probably be closed thanks to https://github.com/bluesky-social/social-app/pull/979

**Comment by pfrazee** [comment]
Thanks!
