### ISSUE TITLE
VoiceControl output being erased in composition field

### ISSUE THREAD

**Issue by oedipusnj** [bluesky-social/social-app#891]
The app allows me to dictate using VoiceControl, but it then erases everything that's been entered into the composition field.

The "undo that" VC command no longer works within Bluesky. The content entered into the field, & deleted by the app, is irretrievable.

Obviously this is a major impediment. I need to be able to use VoiceContol to compose, correct & send posts. Using the iPhone's keyboard far too laborious an undue burden for me & I am not alone.

**To Reproduce**

1. Turn on voice control in settings under accessibility

2. Enter text into a composition field by dictating. The text disappears when one pauses and resumes dictating.
3. The "undo that" & command does not replace the verbally entered text, mere inputs the comand as dictated text

**Expected behavior**

I expected to be able to enter, review & modify text in the composition field using Voice control. Pausing and resuming dictation should not cause previously dictated material to disappear. Issuing the command "undo that" should retrieve the previously entered text, but instead the blue sky app merely echoes the command as new input for the composition field.

**Screenshots**

N/A

**Details**

 - Platform: iPhone 
 - Platform version: 13 Pro Max
 - App version: iOS 16.5

**Additional context**

I am totally blind and also run voiceover, the built-in screen reader for iPhone, in conjunction with voice control. This is the only application in which I have encountered this problem. I only installed the Bluesky app yesterday

**Comment by oedipusnj** [comment]
Related: https://github.com/facebook/react-native/issues/37991

Thanks to Teflo

**Comment by pfrazee** [comment]
Thanks everybody, I'll take a look at this. Worried this looks like it's upstream (thanks @oedipusnj). I'll see what I can do.
