### ISSUE TITLE
Content filters do not apply to quoted posts

### ISSUE THREAD

**Issue by agentjabsco** [bluesky-social/social-app#894]
**Describe the bug**

If a post quotes another post that would normally be hidden or warning-blurred, the quoted post is presented in full view, regardless of the user's Moderation settings.

**To Reproduce**

[here's Alf's dick](https://bsky.app/profile/darthbluesky.bsky.social/post/3jyppvz7umt2t)

**Expected behavior**

I should not see Alf's dick

**Screenshots**

I wonder if GitHub would allow screenshots of Alf's dick in an issue, but not enough to try it

**Details**

 - Platform: desktop Chrome Linux

**Comment by pfrazee** [comment]
Yeah just ran into this. We'll get into it

**Comment by Zero3K** [comment]
I think this has been fixed. If so, please close it.

**Comment by pfrazee** [comment]
Yep, thanks
