### ISSUE TITLE
The text on the Home Feed Preferences page is confusing when compared to the control text.

### ISSUE THREAD

**Issue by blowdart** [bluesky-social/social-app#895]
The text on the Home Feed Preferences page is confusing when compared to the control text.

**To Reproduce**

1. Open the Home Feed Preferences Dialog/Page

**Expected behavior**

1. The explanation text matches the control text

**Screenshots**

![20230623_181920000_iOS](https://github.com/bluesky-social/social-app/assets/796298/6a2cc8c1-74b7-42ea-841f-b079114ee11a)

The control texts are Yes / No, but the explanation talks about enable and disable.

I would suggest switching the control labels to Enabled / Disabled for clarity and for the text for Show Replies to read "Enable and adjust the number ..."

**Details**

 - Platform: Web & iOS (and therefore probably android)
 - Platform version: 1.33.0
 - App version: 1.33.0

**Additional context**

**Comment by pfrazee** [comment]
I'll dig into this
