### ISSUE TITLE
[Web/Desktop-Linux] Flatpak release

### ISSUE THREAD

**Issue by joe733** [bluesky-social/social-app#899]
### Is your feature request related to a problem? Please describe.

Need to navigate to [`bsky.app`](https://bsky.app) every time to open the app.

### Describe the solution you'd like

A [Flatpak](https://flatpak.org) application for cross-distro Linux desktop.

### Describe alternatives you've considered

[AppImage](https://appimage.org) then [Snap](https://snapcraft.io/).

### Additional context

```txt
¯\_ (ツ)_/¯ 
```

**Comment by pfrazee** [comment]
I don't think this is likely, unfortunately. We don't have capacity to add more distributions than we already have

**Comment by GreatGreenStar** [comment]
While this may not solve things for some people, I suggest if possible for people with a chromium-based browser to use BlueSky as a PWA  (or have a separate chromium browser solely for PWA's), this won't completely work the same but should work well for most.
