### ISSUE TITLE
Cancel post dialog is confusing

### ISSUE THREAD

**Issue by runarberg** [bluesky-social/social-app#906]
**Describe the bug**

The Cancel post dialog has ambiguous options. It asks if you want to “cancel” authoring your post, and leaves you two options: *Confirm* and *Cancel*. In UI design, these dialogs often use the active verb (in this case *to cancel* to confirm the action), while here if you click *Cancel* instead of canceling your post, you actually dismiss the dialog and *continue* authoring the post.

**To Reproduce**

1. Click *New Post*
2. Start writing something
3. Hit the <kbd>Esc</kbd> button
4. Observe the ambiguous options

**Expected behavior**

You should be presented with clear unambiguous options.

An example of an unambiguous wording would be: *Erase Draft: Are you sure you’d like to erase this draft?*

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/3984600/94ac8568-7dea-41ec-85bc-c9d834de46e5)

**Details**

 - Platform: web; all browsers
 - Platform version:
 - App version: 1.33.0

**Additional context**

You could use synonyms instead of “Cancel”, such as: *Scratch this post*, *Bail*, etc. You could also write *Dismiss* as the cancel option, as in you want to *dismiss* this dialog.

And aside, generally stacked modal dialogs tend to be annoying, as the post authoring is already a dialog, this additional confirmation to cancel the first dialog might be an over complicated design chose.

Another aside, destructive actions such as these often has the confirmation button colored in red.

**Comment by pfrazee** [comment]
You're right, this is bad copy. We'll dig into it
