### ISSUE TITLE
Add a Media tab to profile pages

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#908]
It would be nice with a Media tab on profile pages. It could show either just the media from the user's posts – this is how e.g. Twitter does it – or (and maybe easier to implement as a first step) all their posts that contain media.

Original idea: https://bsky.app/profile/seductivelysoul.bsky.social/post/3jywikwx3i726

**Comment by pfrazee** [comment]
Yeah I believe this is planned

**Comment by mschwendener** [comment]
This can be closed, no?

**Comment by pfrazee** [comment]
Yep
