### ISSUE TITLE
Mismatched background on SavedFeeds page

### ISSUE THREAD

**Issue by benharri** [bluesky-social/social-app#920]
**Describe the bug**

**To Reproduce**

1. Navigate to /settings/saved-feeds

**Expected behavior**

Background matches theme

**Screenshots**

[screenshots in thread](http://bsky.app/profile/benharr.is/post/3jxonku37mt2s)

**Details**

 - Platform: Web
 - Platform version: latest main
 - App version: main as of 1024f37a543e49e6e292772ffdc20c6a01094b5b

**Comment by pfrazee** [comment]
Thanks for the heads up. Fix merged

**Comment by benharri** [comment]
![image](https://github.com/bluesky-social/social-app/assets/7453240/c033d995-e918-45fd-a46c-b4ba833b1425)

nearly there, still a bit of white on firefox

**Comment by pfrazee** [comment]
Shoot, yep I see it. Header is now throwing it off.

**Comment by rizkisrq** [comment]
It's not just on SavedFeeds. The same bug can be discovered on Mute List. 

![image](https://github.com/bluesky-social/social-app/assets/8591882/552a4a22-e9c5-4270-b9a2-f77741c7289c)

**Comment by pfrazee** [comment]
@estrattonbailey can you fix this? overflow issue on mutelist listing screen

**Comment by ansh** [comment]
Fixed in #943
