### ISSUE TITLE
Starting a post with an @ mention then adding text before it makes that text blue

### ISSUE THREAD

**Issue by alimony** [bluesky-social/social-app#929]
**Describe the bug**

On mobile (only tested on iOS) if you start a post with an @ mention, then put the cursor at the start again and type more text, all text up until the mention is blue.

Originally seen here: https://bsky.app/profile/eaglebaby420.fans/post/3jzcwnc2lmw2t

**To Reproduce**

1. Start a new post
2. Type an @ and some chars to get a suggested mention, then add one of those mentions
3. Move the cursor to before the typed @ 
4. Type some more text

**Expected behavior**

The text before should be normal color like the rest of the post, except mentioned accounts.

**Screenshots**

See this link for screenshots: https://bsky.app/profile/eaglebaby420.fans/post/3jzcwnc2lmw2t

**Details**

 - Platform: iOS
 - Platform version: 16.4.1
 - App version: 1.35

**Comment by chead** [comment]
This can be fixed by adding a state for PasteInput `value` property:
`const [rawtext, setRawtext] = React.useState('');`

and setting it:

```
        <PasteInput
          testID="composerTextInput"
          ref={textInput}
          value={rawtext}
```
