### ISSUE TITLE
Unexpected show/hide behavior of `BottomBar` and `FeedTabBar` on mobile web

### ISSUE THREAD

**Issue by sehyunchung** [bluesky-social/social-app#930]
**Describe the bug**

When scrolling up or down on mobile web (width < 1230px), the BottomBar and FeedTabBar exhibit random "dancing" behavior, showing and hiding repeatedly.

**To Reproduce**

1. Open the app on mobile web (width < 1230px).
1. Randomly scroll up and down. (Exact conditions are added in the Additional context section.)

**Expected behavior**

The BottomBar and FeedTabBar are expected to remain stable, without showing and hiding repeatedly.

**Screenshots**

https://github.com/bluesky-social/social-app/assets/31644638/a6f0907a-25a3-488a-afd6-fda5fd1657b6

**Details**

 - Platform: MacOs Desktop Arc 
 - Platform version: 0.109.1
 - App version: Build version 1.34.0

**Additional context**

Upon investigation of the codebase, it seems that the bug occurs in `useOnMainScroll.ts` when the current `dy` value is the inverse of the previous `dy` value. The relevant code snippet is as follows:

`social-app/src/lib/hooks/useOnMainScroll.ts`
```ts 
export function useOnMainScroll(
  store: RootStoreModel,
): [OnScrollCb, boolean, ResetCb] {
  let lastY = useRef(0)
  let lastDy = useRef(0) // added by me to check last `dy` value
  let [isScrolledDown, setIsScrolledDown] = useState(false)
  return [
    useCallback(
      (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        const y = event.nativeEvent.contentOffset.y
        const dy = y - (lastY.current || 0)

        // below is added by me to check the condition
        const isDancing = dy > DY_LIMIT && lastDy.current * -1 === dy
        console.log({lastDy: lastDy.current, dy})
        if (isDancing) {
          console.error('Dance!') // Starts dance
        }
        lastDy.current = dy
        // end of added by me

        lastY.current = y

        if (!store.shell.minimalShellMode && y > 10 && dy > DY_LIMIT) {
          store.shell.setMinimalShellMode(true)
        } else if (
        // ...
```

and here's the video capture:

https://github.com/bluesky-social/social-app/assets/31644638/9eda3cf5-9858-41f6-83e1-e1f1529baed0

**Comment by pfrazee** [comment]
I tuned the behaviors a bit before merging with https://github.com/bluesky-social/social-app/pull/942

The mobile simulator seemed okay with it but please re-open if I got the thresholds wrong

**Comment by sehyunchung** [comment]
Thank you for tuning the behaviors and merging! I'll let you know if I find any issues. Appreciate your response!
