### ISSUE TITLE
Improving post languages

### ISSUE THREAD

**Issue by intrnl** [bluesky-social/social-app#936]
**Is your feature request related to a problem? Please describe.**

This is a [follow up discussion from Bluesky](https://bsky.app/profile/did:plc:ragtjsm2j2vknwkz3zp4oxrd/post/3jzfjf6andt25)

I think it would be nice if we can improve the post languages experience for multilingual users.

currently, it doesn't seem great that non-English users are unaware that they're currently posting in English, or as an example, both English and Persian.

perhaps a discoverability issue? I think you'd only be aware that it exists at all if,
a. [you have been following Paul Frazee for a while](https://bsky.app/profile/did:plc:ragtjsm2j2vknwkz3zp4oxrd/post/3jytuaevwcp23), or,
b. you actively seek the update notes, either via app store or the bsky.app account

what might also be an issue is the way it's been presented, right now the post composer just has this mysterious button labeled `en` or some other language code, I don't think I'd know what to make of it until I press the button to see what it is about.

**Describe the solution you'd like**

**We should probably reset the current post languages configuration** so that we only default to whatever the no.1 system language is, rather than top 3 languages, this is important for the next point

**We should show the full language name when one language is set**, this ensures that users are clearly aware that the languages that have been specified for the post they're writing, which can look like the image below.

<img width=200 src=https://github.com/bluesky-social/social-app/assets/20620901/db2f1536-1cab-4a85-8cd6-9d2261896ed3 />

in the thread I've mentioned how it might not matter at all if it only shows one language, since it'll be too long if we display multiple languages, but I think so long as points above are taken then we could just defer back to language codes now that users understand that it's the post language button.

**Describe alternatives you've considered**

An alternative would be to add a notice that post languages are a thing at all, that the mysterious `en` button is for changing the post languages, but I feel like this is a band-aid at most, we're better off not displaying language codes I think.

**Additional context**

the `langs` array is an incredibly useful property for custom feeds/clients that would like to make sense of the posts without bringing in an NLP model, which can be problematic in some cases (e.g not suitable for custom clients primarily targetting low-end devices)

**Comment by intrnl** [comment]
Additional thoughts:

**It would be great to be able to quickly remove languages**, it shouldn't take scrolling through a list to disable the language they're no longer using for a new post, especially important as not all multilingual users have multiple languages added to their device (or something is inhibiting it, like Brave browser that would only show primary language despite setting it up)

<img width=200 src=https://github.com/bluesky-social/social-app/assets/20620901/b6b0e3e5-671a-497f-970a-93e60d18cea8 />

**It would be _interesting_ if the languages were ordered**, this is a bit of an odd request, and even I have no idea how useful it can be, but in some cases, users still use primary language to be writing the posts in even if they specified multiple languages, and it would be *interesting* if we can reflect that within the languages array.

<img width=200 src=https://github.com/bluesky-social/social-app/assets/20620901/5ef738bc-bedb-4f59-95da-32ab299f40bd />

**Comment by pfrazee** [comment]
These are good suggestions. We'll talk through it and see what we can do to improve the outcomes

**Comment by pfrazee** [comment]
An update to this UI has been pushed. Not all of the suggestions were included but hopefully it's closer to what youre suggesting
