### ISSUE TITLE
Android: download image from post raises low-level android error rather than grant permission dialog

### ISSUE THREAD

**Issue by hmackiernan** [bluesky-social/social-app#941]
**Describe the bug**

**To Reproduce**

1. From a post with an attached photo
2. Click the photo to view
3. Click 'Save' on the bottom menu of the photo view

**Expected behavior**

Expected: if appropriate permissions for saving files are not already granted to Blue Sky app, prompt for appropriate app permissions
using a standard Android dialog, or an in-app proxy for it. If granted, save the file [prompting for location].  If rejected, fail to save and continue.
 
Actual: Low-level error "Expo.MediaLibrary.createAssetAsync has been rejected", file is not saved.

**Screenshots**
![Screenshot_20230702-074134](https://github.com/bluesky-social/social-app/assets/1683808/9f3b575a-4a60-4e43-8e79-6b01edfc42e6)

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: Build version 1.37.0 (23) production

**Additional context**

**Comment by pfrazee** [comment]
Ah weak, thanks for the heads up
