### ISSUE TITLE
Search bar missing in discover new feeds

### ISSUE THREAD

**Issue by aviramha** [bluesky-social/social-app#944]
It seems there's a search bar since it shows for a second then disappears 

**To Reproduce**

1. Discover new feeds

**Expected behavior**

Search bar to search feeds

**Screenshots**

**Details**

 - Platform: iPhone 11
 - Platform version: 16.5.1
 - App version: 1.37
https://github.com/bluesky-social/social-app/assets/41201924/d8be4875-7cf7-46e3-a35b-d6ce13326e77

**Comment by ansh** [comment]
Working on this!

**Comment by ansh** [comment]
This issue has been fixed in the latest version of the app. Please update your app and let me know! @aviramha
