### ISSUE TITLE
Accessibility issues with larger font sizes

### ISSUE THREAD

**Issue by juliaferraioli** [bluesky-social/social-app#952]
**Describe the bug**
Users that have set their font size to be larger than default experience cut off UI in native clients.

**To Reproduce**

1. Increase system font size
2. Open app OR start to compose a post

**Expected behavior**
I expect to see posts presented without overlap or being cut off AND to be able to compose a post without text disappearing.

**Screenshots**

![Screenshot_20230703-091313~2.png](https://github.com/bluesky-social/social-app/assets/281597/c0af9ea2-7648-436e-ae06-127c25765c61)

https://github.com/bluesky-social/social-app/assets/281597/cb1a5ec5-8a1a-4c2d-9d64-ab400441c72f

(The above link should be a screen recording.)

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: 1.37.0

**Additional context**

Related to issue #901

**Comment by pfrazee** [comment]
Oof not proud of how long this took. It's fixed in the upcoming 1.51 release.
