### ISSUE TITLE
Make it possible to select text in posts etc

### ISSUE THREAD

**Issue by 0x53A** [bluesky-social/social-app#954]
I would like all/most text to be selectable with the default system tools.

For example, on web, I can select parts of a post (by long-tapping), and then do anything with it, including (but not limited to) using the native translation feature.

![image](https://github.com/bluesky-social/social-app/assets/4236651/c0cfcf33-96ac-423e-8ce2-9afcaf26339e)

![image](https://github.com/bluesky-social/social-app/assets/4236651/2bf75286-1840-40df-a7b8-907874bf7919)

On the iOS app, I would have to use the triple-dot menu to copy&paste the whole post into the notes app.

In addition to post text, I would also like alt-text of images to be selectable in app (it is on web). Maybe also profile descriptions?

Lastly, on iOS, there is automatic  (on-device!) OCR for images. I believe apps can opt into this. This would be great for images with text.

This is how it looks on web:

![image](https://github.com/bluesky-social/social-app/assets/4236651/7447d728-888b-43e6-a789-f25c82fcce58)

I’m not an iOS developer but found this article which seems to describe how to enable this: https://developer.apple.com/documentation/visionkit/enabling_live_text_interactions_with_images

**Comment by ansh** [comment]
I would love for this to be possible as well, unfortunately it is quite hard to implement in React Native. I got to a decent place in this branch #453 but the issue happens when you have links and rich text which makes it very difficult to do without having unintended side-effects.

**Comment by intrnl** [comment]
would a toggle suffice as a compromise? I'd imagine when selecting text you wouldn't want to accidentally tap a link and ruin your selection

**Comment by fabriziobertoglio1987** [comment]
I'm available to work on this issue. Thanks

**Comment by haileyok** [comment]
This got merged in 👍
