### ISSUE TITLE
AppView Proxy continues displaying "Load New Posts" popup.

### ISSUE THREAD

**Issue by mussar0x4D5352** [bluesky-social/social-app#961]
**Describe the bug**
When the "AppView Proxy" toggle is enabled, the Load New Posts popup doesn't go away. Disabling the proxy solves the issue.

**To Reproduce**

1. Enable AppViewProxy

**Expected behavior**

To have it only show Load New Posts when new posts are available.

**Screenshots**

![Screenshot 2023-07-03 at 18 48 42](https://github.com/bluesky-social/social-app/assets/67082011/b63f96eb-600f-4f86-a3f2-7e359f3aa179)

**Details**

 - Platform: Desktop Safari
 - Platform version: Version 17.0 (19616.1.17.11.4)
 - App version:Build version: 1.37.0; Platform: web

**Additional context**

EDIT: actually i think it might be showing that when there's updates to things like replies/likes/reposts

**Comment by ansh** [comment]
This has been fixed! #1065
