### ISSUE TITLE
Conversations between follows should be treated differently from replies

### ISSUE THREAD

**Issue by mdruker** [bluesky-social/social-app#963]
**Is your feature request related to a problem? Please describe.**

The current default feed settings show replies of accounts you follow if they exceed a threshold of likes. But with Bluesky picking up, this is not a good enough control, as some accounts are prolific repliers — so the feed is full of random replies. Turning off the reply toggle, however, also (as far as I can tell) stops showing non-random replies - conversations of people I do follow.

**Describe the solution you'd like**

Ideally I would see all conversations between follows, and some other replies based on some measure of relevance/connection. But more immediately I think conversations between follows shouldn't be treated as "replies".

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by pfrazee** [comment]
Yeah I'm +1 to this change
