### ISSUE TITLE
Remove the 'Follow' button in home timeline, to prevent accidentally following others.

### ISSUE THREAD

**Issue by xnuk** [bluesky-social/social-app#966]
### Is your feature request related to a problem? Please describe.
As a user carefully following others to control my home timeline, I found myself I'm stressful at scrolling timeline on my phone, with trying to avoid the follow buttons, maybe because I'm right-handed.

### Describe the solution you'd like
Please remove the 'Follow' button in home timeline, or at least give option to this.

### Describe alternatives you've considered
N/A. May be off-topic: Twitter had put the 'Follow' button in home timeline, and removed it later.

**Additional context**
<img src="https://github.com/bluesky-social/social-app/assets/3071003/8e852f6e-e0e4-4e8c-9f95-605721512f22" width="375" height="667" alt="A normal Bluesky home timeline in mobile view, showing many reposts, each of the repost has a 'Follow' button in right side." />

**Comment by pfrazee** [comment]
Hmm! Do you think there's a version of this that could be just as easy to access without having the accidental press risk? Maybe a quickview button to their profile that opens up as a bottom sheet and gives lots of actions, including mute? (That's been a request in the past)

cc @ansh

**Comment by xnuk** [comment]
Can I close for now since it's gone anyway? The new profile preview drawer is little buggy, but I'll file a new issue if I mind.

**Comment by pfrazee** [comment]
Yep!
