### ISSUE TITLE
Notification when someone likes your feed is unclear

### ISSUE THREAD

**Issue by Emma-Fuller** [bluesky-social/social-app#968]
**Describe the bug**

When someone likes your feed, the notification shows the text "[User] liked your post"
This is unclear since it does not distinguish that it is a feed being liked and not a post, nor does it show which feed was liked

**To Reproduce**

1. Create a feed or use a feed you already own
2. Like the feed so you get a notification

**Expected behavior**

A message along the lines of "[User] liked feed [Feed Name]"

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/89794160/f84fec1b-6c81-49c5-8a34-6b2af0d68378)

**Details**

 - Platform: web (though id imagine it affects all)
 - Platform version: Most recent
 - App version: Most recent

**Additional context**

Additional context provided here
https://bsky.app/profile/clarabelle.xyz/post/3jzplhdm2mu2v

**Comment by Emma-Fuller** [comment]
Just noticed clicking the link leads to a broken page, so definitely a bug

![image](https://github.com/bluesky-social/social-app/assets/89794160/ad36f7b2-025c-4b86-8827-d26f11f395b2)

**Comment by pfrazee** [comment]
Oooh yep. Thanks for the report. @ansh can I hand this one to you?

**Comment by mackuba** [comment]
Oh nice, thanks for this!
