### ISSUE TITLE
bskyweb: fetch post thread and profile from AppView (no login); apply labels

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/social-app#983]
Currently, bskyweb tries to fetch profile and post thread content from PDS, using the golang XRPC client, with auth. This works for just a couple minutes, then the XRPC client auth token expires, and is not automatically refreshed.

A quick fix would be to point bskyweb at the AppView directly instead of PDS. These routes don't require auth there.

A related fix to get in would be to parse labels and not embed images in embeds based on some labels. In particular, takedowns, warn, etc. Code should be flexible to the label authority and set of values, so we can make quick/simple policy changes.

**Comment by pfrazee** [comment]
@Jacob2161 I'm punting this bad boy to you

**Comment by Jacob2161** [comment]
Yup, I'll definitely fix this. I actually have a fix for the current xrpc client but I think it might be better to just use AppView as Bryan suggested, since that should be possible now and is more correct.

**Comment by ansh** [comment]
@Jacob2161 @bnewbold Has this been fixed?

**Comment by Jacob2161** [comment]
Yes, @bnewbold fixed it!
