### ISSUE TITLE
Make the link preview card embed an actual link

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/social-app#995]
**Is your feature request related to a problem? Please describe.**

I normally click most links in a browser with Cmd+click in order to open them in a new tab. However, the preview cards displayed in posts on Bluesky that have link embeds aren't actual link elements - they are just a bunch of DIVs inside DIVs that have a JavaScript event set on them that opens the link on click, but they always open them in a new *window*, not a new tab as I'd like. There is no way to override this behavior like with normal links, by Cmd+clicking or right-clicking and then choosing "Open link in new tab" from the context menu, because it's not a link.

<p><img width="601" alt="Screen Shot 2023-07-07 at 19 42 46" src="https://github.com/bluesky-social/social-app/assets/28465/dd2262a9-d429-4450-b8b3-62bf73faadb5"></p>

^ The cursor shown over the element is the text cursor, not the link pointer, because this is a plain unlinked text paragraph

**Describe the solution you'd like**

It would be nice if the whole link box (the image and the description below) was just an `<a>` element with the same kind of structure inside, so that the browser handles it using normal built-in behaviors for links.

**Comment by runarberg** [comment]
I would call this an accessibility bug, not a feature request.

Users with no access to a mouse have no way of clicking the link card.

**Comment by pfrazee** [comment]
Assigning to @estrattonbailey

**Comment by mackuba** [comment]
Thanks!
