### ISSUE TITLE
[iOS] crash when tapping profile followers

### ISSUE THREAD

**Issue by jakobo** [bluesky-social/social-app#998]
**Describe the bug**

When tapping on the "X followers" string on the bottom sheet, the app crashes

**To Reproduce**

1. From any feed, tap a profile picture
2. On the bottom sheet that appears, tap the "X following" string

**Expected behavior**

Tapping on the follower count should dismiss the bottom sheet and then navigate to a lost view of the profiles followers

**Screenshots**

https://github.com/bluesky-social/social-app/assets/1795/a79c11f3-0088-4509-8450-c80d5b17f654

**Details**

 - Platform: 

Build version: 1.40.0 (1); Platform: ios

**Additional context**

**Comment by pfrazee** [comment]
This has been fixed by https://github.com/bluesky-social/social-app/pull/992 but we've been stuck in some App Review challenges. We'll hopefully get the fix out soon.
