### ISSUE TITLE
[Web] Sticky timeline tabs header stuck on scroll

### ISSUE THREAD

**Issue by Moshyfawn** [bluesky-social/social-app#999]
**Describe the bug**

**To Reproduce**

1. Open [Bluesky timeline](https://bsky.app/)
2. Slow / medium speed scroll down your timeline 2 - 3 times
3. See the tabs header keeps appearing and disappearing

**Expected behavior**

The tabs header is hidden on scroll down and shown on scroll up

**Screenshots**

https://github.com/bluesky-social/social-app/assets/16290753/9b57a9e5-3899-4012-b1d9-5dc725dc9f92

**Details**

 - Platform: Desktop Firefox MacOS
 - Platform version: MacOS Sonoma 14.0 Beta 3, Firefox Developer Edition 116.0b2 (64-bit)
 - App version: 1.41.0

**Additional context**

_N/A_

**Comment by pfrazee** [comment]
This has been plaguing us for a while. We've been tuning the tolerances but I'm starting to think that perhaps multiple hooks are triggering and conflicting with each other. I'll see if I can't finally suss out what's causing this.

**Comment by pfrazee** [comment]
This is fixed in the upcoming 1.51 release
